### ISSUE TITLE
Query patterns on DbSet (Local, Store, etc.)

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFrameworkCore#1003]
Historically, the fact that iterating/querying DbSet directly gives you results from the database has been confusing (because it doesn't reflect additions/deletions made in the change tracker). We should revisit this design to try and do something less confusing.

One proposition is to not have DbSet be queryable and instead have methods like .LocalQuery, .DatabaseQuery etc. to make things more explicit. We could also have separate methods for Tracked and Untracked queries, which makes it more obvious that there is a choice.

We should also consider what we could do in the future with merging local and database queries (i.e. fall back to database when it's not in-memory etc.). We probably wouldn't do this for the initial EF7 release, but we should come up with a design that supports things like this in the future. See this CodePlex issue for some customer feedback - https://entityframework.codeplex.com/workitem/2561.

**Comment by julielerman** [comment]
i'm hunting for the DbSet Local method. Found this ...will keep looking. (and Find) :)

**Comment by ajcvickers** [comment]
@julielerman Local is not implemented yet. You can query against the ChangeTracker (`context.ChangeTracker.Entries<T>`) to get at local data. There is nothing yet that does the data binding stuff from .Local.

See https://github.com/aspnet/EntityFramework/issues/797 for Find. It's not done and we are still debating whether to do it at all. See the other work item linked from it. We will likely do one or the other, but maybe not until after RTM.
