### ISSUE TITLE
Query: Find a better prefix for QueryFilter parameters

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10052]
We fixed #9850 with prefix-ing parameters with `$` but Oracle did not like it :trollface: 
We need to find a suitable prefix apart from `_`
@roji @Kagamine @ErikEJ - Any restrictions on parameter naming in other providers?

At present SqlServer generates parameter named like `@__$Filter`

**Comment by Kagamine** [comment]
MySQL is ok

**Comment by ErikEJ** [comment]
I think SQL CE has same restrictions as SQL Server

**Comment by ajcvickers** [comment]
Prefix: "ef_qf__" -> "@__ef_qf__BlogId"
