### ISSUE TITLE
DbSet<TEntity>.Find for null values

### ISSUE THREAD

**Issue by topguss** [aspnet/EntityFrameworkCore#10096]
Is there possible to remove [NotNullAttribute] from Find method in DbSet<TEntity>?
It will be more useful if we do not need to check if param is null when we call this method.
That will reduce a hundred line of code per project.
 
In the implementation, if at least one param is null, then immediately return null, without query execution.

We need this functionality for null-able FK.

**Comment by Mardoxx** [comment]
>We need this functionality for null-able FK.

I'm not following. Are you doing something like this?

```csharp

/*
Entity {
   int Id { get; set; }

   // ChildEntity nullble FK
   int? ChildEntityId{ get; set; }
}
*/


var childEntityIds = context.Entities.Select(x => x.ChildEntityId).ToList();
foreach(var childEntityId in childEntityIds) {
    if (childEntityId != null) {
        context.Entities.Find(childEntityId);
    }
}
```

And you want to avoid your own null-checking?
