### ISSUE TITLE
Add overloads of HasColumnType that take CLR types

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#10090]
(This may sound strange, but stay with it. 😸)

With the introduction of type conversions it has become possible to map the same CLR types to different types of database column. A good example of this is enums, where the database column can be a numeric type (store numbers) or a string type (store the enum string values). The way to tell EF to store strings instead of numbers is to explicitly map the property to a string column. For example:
```C#
Property(e => e.ShipmentType).HasColumnType("nvarchar(max)");
```
But this is database-specific since the type name is database-specific. To do this in a database-agnostic way I should just have to tell EF that even though the property is of type X, I want to convert and store it as if it was type Y. For example:
```C#
Property(e => e.ShipmentType).HasColumnType(typeof(string));
```
Now the type mapper can pick the appropriate type of "string" column in the normal way without the application code being database-specific.

**Comment by ralmsdeveloper** [comment]
This solved the problem of working with multiple databases in a single application!

I liked

**Comment by smitpatel** [comment]
While API would be different, something similar to this would be used in DocumentDb since there are not "database types" and only "serializable CLR types".
