### ISSUE TITLE
Query: Select.Include.OrderBy ignores the include

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10101]
```C#
                    var query2 = context.Set<OrderLine9912>()
                        .Select(o => o.Order)
                        .Include(o => o.Customer)
                        .OrderBy(o => o.Id)
                        .ToList();
```
If OrderBy is present, we ignore the include, if it is absent then we do include correctly

**Comment by maumar** [comment]
workaround is to apply Include after the order by

**Comment by maumar** [comment]
fixed by d5278006146a178ba807b12fbec620ce2e96f574

**Comment by MarcelChirtes** [comment]
Something strange happens to me, at first run time warning is there, then everything is silent, EF core 2.2.3, contextLifetime and optionsLifetime are scoped.

**Comment by ajcvickers** [comment]
@MarcelChirtes This is expected. The query compiles once, at which time you see the warning, and is then cached for future calls.

**Comment by MarcelChirtes** [comment]
@ajcvickers fair point, I assume there's no way to suppress it? Thank you.

**Comment by ajcvickers** [comment]
@MarcelChirtes Any warning can be suppressed using `ConfigureWarnins` in the `DbContextOptionsBuilder provided by `AddDbContext` or `OnConfiguring`.
