### ISSUE TITLE
Allow delete fixup and cascade timing to be configured

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#10114]
Currently:
* Cascade delete happens as part of SaveChanges. This prevents cascades happening when all that is intended is a re-parenting.
* Fixup of non-deleted entities to no longer reference deleted entities happens after SaveChanges. This prevents graph shredding when marking entities as deleted.

However, there are scenarios where it is useful for these things to happen at different times:
* In a data-binding app, cascade delete should probably happen immediately so that the view of the data correlates to what will happen when SaveChanges is called.
  * Similarly, it can be useful to have the fixup to the deleted entities happen
* When attempting audit state before or in SaveChanges, it is useful to know what will be deleted beforehand.

There are a few things we could do:
* Add a "PerformCascades" method to the context. This would run cascade delete code when called.
* Add a context option to make cascading happen immediately on delete
* Add similar method/option for delete fixup, or have the cascade method/option do the fixup also.

**Comment by nehresma** [comment]
Another use case here:  Being able to detect the entities that were removed (possibly by getting a tree of them prior to SaveChanges) so that you can perform an action afterwards.  For example, removing referenced objects from the filesystem or S3.

**Comment by jonathanford** [comment]
> Fixup of non-deleted entities to no longer reference deleted entities happens after SaveChanges. This prevents graph shredding when marking entities as deleted.

Should the same behaviour occur when query filters are applied such as when doing a soft delete? For example in a Blog/Posts scenario, if a Post is soft deleted (using shadow property and query filter), the Post no longer appears in the DbSet, but I still see it in the navigation collection of the Blog.

**Comment by johnkwaters** [comment]
My 2 cents - my primary interest is in soft delete. I check which entities have been deleted, and instead set an IsDeleted=true and change them to Modified. It would suffice for me to just get some kind of callback where I can do this logic. Since you said the current logic is in order to do the right thing for reparenting, and prevent graph shredding, I don't necessarily want that just undone in the general case. All I need is some point where I get the REAL state of the objects prior to the DB save...

**Comment by ajcvickers** [comment]
Re-opening to ensure breaking change is announced.

**Comment by markhobson** [comment]
What was the conclusion with regard to fixing up navigation properties to no longer reference deleted entities before SaveChanges? i.e. This part of the original issue:

> Currently:
> 
> * Fixup of non-deleted entities to no longer reference deleted entities happens after SaveChanges
> 
> There are a few things we could do:
> 
> * Add similar method/option for delete fixup

As far as I can tell deleted entities are only removed from navigation properties after SaveChanges.

**Comment by ajcvickers** [comment]
@markhobson That part of the changed proved problematic and very breaking. Cascade of states happens immediately by default, but fixup only of navigations only happens after the entity is really deleted by SaveChanges.

**Comment by markhobson** [comment]
Thanks for clarifying.

**Comment by deivyd321** [comment]
@ajcvickers I am using EF Core 3.1. 
I am deleting a navigation property which is configured by delete behaviour cascade.

`
builder.HasMany(p => p.Suggestions)
                .WithOne()
                .IsRequired()
                .HasForeignKey(p => p.CreatorUserId)
                .OnDelete(DeleteBehavior.Restrict);
`

` 
var principal = await repository.GetWithSuggestion(userId, suggestionId);
var suggestion = principal.suggestions.FirstOrDefault(s => s.Id == suggestionId);
principal.suggestions.Remove(suggestion);
await repository.Save();`

However, in save changes I am getting 
_An error occurred while updating the entries. See the inner exception for details. Cannot insert the value NULL into column 'CreatorUserId', table 'Suggestions'; column does not allow nulls. UPDATE fails.
The statement has been terminated._ 

And in the SaveChanges I see that Suggestion entity is not Deleted but Modified. I see that it is the same problem as in this issue, could be it an ef core bug?

**Comment by ajcvickers** [comment]
@deivyd321 `.OnDelete(DeleteBehavior.Restrict)` means _don't_ cascade delete. Use `Cascade`.

**Comment by deivyd321** [comment]
@ajcvickers thanks for reply.

But I don't want to delete the principal entity. The principal entity contains many `suggestions` and I just want to delete a single `suggestion` from the principal entity. I do not want the principal entity to be deleted in any case. 

So I think `Restrict` is ok here and the problem is that in `SaveChanges` method, `Suggestion` entity is marked as `Modified` but not `Deleted`. As I understand this issue was solved before but I still noticed similar issues with mine.

**Comment by TOuhrouche** [comment]
Thanks for all the hard work that went into EF.Core. 
We've built all our logic around the issue being mentioned here. That is, when an entity is deleted, it also gets removed from all navigation properties without calling `SaveChanges`. We heavily rely on this behavior so our bindings update before we call save changes. This way, the user can see the impact of her changes without changing the database. 

Is there a way to achieve a similar outcome without calling `SaveChanges`?

**Comment by gaglia** [comment]
Hello everybody,

we are also in the same situation as @TOuhrouche.
We are migrating from Entity Framework 4.0 and it is crucial for us right now to be able to maintain the behavior described perfectly above:

"When an entity is deleted, it also gets removed from all navigation properties without calling SaveChanges"

So I'm also wondering if there is a way to be able to achieve this behavior?
Because from the tests I'm doing with EF 7 I can't find a solution.

@TOuhrouche did you find a solution in the meantime ?

I appreciate any of your feedback
Thank you

**Comment by cjblomqvist** [comment]
> That part of the changed proved problematic and very breaking. Cascade of states happens immediately by default, but fixup only of navigations only happens after the entity is really deleted by SaveChanges.

@ajcvickers - could you explain why this was problematic? I'm thinking about doing something about this for our own purposes, but if you already have good reasons why one should not do this then I'd prefer not to waste the time :-)

**Comment by ajcvickers** [comment]
> I'm thinking about doing something about this for our own purposes

What are you thinking of doing?

**Comment by cjblomqvist** [comment]
> > I'm thinking about doing something about this for our own purposes
> 
> What are you thinking of doing?

Automatic fixup 😊 Specifically when doing context.Add/remove we're looking into handling navigation properties on "neighboring" entities.

Eg table A and B are "joined" by table C (one-to-many on one side, one-to-one on the other). When a C is added to the context (eg context.Add) we'll automatically add C to navigation properties A.ListOfManyCs (List<C>) and B.MyC. Same when removed, but obviously removed from each navigation property. Same when moved (but less of a use case for us).

@ajcvickers

**Comment by ajcvickers** [comment]
@cjblomqvist EF Core already does this.

**Comment by cjblomqvist** [comment]
Hmm I see. I interpreted #23940 like it wasn't/won't be (before SaveChanges). I created a repro based on an example in that issue, but maybe I'm missing something/there's something wrong with the code?

(or maybe I was unclear that I meant before SaveChanges) 

https://dotnetfiddle.net/J2uzXJ

**Comment by ajcvickers** [comment]
@cjblomqvist For deleted entities, this is tracked by #29486.

**Comment by cjblomqvist** [comment]
> > That part of the changed proved problematic and very breaking. Cascade of states happens immediately by default, but fixup only of navigations only happens after the entity is really deleted by SaveChanges.
> 
> @ajcvickers - could you explain why this was problematic? I'm thinking about doing something about this for our own purposes, but if you already have good reasons why one should not do this then I'd prefer not to waste the time :-)

One can find our solution here: https://github.com/dotnet/efcore/issues/29486#issuecomment-1902317993
