### ISSUE TITLE
Query: Using DbSet property in QueryFilter throws exception

### ISSUE THREAD

**Issue by HappyNomad** [aspnet/EntityFrameworkCore#10117]
How would I construct a filter that has the following semantics?  I want one that actually works and runs in the database.

	modelBuilder.Entity<ProductDetail>().HasQueryFilter( d =>
		Orgs.Single( o => o.ID == TenantID ).PurchasedNames.Split( new char[] { ',' } ).Contains( d.Name )
	);

My attempt to run this results in:

>Microsoft.EntityFrameworkCore.Query:
>	Warning: The LINQ expression 'where value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Org]).Single(o => (o.ID == __TenantID_0)).PurchasedNames.Split(new [] {,}).Contains([d].Name)' could not be translated and will be evaluated locally.
>
>Exception thrown: 'System.ArgumentNullException' in Microsoft.EntityFrameworkCore.dll
>Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
>
>System.ArgumentNullException: Value cannot be null.
>Parameter name: querySource
>   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
>   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.FindEntityType(IQuerySource querySource)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.EntityQueryableExpressionVisitor.VisitConstant(ConstantExpression constantExpression)
>   at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMember(MemberExpression node)
>   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
>   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
>   at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
>   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
>   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
>   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
>   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
>   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
>   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitNewArray(NewArrayExpression node)
>   at System.Linq.Expressions.NewArrayExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
>   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
>   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
>   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMember(MemberExpression node)
>   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
>   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
>   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
>   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
>   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
>   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
>   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitNewArray(NewArrayExpression node)
>   at System.Linq.Expressions.NewArrayExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
>   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
>   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
>   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMember(MemberExpression node)
>   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
>   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
>   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
>   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
>   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
>   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
>   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitNewArray(NewArrayExpression node)
>   at System.Linq.Expressions.NewArrayExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
>   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
>   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
>   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
>   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitNewArray(NewArrayExpression node)
>   at System.Linq.Expressions.NewArrayExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
>   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
>   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionVisitorBase.VisitLambda[T](Expression`1 node)
>   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMethodCall(MethodCallExpression node)
>   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
>   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMember(MemberExpression node)
>   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
>   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
>   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
>   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
>   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database)
>   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass24_0`1.<CompileAsyncQuery>b__0()
>   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
>   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
>   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
>   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
>   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
>   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
>   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)

**Comment by smitpatel** [comment]
Is `Orgs` dbset?

**Comment by HappyNomad** [comment]
@smitpatel  Yes.

**Comment by smitpatel** [comment]
It is not supported atm.

**Comment by HappyNomad** [comment]
I see.  Is there another issue for it, or is this the one and only?

**Comment by HappyNomad** [comment]
After further thought, I see how to work with this limitation in place.  Rather than joining on `Name`, I'll introduce a `ThingContainer` entity to my model.

    modelBuilder.Entity<ThingContainer>().HasQueryFilter( c =>
        c.PurchasedBy.Any( o => o.ID == TenantID )
    );

But this contains a navigation property (#8881) - they aren't supported yet either! 😖

For the current issue, anyway, you can at least provide a nicer exception message.

**Comment by anpete** [comment]
Confirmed already fixed
