### ISSUE TITLE
RevEng: Multi-line DEFAULT SQL results in invalid C#

### ISSUE THREAD

**Issue by chadwixk** [aspnet/EntityFrameworkCore#10134]
Describe what is not working as expected.
When creating the model for table columns that have a default value set via a function, the scaffolding is creating incorrect syntax in the ModelCreating.

In sql server, I have a column with a "Default Vale or Binding" set as `dbo.Set_To_Zero`.

The resulting code created in `protected override void OnModelCreating(ModelBuilder modelBuilder)` was:

``` C#
.HasDefaultValueSql("
/****** Object:  Default dbo.Set_To_Zero    Script Date: 8/20/01 1:54:04 PM ******/

/****** Object:  Default dbo.Set_To_Zero    Script Date: 8/6/01 11:18:06 AM ******/

CREATE DEFAULT Set_To_Zero
\tAS 0




");
```

### Steps to reproduce
Have a sql server column with a Default Value or Binding set to a db function. 
Use DB Scaffold-DbContext to have it create the models.
View result in the resulting Context.cs file.

### Further technical details
EF Core version: (found in project.csproj or packages.config)
    ```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.1" PrivateAssets="All" />
```
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: e.g. Visual Studio 2017

**Comment by smitpatel** [comment]
What is your table definition in database?

**Comment by bricelam** [comment]
RevEng shouldn't sanitize it since this is just how the database returned it. Migrations uses a verbatim string literal for multi-line strings. We should do the same in RevEng.
