### ISSUE TITLE
HasIndex does not work as expected

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [aspnet/EntityFrameworkCore#10135]
I'm trying to map something like that:
```
            b.HasOne(x => x.AppUser)
                .WithMany()
                .IsRequired();

            b.HasIndex(x => x.AppUser)
                .HasName("IX_eo_MyTable_AppUser");
```
MyTable class:
```
public class MyTable() {
...
public virtual User AppUser { get; set; }
...
}
```

When I run the app I receive the following error:
_One or more errors occurred. (Cannot call Property for the property 'AppUser' on entity type 'MyTable' because it is configured as a navigation property. Property can only be used to configure scalar properties.)_

It is fine when I remove the code:
```
            b.HasIndex(x => x.AppUser)
                .HasName("IX_eo_MyTable_AppUser");
```

Could please someone help me? Thanks.

### Further technical details
EF Core version: 2.0.0
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 2.0.0
Operating system: Windows 10 Pro x64 (1703)
IDE: Visual Studio Community 2017

**Comment by smitpatel** [comment]
@denis-pujdak-adm-it - Indexes can be defined on scalar properties only which would be mapped to a database column. You are trying to use HasIndex with a navigation property which is invalid and would throw exception as above. If your intention is to define an index on the foreignkey property used by the relationship then you need to call HasIndex on ForeignKey property and not the navigation.

You can configure foreignkey using `HasForeignKey` method when defining your relationship. And use the same property name for `HasIndex` call.
Given you class, it seems that you are using shadow property (you can use CLR property too if needed) the code would be something like this.
```C#
            b.HasOne(x => x.AppUser)
                .WithMany()
                .HasForeignKey("AppUserId") // Creates a column in database as AppUserId to store the FK value
                .IsRequired();

            b.HasIndex("AppUserId")
                .HasName("IX_eo_MyTable_AppUser");
```

**Comment by denis-pujdak-adm-it** [comment]
Thanks @smitpatel it's working. Cheers.

**Comment by ajcvickers** [comment]
Triage: we should throw a better message that doesn't reference "Property" since the app didn't call "Property" in this case.
