### ISSUE TITLE
Query: add translator for Nullable<>.GetValueOrDefault()

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#10153]
Could be translated to COALESCE

**Comment by avinash-phaniraj-readify** [comment]
@ajcvickers 

I wanted to check with you, what your current thoughts on this one is ? 
Is GetValueOrDefault going to be translated to SQL ? And do you have a rough timeline in mind ?

Background: our current code base (Linq2Sql) has very many complex queries that use this. Without the sql translation, the queries are being partially evaluated in memory and hence the question.

**Comment by ajcvickers** [comment]
@smitpatel @maumar Let's talk about this one in triage.

**Comment by maumar** [comment]
@avinash-phaniraj-readify are any of the queries use the function on a Nullable<DateTime> columns? This function could be easily translated to COALESCE, but https://github.com/aspnet/EntityFrameworkCore/issues/12797 makes it problematic for datetime.

**Comment by malikhassan85** [comment]
The query that we're referring to uses GetValueOrDefault() on Nullable<int> property, also, it has been used in so many places  (more than 3000). That's why we want to know if there is any plan to change this behaviour and translate it to the property SQL to avoid on memory evaluation.

**Comment by maumar** [comment]
fixed in 4cd4301c27ace85d24ef95dbb7eeee28d27b58d2

**Comment by ajcvickers** [comment]
Re-opening to consider including in 2.1.5 patch.

**Comment by ajcvickers** [comment]
@maumar Please create a PR to port this to release/2.1, but don't merge it. Also, please add appropriate quirking--let's discuss if there are issues.

(There is a new process in shiproom and we need to have the final PR to the release branch in order to get approval. Doing this today would be great so we can take this issue tomorrow.)

**Comment by maumar** [comment]
additional fix (constraining to numeric types only) has been added here: 08cf8533053bc3cf813fb5467aa791ca65095a57

**Comment by ajcvickers** [comment]
@maumar The branch is now ready for this to be merged.

**Comment by maumar** [comment]
merged to 2.1 branch in 74860990fad0c7dd73a36325b046da5966f13d67

**Comment by optiks** [comment]
Confirming that this is now fixed in 2.1.4. Many thanks team.
