### ISSUE TITLE
test environment - "SupportsHiddenColumns": false by default - why?

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#10150]
Latest versions of localdb (build 13.0.4001 or later) supports system versioned tables, so i should be "true" since this is available in the localdDB version that comes with VS 2017

**Comment by smitpatel** [comment]
We could. So far our testing SqlServer version has been 2014.

**Comment by ErikEJ** [comment]
Maybe it is time to update, that is 2 released versions behind 😄
