### ISSUE TITLE
Already defined null (Suggestion)

### ISSUE THREAD

**Issue by ralmsdeveloper** [aspnet/EntityFrameworkCore#10176]
I think this could be removed

https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore/DbContext.cs#L544

**Comment by ajcvickers** [comment]
@ralmsdeveloper Send a PR? 😄

**Comment by ralmsdeveloper** [comment]
Yes I'll do it!

**Comment by ajcvickers** [comment]
@ralmsdeveloper Thanks for including in that PR. We will close this once that PR is merged.
