### ISSUE TITLE
1-1 Foreign Key Unique Constraint is missing NULL filter

### ISSUE THREAD

**Issue by bjcull** [aspnet/EntityFrameworkCore#10171]
When I created my model back on EFCore 1.x the unique constraint on a 1-1 foreign key had a filter so I could have multiple nulls. After upgrading to EFCore 2.x new databases are created running the exact same migrations, but they don't create the filter.

### Steps to reproduce  
**Create 1-1 Foreign Key**  

    builder.Entity<Attempt>()
        .HasOne(q => q.Dishonour)
        .WithOne(v => v.Attempt)
        .HasForeignKey<Attempt>(q => q.DishonourId);

**Resulting Index from EFCore 1.x**
![image](https://user-images.githubusercontent.com/184263/32076326-dc242f3c-ba9f-11e7-9417-3706142e9cc3.png)

**Resulting Index from EFCore 2.x**
![image](https://user-images.githubusercontent.com/184263/32076343-e8fe8d2e-ba9f-11e7-8205-de6736c3a27f.png)

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017
Sql Server: 13.0.4001

**Comment by bjcull** [comment]
Looks like it could be an issue with migrating from 1.x to 2.x.

After creating my next migration, I noticed all of my indexes and foreign keys were dropped and recreated. While this is an OK thing for me, I didn't see this in the migration documentation and was not aware I'd have to do it.

To resolve this issue, can you please add a section to the migration document (https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/) mentioning that you should create a new migration to handle changes between the old and new migration code.

**EFCore 1.x migration code**

    migrationBuilder.CreateIndex(
        name: "IX_Attempts_DishonourId",
        table: "Attempts",
        column: "DishonourId",
        unique: true);

**EFCore 2.x migration code**  

    migrationBuilder.CreateIndex(
        name: "IX_Attempts_DishonourId",
        table: "Attempts",
        column: "DishonourId",
        unique: true,
        filter: "[DishonourId] IS NOT NULL");

**Comment by ralmsdeveloper** [comment]
Hello @bjcull,

https://docs.microsoft.com/en-us/ef/core/miscellaneous/1x-2x-upgrade

**Comment by ajcvickers** [comment]
@bjcull Thanks for reporting this. It looks like the issue is that in 1.1, that filter was applied by convention, whereas in 2.0 is is now explicitly scaffolded. We missed that this means that we need to this when running 2.0 code over migrations generated by 1.1 so that we can correctly infer the filter again in these cases.
