### ISSUE TITLE
Migrations: Unused using generated

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#10175]
The following namespaces are generated in the migraiton designer and model snapshot files.
``` csharp
using Microsoft.EntityFrameworkCore.Migrations; // Not used by snapshot
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
```

I suspect it's due to annotations that we later filter out.

**Comment by Tasteful** [comment]
When creating a new migration file with version EFCore 2.0.0 I got a lot of "project" references in the usings that not are used and if I change the namespace of any of them in the application code the migrations script will get compillation errros if I not removing/changing them manually.

![image](https://user-images.githubusercontent.com/357589/34648884-99525be2-f3a3-11e7-9ae2-f1716833bb55.png)
