### ISSUE TITLE
SeedData migration "oversight"

### ISSUE THREAD

**Issue by mrswain** [aspnet/EntityFrameworkCore#10184]
I believe the new SeedData code has an oversight when generating the migration statements.
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L1595

The line above does not filter out keys with temporary values, thus that key would be propgated to the database (an InsertData migration operation on SQL Server sets identity insert on).

I think the proper code should be to add a 
```C#
.Where(col => !col.IsRead || !col.Entry.HasTemporaryValue(col.Property))
```
Before the Select on both the Columns and Values lines, as that should filter out temporary keys.

**Comment by AndriySvyryd** [comment]
Temporary values are not supported as they would prevent calculating the migrations correctly.
