### ISSUE TITLE
[Question] - release notes for 1.1.3?

### ISSUE THREAD

**Issue by dazinator** [aspnet/EntityFrameworkCore#10208]
Are there any release notes or anything for 1.1.3? I would just like to see what changed.

**Comment by bricelam** [comment]
The best source of truth is [the issues](https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aissue+milestone%3A1.1.3+is%3Aclosed)

**Comment by ajcvickers** [comment]
@danroth27 Do you know if release notes is something we are doing for 1.1.3?
