### ISSUE TITLE
Saving null SqlGeography or SqlGeometry params throws

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#10214]
From https://github.com/aspnet/EntityFrameworkCore/pull/10110#issuecomment-341679006 reported by @Xtrophic

Sending null geography / geometry fields throws an exception:
ArgumentException: UdtTypeName property must be set only for UDT parameters.

**Comment by Xtrophic** [comment]
Found an easy fix for the issue. 
File: \src\EFCore.SqlServer\Storage\Internal\SqlServerUdtTypeMapping.cs 
```cs
         private void SetUdtTypeName(DbParameter parameter)
         {
             NonCapturingLazyInitializer.EnsureInitialized(
                 ref _udtTypeNameSetter,
                 parameter.GetType(),
                 CreateUdtTypeNameAccessor);
            
             if (parameter.Value != null && parameter.Value != DBNull.Value)
                 _udtTypeNameSetter(parameter, UdtTypeName);
         }
```
Where the addition is the line:
```cs
if (parameter.Value != null && parameter.Value != DBNull.Value)
```
This will prevent any UDT from beeing set in the SqlCommand when the value is null / dbnull (which causes the exception).

**Comment by ajcvickers** [comment]
@Xtrophic Would you consider submitting a PR?

**Comment by Xtrophic** [comment]
First time doing fork/pr etc. Let me know if there is something that should have been done differently.
