### ISSUE TITLE
EF Core v2.0 vs v1.1.2 performance

### ISSUE THREAD

**Issue by jotab123** [aspnet/EntityFrameworkCore#10220]
I am testing (against SqlExpress) the performance of Entity FrameWork Core v2.0, having worse results than v1.1.2.

The test takes the elapsed time of one SaveChanges for a number of entities.

100 entities: 
    v1.1.2: 0.030 seconds
    v2.0.0: 0.12 seconds (4 times slower aprox.)

1000 entities: 
    v1.1.2: 0.68 seconds
    v2.0.0: 1.04 seconds (0.4 times slower aprox.)

10000 entities: 
    v1.1.2: 3.59 seconds
    v2.0.0: 3.59 seconds (same time aprox.)

For few entities, the performance drops a lot. Does anyone know how to improve it?

Test code:

```

using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;

namespace ConsoleApp1
{
    /*
     * Performance: Entity Framework Core v1.1.2 vs v2.0.0
     * 
     */

    class Program
    {
        static void Main(string[] args)
        {
            const int count = 10000; // change this at your own !!!

            using (var test = new EFSqlServerContext())
            {
                // batch
                test.Insert(count);

                // time
                var watch1 = new Stopwatch();
                watch1.Start();

                test.SaveChanges();

                watch1.Stop();
                Debug.WriteLine("######### {0} Entities: {1} seconds", count, watch1.Elapsed.TotalSeconds);
            }
        }
    }

    public class EFSqlServerContext : DbContext
    {
        public EFSqlServerContext()
        {
            Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Data Source=.\sqlexpress;Initial Catalog=EFPerformanceTest;Integrated Security=True;MultipleActiveResultSets=True");
        }

        public DbSet<MyType> MyTypes { get; set; }


        public void Insert(int count)
        {
            for (int i = 0; i < count; i++)
            {
                var item = Activator.CreateInstance(typeof(MyType));
                this.Add(item);
            }
        }
    }

    [Serializable]
    public class MyType
    {
        [Key]
        public int Id { get; set; }

        public int PropertyA { get; set; }

        public int PropertyB { get; set; }

        public int PropertyC { get; set; }
    }
}
```

**Comment by Diaskhan** [comment]
**jotab123** 

**Questions**
1.Could U provide  solution of ure tested projects ?
2. U must profile 
`  var item = Activator.CreateInstance(typeof(MyType));`
If there some diference in results, this topic is similar to [https://github.com/dotnet/coreclr]
Similar to reflection perfomance !

**Conclusions**
1.U could profile yore program by profiling tools!
2.U could gather a statistic !
```
  public void Insert(int count)
        {
            for (int i = 0; i < count; i++)
            {
                //log here time
                var item = Activator.CreateInstance(typeof(MyType));
                //log here time
                this.Add(item);
                //log here time
            }
        }

```
3. Try to not use reflection methods 
[http://geekswithblogs.net/mrsteve/archive/2012/02/11/c-sharp-performance-new-vs-expression-tree-func-vs-activator.createinstance.aspx]
The reflection method has overhead!

**Comment by roji** [comment]
@jotab123 the benchmark code posted above is problematic in that it has no warm-up phase... The slowdown you're seeing may simply be a result of longer start-up times (e.g. when building the model) - that coincides well with the fact that the slowdown disappears with large row numbers.

It's recommended to not roll your own benchmarks in this way and to avoid all the pitfalls by using BenchmarkDotNet.

There also doesn't seem to be any justification for instantiating your objects via Activator, why not simply instantiate them with new?

**Comment by Diaskhan** [comment]
![image](https://user-images.githubusercontent.com/15046677/37253254-8a8edb5c-2559-11e8-9560-56058493b805.png)

In scenario where all models are statically(static assembly) compilled the best choise is use **New operator**

In the second one when entity load dynamycally from assembly, is only Activator works !

**Comment by csancheztfs** [comment]
I don't measure times for Activator.CreateInstance. I only take times for EFSqlServerContext.Save Method:

watch1.Start();
test.SaveChanges();
watch1.Stop();

Activator.CreateInstance is not taken into account in the timing...

**Comment by Diaskhan** [comment]
Dear Sanchez! The main problem!  That is Activator.CreateInstance create instance by reflection nature! I think when u're creating reflection object when u invoke save method! It acess objects via reflection !

Could u provide demo VS projects for 1.1 and 2.0! I have a time to test it ! Actually i'm interested in reflection nature of net core!
