### ISSUE TITLE
DbCommand execution time can be wrong in logs

### ISSUE THREAD

**Issue by gallivantor** [aspnet/EntityFrameworkCore#10223]
Whenever it runs a query against the DB, EF Core writes a log line like this:

Executed DbCommand (XXXms) [Parameters=.....

The XXX is correct if the query takes less than 1 second. However, my query took 2.5 seconds for example and it was logged as 500ms.

I suspect this is a classic case of using TimeSpan.Milliseconds instead of TimeSpan.TotalMilliseconds

### Steps to reproduce
Execute a command which takes longer than 1 second, and view the log entry that EF Core generates.

A good example here is running a Migration which creates an index, an operation that often takes a few minutes to complete.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS 2017

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/b86eb8548a0deedc1199c3b4bc6b8632bd7824e3/src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs#L111

**Comment by ErikEJ** [comment]
And also several other places in the same file...
