### ISSUE TITLE
Test: Query: Skip/Take without order by gives rise to non-deterministic results in tests

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10231]
https://github.com/aspnet/EntityFrameworkCore/blob/b86eb8548a0deedc1199c3b4bc6b8632bd7824e3/src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs#L1168-L1178

&

https://github.com/aspnet/EntityFrameworkCore/blob/b86eb8548a0deedc1199c3b4bc6b8632bd7824e3/src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs#L1305-L1314

Providers where the default ordering of records is not same as ordering by PK fails on the tests. We generate warning for skip/take without order by. We should not write non-deterministic tests.

**Comment by smitpatel** [comment]
Also following 
https://github.com/aspnet/EntityFrameworkCore/blob/b86eb8548a0deedc1199c3b4bc6b8632bd7824e3/src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs#L936-L959

For `Where_subquery_anon_nested` we should change the City predicate to seattle so that it gives 1 result. At present there are no results so even though #8956 occurs for it too, it hides underneath.

**Comment by maumar** [comment]
fixed in c3955ec1e3ceed1430333bf64ff112cf53736423
