### ISSUE TITLE
Make dynamic query filters more flexible than private field in dbcontext

### ISSUE THREAD

**Issue by nphmuller** [aspnet/EntityFrameworkCore#10274]
I'm trying to implement a tenant id query filter where the tenant id differs p. request. But I'm running into some limitations.

Take the following example:
``` c#

    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new MyContext(new TenantService(1)))
            {
                var res1 = context.Set<MyEntity>().ToList();
            }
            using (var context = new MyContext(new TenantService(2)))
            {
                var res2 = context.Set<MyEntity>().ToList();
            }
        }
    }

    public class MyEntity
    {
        public int Id { get; set; }
        public int TenantId { get; set; }
    }

    public class TenantService
    {
        public TenantService(int tenantId)
        {
            TenantId = tenantId;
        }

        public int TenantId { get; }
    }

    public class MyContext : DbContext
    {
        private readonly TenantService tenantService;

        public MyContext(TenantService tenantService)
        {
            this.tenantService = tenantService;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase("filtertest");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<MyEntity>().HasQueryFilter(e => e.TenantId == tenantService.TenantId);
        }
    }
```

I'm expecting `res2` to only contains entities with `TenantId == 2`, but it only contains entities where `TenantId == 1`. The only way to make this work is to introduce a private field in DbContext that contains the tenantId.

It would be nice if the filter was more flexible and could create dynamic query filters in more cases than just a field in the same DbContext.

The example above is a more simplified version of the solution I'm trying to create. I'm creating a FilterService class that gets injected in the DbContext and gets called by `OnModelCreating`. This service takes care of all the filter responsibilities (and allows additional features like enabling/disabling the filter). Currently it seems impossible to implement this service properly without introducing part of its responsibility in the DbContext itself. Namely the value of each filter that exists (and states like enabled/disabled p. filter).

**Comment by nphmuller** [comment]
I've set up a Gist which shows my query filter use-case and the code I had to write to get it working.
https://gist.github.com/nphmuller/8891c315d79aaaf720f9164cd0f10400

**Comment by smitpatel** [comment]
@nphmuller - Which version of EF Core?

**Comment by nphmuller** [comment]
Sorry! 2.0

**Comment by smitpatel** [comment]
Can you try with 2.0.1 package? It could be possibly working.

**Comment by nphmuller** [comment]
It's working in 2.0.1-rtm-203. Great surprise!
