### ISSUE TITLE
RevEng: bool property with default is marked as nullable even if it is non-nullable in database 

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10305]
Model
```C#
    public class Blog
    {
        public int Id { get; set; }
        public bool? Value { get; set; }
    }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
            var property = modelBuilder.Entity<Blog>().Property(e => e.Value);
            property.HasDefaultValue(true);
            property.IsRequired(true);

        }
```
Generated this table
```SQL
      CREATE TABLE [Blogs] (
          [Id] int NOT NULL IDENTITY,
          [Value] bit NOT NULL DEFAULT 1,
          CONSTRAINT [PK_Blogs] PRIMARY KEY ([Id])
      );
```
Which reverse engineered this model
```C#
    public partial class Blogs
    {
        public int Id { get; set; }
        public bool? Value { get; set; }
    }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blogs>(entity =>
            {
                entity.Property(e => e.Value).HasDefaultValueSql("((1))");
            });
        }
```

We are incorrectly making the property nullable even though it is not.

**Comment by alextof** [comment]
It happens again with .NET Core 2.2.102, latest EF Core Power Tools & Azure SQL Database performing reverse engineering with Power Tools.

**Comment by sgxman** [comment]
> It happens again with .NET Core 2.2.102, latest EF Core Power Tools & Azure SQL Database performing reverse engineering with Power Tools.

I also have this exact problem. 
In SQL-Server: Bit column, NOT NULL, Default Value ((1))
Class gets generated as: public bool?

/Jonny

My Environment
------------------
Visual Studio 2017 (all updates)
SQL Server 2014 SP1
EF Core Power Tools - 2.2.12
EF Core 2.1.8
NET Core 2.2.102

**Comment by ajcvickers** [comment]
@alextof @sgxman This is by-design when the default value in the column is not the same as the CLR default for the type. Once #15182 is implemented, we may generate something different.
