### ISSUE TITLE
EntityFramework Core Scaffolding error - Cannot find path '[path]' because it does not exist.

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#10327]
From VS issues:

Customer created an ASP.NET Core project in Visual Studio and wanted to reverse engineer his database into an EF model using the Scaffold-DbContext from EF Core.  However when he ran this command from the Package Manager Console:

Scaffold-DbContext 'Server=###########.database.windows.net;Database=###########;user id=#########;password=#######;' Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

He received the following error message:

The running command stopped because the preference variable 'ErrorActionPreference' or common parameter is set to Stop: Cannot find path 'C:\\Users\\Backup\\Source\\Repos\\Xxxx\\ServiceFabric\\CoreAPI\\CoreAPI\\CoreAPI.sfproj\\bin\\Debug\\' because it does not exist.

Repro steps:

1. Create a Service Fabric project in VS
2. Select  ASP.NET Core next
3. Select WebAPI next
4. Run Scaffold-DbContext (I used https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db as the basis for the repro)

Result: The running command stopped because the preference variable 'ErrorActionPreference' or common parameter is set to Stop: Cannot find path 'C:\\Users\\Backup\\Source\\Repos\\Xxxx\\ServiceFabric\\CoreAPI\\CoreAPI\\CoreAPI.sfproj\\bin\\Debug\\' because it does not exist.

Workaround: If you ensure that the ASP.NET Core project is set to the startup project, it resolves the issue.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by bricelam** [comment]
We should consider explicitly blocking Service Fabric startup projects like we do Docker projects.

**Comment by ajcvickers** [comment]
Note from triage: we will consider blocking all/some Service Fabric projects explicitly if they are known not to be compatible with EF Core.

**Comment by divega** [comment]
@bricelam @ajcvickers trying to understand if this issue was fixed or just closed. Can you help?

**Comment by bricelam** [comment]
I think it's fixed... Looks similar to other fixes I made while enabling VB and F#

**Comment by MattHartz** [comment]
Doesn't look fixed to me.

**Comment by smitpatel** [comment]
@MattHartz - Can you provide a full repro solution so we can make sure it has been fixed for all incompatible project types?

**Comment by subinmathewit** [comment]
I am also facing the same issue with my service fabric application with Stateless Asp.Net Core Service(.Net Framework). Is there any fix for this?

**Comment by rishabh0202** [comment]
Do check your default project (it should be the on which you have installed EF Core) before running the command on Package Manager Console. It worked for me.
