### ISSUE TITLE
DbFunction schema not output if any arguments are nullable navigation properties

### ISSUE THREAD

**Issue by danobri** [aspnet/EntityFrameworkCore#10421]
When calling a UDF as described in #7368, if the argument being passed to the UDF is a property of a nullable navigation property, the schema prefix is not being output in the generated query despite being properly specified in a DbFunction annotation.

For example:

`context.Widgets.Select(w => context.Foo(w.SomeNullableNavigationProperty.Name)) ;`

 If the nav prop is NOT nullable, the schema is output and the query succeeds:

`context.Widgets.Select(w => context.Foo(w.SomeNOTNullableNavigationProperty.Name)) ;`

I have tried doing a null check on the nav prop, but it doesn't resolve the issue:

`context.Widgets.Select(w => context.Foo(w.SomeNullableNavigationProperty != null ? w.SomeNullableNavigationProperty.Name : string.Empty)) ;`

In all other respects the query is generated correctly.  If I cut and paste from the debug window, and manually add the schema prefix, the query runs without any issues. 

Please let me know if there is another workaround I can try, as I won't be able to use UDFs in my solution if this scenario is not currently supported.

I am using the latest stable version of EF Core (2.0.1).

**Comment by smitpatel** [comment]
Repro code
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database

                db.AddRange(new Blog
                {
                    Posts = new List<Post>
                    {
                        new Post()
                    }
                });
                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var query = db.Posts.Select(w => MyContext.Method(w.Blog.Name))
                    .ToList();

            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        [DbFunction(Schema = "dbo")]
        public static bool Method(string name)
        {
            throw new NotImplementedException();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public int Id { get; set; }
        public int? BlogId { get; set; }
        public Blog Blog { get; set; }
    }
}
```

**Comment by pmiddleton** [comment]
@smitpatel  - I'm taking a look at it.

**Comment by smitpatel** [comment]
Will be fixed by https://github.com/aspnet/EntityFrameworkCore/pull/10370

https://github.com/aspnet/EntityFrameworkCore/blob/efc0025d555b7f56f64c4a052bf0329a1119c414/src/EFCore.Relational/Query/Expressions/SqlFunctionExpression.cs#L130-L137

That code eats schema. It happens because the argument is reducible expression when its nullable navigation access causing new SqlFunctionExpression to be formed without schema.

#10370 Updates that code path. I will add test.

Sorry @pmiddleton - I was too curious to find out why this is happening.

**Comment by pmiddleton** [comment]
Hey wait a minute - I just got to that line and fixed it myself.

No fair - I had to start dinner for my daughter!

**Comment by smitpatel** [comment]
@pmiddleton - You can submit PR if you want to :)

**Comment by pmiddleton** [comment]
@danobri - unfortunately I don't see anyway to work around this right now, other than to make the navigation property non-nullable.

**Comment by pmiddleton** [comment]
@smitpatel - that's ok as long as you have it fixed :)

**Comment by pmiddleton** [comment]
@danobri - actually I just did have one idea which is worth a shot.  You can try reversing your query.  Use the nullable object as the root of the query instead of work out from there.  I don't know your table structure but if it is a simple query it might work.  It's worth a shot.

**Comment by danobri** [comment]
@pmiddleton - Thanks for addressing the issue so quickly, and for the idea for the workaround.  Any guess at when this might make it into a release?

Unfortunately I don't think I can reverse the query, as the UDF has multiple arguments that are nullable properties.  The purpose of the UDF is to create a programmatic name for the primary entity that concatenates and formats values from a number of foreign entities, several of which are nullable.  I could theoretically do the joining inside the UDF, but it would not perform as well since it would be a query with multiple joins  rather a deterministic function.  If EF Core supported table valued or inline functions I would probably go that route, but for the time being it seems like views are probably going to be my best option.
