### ISSUE TITLE
Inconsistent SQL queries in inheritance + FromSql scenarios

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#10501]
For queries that use `FromSql()` on an entity type that has inheritance we create an additional WHERE clause checking for the discriminator, but only if the query is composed over. 

On one hand this is following the general rule that if you don't add any operators to a `FromSql()` query, we will just execute the SQL you provided. But on the other hand, if the reason to add the additional checks is that we don't trust the SQL query provided to only contain rows for the types we know about, I would expect us to add the checks regardless. 

Repro:

``` C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ConsoleAppFoo
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new MyContext())

            {
                context.Database.EnsureCreated();

                var hey = "hey";

                var p1 = context.People.FromSql($@"
                    SELECT TOP(1) [x].[Id], [x].[Discriminator], [x].[Name], [x].[Year]
                    FROM [People] AS [x]
                    WHERE [x].[Discriminator] IN ('Student', 'Person') AND ([x].[Name] = {hey})")
                   .AsEnumerable().FirstOrDefault();

                //exec sp_executesql N'
                //        SELECT TOP(1) [x].[Id], [x].[Discriminator], [x].[Name], [x].[Year]
                //        FROM[People] AS[x]
                //        WHERE[x].[Discriminator] IN(''Student'', ''Person'') AND([x].[Name] = @p0)',N'@p0 nvarchar(4000)',@p0=N'hey'


                var p2 = context.People.FromSql($@"
                    SELECT TOP(1) [x].[Id], [x].[Discriminator], [x].[Name], [x].[Year]
                    FROM [People] AS [x]
                    WHERE [x].[Discriminator] IN ('Student', 'Person') AND ([x].[Name] = {hey})")
                    .FirstOrDefault();


                //exec sp_executesql N'SELECT TOP(1) [p].[Id], [p].[Discriminator], [p].[Name], [p].[Year]
                //FROM(
                //                        SELECT TOP(1)[x].[Id], [x].[Discriminator], [x].[Name], [x].[Year]
                //                        FROM[People] AS[x]
                //                        WHERE[x].[Discriminator] IN(''Student'', ''Person'') AND([x].[Name] = @p0)
                //) AS[p]
                //WHERE[p].[Discriminator] IN(N''Student'', N''Person'')',N'@p0 nvarchar(4000)',@p0=N'hey'



            }
        }
    }


    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }
        public DbSet<Student> Students { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                @"server=(localdb)\mssqllocaldb;database=foo;integrated security=yes;");
        }

    }

    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class Student : Person
    {
        public int Year { get; set; }
    }
}
```

**Comment by ajcvickers** [comment]
Notes from triage:
* FromSQL does inheritance correctly in both cases; this issue is not about that, it's about the `where` cause being there
* If there are discriminators in your data that are not defined in the model, then this could be considered a case where the model doesn't match the database, and as such it can be okay to have what might be an "unexpected" difference in behavior in some scenarios
* Given this, we should just remove the `where` clause everywhere--if the database matches the model, then the functionality will be the same but with less SQL

Leaving open to get input from @anpete

**Comment by ajcvickers** [comment]
New decision from triage is that FromSql should use semantic information from the model, including the type hierarchy. Otherwise doing FromSql on a DbSet of a subtype would by default try to return entities of the parent type.

**Comment by ajcvickers** [comment]
Also, it seems like the filtering is not done currently when FromSql is done on a sub type, so this change would fix that issue as well.
