### ISSUE TITLE
“Parameter count mismatch” error during adding Entity Framework migration under .NET Core 2.0

### ISSUE THREAD

**Issue by Glebby** [aspnet/EntityFrameworkCore#10504]
After migration of my project to .NET Core 2.0, fresh install of Visual Studio 15.5 and .NET CORE sdk 2.1.2, I am having an error when trying to add a migration using EF Core.

```
C:\Projects\SQLwallet\SQLwallet>dotnet ef migrations add IdentityServer.
An error occurred while calling method 'BuildWebHost' on class 'Program'.
Continuing without the application service provider. Error: Parameter count mismatch.


Done. To undo this action, use 'ef migrations remove'
```

The program.cs looks like:
```
    public class Program
    {

        public static IWebHost BuildWebHost(string[] args, string environmentName)
        {...}

        public static void Main(string[] args)
        {


            IWebHost host;
            host = BuildWebHost(args, "Development");


```

As a result an empty migration class is created, with empty Up() and Down() methods.

The migrations worked fine while on Core 1.0. I have a IDesignTimeDbContextFactory implemented, and my DBContext class has a parameterless constructor, so it could not be the reason.

**Comment by bricelam** [comment]
In order for the EF Core Tools to use `BuildWebHost`, it needs to match the [prescribed signature](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/#update-main-method-in-programcs).

The error isn't great though; we should probably make it say something like *No suitable BuildWebHost method was found*...

Note, this code lives in [aspnet/Hosting](https://github.com/aspnet/Hosting) now.

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/Hosting/issues/1295

**Comment by bricelam** [comment]
Re-opening. The Hosting code has been updated to not use invalid methods, but we'll have to update the message on our side.
