### ISSUE TITLE
Query: SqlGeneration optimizations are misplaced for providers to override

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10513]
In DefaultQuerySqlGenerator, we have private method `ApplyOptimizations` which runs few visitors over the expression to make it suitable for SqlGeneration. At present they are called from our base methods (providers does not have access to the method). We have provided hooks for providers to override the code but all those hooks are before we run optimizations. Which may not be correct in all cases.
In the case of Oracle provider, it needs to exclude ordering by constant/parameter. But by the time we apply optimization it has already processed and printed "ORDER BY" and there is no way to back out.

There are potentially multiple ways to resolve this.
- This is second time, we ran into issue of backing out. First one was #9951 . Ideally, the SQL generation and sql tampering should be separate visitor so generator knows what is exactly the tree before entering any node.
- If we try to optimize both of them by combining into 1 visitor (like current one) then we should pull out all optimizations in QM visitor which are not going to change based on parameters.
- Another approach would be to make method protected for providers to call it themselves.
- Or add more hooks so that providers can get expression while visiting after processing.

This also has some intersection with #9143, #10514 
#9143 covers BooleanConditionTranslatingExpressionVisitor which is not needed for postgre but we are applying it anyway in ApplyOptimizations without considering the providers.
#10514 Null semantics at present happens in ApplyOptimizations so providers have no way to influence or opt out of it.

**Comment by smitpatel** [comment]
This would be resolved by introducing ExpressionVisitors before the query is compiled into delegate, so that providers can add/update them. (mainly working based on ShapedQueryExpressionVisitors)

**Comment by MaxG117** [comment]
I need this fixed -- the private fields `_typeMapping` (already mentioned in #9143) and `_valueConverterWarningsEnabled` are used in multiple public virtual methods in `DefaultQuerySqlGenerator`. If I only need to override some of these virtual methods, I lose the benefit of these private fields, and the only solution is to override ALL the virtual methods that use these private fields These private fields must be changed into or made accessible via public properties.

**Comment by smitpatel** [comment]
We have taken approach of applying such optimizations (esp. SearchCondition & nullsemantics on shaped query before we compile delegate. SearchCondition itself has been moved to SqlServer provider specific code. Now providers have full control of which optimization to run and then can add/remove accordingly. Optimizations which are dependent on parameter values still needs to happen at the runtime when we generate RelationalCommand. We have put mechanism for it but not publicly accessible yet. It is covered by #15891
