### ISSUE TITLE
SQL Server: Translate DateTime.TimeOfDay

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10522]
It should be easy to generate based on format string.

**Comment by bricelam** [comment]
SQLite: `strftime('%H:%M:%f', $dateTime)`

**Comment by bricelam** [comment]
I don't see an easy way to do this in T-SQL. Was this issue only about SQLite?

**Comment by divega** [comment]
Does casting to Time help in SQL Server?

**Comment by ralmsdeveloper** [comment]
Is there any work around that?
If it does not I would like to try something around it!

cc/ @ajcvickers , @smitpatel

**Comment by smitpatel** [comment]
@ralmsdeveloper - Go for it. First step would be to figure out what would be the translation on SqlServer.
