### ISSUE TITLE
Sqlite: Translate DateTime.AddXxx methods

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10525]
Pulling it out of scope of #10468 

Leaving the class `SqliteDateAddTranslator`

The biggest issue lack of test coverage for those methods.

**Comment by bricelam** [comment]
.NET | SQL
--- | ---
dateTime.AddDays(value) | datetime($dateTime, $value \|\| ' days')
dateTime.AddHours(value) | datetime($dateTime, $value \|\| ' hours')
dateTime.AddMilliseconds(value) | datetime($dateTime, ($value / 1000) \|\| ' seconds')
dateTime.AddMinutes(value) | datetime($dateTime, $value \|\| ' minutes')
dateTime.AddMonths(value) | datetime($dateTime, $value \|\| ' months')
dateTime.AddSeconds(value) | datetime($dateTime, $value \|\| ' seconds')
dateTime.AddTicks(value) | datetime($dateTime, ($value / 10000000.0) \|\| ' seconds')
dateTime.AddYears(value) | datetime($dateTime, $value \|\| ' years')
