### ISSUE TITLE
Query: SqlFragmentExpression has incorrect type for mixed mode eval

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10520]
For Expressions like `DateTime.Now.Date` in Oracle, DateTime.Now gets translated to SqlFragmentExpression but it has type of object defined for all types. This causes error because after translating `DateTime.Now` we re-generate `DateTime.Now.Date` with translated expression.
Exception:
```
Test 'Microsoft.EntityFrameworkCore.Query.SimpleQueryOracleTest.Where_datetime_today' failed: System.ArgumentException : Instance property 'Date' is not defined for type 'System.Object'
	at System.Linq.Expressions.Expression.Property(Expression expression, String propertyName)
	D:\code\ContributorEF\EntityFrameworkCore\src\EFCore.Relational\Query\ExpressionVisitors\SqlTranslatingExpressionVisitor.cs(700,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitMember(MemberExpression memberExpression)
	at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
	at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
	D:\code\ContributorEF\EntityFrameworkCore\src\EFCore.Relational\Query\ExpressionVisitors\SqlTranslatingExpressionVisitor.cs(127,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
	D:\code\ContributorEF\EntityFrameworkCore\src\EFCore.Relational\Query\ExpressionVisitors\SqlTranslatingExpressionVisitor.cs(539,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.ProcessComparisonExpression(BinaryExpression binaryExpression)
	D:\code\ContributorEF\EntityFrameworkCore\src\EFCore.Relational\Query\ExpressionVisitors\SqlTranslatingExpressionVisitor.cs(165,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression expression)
	at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
````

**Comment by smitpatel** [comment]
The offending test is going away with #11038 
Regardless, we should have ability to specify type for SqlFragment in case the fragment refers to particular server syntax returning specific type.

**Comment by dmitry-lipetsk** [comment]
Please, allow to specify the Type for SqlFragmentExpression.

I have the problems with translation of DateTime.Now to "CURRENT_TIMESTAMP".

**Comment by smitpatel** [comment]
This would be non-issue with client eval going away for most part. Still we should use the correct type of each scalar value in our SQL Tree.

**Comment by ajcvickers** [comment]
Removing this as an independent breaking change; query break is covering it.

**Comment by smitpatel** [comment]
> Please, allow to specify the Type for SqlFragmentExpression.
I have the problems with translation of DateTime.Now to "CURRENT_TIMESTAMP".

`CURRENT_TIMESTAMP` is a SqlFunctionExpression which is niladic.

**Comment by smitpatel** [comment]
SqlFragmentExpression is to generate string in SQL without any particular type information. like `*` or type name for conversion. If someone needs exact typeMapping then SqlFragment is wrong expression to use.

Further, since we do not recreate C# expression with translated components, this issue is not longer encountered.
