### ISSUE TITLE
PMC Tools: Error when Unicode characters in project.assets.json

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#10532]
The `ConvertFrom-Json` cmdlet fails when the `project.assets.json` file contains Unicode characters:

> Invalid object passed, must have ':' or '}'.

**Comment by Eilon** [comment]
This patch is **approved** for the Feb 2018 patch. Please send a PR to the appropriate branch, get it reviewed, and merge.

Please consider adding a [quirks-mode switch](https://github.com/aspnet/Home/wiki/Quirks-mode-switches-in-patches) for this change.
