### ISSUE TITLE
SQLite Query: Should we be translating decimal/TimeSpan operations?

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#10534]
Any operation (besides equality comparison) on `decimal` values will be lossy on SQLite since they are implicitly converted to `REAL` on the server. Should we continue translating them?

**Comment by smitpatel** [comment]
😢

**Comment by ajcvickers** [comment]
This is a specific case of the general problem described in #10265. Leaving this issue open as well since the two things may end up with different priorities.

**Comment by bricelam** [comment]
`TimeSpan` is plagued by the same problems--`Min()` and `Max()` do string comparison, etc.

**Comment by bricelam** [comment]
Found several more cases involving DateTime, DateTimeOffset, and ulong.

**Comment by bricelam** [comment]
Here's a table of the operations we block server-eval for:

Expression | DateTime | DateTimeOffset | decimal | TimeSpan | ulong
--- | --- | --- | --- | --- | ---
-x | | | ❌ | ❌ | ✔
x + y | ❌ | ❌ | ❌ | ❌ | ✔
x / y | | | ❌ | ❌ | ❌
x > y | ✔ | ❌ | ❌ | ❌ | ❌
x >= y | ✔ | ❌ | ❌ | ❌ | ❌
x < y | ✔ | ❌ | ❌ | ❌ | ❌
x <= y | ✔ | ❌ | ❌ | ❌ | ❌
x % y | | | ❌ | | ❌
x * y | | | ❌ | ❌ | ✔
x - y | ❌ | ❌ | ❌ | ❌ | ✔
xs.Average() | | | ❌ | | 
xs.Max() | | ❌ | ❌ | ❌ | ❌
xs.Min() | | ❌ | ❌ | ❌ | ❌
xs.Sum() | | | ❌ | | ✔

**Comment by bricelam** [comment]
Filed #11925 for blocking GroupBy()
