### ISSUE TITLE
Revert 2.0->2.1 provider breaking changes

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#10545]
The biggest test blockers are:

- [x] TableSelectionSet removed causing database cleanup to fail
- [x] IUpdateSqlGenerator scope changed from scoped to singleton causing SqlServer update pipeline to fail
- [x] Transaction methods added to IDbContextTransactionManager causing InMemory provider to fail to load

**Comment by smitpatel** [comment]
We can get TableSelectionSet back in test assembly for testing.

**Comment by AndriySvyryd** [comment]
@smitpatel You mean using type forwarding?
