### ISSUE TITLE
Specs.Tests are inconsistent with test runners

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10558]
Specs.Tests are in src folder and their tfms are net461;netcoreapp2.0
Whereas test projects have tfms net461;netcoreapp2.1;netcoreapp2.0

Should tfms in Specs be updated?

cc: @natemcmaster @pranavkm

**Comment by pranavkm** [comment]
Are you running `dotnet test` on the spec test project by itself? If so, your assertion sounds right. If not, it's fine for it to not compile for `netcoreapp2.1`.

**Comment by smitpatel** [comment]
Not on them directly. They were converted from netstandard to net4x;netcoreapp in past to compile for tfms tests target. I am not sure if they should compile for netcoreapp2.1

**Comment by pranavkm** [comment]
You could leave them be and that seems fine. Tests targeting `netcoreapp2.1` should pick up the `netcoreapp2.0` dependency and afaik, that's not incorrect.

**Comment by natemcmaster** [comment]
Just curious: why were they changed from netstandard2.0 to runtime-specific TFMs?

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/issues/8250

**Comment by smitpatel** [comment]
The main reason behind doing this is overload resolution for some APIs. Especially https://github.com/aspnet/EntityFrameworkCore/issues/8157
From PR for that bug.
> Issue here is:
netstandard2.0 has Trim(params char) method.
net framework implements above and adds overload Trim()
netcoreapp2.0 went beyond that and implemented above method & overload and also added another overload Trim(char).
Therefore we were failing to resolve to correct overload while translating methodcall.
Same goes for TrimStart & TrimEnd.

Compiling specs tests on actual running tfms give queries actual runtime environment pertaining to overload resolution/expression tree compilation.

**Comment by ajcvickers** [comment]
For EF at least, we need to compile and run tests against net461 (or some .NET Framework version) netcoreapp2.0 and netcoreapp2.1.
