### ISSUE TITLE
CLI Tools: Convert to a Dotnet (global) Tool

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#10554]
Instead of using a `<DotNetCliToolReference>`, tools will have the ability to install globally:

    dotnet install tool dotnet-ef
    dotnet ef

We'll need to create yet another package containing our tooling assemblies.

**Comment by DamianEdwards** [comment]
Is this going to land in preview2? Also, can you ensure an issue get's logged in aspnet/templating to remove the project tool reference once this is integrated into the SDK installer, thanks.

**Comment by ajcvickers** [comment]
@DamianEdwards Yes, it will be in preview2.

**Comment by bricelam** [comment]
Mostly done. Just waiting on dotnet/cli#8844 to bundle it in the SDK.

**Comment by bricelam** [comment]
@benday You may find this work rather disruptive. The `Microsoft.EntityFrameworkCore.Tools.DotNet` package is gone. You'll now find the flavors of `ef.exe` under `C:\Program Files\dotnet\sdk\2.1.300\DotnetTools\dotnet-ef\2.1.0\tools\netcoreapp2.0\any\tools`. They also continue to exist in the `Microsoft.EntityFrameworkCore.Tools` package.
