### ISSUE TITLE
Oracle Migrations: Stop parsing T-SQL utility statements

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#10591]
This was carried over from the SQL Server provider, but it should be removed.

**Comment by ajcvickers** [comment]
See note in #10590

**Comment by ajcvickers** [comment]
This is an issue identified on the Oracle sample provider. We don't plan to fix this in the sample, but we would be happy for a community contributor to fix it. Also, anyone taking the sample as a starting point for production code should consider fixing this issue.
