### ISSUE TITLE
2.0 provider compat with 2.1 runtime

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#10708]
Testing the SQLCE 2.x provider against the latest 2.1 preview build, I had to change the following code, I wonder if it is a Backwards compat issue?

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/commit/ddbab9fa9c8f3eb4cbb846bacfdf086439cc4f0e#diff-bd4bdd81fe651de7b5426b6578f5846dL75 

### Further technical details
EF Core version: 2.1.0-preview1-28072
Database Provider: SQLCE 2.0
Operating system: 
IDE: Visual Studio 2017 15.5

**Comment by ajcvickers** [comment]
Notes from triage: we should revert this change and look at what could be done to catch these cases going forward--that is, cases where the code is technically internal but should not be broken because, for example, there is no reasonable public code that a provider can use.
