### ISSUE TITLE
Database with apostrophe in name throws an exception on create

### ISSUE THREAD

**Issue by jotab123** [aspnet/EntityFrameworkCore#10740]
I'm trying to create a named Test'1 database, the code below throws an exception but creates the database in server. Once the database is created, the code works fine:

```
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new AppContext())
            {
                var entity = new Entity();
                ctx.Add(entity);
                ctx.SaveChanges();
            }
        }
    }

    public class AppContext : DbContext
    {
        public DbSet<Entity> Entities { get; set; }

        public AppContext()
        {
            Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test'1;Trusted_Connection=True;");
        }
    }

    public class Entity
    {
        public int Id { get; set; }
    }
```

Exception message: 
> System.Data.SqlClient.SqlException: 'Incorrect syntax near '1'.
> 'READ_COMMITTED_SNAPSHOT' is not a recognized SET option.
> Unclosed quotation mark after the character string ');
> '.'

StackTrace:  
>  en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    en System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    en System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
>    en System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    en System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    en Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
>    en Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Create()
>    en Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
>    en Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
>    en EFCoreTest.AppContext..ctor() en C:\Users\User\Projects\EFCoreTest\EFCoreTest\Program.cs:línea 29
>    en EFCoreTest.Program.Main(String[] args) en C:\Users\User\Projects\EFCoreTest\EFCoreTest\Program.cs:línea 14

If I use double apostrophe to escape the character in connection string, the database is also created but throws a different error:
`optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test''1;Trusted_Connection=True;");`

Exception message:
> System.Data.SqlClient.SqlException: 'User does not have permission to alter database 'Test'1', the database does not exist, or the database is not in a state that allows access checks.
> ALTER DATABASE statement failed.'

StackTrace:  

>    en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    en System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    en System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
>    en System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    en System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    en Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
>    en Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Create()
>    en Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
>    en Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
>    en EFCoreTest.AppContext..ctor() en C:\Users\User\Projects\EFCoreTest\EFCoreTest\Program.cs:línea 29
>    en EFCoreTest.Program.Main(String[] args) en C:\Users\User\Projects\EFCoreTest\EFCoreTest\Program.cs:línea 14

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.4

**Comment by ajcvickers** [comment]
Note from triage: Check for other places where the same issue may be happening.
