### ISSUE TITLE
Off-by-one applying RelationalMaxIdentifierLengthConvention?

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#10796]
PostgreSQL's identifier length [is limited to 63 bytes](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS). However, when I set `RelationalMaxIdentifierLengthConvention` to 63 in NpgsqlConventionSetBuilder, and run the complex navigation query tests, I can see EF is trying to create constraints such as `FK_InheritanceLeafOne_InheritanceOne_SameTypeReference_Inherit~1`, which is 64 bytes long (this causes a failure as two different constraints get truncated by PostgreSQL and become identical).

Will work around this by setting the max length to 62 for now.

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/e45e6739d4e3535c918a2275c323f56c615f5164/src/EFCore.Relational/Metadata/Internal/ConstraintNamer.cs#L148-L149

Needs to subtract 2 because, we add `~` extra.
