### ISSUE TITLE
SqlServer: UseRowNumberForPaging shouldn't return void

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#10808]
`UseRowNumberForPaging` should return the builder to allow chaining and be consistent with the other methods on `RelationalDbContextOptionsBuilder`.

**Comment by Muppets** [comment]
@bricelam @smitpatel I had a quick look through this and seem like a one-liner fix on changing the method of SqlServerDbContextOptionsBuilder and fixing up the Fluent_api_methods_should_not_return_void unit test. I have a branch with these changes ready to PR but I feel like I'm missing a chunk of the work. Any pointers?

**Comment by bricelam** [comment]
That’s all it is! We just had to wait for 3.0 since changing it has a small chance of breaking apps/libraries.

**Comment by Muppets** [comment]
Alright then, I'll leave this here for you guys. Let me know if you need any tweaks to this.

**Comment by smitpatel** [comment]
Fixed via b67d2938111ade303261f5b3aaf9b44b17e5bb99

**Comment by ajcvickers** [comment]
Re-opening to ensure breaking change is announced.

**Comment by smitpatel** [comment]
@ajcvickers - Should this issue be closed?

**Comment by ajcvickers** [comment]
@smitpatel Only if the breaking change is documented.

**Comment by ajcvickers** [comment]
This is basically only a binary break, and there is no action to take other than rebuilding, so closing.
