### ISSUE TITLE
Update() API could be improved and documentation is incomplete and misleading

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/EntityFrameworkCore#10823]
[Documentation for working with Disconnected Entities](https://docs.microsoft.com/en-us/ef/core/saving/disconnected-entities)

The title of the section of documentation cited above is "Disconnected entities" and deals with, presumably, entities that are disconnected from the context.

The documentation goes on to describe how to test for the ID to choose whether to use Update or Add as if that is the only criteria the developer needs to consider before calling one of the two methods.  

This example is provided for how to call Update:
	

	public static void InsertOrUpdate(DbContext context, object entity)
	{
		context.Update(entity);
		context.SaveChanges();
	}

So what is wrong with the example?  Well, the documentation completely omits the fact that the update will fail if an entity with the same ID is being tracked by the context.  Why is that fact never mentioned in the documentation?  A more real-world example of InsertOrUpdate will look like this:

	public static List<object> GetObjectsUnrelatedToInsertOrUpdate(Predicate p)
	{
		return context.Customers.Where(p).cast<object>().ToList();
	}

	public static void InsertOrUpdate(DbContext context, object entity)
	{
		context.Update(entity);
		context.SaveChanges();
	}

Where will the developer who is responsible for troubleshooting the intermittent error that is thrown by above code look to help him find what the problem is?  
	
Also I don't understand why it is insurmountable for EF to simply point to the entity passed to Update as the newly tracked entity.  Is this impossible?  Too hard?  Too easy perhaps?  
Please answer this question thank you.

**Comment by ajcvickers** [comment]
@sam-wheat I have submitted a PR to add notes about identity resolution to the doc: https://github.com/aspnet/EntityFramework.Docs/pull/605
