### ISSUE TITLE
Operator `Contains` is translated in EF Core 1.x, but throws exception in 2.0.

### ISSUE THREAD

**Issue by Dixin** [aspnet/EntityFrameworkCore#10868]
Operator `Contains` is translated in EF Core 1.x, but throws exception in 2.0.

Recently I upgraded EF Core 1.x to 2.0 and got this problem. Take the AdventureWorks database's Product table as an example:

```cs
IQueryable<Product> source = adventureWorks.Products;
Product single = source.Single(product => product.ListPrice == 20.24M); // Execute query.
bool contains = source
    .Where(product => product.ProductSubcategoryID == 7)
    .Contains(single).WriteLine();
```

In 1.x the above query is translated to:

```sql
SELECT [product].[ProductID], [product].[ListPrice], [product].[Name], [product].[ProductSubcategoryID]
FROM [Production].[Product] AS [product]
WHERE [product].[ProductSubcategoryID] = 7
```

In 2.0 the above query throws `ArgumentException`:

> Expression of type 'Product' cannot be used for parameter of type 'Microsoft.EntityFrameworkCore.Storage.ValueBuffer' of method 'Boolean Contains[ValueBuffer](System.Collections.Generic.IEnumerable``` `1 ``` [Microsoft.EntityFrameworkCore.Storage.ValueBuffer], Microsoft.EntityFrameworkCore.Storage.ValueBuffer)' 
> Parameter name: arg1
>    at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
>    at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
>    at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable``` `1 ``` 1 arguments)
>    at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression[] arguments)
>    at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.CallWithPossibleCancellationToken(MethodInfo methodInfo, Expression[] arguments)
>    at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleContains(EntityQueryModelVisitor entityQueryModelVisitor, ContainsResultOperator containsResultOperator, QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.<>c.<.cctor>b__33_6(EntityQueryModelVisitor v, ResultOperatorBase r, QueryModel q)
>    at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator)
>    at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleContains(HandlerContext handlerContext)
>    at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
>    at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection``` `1 ```  resultOperators, QueryModel queryModel)
>    at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger``` `1 ```  logger, Type contextType)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0``` `1 ``` .<Execute>b__0()
>    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func``` `1 ```  compiler)
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
>    at System.Linq.Queryable.Contains[TSource](IQueryable``` `1 ```  source, TSource item)
>    at Tutorial.LinqToEntities.QueryMethods.ContainsEntity(AdventureWorks adventureWorks) in D:\Dixin\GitHub\CodeSnippets\FunctionalProgramming+LINQ\Tutorial.Shared\LinqToEntities\QueryMethods.cs:line 1890
>    at Tutorial.Tests.LinqToEntities.QueryMethodsTests.QuantifiersTest() in D:\Dixin\GitHub\CodeSnippets\FunctionalProgramming+LINQ\Tutorial.Tests.Shared\LinqToEntities\QueryMethodsTests.cs:line 360

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017 15.5.5)

**Comment by smitpatel** [comment]
Hijacking this!
