### ISSUE TITLE
Update API test for fluent API chaining

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#10863]
To avoid issues like #10808

**Comment by orubel** [comment]
This is not API Chaining(tm) which was created and trademarked by myself several years ago and is a process in the BeAPI Framework. What you are doing is chaining request/response to the next request/response to the next request/response, etc.

This trademark has been enforced against Mulesoft, NordicAPI, Apigee, and others.

To read on how to implement, go to the documentation page for API Chaining https://orubel.github.io/Beapi-API-Framework/chain.html

There it clearly states 'API Chaining as a process is only considered successfully implemented if:

it uses one REQUEST/RESPONSE
the client can dynamically create chains based on endpoints accessible by their ROLE/PRIVILEGE; - no hardcoded chains
no more than ONE non-safe REQUEST method is used in a chain; chains CAN chain off each other however
Please read the documentation

**Comment by Eilon** [comment]
@orubel , per my comment in the PR thread, we will follow up ASAP.
