### ISSUE TITLE
Annotations on the first owned entity type reference are lost

### ISSUE THREAD

**Issue by mrswain** [aspnet/EntityFrameworkCore#10911]
I discovered an odd regression that has occurred between build 28148 and 300047. I will have to spend some time tracking down when it occurred, I will try to do that tomorrow.

The issue is that my model has sub-owned types and suddenly the migration would stop generating correctly. I have tracked it down to two issues in the ModelSnapshot code, below is a Gist of a sample snapshot.

https://gist.github.com/mrswain/f975e4a2538eaea8d9b06d26d961cecc

The end result of the model should be 4 entities and 7 owned entities, and all entities should be mapped to 4 schema.table pairs.

What happens is I now get 6 entities (two owned ones become unowned) and some of the owned entities lose their table relational attributes.

I dropped the test back to build 28148 and it gives the correct output so some change has caused this.

NOTE:
My test program is a simple
```C#
using System;

namespace EFTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var snapshot = new SnapshotTest();

            var model = snapshot.Model;

        }
    }
}
```
I have a breakpoint on the model assignment so I can view the results.

**Comment by smitpatel** [comment]
@mrswain - Please share your model classes and OnModelCreating code.

**Comment by mrswain** [comment]
I tracked the break point down to.. 2.1.0-preview2-28212 -- commit e4c8bbb22e12d6fc0b07111c18c19c57d91fee6d

2.1.0-preview2-28189 -- commit 273662d43b1265eb7f7f4e91b9b145e5d7f5de93
is the last version I get the correct results with, so some change after this commit broke the snapshot.

@smitpatel 
What I provided is only a portion of my actual model snapshot, the portion that demonstrates and exhibits the problem. Given that this is entirely reproducible with the code given, I do not see how providing the full model or the code used to configure it is relevant, unless you believe the snapshot is in error.

**Comment by smitpatel** [comment]
f2dc8c0709af75f69977b8bf8cb9f3ea34198a6f is the commit which would have highest impact causing this. It has very little to do with model snapshot. It is model building part which is generating a different model now. Hence I asked for model code.

**Comment by mrswain** [comment]
The model snapshot I provided was generated in 300047 so if it is an issue with the model snapshot it is because the latter code broke it. Also the code I provided is only a small subset of my model and posting the complete model and model generation code would need its own repository as it consists of many files and supporting libraries. I just distilled it down to the essence of what was needed to reproduce the issue.

I still fail to see what the model or OnModelCreating has to do with a problem with parsing the snapshot structure.

I feel the problem lies in extension code that detects if a type is an owned type, not properly detecting in the model created from the snapshot, or the snapshot to model builder not setting up enough of the structure for detection.

**Comment by AndriySvyryd** [comment]
Seems that some annotations on the first owned entity type reference for each owned type are being lost. Here's a minimal repro:
```C#
var modelBuilder = new ModelBuilder(SqlServerConventionSetBuilder.Build());
modelBuilder.Entity("A").OwnsOne("O", "O1").ToTable("T", "S");
modelBuilder.Entity("B").OwnsOne("O", "O2").ToTable("T", "S");

foreach (var entityType in modelBuilder.Model.GetEntityTypes().Where(t => t.IsOwned()))
{
    Assert.Equal("S", entityType.SqlServer().Schema);
    Assert.Equal("T", entityType.SqlServer().TableName);
}
```

**Comment by FrederickBrier** [comment]
@mrswain Thank you so much for filing this bug. I was pretty sure it was updating to a nightly build, because my tests and code broke so radically. I am using owned types as well. Going back to 2.1.0-preview2-28189 fixed it. Again, thank you. And thank you Andriy!

**Comment by AndriySvyryd** [comment]
@mrswain @FrederickBrier This fix should be in the next nightly build or the one after it, please try it out and let me know if there is anything else that's still broken.

**Comment by mrswain** [comment]
preliminary tests with rebuilding the migrations seem to work so far, at least as far as the second stage. I still have two mare stages to rebuild but I think this may work. I will follow up once I get them rebuilt.

**Comment by AndriySvyryd** [comment]
@fbrier That looks like a new regression. Could you file a separate issue with a small repro?
