### ISSUE TITLE
Disable `Task.WhenAll()` in all cases 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#10914]
Currently we have guards in query code that allow multiple queries from the same `DbContext` get serialized when using Task.WhenAll(). We originally did this to work with some of the query operators in IX Async which consumed the async enumerables in parallel. We now think this may be introducing unnecessary overhead, plus customers actually using Task.WhenAll() directly aren't getting what they expect. 

This issue is about throwing when we find this scenario. It is a breaking change, but we believe it is worth considering. The code necessary to throw should have less overhead.

cc @anpete @ajcvickers @roji

**Comment by ajcvickers** [comment]
Remove in 3.0.

**Comment by smitpatel** [comment]
Pulled this back in 3.0 since it was a product bug due to #12138
