### ISSUE TITLE
Exception when removing migration

### ISSUE THREAD

**Issue by MisinformedDNA** [aspnet/EntityFrameworkCore#10921]
Ran remove-migration twice, saw this error both times. I'm not using any HashTables or IEnumerables in my EF model.

```
PM> remove-migration
Removing migration '20180208204117_FixLocationId'.
Reverting model snapshot.
Done.
System.InvalidCastException: Unable to cast object of type 'System.Collections.Hashtable' to type 'System.Collections.Generic.IEnumerable`1[System.String]'.
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase.RemoveMigration(String contextType, Boolean force)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsRemoveCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Unable to cast object of type 'System.Collections.Hashtable' to type 'System.Collections.Generic.IEnumerable`1[System.String]'.```

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10 1511
IDE: Visual Studio 2017 15.5.4

**Comment by smitpatel** [comment]
@MisinformedDNA - You are using 1.x version of EFCore.Tools. Please upgrade EFCore.Tools package to 2.0.1

**Comment by MisinformedDNA** [comment]
There is another project in the solution that uses the 1.x tools, but that project was not part of this operation. The Startup project I'm using has EFCore.Tools 2.0.1. The Data project has EFCore.SqlServer 2.0.1. Please reopen so we can resolve.

**Comment by smitpatel** [comment]
`System.Collections.Generic.IEnumerable`1[System.String]` is type being used in EFCore tools 1.x. The API got changed in 2.0 version. So regardless of project setup, you are invoking tools on 1.x version.

@bricelam - What would be tools behavior if both 1.x & 2.x tools are installed in different projects in same VS solution? Which tools PMC will invoke.

**Comment by bricelam** [comment]
Probably 2.x. It depends on the order NuGet calls init.ps1. We could make it more deterministic, but you can always just manually call the version you want before invoking commands if you really want to use both. If you only want to use one, uninstall the other. Could also split into two VS solutions.

**Comment by bricelam** [comment]
Also relevant: We made this breaking change from 1.x to 2.x, but we are less likely to make tooling breaking changes going forward so the 3.x tools will probably work with 2.x projects.

**Comment by MisinformedDNA** [comment]
It doesn't actually break anything or stop anything from working, right? So I can just ignore the error?

**Comment by bricelam** [comment]
Correct; it's benign on .NET Core SDK projects.

**Comment by MisinformedDNA** [comment]
With effective workarounds and solutions, I think we can close this.

**Comment by bricelam** [comment]
Reopening so we can discuss briefly as a team.

**Comment by ajcvickers** [comment]
Triage: We will add a flag to use newer versions if available.

**Comment by bricelam** [comment]
The fix is only effective going forward. Versions older than 2.1.0 will continue replacing newer versions.
