### ISSUE TITLE
Force providers to subclass new test classes

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#10934]
At the moment, if a test is added in an existing class in the specification tests, it is automatically inherited and executed in all providers - this is great. But if a new class of tests is added, there's nothing informing providers that they need to subclass it.

You could have a test which reflects on the provider's test assembly and makes sure that all test classes have been properly subclasses (i.e. all classes which contain tests in `EFCore.Relational.Specification.Tests` must also exist in `Npgsql.EntityFrameworkCore.PostgreSQL.FunctionalTests`). This would provide a failing test if you added a test class and I didn't include it.

Some opt-out mechanism needs to be available if a specific test class isn't relevant for a provider. They could define the the class and skip it entirely via xunit, or you may have some custom assembly-level attribute to specify that you're opting out of a certain class, or something similar.

**Comment by smitpatel** [comment]
We need this! Even InMemory provider is not running a lot of async test because of no derived test classes. 😞
