### ISSUE TITLE
Problematic interaction between MigrationsSqlGenerator and new type mapper

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#10942]
I have an Npgsql test failing in both preview1 and preview2, tracking it down points to [the following code in MigrationsSqlGenerator](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs#L1312):

```c#
return (clrType == typeof(string)
#pragma warning disable 618
            ? Dependencies.TypeMapper.StringMapper?.FindMapping(unicode ?? true, keyOrIndex, maxLength)?.StoreType
            : clrType == typeof(byte[])
                ? Dependencies.TypeMapper.ByteArrayMapper?.FindMapping(rowVersion, keyOrIndex, maxLength)?.StoreType
                : null)
#pragma warning restore 618
        ?? Dependencies.CoreTypeMapper.GetMapping(clrType).StoreType;
```

This code is responsible for finding the type mapping when there's no Property for it. If the old type mapper is used, everything seems to be OK and the StringMapper and ByteArrayMapper correctly receive `maxLength`, `unicode` and the other facets. However, with the new type mapper, only the clrType is passed and the other information is lost. Thus, if an AlterColumnOperator with a MaxLength of 30 is executed without a Property, the max length will not be passed into the type mapper and will be lost.

It seems like the code here should be constructing a `RelationalTypeMappingInfo`, populating it with everything, and passing that to the typemapper.

**Comment by bricelam** [comment]
> It seems like the code here should be constructing a RelationalTypeMappingInfo, populating it with everything, and passing that to the typemapper.

👍

**Comment by ajcvickers** [comment]
@roji @bricelam I think I had the pragmas in there while I was working on this so I didn't have to tackle the migrations stuff while getting the rest to work, and I obviously then forgot I did this!
