### ISSUE TITLE
Please document the change to when EF traverses a graph and TrackGraph.

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/EntityFrameworkCore#10947]
[This post](https://github.com/aspnet/EntityFrameworkCore/issues/4424) mentions:

>>...if you want to set the state of a single entity then context.Entry(myEntity).State = EntityState.Added is probably the easiest. >>TrackGraph will work... but that is really designed for iterating over a graph of entities and setting the state for each one.

>>...EF Core is now ok with having tracked entities reference entities that are not tracked.

The above is the most wonderful thing ever to happen to EF surely it is worth mentioning [here](https://docs.microsoft.com/en-us/ef/core/saving/related-data).

Also worthy of mention is [TrackGraph](https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.changetracking.changetracker).

Given the above changes it is unfortunate that the Add() api was not synchronized to reflect them.
I am two years too late to comment on this but perhaps in some future version of EF core it will be fixed:

	var blog = null;
	using (var context = new BloggingContext())
	{
	   blog = context.Blogs.First();
	}

	using (var context = new BloggingContext())
	{
		var post = new Post {Title = "Hello World", BlogID = blog.ID, Blog = blog };
		context.Posts.Add(post);
		context.SaveChanges();  // Exception!!!
	}

Here we are newing up a context, newing up an entity, and adding that _specific_ entity to a _specific_ dbset in the context.  Yet our add fails due to a PK conflict that relates to an entity that our dbcontext should know nothing about!  I don't want to sound critical but that api is really unintuitive.  Having it come up for consideration in the above referenced link and not be changed is very sad. 

Even more baffling and ironic is that the syntax that should traverse the graph does not:

    db.Entry(post).State = EntityState.Added;
	
Here we are adding the entity to the context versus a specific DBSet/table.  In my mind this syntax is much more liberal and gives the context freedom to traverse the graph and add as necessary.

**Comment by ajcvickers** [comment]
@sam-wheat Are you asking that we document more clearly that Add adds a graph of entities, while setting the state of an entity only changes the state of that single entity?

**Comment by sam-wheat** [comment]
>> Are you asking that we document more clearly that Add adds a graph of entities, 

No that is quite clear.

>>while setting the state of an entity only changes the state of that single entity?

This is not mentioned (perhaps I missed it) and is invaluable.
