### ISSUE TITLE
Migrations with multiple startup projects

### ISSUE THREAD

**Issue by QuantumHive** [aspnet/EntityFrameworkCore#10967]
When having a Visual Studio solution with a [multi-tier architecture](https://en.wikipedia.org/wiki/Multitier_architecture) like the following:

- ...
- `MyProject.DataAccess`
- `MyProject.Api`
- `MyProject.App`
- ...

With `MyProject.DataAccess` being a `netstandard` project and  
`MyProject.Api` and `MyProject.App` being a `netcore` project.

And the Api project has a reference to the DataAccess project.
The DataAccess project has a `DbContext` (e.g. `MyContext`) class.

The *EF Core Package Manager Console Tools* is throwing the following exception when executing any command (e.g. try Add-Migration Initial):

```
Startup project '<redacted>' targets framework '.NETStandard'. There is no runtime associated with this framework, and projects targeting it cannot be executed directly. To use the Entity Framework Core Package Manager Console Tools with this project, add an executable project targeting .NET Framework or .NET Core that references this project, and set it as the startup project; or, update this project to cross-target .NET Framework or .NET Core.
```

### Because I have set my project to multiple startups.

**Right-click solution** -> **Properties** -> **Select Multiple startup projects** -> **Set Action on `MyProject.Api` and `MyProject.App` to Start**

Workaround to perform migrations is to set the `MyProject.Api` as *Single startup project*. However I would expect the tooling to notice that one of the startup projects (`MyProject.Api`) has a reference to the DataAccess project and thus not throw the exception and just perform the migration command.

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.6

**Comment by Tarig0** [comment]
Try Add-Migration Initial -startupproject MyProject.Api

**Comment by ajcvickers** [comment]
Triage: while we could consider more probing here, this is an area that can be temperamental so we feel that the flag to specify the startup project is the best way to deal with this situation.

**Comment by QuantumHive** [comment]
@ajcvickers I understand. Perhaps the exception message could be improved to inform the developer that multiple startup projects won't work with migrations? The current message causes confusion, because from the perspection of the developer, his startup projects already references the project containing the DbContext.

**Comment by bricelam** [comment]
Using `-Verbose` shows the following:

> More than one startup project found.
> Using startup project 'MyProject.DataAccess'.

**Comment by bricelam** [comment]
We could make the first line a warning...

**Comment by ajcvickers** [comment]
Triage: we should make this a warning. marking it as stretch for 2.1.
