### ISSUE TITLE
Test: Can_use_with_fanned_relationships has incorrect assertion

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10971]
Can_use_with_fanned_relationships ignores a relationship but the seed data still contains connected data so when we load data from database and assert, it fails.

**Comment by smitpatel** [comment]
Query_when_group_by throws client eval warning.

**Comment by AndriySvyryd** [comment]
Also add test for multiple identifying FKs where the principal types are siblings and another test where one of the principal types is assignable to the other.

**Comment by smitpatel** [comment]
`Can_query_shared_derived` has incomplete data.

**Comment by smitpatel** [comment]
Also `F1Fixture` also has `TitleSponsor` has Owned navigation `Details`
