### ISSUE TITLE
Benchmarks: Run EF Core dev benchmarks with netcoreapp2.1 runtime

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10972]
Also upgrade versions of EF to latest on nuget for older versions.

cc: @divega

**Comment by ajcvickers** [comment]
All the 1.x stuff can go.

We should have:
- 2.1 EF Core on 2.1 .NET Core
- 2.0 EF Core on 2.0 NET Core
- 2.1 EF Core on 2.0 NET Core
- 2.1 EF Core on .NET Framework
- 2.0 EF Core on .NET Framework
- EF6 on .NET Framework
