### ISSUE TITLE
Attempting to access entity on group throws "disposed object...." error

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/EntityFrameworkCore#11004]
```c#    
    class Program
	{
		public const string ConnectionString = "Data Source=.\\SQLEXPRESS;Initial Catalog=Staging;Integrated Security=True;MultipleActiveResultSets=True;";

		static void Main(string[] args)
		{
			try
			{
				new Program().Run();
			}
			catch (Exception ex)
			{
				string y = ex.Message;
				// Cannot access a disposed object. 
				// A common cause of this error is disposing a context that was resolved from dependency injection 
				// and then later trying to use the same context instance elsewhere in your application. This may occur 
				// if you are calling Dispose() on the context, or wrapping the context in a using statement. 
				// If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
				// Object name: 'Db'.
			}
		}

		public void Run()
		{
			var junk = GetSeries(0, 100000).Result;
			var moreJunk = junk.First().First().ID; // throws here
		}

		public virtual async Task<List<IGrouping<string, DTOSeries>>> GetSeries(int skip, int take)
		{
			List<IGrouping<string, DTOSeries>> series = null;

			using (Db db = new Db(new DbContextOptionsBuilder<Db>().UseSqlServer(Program.ConnectionString).Options))
			{
				series = await db.DTOSeries
					.GroupBy(x => x.Symbol)
					.OrderBy(x => x.Key)
					.Skip(skip).Take(take).ToListAsync();
			}
			return series;
		}
	}

	

	public class Db : DbContext
	{
		public DbSet<DTOSeries> DTOSeries { get; set; }

		public Db(DbContextOptions<Db> options)
			: base(options)
		{

		}
	}


	public partial class DTOSeries
	{
		[XmlIgnore]
		public int ID { get; set; }

		[XmlIgnore]
		public int CategoryID { get; set; }

		[XmlAttribute("id")]
		public string Symbol { get; set; }

		[XmlAttribute("title")]
		public string Title { get; set; }

		[XmlAttribute("frequency")]
		public string Frequency { get; set; }

		[XmlAttribute("units")]
		public string Units { get; set; }

		[XmlAttribute("seasonal_adjustment_short")]
		public string SeasonalAdj { get; set; }

		[XmlAttribute("last_updated")]
		public String LastUpdated { get; set; }

		[XmlAttribute("popularity")]
		public int Popularity { get; set; }

		[XmlAttribute("realtime_start")]
		public DateTime RTStart { get; set; }

		[XmlAttribute("notes")]
		public string Notes { get; set; }
	}
```

**Comment by ajcvickers** [comment]
Triage: assigning to @anpete to provide workarounds that will force all the queries to be fully materialized, and to investigate what we might be able to do in these kinds of case going forward,

**Comment by anpete** [comment]
Turns out that this is due to trying to track the entities in the groups. We currently only track entities in groups if they are actually consumed, i.e. the group is enumerated.

So, the easy thing to do in this specific case is to make the query non-tracking.

@divega, @ajcvickers Thoughts on whether we should change anything here. We should consider:

- Skipping the tracking code path if the context has been disposed.
- Eagerly tracking the entities in the groups.

**Comment by sam-wheat** [comment]
About a month ago I wrote [this comment](https://github.com/aspnet/EntityFrameworkCore/issues/5536).  I suppose the comment seems a little on the fringe but perhaps issues like this one will help make it clear why I wrote it.  

I think many users use EF in a stateless manor - we get some entities and dispose the context.  When we are ready to write changes we create a new context, save, and dispose again.  So the idea of tracking __from my perspective as a developer__ is that it is something I really dont need.  When I read comments like @anpete that imply tracking is causing problems I am more than happy to raise my hand and vote for abstracting tracking away from the developer completely if it will resolve any root issues.
Another area where EF seems confused as to weather it should be stateful or stateless is the [Add](https://github.com/aspnet/EntityFrameworkCore/issues/10947) and [Update](https://github.com/aspnet/EntityFrameworkCore/issues/10823) API's.  I think these API's are tripwires in the sense that they require the developer to be mindful of what is tracked and what is not.  Much preferred - let tracking be something internal to EF and let me Add() or Update() without even knowing what tracking is.  I don't mean to be critical in any way I know you guys get pulled in lots of different directions.

**Comment by anpete** [comment]
@sam-wheat Have you seen this? https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.querytrackingbehavior

**Comment by ajcvickers** [comment]
@anpete Has the query already been executed before the context is disposed? Otherwise using a disposed context to execute a query would be bad--that is, even if we have a command/data reader/whatever, if the connection has been disposed (which it usually will be when the context is disposed) then it would not be safe to run a query on it.

**Comment by sam-wheat** [comment]
@anpete  Thanks, yes I am aware of that option.  My point in the previous post is that because the option to use tracking exists the EF developer team must account for it in the design of the framework and the API.  Since it is of little value to me I don't mind sacrificing the functionality it provides in order to make EF cleaner and simpler.
