### ISSUE TITLE
Configuring a custom type mapper for a generated column breaks value generation

### ISSUE THREAD

**Issue by LeroyK** [aspnet/EntityFrameworkCore#11010]
Version: 2.1.0-preview2-30132

When using a type mapper as described in #242 on a generated column, EF Core seems to use the model type instead of the provider type to check if its value can be generated. 

To reproduce, create an entity with a rowversion property and configure a custom type mapper on that property. EF Core will not handle it as a rowversion column after this.

The fix might be changing .ClrType to .GetProviderClrType() in [ValueGeneratorConvention.cs](https://github.com/aspnet/EntityFrameworkCore/blob/69f870ab1f32b3185c3599887fbe020c0f70c445/src/EFCore/Metadata/Conventions/Internal/ValueGeneratorConvention.cs#L103), but I have not tested this and I don't know what other implications this might have.

**Comment by ajcvickers** [comment]
@LeroyK I'm working on fixing the issues with value generators and converters, but I am now unsure if this is what you are really hitting, since rowversion doesn't use a value generator. Can you provide some more details on what conversion you are using?
