### ISSUE TITLE
Issue when using EFCore with Automapper's ProjectTo and Unions

### ISSUE THREAD

**Issue by philcarbone** [aspnet/EntityFrameworkCore#11033]
Issue also opened on Automapper GitHub here: https://github.com/AutoMapper/AutoMapper/issues/2537

Also posted on Stackoverflow here:
https://stackoverflow.com/questions/48847744/how-do-i-correctly-use-ef-core-with-automapper-projectto

My Setup
-------

 - ASP.NET Core 2.0
 - EntityFrameworkCore 2.0.1
 - AutoMapper 6.2.2

----------

Problem
-------

I have a project with a DTO called `PersonDetail` and an Entity called `Person`. 
When I call 

    db.People.Where(p => p.FirstName == "Joe").Union(db.People.Where(p => Age > 30)).ProjectTo<PersonDetail>(mapperConfig).ToList(); 

I do not get the `PersonDetail` DTOs and Entity Framework (Core) throws an exception with the message:

> ArgumentException: The input sequence must have items of type 'Test.Module.Entities.Person', but it has items of type 'Test.Module.Dtos.PersonDetail'.

----------

Example without the problem
---------------------------

When I run the code:

     db.People.Where(p => p.FirstName == "Joe").Union(db.People.Where(p => Age > 30)).ToList(); 

I get the `Person` entities with no exceptions.

----------

The Execution Plans
---------------------------

Here is a working plan (with a union):
> {value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable\`1[Test.Module.Entities.Person]).Where(entity => ((entity != null) And ((63ed0ebd-2c02-4496-ac8d-b836cbf13259 == entity.CreatedBy) Or (393a6bb0-b437-4664-beb0-6800f509451b == entity.CreatedBy)))).Union(value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Test.Module.Entities.Person]))}

Now here is the same plan but with automapper projections too: 

> {value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable\`1[Test.Module.Entities.Person]).Where(entity => ((entity != null) And ((63ed0ebd-2c02-4496-ac8d-b836cbf13259 == entity.CreatedBy) Or (393a6bb0-b437-4664-beb0-6800f509451b == entity.CreatedBy)))).Union(value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Test.Module.Entities.Person])).Select(dto => new PersonDetail() {FirstName = dto.FirstName, LastName = dto.LastName, Deleted = dto.Deleted, Age = dto.Age, CreatedUtc = dto.CreatedUtc, CreatedBy = dto.CreatedBy, Id = dto.Id, RecordVersion = dto.RecordVersion, DisplayLabel = ((dto.FirstName + " ") + dto.LastName)})}

----------

Note:
-----

I'm only calling ToList to reduce this problem to it's smallest form. I understand that this doesn't seem like I need to use ProjectTo in this example. In my actual code, we are using OData and we need the final result to be a projected query with the DTOs as Queryable objects. I also understand that this Union is not really a good union example, bu again, just for simplification of the Union problem.

**Comment by smitpatel** [comment]
Repro
```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database


                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var query = db.Blogs.Where(b => b.Name == "A").Union(db.Blogs.Where(b => b.Age > 1))
                    .Select(b => new BlogDetails { Id = b.Id, Age = b.Age }).ToList();
            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }

    public class BlogDetails
    {
        public int Id { get; set; }
        public int Age { get; set; }
    }
}
```
Issue is Union + DTO projection.

As a work-around you can do union after calling `ProjectTo` on both sources. Like this
```C#
var query = db.Blogs.Where(b => b.Name == "A").Select(b => new BlogDetails { Id = b.Id, Age = b.Age })
    .Union(db.Blogs.Where(b => b.Age > 1).Select(b => new BlogDetails { Id = b.Id, Age = b.Age })).ToList();
```

**Comment by philcarbone** [comment]
@smitpatel Thank you for the work-around. We will see if we can use this as our query is manipulated via an OData feed and most of it's creation is generated. We will keep an eye on this bug fix and try to use the work-around in the meantime. Thanks again!
