### ISSUE TITLE
Reveng: custom naming of properties, dbset and entity?

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#11056]
Is this possible by overriding the 3 methods in RelationalScaffoldingModelFactory? (Internal, I know)

**Comment by smitpatel** [comment]
How about injecting `ICandidateNamingService`? 
Currently naming pipeline works this way
1. From DatabaseModel object fetch name.
2. Use CandidateNamingService to generate candidateName from name (this is where pascal casing happens.
3. Run candidateName through CSharpUtilities to generate a valid C# identifier.
4. Take the identifier generated and run through pluralizer.
5. Take the identifier after singularize/pluralize and uniquify it with existing identifier if any (e.g. class cannot contain property same name as class i think)

If you are looking to update just a part of above pipeline then perhaps you could achieve using service.

Though above pipeline is integrated in code in very awkward way and we have cleanup task for that. You can override from `RelationalScaffoldingModelFactory` and take control of full pipeline (though it could break in future). Allowing to override is what made those methods virtual in first place. And not having a good pipeline implemented right now makes the class internal.

**Comment by ErikEJ** [comment]
@smitpatel  Actually, ICandidateNamingService is not specific enough (it accepts a string, not a DatabaseTable or DatabaseColumn object)

**Comment by ErikEJ** [comment]
Thanks, maybe we can briefly discuss later this week?

**Comment by ajcvickers** [comment]
@ErikEJ We can certainly discuss this week, but regardless we would be interested in getting a PR for the changes you would like--it's certainly something we would consider.

**Comment by ErikEJ** [comment]
I guess it should be a change in  from:

      string GenerateCandidateIdentifier([NotNull] string originalIdentifier);

To:

      string GenerateCandidateIdentifier([NotNull] DatabaseTable databaseTable);

and

      string GenerateCandidateIdentifier([NotNull] DatabaseColumn databaseColumn);

**Comment by ajcvickers** [comment]
@ErikEJ Looks good. PR?

**Comment by ErikEJ** [comment]
Coming up!

**Comment by ErikEJ** [comment]
PR submitted
