### ISSUE TITLE
Provide more details for "An item with the same key has already been added" exception

### ISSUE THREAD

**Issue by ctrl-brk** [aspnet/EntityFrameworkCore#11062]
When Entity prepares a list of changes for update it keeps them in a dictionary.
One example is at this line:
https://github.com/aspnet/EntityFrameworkCore/blob/bfe07c526fd59be235439825a37d9fe9817c6940/src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs#L631

I had a situation where a unique index was not configured properly in the DbContextOptionsBuilder and as a result Entity was trying to add duplicated key values to the dictionary causing an exception with the following message:
`An item with the same key has already been added. Key: Object`

This doesn't help much. Would be nice to provide more information referencing key value and possible causes for the error.

**Comment by SSkovboiSS** [comment]
Did you turn on sensetive data logging? It has to be enabled in order to get column values logged.

**Comment by ctrl-brk** [comment]
I did but I haven't noticed any additional info. Where should I look?

**Comment by smitpatel** [comment]
Sensitive data logging is not going to give any additional info. There is no logging around that (or at least in the code linked above)

**Comment by smitpatel** [comment]
@ctrl-brk - Can you share some code which reproduces above?

**Comment by ctrl-brk** [comment]
I don't have the whole running project but here's basically what happend:

```
create table MyTable
(
  Col1 int,
  Col2 int
);

create unique nonclustered index IX_Index1 on MyTable
(
    Col1,
    Col2
)

```
But the index in Entity didn't include Col2

```
modelBuilder.Entity<MyTable>(entity =>
{
    entity.HasIndex(e => e.Col1).HasName("IX_Index1").IsUnique();
});
```

And when I try to delete 2 or more records with the same value in Col1 I get the error above.
