### ISSUE TITLE
2.1 preview 1 - Unable to set up cascade delete when using TPH

### ISSUE THREAD

**Issue by slubowsky** [aspnet/EntityFrameworkCore#11094]
Using TPH have 2 entity types. Want to set up relationship with parent table as cascade delete. Get error when apply migration. Works as expected using 2.0 resulting in one foreign key with cascade delete.
Commenting out one or the other of the cascade deletes "solves" the issue - but we also end up with an extra foreign key relationship set up to parent type. One with the cascade delete and one without. 
Trying to set up one cascade delete using base type doesnt compile either as neither navigation property is of type BaseEntity

```
System.Data.SqlClient.SqlException (0x80131904): Introducing FOREIGN KEY constraint 'FK_BaseEntity_Parent_ParentId1' on table 'BaseEntity' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
```

### Steps to reproduce
```c#
public class BaseEntity
{
	...

	public int ParentId { get; set; }
	public Parent Parent { get; set; }
}

public class DerivedTypeA : BaseEntity
{
	...
}

public class DerivedTypeB : BaseEntity
{
	...
}

public class Parent
{
	...
	public ICollection<DerivedTypeA> DerivedTypeAs { get; set; }
	public ICollection<DerivedTypeB> DerivedTypeBs { get; set; }
}

modelBuilder.Entity<BaseEntity>()
	.ToTable("BaseEntity");

modelBuilder.Entity<DerivedTypeA>()
   .HasOne(p => p.Parent)
   .WithMany(b => b.DerivedTypeAs)
   .OnDelete(DeleteBehavior.Cascade);

modelBuilder.Entity<DerivedTypeB>()
   .HasOne(p => p.Parent)
   .WithMany(b => b.DerivedTypeBs)
   .OnDelete(DeleteBehavior.Cascade);
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by AndriySvyryd** [comment]
This is caused by https://github.com/aspnet/EntityFrameworkCore/issues/10329 - now we uniquify foreign key names generated by convention

@slubowsky As a workaround you can call `.HasName` with the same value on both relationships:
```C#
modelBuilder.Entity<DerivedTypeA>()
   .HasOne(p => p.Parent)
   .WithMany(b => b.DerivedTypeAs)
   .OnDelete(DeleteBehavior.Cascade)
   .HasName("FK_BaseEntity_Parent_ParentId");

modelBuilder.Entity<DerivedTypeB>()
   .HasOne(p => p.Parent)
   .WithMany(b => b.DerivedTypeBs)
   .OnDelete(DeleteBehavior.Cascade)
   .HasName("FK_BaseEntity_Parent_ParentId");
```

**Comment by slubowsky** [comment]
@AndriySvyryd Thanks, that worked. You meant `HasConstraintName` though, not `HasName`

**Comment by AndriySvyryd** [comment]
Keeping this open to discuss whether this is a breaking change we want to revert.

**Comment by ajcvickers** [comment]
Notes from triage: We will attempt to unify into one database constraint for the case where the navigation/fk are defined on the parent type.
