### ISSUE TITLE
Value converters on key properties are propagated to FK properties

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#11117]
This is the same as we do for other facets to make sure that the FK column type is aligned with the PK column type. However, in cases where the type is explicitly different--see #11112--there then doesn't seem to be a way to reverse this.

**Comment by AndriySvyryd** [comment]
Fixed in 9172c66fcd93259ba7a64625d623951f34740883

**Comment by Dosihris** [comment]
Hey guys, 

is this already wotking? I want to create a fk and the datatypes are enum and long. i always get this exception:
System.InvalidOperationException
  HResult=0x80131509
  Nachricht = The types of the properties specified for the foreign key {'Katalog_Id'} on entity type 'KatalogWert' do not match the types of the properties in the principal key {'Id'} on entity type 'Katalog'.
  Quelle = Microsoft.EntityFrameworkCore
  Stapelüberwachung:
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.AreCompatible(IReadOnlyList`1 principalProperties, IReadOnlyList`1 dependentProperties, EntityType principalEntityType, EntityType dependentEntityType, Boolean shouldThrow)
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.AreCompatible(EntityType principalEntityType, EntityType dependentEntityType, MemberInfo navigationToPrincipal, MemberInfo navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 unique, Nullable`1 required, Boolean shouldThrow)
   bei Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceCollectionBuilderBase..ctor(InternalRelationshipBuilder builder, ReferenceCollectionBuilderBase oldBuilder, Boolean foreignKeySet, Boolean principalKeySet, Boolean requiredSet)
   bei Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceCollectionBuilder`2.HasPrincipalKey(Expression`1 keyExpression)
   bei OrgaWare.Oak.Server.ApplicationContext.Verwaltung.KatalogWert.OnModelCreating[T](ModelBuilder modelBuilder) 

technical details:
Visual Studio 2019 (16.1)
EF Core 3.0 preview 7 - 27912-14

this is my code:

            modelBuilder.Entity<KatalogWert>().Property(p => p.Katalog_Id).HasConversion<long>(); // HasConversion(v => (long)v, v => (EKatalog)v);
            modelBuilder.Entity<Katalog>().Property(p => p.Id).HasConversion(v => (EKatalog)v, v => (long)v);

            modelBuilder.Entity<KatalogWert>().HasOne(kw => kw.Katalog).WithMany(k => k.KatalogWerte).HasForeignKey(kw => kw.Katalog_Id).HasPrincipalKey(k => k.Id).OnDelete(DeleteBehavior.ClientSetNull);

**Comment by ajcvickers** [comment]
@Dosihris Please file a new issue and include a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by jayoungers** [comment]
@ajcvickers - do you know if there are any working examples of successfully using ValueConverters to handle type mismatches in `HasPrincipalKey()/HasForeighKey()`?

I'm using EFCore 5, trying to tie two tables together (one having a column of `int` and another of `smallint`): at this point it's not feasible to update the SQL schema to have them match; I'm just looking to simplify the linq queries in code.

There are a few other issues mentioning this should work (#11112), but I haven't seen anything concrete.

**Comment by ajcvickers** [comment]
@jayoungers This works for me:

```C#
public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
    
    public ICollection<Post> Posts { get; set; }
}

public class Post
{
    public int Id { get; set; }
    public string Content { get; set; }

    public int? BlogId { get; set; }
    public Blog Blog { get; set; }
}
```
```C#
     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
         modelBuilder.Entity<Post>().Property(e => e.BlogId).HasColumnType("smallint");
     }
```
This makes the FK a `smallint` in the model, while the PK it references is still an `int`.

If you are running into issues, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by jayoungers** [comment]
Thanks @ajcvickers !

I think my issue stems around trying to let the scaffolding tools do what they want to do, which would result in this for your example:

```
public class Post
{
    public int Id { get; set; }
    public string Content { get; set; }

    public short? BlogId { get; set; }
    public Blog Blog { get; set; }
}
```

Once the scaffolding does that, there doesn't appear to be a way to handle it from there without overwriting the generated files in the manor you have, which can be cumbersome when schema management is handled elsewhere and scaffolding (to consume the new changes) is re-run often.

**Comment by ajcvickers** [comment]
@jayoungers #831 is tracking allowing the model to be updated from the database without overwriting changes. #4038 would also likely allow this since the template could be updated to handle cases like this.

**Comment by jayoungers** [comment]
I'll keep my eye on those; thanks again!

**Comment by walter-silveira** [comment]
I have this problem too and even doing what you all suggests didn't work. These are my classes:

```
[Table("PR_BLOG")]
public class Blog
{
    [Key]
    public int Id { get; set; } //in data base this column is int
    public string Name { get; set; }
    
    public ICollection<Post> Posts { get; set; }
}

[Table("PR_POST")]
public class Post
{
    [Key]
    public int Id { get; set; }
    public string Content { get; set; }

    public long BlogId1 { get; set; } //In data base this column is long
    [ForeignKey("BlogId1")]
    public Blog Blog { get; set; }

    public long BlogId2 { get; set; }
}
```

If i change the data type of Id on Blog class to long and map it with `modelBuilder.Entity<Blog>().Property(x => x.Id).HasColumnType("int")`  i have these exceptions when i call `_context.Post.Include(p => p.Blog)`:

InnerException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
Message: An exception occurred while reading a database value for property 'Candidato.SC_CursoID1'. The expected type was 'System.Int64' but the actual value was of type 'System.Int64'.

**Comment by ajcvickers** [comment]
@walter-silveira EF Core does not support different CLR types for the FK and PK properties.
