### ISSUE TITLE
BoolToStringConverter does not use non-default values when seeding

### ISSUE THREAD

**Issue by edwiles** [aspnet/EntityFrameworkCore#11131]
Using BoolToStringConverter on a property always results in the strings "0" and "1" being stored in the database, even if non-default values such as "N" and "Y" are specified in its constructor. I am using migrations.

### Steps to reproduce
1. Create an entity with a boolean property:
```
   public int Id { get; set; }
   public bool MyTestBool { get; set; }
   public bool MyTestBool2 { get; set; }
```

2. Add a property configuration (and apply this during OnModelCreating as usual):
```
            var converter = new BoolToStringConverter("N", "Y");

            builder.Property(o => o.MyTestBool)
                .IsRequired()
                .HasConversion(converter);

            builder.Property(o => o.MyTestBool2)
                .IsRequired()
                .HasConversion(converter);
```

3. Seed the entity in OnModelCreating:
```
            modelBuilder.Entity<MyEntity>().SeedData(
                new { Id = 1, MyTestBool = true, MyTestBool2 = false });
```

4. Drop and recreate the database via migrations:
```
dotnet ef database drop -f
dotnet ef migrations remove
dotnet ef migrations add InitialCreate
dotnet ef database update
```

5. Use SSMS to run the query "select * from MyEntity"

Result: In the MyEntity table, the MyTestBool and MyTestBool2 columns are both type nvarchar(1), but the created row contains the values "1" and "0" rather than "Y" and "N".

I note that the InitialCreate.Designer.cs file created by migrations contains the following:
```
                    b.Property<bool>("MyTestBool")
                        .HasConversion(new ValueConverter<bool, string>(v => default(string), v => default(bool), new ConverterMappingHints(size: 1)));
```

which does not refer to the "N"/"Y" values.

Here is an extract from my csproj in case of use:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
  </ItemGroup>
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Professional
IDE: Visual Studio 2017 15.5.4

**Comment by ajcvickers** [comment]
Note for triage: this is an issue when value conversions are used with data seeding. The seed values need to be converted either before putting in the migration, or when being read from the migration and written to the database. The former may be better because it avoids attempting to create literals for user types.
