### ISSUE TITLE
Migration is missing namespace import when using a ValueConverter

### ISSUE THREAD

**Issue by mj1856** [aspnet/EntityFrameworkCore#11155]
Trying out `ValueConverter` on a new application.  Found that when creating the initial migration using `Add-Migration`, that the files generated would not compile because they include `ValueConverter` but are missing the namespace import `using Microsoft.EntityFrameworkCore.Storage.Converters;`

Adding the namespace import manually works around the problem.

**Comment by iriza84** [comment]
Where or How can I get Microsoft.EntityFrameworkCore.Storage.Converters? I cannot use HasConversion() in my model builder. I been searching a lot but cannot find it.

**Comment by bricelam** [comment]
This was fixed in 2.1.0-preview2-final
