### ISSUE TITLE
Query: Selecting scalar properties alongwith entity fails to lift and causes N+1 eval

### ISSUE THREAD

**Issue by alexk8** [aspnet/EntityFrameworkCore#11186]
//With classic Parent-Children (like in issue #10472)
This works well (within single select):
```
ctx.Parents.Select(p => new
	{
		ParentId = p.Id,
		ChildrenCount = p.Children.Count(),
		ChildrenSumXX = p.Children.Sum(c=>c.XX)
	}).ToList()

```
But this works as 2N+1 queries:

```
ctx.Parents.Select(p => new
	{
		Parent = p,
		ChildrenCount = p.Children.Count(),
		ChildrenSumXX = p.Children.Sum(c=>c.XX)
	}).ToList()
```
	
That's a bug? Or what's the problem, I cannot see any difference...	

That's in 2.1.0-preview1

**Comment by smitpatel** [comment]
The difference is
in first query, individual property (-ies) are being selected from entity rather than whole entity as in second query. Selecting whole entity requires us to use materialization code path.
At present materialization is tied closely with shaper and there would be one shaper for each query source, we cannot do materialization and some other scalar value processing both on single query source (in this case p). Future enhancement.

As a work-around you can construct object Parent manually by selecting individual properties and avoid materialization code path.

**Comment by alexk8** [comment]
It looks like just a technical imperfections at first, but I think it should be fixed with a high priority, because these queries are commonly used here and there.
In order to materialize it easily, query should look like just this 
```
   SELECT 
     [anonymType1.p].[id] AS [anonymType1.p.id], 
     [anonymType1.p].[someproperty1] AS [anonymType1.p.someproperty1], 
     [anonymType1.p].[someproperty2] AS [anonymType1.p.someproperty2], 
     
	  (
          SELECT COUNT(*)
          FROM [children] AS [c]
          WHERE [anonymType1.p].[id] = [c].[parentid]
      ) AS [anonymType1.cnt], 
	  (
          SELECT SUM([c0].[XX])
          FROM [children] AS [c0]
          WHERE [anonymType1.p].[id] = [c0].[parentid]
      ) AS [anonymType1.sum]
      FROM [parents] AS [anonymType1.p]
```

**Comment by NiekGr** [comment]
Can this be added to the 2.1 milestone?

**Comment by divega** [comment]
Clearing up the milestone to discuss taking these scenarios into account in the query design for 3.0. We are already overbooked for 3.0 so we may not be able to adress it, however I would like if possible that the design doesn't prevent us from doing this.

**Comment by mevansdev** [comment]
Not sure if I have the same issue or if I'm doing something wrong, see code example below, might be isolated to the Max operator;

```
var query = DatabaseContext.Parents
    .Select(parent => 
        new ParentModel
        { 
            Name = parent.Name, 
            DobOfEldest = parent.Children.Max(child => child.DateOfBirth)
        });
```

This is generating multiple queries to get the Max(child.DateOfBirth)

**Comment by Seregwethrin** [comment]
Another example from me.

### Query definition:
```
post: A board post
post.User: Poster
UserPhoto: user has photos where only one of them is uniquely IsPrimary = true
UserLike: did the viewing user like this photo?
PostPhotos: Post might have multiple attached photos (like a Facebook post's photos)
```
```
.Select(post => new
{
	post,
	post.User,
	UserPhoto = post.User.Photos.Where(ph => ph.IsPrimary).Take(1).SingleOrDefault(),
	UserLike = post.Likes.Any(likes => likes.UserId == forUserId),
	PostPhotos = post.PostPhotos.Take(4).Select(pp => pp.Photo),
}).ToList();
```

### Issue Explanation
Main query generated:
```
SELECT p..., "p.User"...
	FROM "Posts" AS p
	INNER JOIN "Users" AS "p.User" ON p."UserId" = "p.User"."Id"
	WHERE p."Id" = $1
	ORDER BY p."Id"
	LIMIT $2
```

So Entity Framework understands the `user` and fetches it directly in 1 query.
Every single other join is a separate query.
if we want to get 10 posts, 1 query for all the posts and users, 10 * 3 = 30 for the joins, our infamous N+1 problem here. (_I also tested if it is 10 posts are we having only 1+3=4 queries in total or 1 + 3 * 10, and unfortunately it is the latter._)

### Expected:
EF Core could have joined UserPhotos and UserLikes by understanding the relation is a `one-to-zero or one` so they can be achieved with a LEFT JOIN each.

```post: A board post
post.User: one-to-one defined in the entity
UserPhoto: one-to-zero or one could be inferred from query
UserLike: one-to-zero or one could be inferred from query
PostPhotos: one-to-many
```

PostPhotos is a `one-to-many` so having separate queries for that is okay, though I do think with some aggregation functions it might be possible to also get them but I do understand the complexity and vendor difference.

### Further technical details
EF Core: 3.0.0-preview3.19153.1
Provider: Npgsql 3.0.0-preview3
OS: (Development machine, MacOS)
IDE: Rider 2019.1

But I do want to emphasize that the join functionality actually works, what's missing is understanding a join in the query is one to zero or one at runtime. If it is defined in the entity the results are expected. 

So I can actually provide the Primary User Photo Id in the entity and refer to the Photo table as one to one for that property, that should work, but that would mean changing the database design to make EF work which would result in redundant data that needs to be kept updated.

**Comment by smitpatel** [comment]
This has been done.
