### ISSUE TITLE
Investigate perf regressions from 2.0 related to change tracking

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#11194]
Specifically:
* Add/Attach/Update/Remove including Range, Children, and Parent variations
* QueryChildren

**Comment by divega** [comment]
I found that this issue was closed automatically and no "closed-fixed" label was added. 

Re-opening in 2.1.0 milestone in case it wasn't intentional, so we can decide explicitly if we have done enough to mark it as fixed.

**Comment by smitpatel** [comment]
Fixed by #11493 PR
