### ISSUE TITLE
Create a log of changes that could impact providers

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#11198]
The log would include:
* The PR/commit where the change was made
* A simple, one-line description of why a provider writer might care or need to react

We still need to find the best place for this; it will likely not happen until post 2.1.

/cc @roji @cincuranet @ErikEJ @caleblloyd

**Comment by ajcvickers** [comment]
See #12623

**Comment by roji** [comment]
I start something similar of my own in https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/416, you may want to copy what's there.

**Comment by ajcvickers** [comment]
@roji Thanks Shay! This is great. I just haven't had time to get to this yet, so you doing it really helps!

**Comment by roji** [comment]
https://github.com/aspnet/EntityFrameworkCore/pull/12666 introduces test breakage.
