### ISSUE TITLE
RelationalQueryCompilationContext accepts internal types in constructor

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#11247]
RelationalQueryCompilationContext is a public type that needs to be subclassed by providers (IsLateralJoinSupported, MaxTableAliasLength). However, its constructor requires two internal types (ILinqOperatorProvider, IQueryMethodProvider) which force providers to reference internal namespaces in EF Core.

Also, QueryCompilationContextDependencies itself is internal.

**Comment by ajcvickers** [comment]
Assigning to @smitpatel to add annotations (comments) to the code about this--part of #11266.
