### ISSUE TITLE
Feature parity: Add IQueryTypeConfiguration<TEntity>

### ISSUE THREAD

**Issue by ilmax** [aspnet/EntityFrameworkCore#11257]
I really like the addition of the new `IEntityTypeConfiguration<TEntity>` type that allows us [self-contained type configuration for code first](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0#self-contained-type-configuration-for-code-first) and if I'm not missing anything, this types allows only entity (i.e. not query types) to be configured. 
I think ef can provide the same experience for query types as well so I propose adding a new `IQueryTypeConfiguration<TEntity>` with this shape:

```csharp
public interface IQueryTypeConfiguration<TEntity>
   where TEntity : class
{
     void Configure(QueryTypeBuilder<TEntity> builder);
}
```
 as well as a new `ApplyConfiguration` overload on the `ModelBuilder` class like the following:

```csharp
public virtual ModelBuilder ApplyConfiguration<TEntity>([NotNull] IQueryTypeConfiguration<TEntity> configuration)
   where TEntity : class
{
   // implementation omitted
}
```
allowing us to write configuration for entity types and query types in a consistent way.

**Comment by ilmax** [comment]
if you guys like the idea and label it as an up for grabs/are interested in a contribution for this one, I can submit a PR

**Comment by ajcvickers** [comment]
@ilmax We would love a PR to fix this one. Thanks!
