### ISSUE TITLE
Setup functional spec tests to run on MySQL repo

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#11305]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/512#issuecomment-373572421

**Comment by ErikEJ** [comment]
This is required for any good quality provider.. Let me know if I can help in any way...

**Comment by ajcvickers** [comment]
@ErikEJ If you want to volunteer to get this setup on their repo that would be great. (Not get all the tests passing, but just the infrastructure, which we were planning to copy from either you or @roji anyway.)

**Comment by roji** [comment]
Agree that there is a lot of value in doing this. Am very busy with my own things at the moment so I don't think I can actively contribute, but would definitely be happy to provide any advice.

In any case, just setting up the infrastructure should be pretty quick and easy, the arduous part is slowly making all the tests green, which is a very MySQL-specific task anyway...

**Comment by ErikEJ** [comment]
Like @roji , I am quite busy prepping the 2.1 SQLCE provider, but will be happy to provide any inspiration and advice to the MySQL team of volunteers, which should be big, considering how popular a database system it is.

**Comment by ErikEJ** [comment]
Also #11555 was added recently, that should help ensure that all spec tests are set up

**Comment by AndriySvyryd** [comment]
Tests added in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/commit/6c18406993d612dc9e9dd2d773e6b5c1a6aed5f6

**Comment by caleblloyd** [comment]
Thanks for all of your help with this @AndriySvyryd and @maumar!  I just merged your 2.1.0 work to `master` today.  We're lined up to do a Pomelo 2.1.0-rc shortly after EF 2.1.0 releases.
