### ISSUE TITLE
Remove CoreStrings.ArgumentIsEmpty() and CollectionArgumentIsEmpty()

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#11307]
Moved to EFCore.Abstrations, but kept in EFCore to prevent breaking providers.

**Comment by Muppets** [comment]
I've raised a [PR](https://github.com/aspnet/EntityFrameworkCore/pull/14589) for this. 

While I was in there, I spotted CoreStrings.StillUsingTypeMapper is not being called anywhere. Is this still needed?

**Comment by bricelam** [comment]
You can remove it too. We probably missed it while removing obsolete APIs.

**Comment by ajcvickers** [comment]
Re-opening to ensure breaking change is announced.
