### ISSUE TITLE
Fixup ends up with entries with different state managers in DbContext Pooling

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#11311]
https://github.com/aspnet/EntityFrameworkCore/blob/2bdb72f0206ef0f4657f565b5a5bf7226564befc/src/EFCore.Specification.Tests/GraphUpdatesFixtureBase.cs#L29

Enable pooling with above line.
Some tests fail.
I investigated in Optional_many_to_one_dependents_with_alternate_key_are_orphaned_starting_detached test for (ChangedNotifications : GraphUpdatesSqliteTestBase<ChangedNotifications.ChangedNotificationsFixture>)

Test remove dependent from one of the collection of the root. After save changes during fixup, while removing entity from root's collection when it fire CollectionChanged event, but the entity entry handling the event is incorrect entry and has StateManager from previous state. Since both of them have different NavigationFixer, we removing both sides of navigations (instead of just from parent to child).

Need to investigate more.

**Comment by ajcvickers** [comment]
Note for implementer: I suspect this is because events are not be unscribed when the services are reset.

**Comment by ajcvickers** [comment]
Investigated this and found that it is a test infra issue, so moving out of 2.1. The test fixture obtains the context from the pool, but then disposes of it in the normal way instead of returning it to the pool.
