### ISSUE TITLE
Migration tool for Enum to string attempts to alter column on every migration

### ISSUE THREAD

**Issue by dubs999** [aspnet/EntityFrameworkCore#11343]
Issue with migrations tool attempting to alter string enum property on every `add-migration` step when using `HasConversion<string>()`.

### Steps to reproduce
- Create an entity with an enum property
- Add the `.HasConversion<string>()` to the model builder
- Add a migration (works fine)
- Add an additional migration (tool attempts to alter already correct property)

### Repro
https://github.com/dubs999/efcore-string-enum-bug

### Further technical details
EF Core version: 2.1.0-preview-1
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: (e.g. Visual Studio 2017 15.4)

**Comment by bricelam** [comment]
Related to #11297. Snapshot should contain `.IsRequired()` on the converted property.
