### ISSUE TITLE
Analyzers: Remove DbCommand.CommandText analyzer

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#11371]
I believe we wanted to find a home outside of EF Core for this analyzer to live.

**Comment by bricelam** [comment]
Failures in Universe:
- Identity\test\EF.Test\Utilities\SqlServerTestStore.cs(113,21)
- Identity\test\EF.Test\Utilities\SqlServerTestStore.cs(141,21)
- Identity\test\Service.EF.Test\Utilities\SqlServerTestStore.cs(113,21)
- Identity\test\Service.EF.Test\Utilities\SqlServerTestStore.cs(141,21)

**Comment by roji** [comment]
Note https://github.com/dotnet/roslyn-analyzers/issues/628 which seems similar.
