### ISSUE TITLE
Query: rewrite predicate with constanList.Any(e =>e == someProperty) to Contains

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#11389]
We can fully translate contains, but Any will cause client eval currently

**Comment by smitpatel** [comment]
Restrictions:
- Has to be equality or inequality (includes operators & Equals method call both)
- The constant list has to be of type which type mapper can generate literal for.
- The lambda parameter needs to appear without any modification. (perhaps no convert etc)

**Comment by smitpatel** [comment]
merged via 98c8ac46a091615fb5fb8979a06af4aacf68edea
