### ISSUE TITLE
Update/Command: Internal code usage in providers

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#11409]
If provider needs to customize the command generated then overriding IRelationalCommandBuilder to generate a difference RelationalCommand requires access to IndentedStringBuilder (part of interface contract). Further Provider also has to implement IRelationalParameterBuilder. Relational Implementation of it is internal. RelationalCommand is also internal so provider cannot reuse code.

Further providers are also using log messages in custom RelationalCommand to log command start/end/error. Transaction start/commit/error/rollback/Use

Some providers are using ISingletonUpdateSqlGenerator which is internal.

**Comment by ajcvickers** [comment]
Command
- ~IndentedStringBuilder~ No longer needed
- ~RelationalParameterBuilder~ Removed
- ~RelationalCommand~ Public
- ~Logger.CommandExecuting/Executed/Error log mssages~ Public
- ~TransactionLogger.TransactionStarted/Used/Committed/Error/Rolledback~ Public

Update
- ~ISingletonUpdateSqlGenerator~ Removed
