### ISSUE TITLE
Migrations/Scaffolding: Internal code usage in providers

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#11408]
To generate custom string Migrations use IndentedStringBuilder
In scaffolding providers are using TableSelectionSet (deprecated) & ScaffoldingAnnotationNames.

**Comment by bricelam** [comment]
@ajcvickers Was this resolved by #15067?

**Comment by ajcvickers** [comment]
@bricelam I believe so, but I'm going to double check before closing.

**Comment by ajcvickers** [comment]
RevEng
- ~TableSelectionSet~ Removed
- ~ScaffoldingAnnotationNames~ Public
