### ISSUE TITLE
Resources/Utility code: Internal code usage in providers

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#11407]
Providers are using some resources from AbstractionStrings/CoreStrings/RelationalStrings in their exception messages.

Further creating pretty formatted exception message requires to use `DisplayName`/`ShortDisplayName` methods.
In our provider we share some utility files as common code which are using Internal types and through them our providers have access to the same code which other providers cannot easily copy.

**Comment by ajcvickers** [comment]
Fixed by #15091 and #15067

**Comment by ajcvickers** [comment]
RevEng
- ~TableSelectionSet~ Removed
- ~ScaffoldingAnnotationNames~ Public

Logging
- ~RelationalStrings~ Public
- ~CoreStrings~ Public
- ~AbstractionStrings~ Public

Utility
- ~DisplayName()~ Public
- ~ShortDisplayName()~ Public
- ~NonCapturingLazyInitializer~ Use LazyInitializer instead
