### ISSUE TITLE
Perf: make TypeMappingInfo a struct

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#11424]
Use composition instead of inheritance.
Use a separate cache for every TypeMappingSource that uses a custom type.
This would reduce allocations during model building.

**Comment by ilmax** [comment]
What about passing `TypeMappingInfo` as `in` parameter where it's possible to avoid GC defensive copies after [this](https://github.com/aspnet/EntityFrameworkCore/pull/11498) will be merged?
