### ISSUE TITLE
Review UnwrapEnumType usages

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#11462]
Now that we have value converters, all the places we call `UnwrapEnumType` should probably be reviewed. For example, [tihs one](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs#L728) looks like it should be changed.

**Comment by ajcvickers** [comment]
I already did this a couple of times, but have now done it again. :-)
