### ISSUE TITLE
SQLCE issue with WithConstructorsTestBase

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#11471]
When seeding this, SQLCE fails, as it cannot insert into a table with just a single identity column.
Adding an extra dummy column would solve the issue.
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Specification.Tests/WithConstructorsTestBase.cs#L878

```
public string Dummy { get; private set; }
```

SQL is:

```
INSERT INTO [HasContext<DbContext>]
DEFAULT VALUES
```
This would work

```
INSERT INTO [HasContext<DbContext>] 
(Dummy) VALUES (DEFAULT)
```

Error is:  There was an error parsing the query. [ Token line number = 2,Token line offset = 1,Token in error = DEFAULT ]

### Further technical details
EF Core version: 2.1-preview1
Database Provider: SQLCE

**Comment by ajcvickers** [comment]
@ErikEJ I guess enough time has passed since you last reminded me of this CE limitation that I forgot about it again! 😸 PR?

**Comment by ajcvickers** [comment]
Yep, adding a dummy property is the typical fix.
