### ISSUE TITLE
Too long Foreign Key names result in redundant changes in future migrations

### ISSUE THREAD

**Issue by bpaczkowski** [aspnet/EntityFrameworkCore#11473]
When a Foreign Key name generated by EF Core in a migration is longer than 62 characters, the rest of it gets truncated in the database. When you try to create another migration, EF Core generates one that drops all those Foreign Keys with truncated names and tries to create them again, with the same specs as in the first migration.

This very well may be an issue with Npgsql, although I'm not sure so I'm reporting it here first.

### Further technical details
EF Core version: 2.1.0-preview1
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10
IDE: Visual Studio 2017 15.6

**Comment by bpaczkowski** [comment]
My bad, it seems this was fixed recently and now the first migration is created properly with Foreign Key names truncated already. My migration must have been created before the fix.

**Comment by bpaczkowski** [comment]
Turns out it's not fully fixed... The first migration is created with correct, truncated FK names, but subsequent migrations try to drop non-existing FKs with full names (which results in an exception) and add them with truncated names again.

**Comment by divega** [comment]
@bpaczkowski We are going to need some help to repro. Could you provide a project and if possible detailed repro steps?

**Comment by bpaczkowski** [comment]
Here it is: [test.zip](https://github.com/aspnet/EntityFrameworkCore/files/1869051/test.zip). To reproduce simply add 2 migrations with `Add-Migration` command. Notice how in the first migration the FK is created correctly, while in the second migration a non-existent FK is being removed and a new FK is added, the same as in the first migration.

**Comment by bricelam** [comment]
It looks like the `Relational:MaxIdentifierLength` annotation is ignored when generating the snapshot.

We should either serialize it, or compensate for it when reading the snapshot. @AndriySvyryd thoughts?

If we want to compensate for it, we'll need to have the value available in Migrations. Today it's hard-coded in the provider's convention set builder:
``` csharp
conventionSet.ModelInitializedConventions.Add(new RelationalMaxIdentifierLengthConvention(128));
```

**Comment by AndriySvyryd** [comment]
@bricelam Serializing seems like the easy and robust way to do it.

**Comment by bricelam** [comment]
Sounds good to me.

**Comment by bricelam** [comment]
Workaround
===
To work around the issue, give the constraints explicit names:
``` csharp
modelBuilder.Entity<TestEntityA>()
    .HasOne(a => a.ThisIsAVeryLongNameSoAsToExceedTheCharacterLimit)
    .WithMany()
    .HasConstraintName("FK_TestEntityA_TestEntityB_ThisIsAVeryLongNameSoAsToExceedThe~");
```
