### ISSUE TITLE
SQL Server full-text search: Contains predicate

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#11486]
We already support FreeText in 2.1 and [Contains](https://docs.microsoft.com/en-us/sql/t-sql/queries/contains-transact-sql) should be very similar and relatively easy.

**Comment by Djangoum** [comment]
Hi, i can take a look at Contains if none of you are looking for this! @divega

**Comment by smitpatel** [comment]
@Djangoum - Feel free to start working on it. I will assign myself to make sure no one else in the team start working on it.

**Comment by DSilence** [comment]
Anyone working on this at the moment? If not, I'm willing to make a contribution.

**Comment by Djangoum** [comment]
I'm sorry but now i can't work on that, feel free to start working on it. @DSilence
