### ISSUE TITLE
SQL Server full-text search: Short-term improvements to FreeText functions

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#11481]
This is the short-term part of the break down discussed in #1590, i.e. things we should improve on the FreeText API before release.

The first argument is not really a property name but it has to be a reference to a property on the range variable:

1. Disallow (e.g. by throwing while translating the query) any string expression that is not a reference to a property. We need to be able to translate it to a column reference in SQL.  
2. Rename the parameter from `propertyName` to `propertyReference` (feel free to ask for feedback from the team if you don't like this name. Another option is to just call it property).

**Comment by smitpatel** [comment]
Removing milestone to discuss further based on discussion https://github.com/aspnet/EntityFrameworkCore/pull/11524#discussion_r178936215
