### ISSUE TITLE
Online index migrations

### ISSUE THREAD

**Issue by flagbug** [aspnet/EntityFrameworkCore#11499]
For a highly available zero-downtime deployment, we would need the ability to perform online index operations on Azure SQL Database, so basically

`CREATE INDEX ... WITH (ONLINE = ON)`

Is there anything in EF Core that supports this and if not, is this something on the teams roadmap?

**Comment by flagbug** [comment]
Alright, so I've figured out how to customize this pretty easily:

First, we create an extension to the index migration that adds an annotation:

```cs
public static class IndexMigrationExtensions
{
    public static OperationBuilder<CreateIndexOperation> AsOnlineIndexMigration(this OperationBuilder<CreateIndexOperation> operation)
    {
        operation.Annotation("SqlServer:OnlineIndex", String.Empty);

        return operation;
    }
}
```

Second, we override the SQL Server migration generator and look up if the annotation exists:

```cs
public class OnlineIndexSqlServerMigrationsSqlGenerator : SqlServerMigrationsSqlGenerator
{
    public OnlineIndexSqlServerMigrationsSqlGenerator(MigrationsSqlGeneratorDependencies dependencies, IMigrationsAnnotationProvider migrationsAnnotations) :
        base(dependencies, migrationsAnnotations)
    {
    }

    protected virtual string StatementTerminator => ";";

    protected override void Generate(CreateIndexOperation operation, IModel model, MigrationCommandListBuilder builder, bool terminate)
    {
        base.Generate(operation, model, builder, false);

        var includeIndexAnnotation = operation.FindAnnotation("SqlServer:OnlineIndex");

        if (includeIndexAnnotation != null)
        {
            builder.Append($" WITH(ONLINE = ON)");
        }

        if (terminate)
        {
            builder.AppendLine(StatementTerminator);
            EndStatement(builder);
        }
    }
}
```

Now, in the migration itself, we can apply the online index modifier like this:

```cs
migrationBuilder.CreateIndex(
    name: "IX_Bla",
   table: "Bla",
   column: "Bla")
.AsOnlineIndexMigration();
```

The generated SQL will look like this:

```sql
CREATE INDEX [IX_Bla] ON [Bla] ([Bla]) WITH(ONLINE = ON);
```

Is this something that EF Core should support out of the box? Seems pretty important for highly-available systems.

**Comment by nikitasavinov** [comment]
Dear maintainers,

Would you mind if I work on this issue? Implementation seems to be relatively trivial.
I thought of  creating an API which is similar to ForSqlServerIsClustered i.e.
1. Add a new annotation constant to SqlServerAnnotationNames
2. Add a new property to ISqlServerIndexAnnotations and it's implementations
3. Add a method similar to ForSqlServerIsClustered (ForSqlServerOnline?)
4. Cover with tests

**Comment by smitpatel** [comment]
@nikitasavinov - Certainly go for it. Your steps cover everything needed from model side. You would also need to flow the information to migration and generate specific SQL. (similar to code snippets show in above post).

**Comment by nikitasavinov** [comment]
@smitpatel Thank you for such a quick reply! 
Yes, indeed, I didn't mention these steps but also meant them.

**Comment by Kukkimonsuta** [comment]
@nikitasavinov Are you still working on this? If not I'd like to take this on.

**Comment by nikitasavinov** [comment]
Frankly - no, I didn't find time for it. Good luck!

ср, 10 окт. 2018 г. в 14:47, Lukáš Novotný <notifications@github.com>:
