### ISSUE TITLE
Add built-in conversions from strings to other types

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#11492]
We have strings to bytes, but we could also have strings to anything else that can be parsed. (I did intend to do this, but seem to have missed it.)

**Comment by ajcvickers** [comment]
Note for triage: doesn't have to be in 2.1, but would be nice if we have time.

**Comment by SSkovboiSS** [comment]
Is this up-for-grabs? I would give it a try.
