### ISSUE TITLE
Analyzer might need to target a lower TFM

### ISSUE THREAD

**Issue by pranavkm** [aspnet/EntityFrameworkCore#11507]
Got this when I was building scaffolding locally:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	IDE1003	Analyzer assembly 'C:\Users\Pranav\.nuget\packages\microsoft.entityframeworkcore.analyzers\2.1.0-preview2-30478\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll' depends on 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.	VS.Web.CG.EFCore		1	Active
```

Most other analyzers out there target `netstandard1.3` or lower (e.g. https://github.com/dotnet/roslyn-analyzers/blob/26fe065161a871718c717da1821d82c4decbc8e9/src/Microsoft.CodeAnalysis.Analyzers/CSharp/Microsoft.CodeAnalysis.CSharp.Analyzers.csproj#L4, https://github.com/xunit/xunit.analyzers/blob/master/src/xunit.analyzers/xunit.analyzers.csproj#L14)

**Comment by pranavkm** [comment]
cc @ajcvickers might need this for preview2.

@pakrym do you know much about the tfm requirements? Logging's already targeting ns1.3

**Comment by pakrym** [comment]
I think I just did lowest possible without a lot of thinking.

**Comment by smitpatel** [comment]
Reason for ns1.3 https://github.com/dotnet/roslyn/issues/22368

**Comment by smitpatel** [comment]
Re-opening to discuss in triage.

**Comment by divega** [comment]
@smitpatel curious, what is that we should discuss? There is at least one report that the problem still repros in some cases.

**Comment by smitpatel** [comment]
This was done since deadline for preview2 and it was "blocking" in preview2. It was done without any triage discussion with team. So I re-opened.

**Comment by divega** [comment]
**EF Triage: ** We believe that this is fine the way it is.
