### ISSUE TITLE
2.1.0-preview2 verification: Exploratory testing of global tools

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#11545]
@smitpatel to try the new dotnet ef global tools on Mac.

**Comment by smitpatel** [comment]
Tested & verified following:
- `dotnet ef` is available everywhere after installing SDK
- Running dotnet restore when referencing Tools.DotNet shows warning that its obsolete and can be removed. Tools are bundled in SDK.
- `dotnet ef` works correctly with project referencing EF Core 2.0.0/2.1.0-preview1
- Running `dotnet ef` on project targeting netcoreapp1.1 using EF Core 1.1.4 gives error message that tools needs netcoreapp2.0 or higher.
- Running `dotnet ef` on netcoreapp2.0 project with EF Core 1.1.4 throws exception. (low priority to fix in 1.1.x patch)

**Comment by divega** [comment]
> Running dotnet ef on project targeting netcoreapp1.1 using EF Core 1.1.4 gives error message that tools needs netcoreapp2.0 or higher.

@bricelam @smitpatel does it have a fwlink?

**Comment by smitpatel** [comment]
Yes https://go.microsoft.com/fwlink/?linkid=871254
