### ISSUE TITLE
2.1.0-preview2 verification: Exploratory testing of inheritance with owned types 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#11547]
@maumar to try inheritance with owned types, combined with:
- Data seeding
- Value conversions
- Enums
- Migrations 

On a raspberry pi in the cloud :trollface:

**Comment by ajcvickers** [comment]
@maumar @divega Punt this to RC as well?

**Comment by maumar** [comment]
Found issue: https://github.com/aspnet/EntityFrameworkCore/issues/11607
