### ISSUE TITLE
DateTimeOffset.Now should be translated to SYSDATETIMEOFFSET()

### ISSUE THREAD

**Issue by nidilong** [aspnet/EntityFrameworkCore#11594]
im use entityframework core 2.1.0-preview1-final.

I hava a model:
`public class SmsRecord
{
public int Purpose { get; set; }
public string Mobile { get; set; }
public string Code { get; set; }
public DateTimeOffset ExpireDate { get; set; }
public bool IsDeleted { get; set; }
public DateTimeOffset CreateDate { get; set; }

}`

and:
`public void Configure(EntityTypeBuilder<SmsRecord> builder) {
    builder.ToTable("SmsRecords");

    builder.Property<SmsPurpose>("Purpose").IsRequired();
    builder.Property<string>("Mobile").HasMaxLength(16).IsRequired();
    builder.Property<string>("Code").HasMaxLength(16);
    builder.Property<DateTimeOffset>("ExpireDate").IsRequired();

    builder.Property<DateTimeOffset>("CreateDate").IsRequired();
    builder.Property<bool>("IsDeleted").IsRequired();

}`

use the linq
`await _db.SmsRecords.AnyAsync(p => !p.IsDeleted && p.Purpose == purpose && p.Code == code && p.Mobile == mobile && p.ExpireDate > DateTimeOffset.Now)`
and get the following sql:
`exec sp_executesql N'SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [SmsRecords] AS [p]
        WHERE (((([p].[IsDeleted] = 0) AND ([p].[Purpose] = @__purpose_0)) AND ([p].[Code] = @__code_1)) AND ([p].[Mobile] = @__mobile_2)) AND ([p].[ExpireDate] > CAST(GETDATE() AS datetimeoffset)))
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END',N'@__purpose_0 int,@__code_1 nvarchar(16),@__mobile_2 nvarchar(16)',@__purpose_0=5,@__code_1=N'659375',@__mobile_2=N'12345678901'`
the DateTimeOffset.Now was translated to "CAST(GETDATE() AS datetimeoffset)", the timezone info was lost.
it should be translated to SYSDATETIMEOFFSET() instead of GETDATE()

**Comment by ajcvickers** [comment]
@nidilong What version of EF Core are you using and with which database provider?

**Comment by ajcvickers** [comment]
Discussed in triage and looks like this is a bug in the SQL Server provider. Putting on the backlog.

**Comment by smitpatel** [comment]
Adding up-for-grabs lablel. It should be easy to make a fix in https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerDateTimeMemberTranslator.cs

**Comment by nidilong** [comment]
@ajcvickers Yes, im use SQL Server provider.
