### ISSUE TITLE
Query: Remove RelationalQueryCompilationContext dependency from SelectExpression

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFrameworkCore#11601]
`SelectExpression` is referenced by compiled queries, which caused us to leak an instance of  `RelationalQueryCompilationContext` via `SelectExpression._queryCompilationContext`. As a mitigation we introduced `SelectExpression.DetachContext`, but we should just break the dependency.

**Comment by smitpatel** [comment]
Fixed in new pipeline.
