### ISSUE TITLE
2.1 preview2 - why so many packages

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#11633]
When moving my 4.6.1 based provider from preview1 to preview2, the number of packages has exploded - is this expected?

https://github.com/ErikEJ/EntityFramework.SqlServerCompact/commit/15a43663d3712b388530e90c518ce21259b98716

**Comment by smitpatel** [comment]
`EFCore.Analyzers`

**Comment by ErikEJ** [comment]
Thought so - not a good end user experience, sadly
