### ISSUE TITLE
Having clause missing in Grouping Subquery

### ISSUE THREAD

**Issue by Suchiman** [aspnet/EntityFrameworkCore#11646]
While trying to find a workaround for #10012 that does not generate exceptions due to invalid sql, i've found this query that executes successful but delivers incorrect results as it forgets about the `HAVING` clause

### Steps to reproduce

```c#
class Program
{
    public static readonly LoggerFactory MyLoggerFactory = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    static void Main(string[] args)
    {
        var context = new FileContext();
        context.Database.EnsureCreated();

        var duplicateSizes = context.FileEntries
            .GroupBy(x => x.Size)
            .Where(x => x.Count() > 1)
            .Select(x => x.Key);

        var fileEntries = context.FileEntries
            .Where(x => duplicateSizes.Contains(x.Size))
            .ToList();
    }
}

class FileContext : DbContext
{
    public DbSet<FileEntry> FileEntries { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var builder = new SqliteConnectionStringBuilder();
        builder.DataSource = "db.sqlite";
        optionsBuilder
            .UseLoggerFactory(Program.MyLoggerFactory)
            .UseSqlite(builder.ToString());
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FileEntry>()
            .HasIndex(x => x.Size);
    }
}

class FileEntry
{
    public long Id { get; set; }
    public long Size { get; set; }
    public string Path { get; set; }
}
```

### Produced SQL
```sql
SELECT "x"."Id", "x"."Path", "x"."Size"
FROM "FileEntries" AS "x"
WHERE "x"."Size" IN (
  SELECT "x0"."Size" AS "Key"
  FROM "FileEntries" AS "x0"
  GROUP BY "x0"."Size"
)
```

### Expected SQL
```sql
SELECT "x"."Id", "x"."Path", "x"."Size"
FROM "FileEntries" AS "x"
WHERE "x"."Size" IN (
  SELECT "x0"."Size" AS "Key"
  FROM "FileEntries" AS "x0"
  GROUP BY "x0"."Size"
  HAVING COUNT(*) > 1
)
```

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.7 p3

**Comment by smitpatel** [comment]
@Suchiman - Thanks for trying out preview and reporting this bug. I will have fix out soon.

**Comment by zulander1** [comment]
I am not sure if this is related of not but the where is not working  as expected in the group by in 2.1.0-preview2-final.
this is the simplified query. it is have the same effect as above.


var Test = (from orderPlaced in db.Orders
				  where orderPlaced.OrderDate > StartDate && orderPlaced.OrderDate < EndDate
				  group orderPlaced by new { orderPlaced.id } into orderPlacedGrp
				  select new OrderPlaced()
				  {
					  Placed = orderPlacedGrp.Where(x => x.IsPlaced == true).Count(),
					  UnPlaced = orderPlacedGrp.Where(x => x.IsPlaced == false).Count(),
				  }).AsQueryable();

**Comment by smitpatel** [comment]
@zulander1 - It is different issue. I filed #11695
