### ISSUE TITLE
Consider either moving more sample code to docs repo or better leverage the fact that is here

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#11702]
At some point we started creating more sample code in this repo with the idea that this would help having a rich set of runnable samples that you could access directly in the EF Core repo rather than just projects were we can host the documentation's code snippets. 

Technically things almost work thanks to the fact that you can link additional repos in the docs build (@anpete figured out how to do it).

However from the perspective of authoring the documentation (arguably one of the main goal of the samples we have so far) requires two separate PRs (for example, https://github.com/aspnet/EntityFramework.Docs/pull/682 and https://github.com/aspnet/EntityFrameworkCore/pull/11701). 

Also, from the perspective of maintaining runnable samples, having them on this repo is apparently not helping a lot because we don't compile the samples and they can easily become stale (again see https://github.com/aspnet/EntityFrameworkCore/pull/11701).

**Comment by anpete** [comment]
I'm onboard with removing the samples from EF Core if having them is causing friction.

**Comment by ajcvickers** [comment]
Approved for the PM to move the code.
