### ISSUE TITLE
Conventions: Add logging

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#1171]
It would be helpful to find out what the conventions did/didn't do

**Comment by AndriySvyryd** [comment]
Log warning for ambiguous scenarios:
1. Determining the principal end of one-to-one relationship where there are FK candidates on both ends
2. Discovering FK properties of lower priority when the best match is already used (the resulting FKs potentially depend on the order in which the relationships are discovered)
3. Creating multiple shadow FKs (naming depends on order)
4. Discovering the primary key when multiple properties match

**Comment by rowanmiller** [comment]
@abaranch I think this is probably covered by #222, agree?

**Comment by AndriySvyryd** [comment]
This would require changing the convention API and would potentially break providers.
