### ISSUE TITLE
[2.1 Verification] Test defining queries and filters with navigations

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#11729]
See #8881 #3932

**Comment by maumar** [comment]
Found the following issues: https://github.com/aspnet/EntityFrameworkCore/issues/11789 https://github.com/aspnet/EntityFrameworkCore/issues/11790 https://github.com/aspnet/EntityFrameworkCore/issues/11791 https://github.com/aspnet/EntityFrameworkCore/issues/11792 https://github.com/aspnet/EntityFrameworkCore/issues/11803
