### ISSUE TITLE
EntityFramework Core sometimes rounds average to 2 decimal places

### ISSUE THREAD

**Issue by dmytro-ielkin** [aspnet/EntityFrameworkCore#11885]
I have a table with a column of type `DECIMAL(18, 8) among others.
Corresponding model property Price has type `decimal`

When I call `_db.PriceTickers.Average(p => p.LastPrice)` and the result is less that 0.01 it would return 0.01 or even 0.00 sometimes. If however average is greater than 0.01 it shows actual value.

SQL profiler revealed that when EF sends a query it casts the column to DECIMAL(18,2)

[Here is my code EntityFrameworkSqlServerAverageBug.zip](https://github.com/aspnet/EntityFrameworkCore/files/1970554/EntityFrameworkSqlServerAverageBug.zip)

### Steps to reproduce
Compile and run the code

Data:
1	0.00112000
2	0.00232111
3	0.00345223

Tried explicitly setting column type

```c#
            modelBuilder.Entity<PriceTicker>()
                .Property(b => b.Price)
                .HasColumnType("DECIMAL(18,8)");
```

### Further technical details
EF Core version: 2.0.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6
Database Server: SQL Server Express 2017

### Workaround
Materialize the list of decimal values and then call Average method

**Comment by smitpatel** [comment]
Generated SQL
```SQL
SELECT AVG(CAST([pt].[Price] AS decimal(18, 2)))
FROM [PriceTickers] AS [pt]
```
Since we are casting to `decimal(18,2)` here, we truncate useful data. It is one of the case of type inference. For explicit cast expression we are just looking at CLR Type ignoring type set on property altogether.

**Comment by smitpatel** [comment]
`_db.PriceTickers.Average(p => p.LastPrice)`
QM
```
      Optimized query model:
      '(from PriceTicker pt in DbSet<PriceTicker>
      select [pt].Price).Average()'
```
