### ISSUE TITLE
SQL Server reveng does not work with SQL Server 2008 - is this intentional?

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#11932]
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs#L269 

https://github.com/ErikEJ/SqlCeToolbox/issues/706 

https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-transact-sql?view=sql-server-2017

**Comment by Ronan-Farrell** [comment]
I'm also getting "'CONCAT' is not a recognized built-in function name."

Microsoft SQL Server Standard Edition (64-bit)
10.50.6220 SP3

**Comment by ErikEJ** [comment]
The CONCAT function was added in SQL Server 2012

**Comment by ajcvickers** [comment]
@bricelam @divega Was this intentional? Should we consider reverting for 2.1?

**Comment by bricelam** [comment]
Unintentional. [Looks like](https://support.microsoft.com/en-us/lifecycle/search?alpha=Microsoft%20SQL%20Server%202008) mainstream support has ended for SQL Server 2008 (and R2)...

**Comment by ErikEJ** [comment]
Yes, but then you should make an official decision to not support it any longer, and remove ROW_NUMBER paging etc.

**Comment by bricelam** [comment]
I'm also not against fixing it--just wanted to call that out to consider.

**Comment by ajcvickers** [comment]
@bricelam I think we should prepare a fix and take it to shiproom. If they say no, then so be it. /cc @divega

**Comment by ajcvickers** [comment]
This is _not_ approved from RTM. We should bring it back for the first patch.

**Comment by bricelam** [comment]
Filing #11958 to track porting to 2.1
