### ISSUE TITLE
Include with a mapped query view with invalid navigation name fails with null object from internal code

### ISSUE THREAD

**Issue by julielerman** [aspnet/EntityFrameworkCore#11971]
I've mapped a DbQuery of a non-entity type to a database view.
(The true type and db view are named AuthorArticlesCount. I'm calling them AuthorStat here to simplify but the repo I'm linking to uses the longer name.)

`  public DbQuery<AuthorArticleCount> AuthorArticleCounts{get;set;}`
     
I can run simple LINQ queries successfully.

I then mapped that type as a dependent in a one to one relationship with an entity.

```
modelBuilder.Query<AuthStat>().HasOne<Author>()
                               .WithOne()
                               .HasForeignKey<AuthorStat>(a=>a.AuthorId); 
```
Note that there are no navigation properties in Author or AuthorStat. AuthorStat has only AuthorId FK property.

Queries against the query type that include the entity fail.
Queries against the entity that include the query type fail.
e.g.

    `   var results = _context.Authors.Include("AuthorArticleCounts").ToList();
   `  
The failure is a null reference exception coming from 
 Microsoft.EntityFrameworkCore.Metadata.Internal.EntityTypeExtensions.DisplayName(IEntityType type)

Full repo: https://github.com/julielerman/PublicationsTracker

### Further technical details
EF Core version:2.1.0-rc1-final
Database Provider:  Microsoft.EntityFrameworkCore.Sqlite)
Operating system: macOS High Sierra 
IDE: VS Code 1.21.1

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/9c642d3df13a6367d312bbd08a6c440fec012664/src/EFCore/Query/Internal/IncludeCompiler.cs#L248-L283

Not all paths set value of longestMatchFound. Especially for the case when stack count is 0 and nav prop is not found. Causing error during throwing exception for bad include.

**Comment by ajcvickers** [comment]
Triage: Since "AuthorArticleCounts" is not a navigation property this would be expected to fail. although with a better message.

**Comment by julielerman** [comment]
Modelbuilder doesn't like that!

 ```
public class Author
    {
        public int AuthorId { get; set; }
        public string Name { get; set; }
        public List<Article> Articles { get; set; }
        public AuthorArticleCount ArticleCount{get;set;}
    }
```

AuthorArticleCount started out as:

```
public class AuthorArticleCount
{
    public string AuthorName { get; private set; }
    public int ArticleCount { get; private set; }
    public int AuthorId { get; private set; }
}
```

I also removed the HasOne mapping thinking that maybe it would be conventional anyway.
Also, note that I have a DbQuery for AuthorArticleCount and another Query mapping so I could use ToView. So the context knows it's a query type.

Yet I'm getting:
`'Cannot access type 'AuthorArticleCount' as a query type because it has already been declared as an entity type.'`

I have tried a variety of schemas. 

I removed AuthorId from AuthorArticleCount.

Same error.

I added the HasOne mapping back in but without the FK method so it now looks like this:
  ` modelBuilder.Query<AuthorArticleCount>().HasOne<Author>().WithOne(a=>a.ArticleCount); `

Same error.

I added the AuthorId property back in to AuthorArticleCount.

same error.

I just pushed the latest state of this up to my repo linked in the initial post in this issue.

**Comment by divega** [comment]
@julielerman in your model `Author` has a navigation property of type `AuthorArticleCount`. This means `AuthorArticleCount` has to be an entity (since it doesn't have a key property, it can be an owned entity if you configure it as such).

If you want `AuthorArticleCount` to be a query type that has a relationship, then you want a navigation property on `AuthorArticleCount` that points to some principal, for example `Author`.

Relationships without navigation properties don't mean much for objects that aren't tracked.

**Comment by julielerman** [comment]
ok i will try again. Being that the query type is the dependent in the relationship, it made most sense to me to do it the other way. It's too bad there wasn't an example somewhere. I've spent the last two days guessing. I will switch it around and report back.

**Comment by julielerman** [comment]
that works but it was super unintuitive. And it sure feels like this setup puts the query type as the principal which is probably why I avoided it for so long given the fact that it can't be.

**Comment by julielerman** [comment]
One more note ...I think if I had chosen one to many rather than one to one, it would have come to me more quickly! I will try one to many next.

**Comment by divega** [comment]
> .I think if I had chosen one to many rather than one to one, it would have come to me more quickly!

Yes, exactly, I was going to be say the same thing. You are thinking about 1:1 and the you tend to have the nav prop pointing to the principal to the dependent. 

In the docs we currently say:

> Only support a subset of navigation mapping capabilities - Specifically, they may never act as the principal end of a relationship.

Agreed that we can make this much more explicit.

**Comment by julielerman** [comment]
thanks, Diego!

**Comment by andriysavin** [comment]
One more thing to note: if I change DbQuery<AuthorArticleCount> property name on the DbContext so it's alphabetically earlier than DbSet<Author> property name, then all works nice. So this behaviour isn't stable and depends on the order in which Sets are enumerated. Is that all by design, or a bug?

**Comment by andriysavin** [comment]
Here it is: https://github.com/aspnet/EntityFrameworkCore/issues/12119

**Comment by stil** [comment]
I have encountered this error and I think the exception message could be more informative than `NullReferenceException`.

In my case I did `.Include(message => message.UserId)` instead of `.Include(message => message.User)` (included foreign key instead of navigational property). I spend good 20 minutes tracking this simple problem.

**Comment by nickelbob** [comment]
@julielerman I'm struggling a bit to figure out how you got it to work and the repo doesn't look updated. Would you be able to share some code samples here?

I'd also be very interested to see if/how you got one to many to work as I'm currently struggling with that.

Thanks!

**Comment by nickelbob** [comment]
Nevermind, found some good examples here - https://msdn.microsoft.com/en-us/magazine/mt847184

**Comment by SimonCropp** [comment]
can someone answer the question from @stil  https://github.com/aspnet/EntityFrameworkCore/issues/11971#issuecomment-399711832

**Comment by smitpatel** [comment]
@SimonCropp @stil - In 2.2 release, it will throw exception saying that `UserId` is not navigation for `Message` to be used in Include.
