### ISSUE TITLE
Benchmarks: Run benchmarks for EF Core 2.1

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#11997]
Combinations would be
EF Core 2.0 on net461/netcoreapp2.0
EF Core 2.1 on net461/netcoreapp2.1
EF Core dev (2.2) on net461/netcoreapp2.0/netcoreapp2.1/netcoreapp2.2

**Comment by divega** [comment]
@smitpatel should this be closed?
