### ISSUE TITLE
Oracle Sample: Upgrade to .NET Core data provider

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFrameworkCore#12036]
https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/2.12.0-beta2

**Comment by ajcvickers** [comment]
@ralmsdeveloper Can you try running all the tests like you did before? (We likely won't be able to use the beta ourselves because the license is problematic.)

**Comment by ralmsdeveloper** [comment]
@ajcvickers 
253 tests failed.
But I solved with a small adjustment, this also solves: https://github.com/aspnet/EntityFrameworkCore/issues/12053

If you want I can do a PR

**Comment by ajcvickers** [comment]
@ralmsdeveloper Yes, please!

**Comment by ajcvickers** [comment]
@ralmsdeveloper Thanks for testing this!
