### ISSUE TITLE
wrong method-name in warning when not explicitly define precisions for decimals

### ISSUE THREAD

**Issue by riscie** [aspnet/EntityFrameworkCore#12041]
The (new) warning produced by EF when not explicitly define precisions for decimals seems to suggest the usage of the wrong Fluent API method-name. (`ForHasColumnType()` instead of `HasColumnType()`).

The warnings xml-name value is `LogDefaultDecimalTypeColumn`.

See here: https://github.com/aspnet/EntityFrameworkCore/blob/c786c334ff1a403a3d72f33c9374eb0a70e7c3f8/src/EFCore.SqlServer/Properties/SqlServerStrings.resx#L145

Here is the link to the method in question: 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalpropertybuilderextensions.hascolumntype?view=efcore-2.0

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Any
IDE: Any

**Comment by smitpatel** [comment]
@riscie - Would you like to submit a PR to correct this?

**Comment by riscie** [comment]
Sure, I would like to do so 👍

**Comment by smitpatel** [comment]
@riscie - Can you open a PR so we can look at what is going wrong? Perhaps current code is not propertly generated. For this small change hand editing .resx & designer.cs should also be fine.

**Comment by riscie** [comment]
@smitpatel - I did the change by hand.
