### ISSUE TITLE
Internalize external dependencies

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#12048]
There is an ongoing discussion on how to improve our ability to service libraries like EF Core if things go really bad, e.g. if there is a security issue that needs to be patched urgently but we cannot wait for a dependency to be patched. 

This issue is about executing on the plan resulting from the discussion, whatever it ends up being (the title assumes that it will require somehow internalizing some of our current dependencies, but it may end up looking different).

**Comment by smitpatel** [comment]
From today's discussions:
- Future of `IAsyncEnumerable` from corefx is unknown.
- We use Ix-Async for linq operators implementation on AsyncEnumerables
- We may need to internalize Ix-Async if we cannot get implementation from corefx. (or implement ourselves)
- Only providers which would do client eval on async enumerables need it. For relational, it would be only FirstOrDefault/Select, For InMemory, it could be everything.
