### ISSUE TITLE
DbFunction tests are missing from the Relational specification tests

### ISSUE THREAD

**Issue by tuespetre** [aspnet/EntityFrameworkCore#12044]
Self-explanatory -- the SQL Server and Oracle test suites have some pretty thorough UDF test classes but these are not available from the `Microsoft.EntityFrameworkCore.Relational.Specification.Tests` package. It would be nice if these were available for other providers or libraries to implement.

**Comment by pmiddleton** [comment]
I can do this if @divega signs off that it is something we want to do.

**Comment by ajcvickers** [comment]
@pmiddleton Yes, a PR for this would be good.

**Comment by smitpatel** [comment]
@pmiddleton - They are not run as part of automated build. They are also broken at present. @ralmsdeveloper is looking into it currently. We can fix the oracle related issues while merging.

**Comment by anpete** [comment]
Fixed in 8f4faa7ccb6e752e27996f802bebbb42b119cbbe
