### ISSUE TITLE
Using many owned types in a join will throw stackoverflow exception in 2.1.0-rc1-final

### ISSUE THREAD

**Issue by Lejdholt** [aspnet/EntityFrameworkCore#12061]
Using many owned types in a join will throw stackoverflow exception in 2.1.0-rc1-final
Unit tests using the InMemoryProvider failes after uppgrading to 2.1.0-rc1-final. Works with the real sql provider. Tests times out and once in a while throws Stackoverflow exception.

I tried 2.1.0-rc1-final because of performace issues with my design in 2.0.0. Haven't had time to evaluate if it's better in 2.1.0-rc1-final because of replicating the bug in another repo.

My design worked good in "old" entity framework. Very bad performance in Core 2.0.0. Failing tests in 2.1.0-rc1-final.

Any design suggestions are welcome.

### Steps to reproduce

[Repo showing the error](https://github.com/Lejdholt/EntityFrameworkCore21Bug)
commit 2f8334ed shows the code base as close to how my real code base is.
The commits after that one are trying to fix the issue. Removeing the owned properties is the only way I could solve it.

My data model needs to save the source for each value along with the value. 
So I've created a some classes that holds value of different tyoes and source like this:

```c#
  public class ReferenceValueDecimal
    {
        public string Source { get; set; }
        public decimal? Value { get; set; }
    }

```
The basic look of the class is like below. Just an example of how it look in my real code base. 
The example has 3 data classes.

```c#
    public class Data1
    {
        public long Id { get; set; }
        public Guid EntityId { get; set; }  
        public ReferenceValueBool Prop1 { get; set; }
        public ReferenceValueDateTime Prop2 { get; set; }
        public ReferenceValueDateTime Prop3 { get; set; }
        public ReferenceValueDouble Prop4 { get; set; }
        public ReferenceValueDouble Prop5 { get; set; }
        public ReferenceValueInteger Prop6 { get; set; }
        public ReferenceValueDateTime Prop7 { get; set; }
        public ReferenceValueDecimal Prop8 { get; set; }
        public ReferenceValueDouble Prop9 { get; set; }
        public ReferenceValueDecimal Prop10 { get; set; }
        public ReferenceValueInteger Prop11 { get; set; }
        public ReferenceValueDouble Prop12 { get; set; }
        public ReferenceValueDecimal Prop13 { get; set; }
        public ReferenceValueInteger Prop14 { get; set; }
        public ReferenceValueDateTime Prop15 { get; set; }
        public ReferenceValueDecimal Prop16 { get; set; }
        public ReferenceValueDateTime Prop17 { get; set; }
        public ReferenceValueDouble Prop18 { get; set; }
        public ReferenceValueDateTime Prop19 { get; set; }
        public ReferenceValueDateTime Prop20 { get; set; }
    }
```

So when I try to join my three data classes on the same EntityId the  tests fails. Like This:
```c#
  using (var context = new DataContext(options))
            {
                Guid[] ids = new[] { entityId };

                var query = from data1 in context.Data1s
                            where ids.Contains(data1.EntityId)
                            join data2 in context.Data2s on data1.EntityId equals data2.EntityId
                            join data3 in context.Data3s on data1.EntityId equals data3.EntityId
                            select new { data1, data2, data3 };

                var result =  query.ToArray();
            }
```
### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10
IDE:  Visual Studio 2017 15.7.1

**Comment by smitpatel** [comment]
After upgrading the repro project to 3.1, the test passes.
