### ISSUE TITLE
SqlServerXXXXTypeMapping::Clone(string storeType, int? size)

### ISSUE THREAD

**Issue by dmitry-lipetsk** [aspnet/EntityFrameworkCore#12075]
### Further technical details
EF Core version: dev

SqlServerByteArrayTypeMapping and SqlServerStringTypeMapping have the method "public override RelationalTypeMapping Clone (string storeType, int? Size)", which has the same code as base RelationalTypeMapping :: Clone (string storeType, int? Size)

ByteArrayTypeMapping and StringTypeMapping does not define Clone (string storeType, int? Size)

I offer to remove the Clone (string storeType, int? Size) from SqlServerByteArrayTypeMapping and SqlServerStringTypeMapping

Or write the comment about reason of they definition.

It can help to writers of another EFCore providers.

Thanks.

**Comment by ajcvickers** [comment]
@AndriySvyryd Can the overrides be removed from https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.SqlServer/Storage/Internal/SqlServerByteArrayTypeMapping.cs#L67 and https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs#L76?
