### ISSUE TITLE
Remove LogValueConversionSqlLiteralWarning

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#12085]
And add a fwlink to the message.

**Comment by ajcvickers** [comment]
@divega to create the forward link.

**Comment by divega** [comment]
Created fwlink: https://go.microsoft.com/fwlink/?linkid=874557. Currently pointing to https://docs.microsoft.com/ef/core/modeling/value-conversions#limitations, but this section should be expanded with more useful information. I will create a docs issue for that.

**Comment by ajcvickers** [comment]
Moving this to 3.0 to consider after query 3.0 work. Examples of things we might warn for:
* Any SQL translation that makes use of a value-converted property, since the translation may not work with the actual database type.
* Consider not warning if it is known the translation is safe--e.g. for quality,

**Comment by smitpatel** [comment]
Blocked on #13192

**Comment by smitpatel** [comment]
Discussed with @ajcvickers about this,
We wanted to warn whenever SQL literals/parameters generated using ValueConverters, but with #13192, it would be mostly correct use. It is highly likely that if we make error, it would cause invalid SQL. With that the warning provides little value. There could be some cases where it would generate valid but incorrect SQL, but if we are smart enough to identify such case, we can just fix it.

Re-purposing this issue to remove the warning.

**Comment by smitpatel** [comment]
The warning has been removed.
