### ISSUE TITLE
ORA-00942:  the table or view does not exist

### ISSUE THREAD

**Issue by ralmsdeveloper** [aspnet/EntityFrameworkCore#12099]
I'm working on some things in Oracle and now I have this message: 
`ORA-00942:  the table or view does not exist`

I have the same problem with my Firebird provider, maybe @roji  has the same message.
This is because the escape of `Entities1` was removed here:
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs#L683-L685

Can I submit this simple fix as part of PR Oracle?

cc/ @AndriySvyryd @ajcvickers

**Comment by ralmsdeveloper** [comment]
The same here: 
[QueryNoClientEvalTestBase.cs#L121](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs#L121)  And [QueryNoClientEvalTestBase.cs#L134](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs#L134)
 
cc/ @AndriySvyryd

**Comment by ralmsdeveloper** [comment]
@AndriySvyryd, let me know if I can do the PR, I have already uploaded the work to my repository.

The change was simple, you can review [here ](https://github.com/ralmsdeveloper/EntityFrameworkCore/blob/a068a4ea0ae6df996361d3c6ad4ac585c20a14a6/src/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs#L121)

**Comment by AndriySvyryd** [comment]
@ralmsdeveloper the change is a bit more complex because not all providers support the " as a delimeter
