### ISSUE TITLE
Investigate deadlock in AsyncSimpleQueryTestBase tests using pooling

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#12138]
The tests `Throws_on_concurrent_query_list` and `Throws_on_concurrent_query_first` cause deadlocks in other tests.

**Comment by ajcvickers** [comment]
Closing as this is no longer relevant with the latest query changes.

**Comment by smitpatel** [comment]
There is still deadlock in ConcurrencyDetectorTestBase

**Comment by smitpatel** [comment]
Found the cause: re-entrant exception makes ConcurrencyDetector unusable and in pooling scenario, it would cause deadlock.
