### ISSUE TITLE
Using SizeLimit with MemoryCache cause queries to fail

### ISSUE THREAD

**Issue by sanishmistry** [aspnet/EntityFrameworkCore#12157]
### Steps to reproduce

Use MemoryCache with ASP.NET Core in Startup.cs

            services.AddMemoryCache(o => {
                o.SizeLimit = 5000;
                
            });

Then do a query

        public IActionResult Test([FromServices] AppDbContext db)
        {
            var x = db.PostCodes.Where(p => p.Value == "XXXX").ToList();
    ...
        }

### The issue

You get an exception like this 

                    An unhandled exception has occurred while executing the request
            System.InvalidOperationException: Cache entry must specify a value for Size when SizeLimit is set.
                at Microsoft.Extensions.Caching.Memory.MemoryCache.SetEntry(CacheEntry entry)
                at Microsoft.Extensions.Caching.Memory.CacheEntry.Dispose()
                at Microsoft.Extensions.Caching.Memory.CacheExtensions.Set[TItem](IMemoryCache cache, Object 
            key, TItem value)
                at 
            Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc] 
            (Object cacheKey, Func`1 compiler)
                at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
                at Remotion.Linq.QueryableBase`1.GetEnumerator()
                at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
                at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

### Further technical details

EF Core Version : 2.0.2
MySQL version:  5.7.22-0ubuntu0.16.04.1 - (Ubuntu)
Operating system:  Ubuntu 16.04.4 LTS
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

**Comment by smitpatel** [comment]
This should probably moved to aspnet/Caching repo. We use Set method directly which has no way to specify size for the entry. MemoryCache extension methods create CacheEntry itself so it should set value for size. (especially when they have check for it)

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/Caching/issues/399

**Comment by divega** [comment]
@Tratcher stopped by to talk about this. 

I am reactivating to consider moving EF Core to have its own private instance of the cache service, which would prevent the issue reported by the customer. Apparently we are already doing this on other ASP.NET Core libraries and the resolution for https://github.com/aspnet/EntityFrameworkCore/issues/2052#issuecomment-106118489 no longer applies. However because memory cache is still registered as a singleton we cannot use DI to instantiate it.

@Tratcher also recommended that we include our own configurable and default size limit setting and sliding window eviction policy to mitigate the possibility of cache explosion.

**Comment by divega** [comment]
Some examples provided by @Tratcher:

https://github.com/aspnet/ResponseCaching/blob/dev/src/Microsoft.AspNetCore.ResponseCaching/ResponseCachingOptions.cs#L14
https://github.com/aspnet/ResponseCaching/blob/d5430992d3bcf0333bcd9974558188d45ca8b489/src/Microsoft.AspNetCore.ResponseCaching/ResponseCachingMiddleware.cs#L40-L43
https://github.com/aspnet/ResponseCaching/blob/d5430992d3bcf0333bcd9974558188d45ca8b489/src/Microsoft.AspNetCore.ResponseCaching/Internal/MemoryResponseCache.cs#L68-L72
https://github.com/aspnet/Caching/blob/dfd3f2c5c456d4aeceae296ac2ee3d22f8d22cf7/src/Microsoft.Extensions.Caching.Abstractions/MemoryCacheEntryOptions.cs#L55-L59

**Comment by Tratcher** [comment]
Filed https://github.com/aspnet/Docs/issues/6958 for doc updates.

**Comment by ajcvickers** [comment]
Notes from triage: to add to Diego's comments, we currently attempt to use the cache from the external service provider if available. We can stop doing this, meaning in all normal cases we would use our own cache. If the application is explicitly building the internal service provider and wants it to use the application service provider for this (which is not common) will there need to be common configuration for both, but that doesn't seem unreasonable.

**Comment by ajcvickers** [comment]
Re-discussed in triage and decided to move this to 2.2 to at least help prevent a bug in query caching from resulting in out-of-memory. See #8223

**Comment by ajcvickers** [comment]
Per discussion in triage, using this bug to track cache eviction (as indicated in last comment) is not appropriate, so filed #12905 instead.

**Comment by AndriySvyryd** [comment]
Fixed in cbd28ff4871cc5abc626dc7b4917a0b20538e2f8
