### ISSUE TITLE
CommandParameterName and CommandParameterMarkerName

### ISSUE THREAD

**Issue by dmitry-lipetsk** [aspnet/EntityFrameworkCore#12152]
EF Core version: dev

**Terms**
1. Parameter Marker Name - string, which used in command text. For example: "@a" - "select ID from TTT where ID=@a".
2. Parameter Name - string, which used for acces of parameter object. For example: "@a" or "a"

As I understood, EF Core supports only variant when "parameter marker name" equal to "parameter name": "@a" / "@a".

And not support variant, when parameter name does not contain the "parameter prefix" ("@"): "@a" / "a".

I need in the support of second variant.

This can be done through overriding of exists virtual methods?

Thanks.

**Comment by smitpatel** [comment]
@dmitry-lipetsk - Can you elaborate this more? I am not able to understand the terms correctly. 
In query side at least,
Each parameter has normal name (like `__a` `__` is query prefix for parameters), and they are converted to parameter name using following code.
https://github.com/aspnet/EntityFrameworkCore/blob/5815024858f4a5787555da5fa212130b6960bb7f/src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs#L48-L49

Providers can override that method to generate custom parameter names.

**Comment by dmitry-lipetsk** [comment]
I want to configure EFCore for usage "@a" (prefix+name) in command text and "a" (name only) as name of command object parameter (DbParameter.ParameterName)

Currently, EFCore uses "@a" in both cases.

RelationalSqlGenerationHelper should expose two methods:
1. GenerateParameterName - for DbParameter.ParameterName ("a" or "@a")
2. GenerateParameterMarker - for command text ("@a")

**Comment by smitpatel** [comment]
Perhaps we could do that. I believe since we haven't encountered such provider we did not have 2 methods.
For now (at least for queries), you could override following code to use different names in parameters list and in command text.
https://github.com/aspnet/EntityFrameworkCore/blob/e4f00d4ae9871d1cb16b75af98cd12f068d3d7df/src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs#L1717-L1742

**Comment by dmitry-lipetsk** [comment]
Ok. I will try.

Thank you.

**Comment by ajcvickers** [comment]
@dmitry-lipetsk Is it necessary that the parameter name be different from the "marker name" or is it just a preference?

**Comment by dmitry-lipetsk** [comment]
I think, EFCore should allow (me) select structure for name and marker.

In MSSQL world: marker==name. Both contains the prefix.
In Delphi (InterBase/Firebird) world: marker == prefix+name.

My ADO.NET driver supports both variants. User defines required mode through connection string.

Look to System.Data.Common.DbCommandBuilder. This class has the next abstract methods:

```
//Returns the name of the specified parameter in the format of p*#*. Use when building a custom command builder.
protected abstract string GetParameterName(int parameterOrdinal);

//Returns the placeholder for the parameter in the associated SQL statement.
protected abstract string GetParameterPlaceholder(int parameterOrdinal);
```

GetParameterName generates the name
GetParameterPlaceholder generates the "marker"

**Comment by ajcvickers** [comment]
@dmitry-lipetsk Let me try to ask the question in a different way. When will marker == name fail for Firebird? Always? Only when the provider is configured in some way? Never, it just looks wrong?

**Comment by dmitry-lipetsk** [comment]
Firebird does not support named parameters. Only unnamed: select ... where COL=?

Support of named parameters is implemented in the data providers.

FirebirdSql.Data supports only "marker=name".

My providers (IBProvider + lcpi.data.oledb) for FB/IB support both variants. By default: marker = prefix+name. As result, by default, my adapter for EFCore not works. Because EFCore always uses "MSSQL" style.

Of cource, I can write in documentation - "enable in connection the 'MSSQL' style for parameter names". But, as you know - nobody does not read the documentation :)

Or, as variant, I can (in adapter for EFCore) generate the error when I see wrong setting in connection.

But in general, I offer split the terms of parameter marker and parameter name. And allow generate different strings for them.

**Comment by ajcvickers** [comment]
@dmitry-lipetsk We discussed this in triage and we would consider a PR to add something like "GenerateParameterNamePlaceholder(string parameterName)" which would be default just return what is passed in, but could be overridden by your provider to generate something different--for example, remove the @.
