### ISSUE TITLE
Consider using the nullable 'bool?' - Warning Annoyance

### ISSUE THREAD

**Issue by cgountanis** [aspnet/EntityFrameworkCore#12198]
CORE SDK 2.1.300

> 2018-06-01 01:12:22.510 -05:00 [Warning] The 'bool' property '"Deleted"' on entity type '"DataAttachment"' is configured with a database-generated default. This default will always be used for inserts when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used for inserts when the property value is 'null'.   Microsoft.EntityFrameworkCore.Model.Validation 

Model
```
[Required]
public bool Deleted { get; set; } 
```

I can fix it by uncommenting this option in my AddDbContext options.
```
// Add DbContext using connection string from settings.
services.AddDbContext<Context>(options =>
{
	options.UseSqlServer(_configuration.GetConnectionString("DefaultConnection"));
	//options.ConfigureWarnings(wc => wc.Ignore(RelationalEventId.BoolWithDefaultWarning));
});
```

I thought this was going to be fixed? Do I have to add an annotation or default value to all my bool properties? I expect and want them to be false and even set a default value of false on those fields.

`builder.Property(o => o.Deleted).HasDefaultValue(false);`

**Comment by ajcvickers** [comment]
@cgountanis What version of EF Core are you using? (Note that this may not be the same as the SDK version.)

**Comment by cgountanis** [comment]
I only have the CORE 2.1.300 SDK installed to keep things simple as I upgrade to make sure nothing gets funky. I get a bit confused on NUGET vs. SDK, at times it is not correct seems to be getting better.

![image](https://user-images.githubusercontent.com/14899817/40851368-d7f81c96-658c-11e8-99b1-06fc03c1dbf2.png)

```
>dotnet ef --version
Entity Framework Core .NET Command-line Tools
2.1.0-rtm-30799
```

**Comment by bricelam** [comment]
Did you reverse engineer the model using Scaffold-DbContext/dotnet ef dbcontext scaffold?

**Comment by cgountanis** [comment]
@bricelam No as stated, I am doing code-first with Add-Migration unless I am misunderstanding the question.

**Comment by ajcvickers** [comment]
Triage: we should not generate this warning if the database default is `false` because when the default value is `false` the outcome will be the same regardless of whether `false` is inserted or `false` is generated by the store. We will still generate the warning for `true`.

**Comment by cgountanis** [comment]
So does this mean in future release I will not need to suppress the warning with the code (options.ConfigureWarnings) that I have provided?

**Comment by ajcvickers** [comment]
@cgountanis Correct.

**Comment by HybridSolutions** [comment]
This issue still is happening in EF5. Why?

```
Microsoft.EntityFrameworkCore.Model.Validation[20601]
      The 'bool' property 'IsLocked' on entity type 'ApplicationUser' is configured with a database-generated default. This default will always be used for inserts when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used for inserts when the property value is 'null'.
```

My configuration
```
builder.Property(e => e.IsLocked)
                .IsRequired()
                .HasDefaultValueSql("(CONVERT([bit],(0),0))");
```

Here's my migration code but got the warning on all my custom bool properties:

```
migrationBuilder.CreateTable(
                name: "AspNetUsers",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FirstName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    LastName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    JobPosition = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    Photo = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    IsListed = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "(CONVERT([bit],(0),0))"),
                    IsDisabled = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "(CONVERT([bit],(0),0))"),
                    IsLocked = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "(CONVERT([bit],(0),0))"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    LastLoginDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    LastActivityDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    LastSessionId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    PrivateFolder = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    IsOnApproval = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "(CONVERT([bit],(0),0))"),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValueSql: "(CONVERT([bit],(0),0))"),
                    UserName = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    NormalizedUserName = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    Email = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    NormalizedEmail = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    EmailConfirmed = table.Column<bool>(type: "bit", nullable: false),
                    PasswordHash = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SecurityStamp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PhoneNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PhoneNumberConfirmed = table.Column<bool>(type: "bit", nullable: false),
                    TwoFactorEnabled = table.Column<bool>(type: "bit", nullable: false),
                    LockoutEnd = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    LockoutEnabled = table.Column<bool>(type: "bit", nullable: false),
                    AccessFailedCount = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUsers", x => x.Id);
                });
```

Am I doing something wrong here?

**Comment by cgountanis** [comment]
I still see it every time I database first scaffold when there's a nullable bit with a default value of true which does seem kind of dumb but I'm not the DBA.

**Comment by ajcvickers** [comment]
@HybridSolutions You likely still see this because we don't know what the default value is. Do you still see this warning with EF Core 5.0 if you use HasDefaultValue, instead of HasDefaultValueSql? For example:

```C#
builder.Property(e => e.IsLocked)
                .IsRequired()
                .HasDefaultValue(false);
```

**Comment by HybridSolutions** [comment]
> @HybridSolutions You likely still see this because we don't know what the default value is. Do you still see this warning with EF Core 5.0 if you use HasDefaultValue, instead of HasDefaultValueSql? For example:
> 
> ```cs
> builder.Property(e => e.IsLocked)
>                 .IsRequired()
>                 .HasDefaultValue(false);
> ```

Well, it seems that following that recommendation solves the issue. I don't need to use nullable Booleans anymore. My configuration files where generated by the EF Core Power Tools extension (2.5.692) and I have to confess I found weird that it used .HasDefaultValueSql("(CONVERT([bit],(0),0))"); instead of  .HasDefaultValue(false);

It would be great to have Entity Framework Core provide such tools so that it would't be necessary to use these extensions.

Thanks for the help!

**Comment by ErikEJ** [comment]
The standard tooling would generate the exact same configuration code, actually.

power tools allows you to remove the defaults for nullable bool, btw.

**Comment by ajcvickers** [comment]
@HybridSolutions What is the column definition in SQL?

**Comment by HybridSolutions** [comment]
> @HybridSolutions What is the column definition in SQL?

With the change you suggested in my migration file, the column ended like this after updating database. 

![image](https://user-images.githubusercontent.com/8672899/127022425-0d89ea99-a96f-4dcb-95cc-14da73d960e0.png)

**Comment by HybridSolutions** [comment]
> The standard tooling would generate the exact same configuration code, actually.
> 
> power tools allows you to remove the defaults for nullable bool, btw.

You mean this option? I didn't choose because it was in preview.

![image](https://user-images.githubusercontent.com/8672899/127024446-bd3e2e67-489e-4cb0-9906-c6ce28f103af.png)

**Comment by ErikEJ** [comment]
Yes - try it out, be brave! If it works for you, it may go out of preview state! 😅

**Comment by ajcvickers** [comment]
@ErikEJ Is `CONVERT([bit],(0),0))` something that SQL Server or its tooling automatically generates? Should we be identifying this as a common pattern?
/cc @bricelam

**Comment by ErikEJ** [comment]
@ajcvickers It is not something I have seen before..

**Comment by bricelam** [comment]
+1 (haven't seen it), but if we find it comes from a common tool, I'm happy to add it to the ignore list.

**Comment by cgountanis** [comment]
Still getting the warnings on Core 5 (.NET 5), we just ignore for now. Simply, a `BIT NOT NULL DEFAULT (1)`, drives it nuts for some reason. Just accept it and relax :)

**Database-First Scaffold**

![image](https://user-images.githubusercontent.com/14899817/127378807-c95e495b-fb24-4fb5-b8d4-59bdf6a6b36c.png)

![image](https://user-images.githubusercontent.com/14899817/127378831-50db0df2-39a1-4f51-9acb-e425c831c689.png)

The column 'dbo.TableName.IsActive' would normally be mapped to a non-nullable bool property, but it has a default constraint. Such a column is mapped to a nullable bool property to allow a difference between setting the property to false and invoking the default constraint. See https://go.microsoft.com/fwlink/?linkid=851278 for details.

**Comment by cgountanis** [comment]
Still would be nice to get this off the warning list. NOT NULL BIT (1) is something that does come up once and awhile.

**Comment by TolchinJ** [comment]
Still getting the warning when using Microsoft.AspNetCore.Identity.EntityFrameworkCore 8.01:
            entity.Property(e => e.Active)
                .IsRequired()
               .HasDefaultValueSql("((1))");
but goes away if changed to:
            entity.Property(e => e.Active)
                .IsRequired()
                .HasDefaultValue(true);               

Also, using a decorator makes no difference:
    [DefaultValue(true)]
    public bool Active { get; set; }
