### ISSUE TITLE
Using HasData with enum keys causes Add-Migration to generate unneeded deletes/inserts

### ISSUE THREAD

**Issue by schroe2a** [aspnet/EntityFrameworkCore#12194]
My first ever issue report so I apologize in advance if I don't do this right.

I've created the following entity and used PMC "Add-Migration" to generate a migration.  This works as expected and creates both the table and generates insert commands for the data.

```c#
    public class DocumentStatus
    {
        public DocumentStatusTypes Id { get; set; }
        [Required]
        public string Name { get; set; }
        
        public static void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<DocumentStatus>().HasIndex(p => p.Name).IsUnique(true);

            foreach(var e in Enum.GetValues(typeof(DocumentStatusTypes)).Cast<DocumentStatusTypes>())
            {
                builder.Entity<DocumentStatus>().HasData(new DocumentStatus { Id = e, Name = e.ToString() });
            }
        }
    }
    public enum DocumentStatusTypes : int
    {
        PreProcessing = 1,
        AwaitingReview = 2,
        QualityControl = 3,
        Reviewed = 4        
    }
```

NOTE: not pictured the static "OnModelCreating" method here is called from within "OnModelCreating" in the context.

Again, this all works as expected for the first migration you generate.  The problem I'm experiencing is when I generate a second migration by calling "Add-Migration" again, which results in a migration which has commands to delete every row and then insert them all again.  In fact every migration I generate from here out gets 4 deletes and 4 inserts to remove and then replace the identical data.

To this developer it *feels* like a problem where it fails to correctly compare the existing (shapshot) data to that specified in the HasData calls perhaps because one of the properties is an enum instead of a normal integer?

### Further technical details
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: WIN 10
IDE: Visual Studio 2017 15.7.2

**Comment by bricelam** [comment]
What version of the Microsoft.EntityFrameworkCore.SqlServer package are you using?

**Comment by schroe2a** [comment]
That package I referenced from NuGet and is version 2.1.0

FWIW I'm also using the AspNetCore.Identity which is also 2.1.0

```
   <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.0" />
'''

**Comment by huancz** [comment]
I can confirm that seeds are nearly unusable in 2.1 if some of the tables have enum primary keys. Unfortunately our app is full of them and requiring all team members to manually sanitize each new migration is not something I'm comfortable doing, so update to 2.1 seed style will have to wait (I realize this is not critical feature, we all had to do without any seed support before 2.1).

But main reason i'm commenting is to add one more issue here that seems related.

```c#
builder
    .HasData(new ApplicationUser
    {
        Id = ApplicationUser.Entry.SystemUserId,
        ConcurrencyStamp = "aedb6638-2230-4efc-a351-6912fe4cf55e", // type: (string)
        LockoutEnd = DateTime.MaxValue,                            // type: (DateTimeOffset?)
        // ... rest of the IdentityUser<Guid> fields
    });
```

This seed will try to UpdateData() for the two shown fields in every migration (with unchanged values).

ApplicationUser is just slightly extended IdentityUser&lt;Guid&gt;, with the same model configuration. I can imagine that the reason for ConcurrencyStamp update is that it's configured as concurrency token (still wrong behaviour IMO). No idea why it tries to update LockoutEnd though.

Found one workaround - setting the fields to null will stop repeated updates, and I can update the migrationBuilder.InsertData manually.

**Comment by ajcvickers** [comment]
@huancz We looked at this in triage and the scenario seems different, although it is possible they have the same root cause. Can you please file a new issue and include a project/solution or code listing that demonstrates what you are seeing?
