### ISSUE TITLE
Snapshot should preserve the property CLR type when value conversion is used

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#12212]
If the value converted changes the CLR type and no explicit column type has been set then the snapshot should store the model CLR type as the mapping for the provider CLR type might be different.

See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/580

**Comment by ajcvickers** [comment]
Rather than setting the column type explicitly, which is very provider-specific, we should preserve the property CLR type even when there is a conversion without hints.
