### ISSUE TITLE
Invalid SQL generated if GroupBy is preceded by a Distinct and property name is transformed

### ISSUE THREAD

**Issue by flagbug** [aspnet/EntityFrameworkCore#12233]
Im seeing invalid SQL being generated in the specific case that a `GroupBy` is preceded by a `Distinct` and a property name is transformed via `Select`.

My use case is that EF doesn't implement `COUNT(DISTINCT)`, so I'm sometimes writing queries that basically look like this:

```cs
 var results = db.Foos
     .Select(x => new { NewName = x.Prop1, x.Prop2 }) // Notice the name transformation
     .Distinct()
     .GroupBy(x => x.NewName)
     .Select(x => new { x.Key, Count = x.Count() })
     .ToList();
```

In this case, if `x.Prop1` is transformed to `NewName` (ignore the fact that in the query above it doesn't really makes sense, it's for demonstration purposes) AND the `GroupBy` is preceded by a `Distinct`, EF Core generates invalid SQL that looks something like this (please find the exact SQL generated in the reproduction sample below):

```sql
SELECT [t].[Prop1] AS [Key], COUNT(*) AS [SolvedLessons]
FROM (
    SELECT DISTINCT [f].[Prop1] AS [NewName], [f].[Prop2]
    FROM [Foo] AS [f]
) AS [t]
GROUP BY [t].[Prop1]
```

Here it can't find `Prop1` in the outer query, since it's been renamed in the inner query.

This worked fine previous to EF Core 2.1, since q query like this would be partially executed in-memory.

This happens on both SQL Server and SQLite

### Steps to reproduce

I've quickly created a reproducable sample here: [EfCoreDistinctGroupByRepro.zip](https://github.com/aspnet/EntityFrameworkCore/files/2069795/EfCoreDistinctGroupByRepro.zip)

Just run `dotnet run` at the project level and you should get an exception

### Further technical details
EF Core version: 2.1.0
Database Provider: SQLite, SQL Server
Operating system: Windows 10

**Comment by maumar** [comment]
regression tests added in 5ced4046b25fdc71c69e67f076dfbdcda46e2b6e
