### ISSUE TITLE
Implement AttachGraph

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#1229]
As per design meeting discussions here:
https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes:-December-4,-2014#graph-behaviors

**Comment by julielerman** [comment]
beta4 on nuget; where has attachgraph gone? I see issues but not finding discussion of removing. github search finds no attachgraph in code. What's the status of it? Will keep searching.. :)

**Comment by julielerman** [comment]
ooops found TrackGraph! :)
