### ISSUE TITLE
Improve seeding error message when CLR default is used

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#12399]
Posted by @TheBauwssss here: https://github.com/aspnet/EntityFrameworkCore/issues/11776#issuecomment-397814148

Can the error message

> System.InvalidOperationException: The seed entity for entity type '<class>' cannot be added because there was no value provided for the required property 'Id'.

be changed to

> System.InvalidOperationException: The seed entity for entity type '<class>' cannot be added because there was no value provided for the required property 'Id'. **Please note that 0 is not a valid value for the Id field. Please start incrementing from 1.**

I just wasted a whole day trying to figure out why it was not working only to discover that I needed to start incrementing from 1 instead of 0.

**Comment by ajcvickers** [comment]
Triage: we should also look at other exception messages where this information may be helpful.

**Comment by TheBauwssss** [comment]
Thanks! 👍
