### ISSUE TITLE
Remove precision and scale type mapping fallback

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#12405]
Also don't set `Size`, `Precision` or `Scale` in `RelationalTypeMapping` if the corresponding `StoreTypePostfix` is not set.

**Comment by roji** [comment]
@AndriySvyryd can I poach? Am working in the area on #11896.

**Comment by AndriySvyryd** [comment]
@roji Sure, let me know if you have any questions.
