### ISSUE TITLE
Consider always write to backing fields by default

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#12430]
However, also consider notification entities where setting the property may be needed to trigger the notification.

**Comment by sjb-sjb** [comment]
The advantage to backing fields cited in https://docs.microsoft.com/en-us/ef/core/modeling/backing-field is that one can then have private property setters. 

The programmer's decision to have property setters used for materialization (or, for example, for reversion when State is set to Unchanged) is likely based on very different considerations than the decision of whether a given property should be public or private. Therefore, it would be very useful to be able to have EF use the property setter even though it is private. This would not be a breaking change.

**Comment by ajcvickers** [comment]
@sjb-sjb EF Core has always been able to map private (protected, internal, etc.) properties. I'm curious what the text is in that link that made you think otherwise.

**Comment by ajcvickers** [comment]
@sjb-sjb EF maps to, writes to, and reads from private getters and setters, as well as fields, depending on our the property is configured.

**Comment by sjb-sjb** [comment]
Ah ha! Great!

**Comment by sjb-sjb** [comment]
@ajcvickers responding to your question "I'm curious what the text is in that link that made you think otherwise", I was taken in by the sentence that says "If the property is read-only, then it will write to the field." 

I read this a bit too quickly perhaps and I thought that 'read-only' referred to the perspective from outside the class, i.e. public getter, private setter would mean read-only. I suppose it meant no setter at all.

**Comment by ajcvickers** [comment]
@sjb-sjb Thanks for the feedback.

**Comment by ajcvickers** [comment]
Re-opening to ensure breaking change is announced.

**Comment by vanillajonathan** [comment]
With this you will be able to expose a navigational property as a `IReadOnlyCollection`.

Example:
```cs
public class Blog
{
    private List<Post> _posts = new List<Post>();

    public int BlogId { get; set; }
    public string Url { get; set; }

    public IReadOnlyCollection<Post> Posts => _posts.AsReadOnly();
}
```

**Comment by ajcvickers** [comment]
@vanillajonathan That is already possible. This change means that it should work without additional configuration to tell EF to map to the field.

**Comment by sjb-sjb** [comment]
The original post was intended to be about scalar values, but... If the navigation collection is readonly then how is EF supposed to update the navigation and fix up relationships during materializion?

**Comment by ajcvickers** [comment]
@sjb-sjb But it's not read-only...

**Comment by bigworld12** [comment]
how does this stack with https://github.com/aspnet/EntityFrameworkCore/issues/2968 ? if you force all read/writes to fields, how are you going to implement custom getters/setters for properties ?

**Comment by sjb-sjb** [comment]
@bigworld12, for my purposes the point is that EF will use direct field access during materialization while my application code will use the setters/getters. I want different things to happen in the two cases.
