### ISSUE TITLE
Update IX Async dependency to 3.2

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#12528]
Main features IX Async carries are:
- Adds a .NET Standard 2.0 target (good for https://github.com/aspnet/EntityFrameworkCore/issues/10968)
- It is a signed package

**Comment by onovotny** [comment]
Ix Async 3.2 was just pushed to NuGet today.

**Comment by Eilon** [comment]
Ix-Async 3.2.0 OSS approval is complete.
