### ISSUE TITLE
Left Join and Group by is client evaluated

### ISSUE THREAD

**Issue by sirJimmy1** [aspnet/EntityFrameworkCore#12522]
Hi, I am working with version EF core 2.1.1 and it seems to me that left join with group by not working.

Please see simple example: 
```C#
var query = from table1 in _dbContext.Table1
join table2 in _dbContext.Table2 on table1.Table2_Id equals table2.Id
//join published in _dbContext.Table3Publish on table1.Id equals published.Table1Id into publishedGroup  
//  from pub in publishedGroup.DefaultIfEmpty()
                           
group table1 by new { table1.Column1, table1.Column2} into grp
select new { grp.Key.Column1, grp.Key.Column2 };
```

With commented left join part it is translated correctly, 
unfortunately with left join it is translated as:
```sql
SELECT [All collumns from all joined tables]
FROM [table1] AS [table1_0]
INNER JOIN [table2] AS [table2_0] ON [table1_0].[Table2_Id] = [table2].[Id]
LEFT JOIN [Table3Publish] AS [published0] ON [table1_0].[Id] = [published0].[table1_Id]
ORDER BY [table1_0].[Id]
```

and it's grouped by in memory.

I found this issue has been resolved in https://github.com/aspnet/EntityFrameworkCore/issues/11755
but with EF core 2.1.1 it's not working again.

**Further technical details**
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.3

**Comment by cccvvv2012** [comment]
You may try two possible solutions 

1
force select at first 
var query = from table1 in _dbContext.Table1
join table2 in _dbContext.Table2 on table1.Table2_Id equals table2.Id
join published in _dbContext.Table3Publish on table1.Id equals published.Table1Id into publishedGroup  
 from pub in publishedGroup.DefaultIfEmpty()
 select table1 into stable1                          
group stable1 by new { stable1.Column1, stable1.Column2} into grp
select new { grp.Key.Column1, grp.Key.Column2 };

2
use group by later
var query = from table1 in _dbContext.Table1
join table2 in _dbContext.Table2 on table1.Table2_Id equals table2.Id
join published in _dbContext.Table3Publish on table1.Id equals published.Table1Id into publishedGroup  
 from pub in publishedGroup.DefaultIfEmpty()
 select table1;
query.GroupBy(t=> new { t.Column1, t.Column2}).Select(grp => new { grp.Key.Column1, grp.Key.Column2 });
