### ISSUE TITLE
Change nuget packages projectUrl to point to doco or better landing page

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#12537]
Moved from https://github.com/aspnet/EntityFramework.Docs/issues/803 filed by @SimonCropp since NuGet packages and their metadata are generated as part of the build.

Often searches will resolve to a nuget package. or people will know the nuget they are using and want to find the doco for it. 

However most MS nuget 

At the moment nugets point to generic getting stated pages. For example 
 
 * [Microsoft.Extensions.Logging.Console](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Console/)
 * [Microsoft.EntityFrameworkCore.SqlServer](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/)
* [Microsoft.AspNetCore](https://www.nuget.org/packages/Microsoft.AspNetCore)

All point to https://www.asp.net/

This experience looses all context of the users navigation history, and is unlikely to be the desired page for most people. I would expect the better locations would be

 * https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#built-in-logging-providers
 * https://docs.microsoft.com/en-us/ef/core/providers/sql-server/
 * https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1  (note the view goes to the correct version)

I realise that the history of nuget versions is static, but doco is a changing structure. but you could manage the redirects dynamically with all nuget pointing to a redirector `https://docs.microsoft.com/nugets?Microsoft.EntityFrameworkCore.SqlServer&version=1.2.3`

another option would be ad to nuget the ability to store more urls. eg "project hosting url", "docs url" etc

**Comment by ajcvickers** [comment]
Assigning to @bricelam for the build part, and @divega to update existing packages on NuGet.

**Comment by SimonCropp** [comment]
@ajcvickers  sorry for the cheese moving. but i actually think this should be in https://github.com/MicrosoftDocs/feedback. since it is not specific to only EF. thoughts??

**Comment by ajcvickers** [comment]
@SimonCropp We can change what we do for EF packages. For other packages, you'll need to file an issue in an appropriate place where the owners of those packages will see it. I suspect in all cases the issues should be in "code" repos not docs repos because the packages are generated by the build. The same thing applies to API docs. For other packages in ASP.NET, https://github.com/aspnet/Home would be the right place.

**Comment by divega** [comment]
> @divega to update existing packages on NuGet.

I tried to do this. I was wrong. 

> Editing package metadata is not supported.
To make edits to the package metadata, we recommend uploading a new version of the package created using the updated nuspec. Read more

**Comment by bricelam** [comment]
@divega What URL should we use?

**Comment by divega** [comment]
For starers, I would point almost all our packages to https://docs.microsoft.com/ef/core/. But providers can point to their specific pages, e.g. https://docs.microsoft.com/ef/core/providers/sql-server/.

We should also make sure we have pointers to GitHub visible in the documentation (the SQL Server provider already has it).

Normally I would use a fwlink, but it just happens that NuGet gallery shows the actual URL in the UI, so perhaps aka.ms links with something meaningful would be better.

Sounds good?
