### ISSUE TITLE
Using HasData with new lines breaks the migrations

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/EntityFrameworkCore#12542]
Describe what is not working as expected.
I create a HasData that has a new line in it, and the corresponding HasData doesn't deal with new lines, Need to add @"" to make it work.

### Steps to reproduce
1. Add HasData with a new line:

```c#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      base.OnModelCreating(modelBuilder);

      modelBuilder.Entity<Product>()
        .HasData(new Product()
        {
          Id = 1,
          Title = "Temp",
          ArtDescription = @"In Rembrandt’s time, peacocks were a delicacy for the well-to-do: the meat was used as filling for pasties. After being slaughtered, the birds were hung upside down to drain their blood, as Rembrandt has depicted
                in this pantry. He must have been fascinated by the plumage’s magnificent markings and dazzling colours:
                blue, green and yellow ochre."
        });
    }
```

2. Do "dotnet ef migrations add Seeding"
3. Compile project and fails because of new lines in generated code.

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10 Pro
IDE: (e.g. Visual Studio 2017 15.7)

**Comment by jzabroski** [comment]
@shawnwildermuth  What generated code does the  "dotnet ef migrations add Seeding" command generate? I was a bit confused... are you saying that doing @"" solves the problem?
As a workaround, I recommend using FluentMigrator.

@ajcvickers  I feel you should push customers harder on submitting complete repros. How much time does Microsoft waste even building test repros for this stuff?

**Comment by ajcvickers** [comment]
@AndriySvyryd I was not able to find the dupe for this.

**Comment by AndriySvyryd** [comment]
Then it's not a dupe

**Comment by shawnwildermuth** [comment]
Sorry I missed this. The Github notifications app is down on my phone. I can give you a repro if you like.

**Comment by jzabroski** [comment]
If you do, I'll take a stab at fixing it.

**Comment by shawnwildermuth** [comment]
Ok, the real problem with is newline only (not /r/n but just /n as in my case with a Json file from a non-windows line ending). Here is a repro case: 

https://github.com/shawnwildermuth/NewLineHasDataMigrationIssue

**Comment by bricelam** [comment]
@jzabroski Update [this line](https://github.com/aspnet/EntityFrameworkCore/blob/2.1.1/src/EFCore.Design/Design/Internal/CSharpHelper.cs#L313). 😉

**Comment by usamakhalil86** [comment]
Is it fixed ?

**Comment by AndriySvyryd** [comment]
@usamakhalil86 Yes, in 2.2.0 If you are still experiencing it open a new issue with a small repro project
