### ISSUE TITLE
Releases Page - Version 2.0.1 latest?

### ISSUE THREAD

**Issue by Rand-Random** [aspnet/EntityFrameworkCore#12550]
Any reason the releases page:
https://github.com/aspnet/EntityFrameworkCore/releases

Highlights 2.0.1 as latest release?

**Comment by ajcvickers** [comment]
@Rand-Random Because we missed updating it.

**Comment by Rand-Random** [comment]
@ajcvickers Thx for the info, thought maybe it was intended and its the recommended version or something.

**Comment by divega** [comment]
@danroth27 @Eilon I noticed release notes are not updated in other repos either. For example https://github.com/aspnet/Mvc/releases is also 2.1.0-preview2 and 2.0.1 as latest stable release?

Do we have any intention to keep these up to date moving forward? If now, perhaps we should remove them to avoid confusion.

**Comment by Eilon** [comment]
I don't think we plan on updating them in each repo because it doesn't seem to provide any value. We blog/tweet releases and have proper landing sites with more meaningful release notes.

**Comment by Rand-Random** [comment]
@divega 
Not that it matters much, but you mentioned that the MVC states that 2.0.1 is the latest this seems to be incorrect as this URL
https://github.com/aspnet/Mvc/releases/latest

Redirects to version 1.1.5.

**Comment by Misiu** [comment]
@Eilon I've found this issue bu browsing issues in 2.2.0.
Releases pages should be fixed. If You look at https://github.com/aspnet/SignalR/releases latest highlighted one is pre-release from 10 Oct 2017.

**Comment by Rand-Random** [comment]
Out of curiosity, so decision was made to maintain the release page? Does this include all Microsoft Projects on GitHub?

**Comment by ajcvickers** [comment]
@Rand-Random I can only speak to the EF repo, where we decided to add releases but with very little overhead.
