### ISSUE TITLE
Query: error when projecting is a nullable struct in a conditional expression

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#12566]
Reported here: https://github.com/aspnet/EntityFrameworkCore/issues/11687 by @mrhmouse 

query:

```cs
quux.Select(q => new Foo
{
    Bar = q.X.HasValue && q.Y.HasValue
        ? new Bar { X = q.X.Value, Y = q.Y.Value }
        : (Bar?)null,
})
```

**Comment by mrhmouse** [comment]
@maumar 
> @mrhmouse are you using EFCore version 2.1?

I can reproduce this on 2.0.2 and 2.1.1

**Comment by ajcvickers** [comment]
@mrhmouse It would be helpful if you could also provide the entity types that are used here.

**Comment by mrhmouse** [comment]
I'll submit a small project that reproduces the bug

**Comment by maumar** [comment]
this is fixed in the current bits
