### ISSUE TITLE
Scaffold-DbContext skips columns of type 'sysname' in version 2.1

### ISSUE THREAD

**Issue by oxxa** [aspnet/EntityFrameworkCore#12595]
I have upgraded my solution from EF Core 2.0 to 2.1 and noticed a change in behavior of Scaffold-DbContext.  Now when I run it skips any columns in my tables which have type `sysname`.  ie I get lots of:

```
Could not find type mapping for column 'dbo.Table.FooColumn' with data type 'sysname'. Skipping column.
```

Is there a workaround for this?  In version 2.0 it happily mapped these columns to string type.

### Steps to reproduce
To reproduce just try and scaffold any table with columns having type=sysname.  This is the command I use in VS pmc.

```powershell
Scaffold-DbContext -Connection "Server=localhost;Database=testdb;Trusted_Connection=True;" -Provider Microsoft.EntityFrameworkCore.SqlServer -OutputDir TestContext -Context "TestDbContext" -Force -Project TestProj
```

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
.Net SDK: 2.1.300
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.7.4

**Comment by bricelam** [comment]
After scaffolding, you should just be able to add a `string` property with the same name as the column to the corresponding class and have it work.

**Comment by oxxa** [comment]
Yes I can fix it up afterward, just thought it was strange that it had changed from how it automatically mapped it before.  It can also be more of a pain in that if a table has a PK involving a sysname column then that entity won't be generated at all now. Anyway, we have decided it will be easier all round if we just convert our sysname columns to be nvarchar(128) in the DB.  So it won't affect us going forwards but I think if it is not a conscious design choice that it might be nice if the pre-2.1 behavior returned.
