### ISSUE TITLE
Revisit multiple principals issue

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#12592]
Issue #12227 is planned to be patched with #12571. However, some things still need doing post-patch:
* GetPrincipal should be fixed, and a new method should be added to get all possible principals
* Decide if/how required/optional relationships should be handled differently
* Consider allowing non-nullable optional foreign keys in this case

**Comment by AndriySvyryd** [comment]
Non-nullable optional foreign keys might need https://github.com/aspnet/EntityFrameworkCore/issues/13146

**Comment by ajcvickers** [comment]
Marking for re-triage. Proposal: we stop throwing here ever if the principal found does not match the expected type. The reasoning is that just because non of the loaded principals match does not mean that none of the principals in the database match.

For the common case, a database FK constraint violation will be thrown anyway when SaveChanges is called. 

So the code change we would make here is to always filter out principals that match by key value but for which the type does not match.

**Comment by ajcvickers** [comment]
Triage: we will merge this as is, but pinging @divega to take a look.
