### ISSUE TITLE
Ignored includes - makes strange warnings

### ISSUE THREAD

**Issue by zd-dalibor** [aspnet/EntityFrameworkCore#12662]
Documentation for ef core [Ignored includes](https://docs.microsoft.com/en-us/ef/core/querying/related-data#ignored-includes) says if you include related entity but query does not return entity that the query began with include will be ignored and you will get the warning.

I have following entity:
```c#
public class Product : BaseEntity
{
    public Guid Id { get; set; }

    [Required]
    [MaxLength(255)]
    public string Name { get; set; }

    [MaxLength(255)]
    public string Description { get; set; }

    [Required]
    public Guid RestaurantId { get; set; }
    public Restaurant Restaurant { get; set; }

    public decimal Price { get; set; }

    [Required]
    public Guid CategoryId { get; set; }
    public Category Category { get; set; }


    public bool IsActive { get; set; }

    public IList<OrderItem> OrderItems { get; set; }
}
```

than I have this query
```c#
var q = from product in Database.Products
    where product.Id == id
    select product;

q
    .Include(x => x.Category)
    .Include(x => x.Restaurant)
    .FirstOrDefault();
```

And I got this warnings:
```
warn: Microsoft.EntityFrameworkCore.Query[10106]
InstaOrder.Web>       The Include operation for navigation '[product].Category' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information.
InstaOrder.Web> warn: Microsoft.EntityFrameworkCore.Query[10106]
InstaOrder.Web>       The Include operation for navigation '[product].Restaurant' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information.
```

Why I got these warnings when result is entity that query began with????

EF Core version: SDK 2.1301, Runtime 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.1.1
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.5

**Comment by dalibor983** [comment]
Why need someone to wary about what someone wants to include in final result of query?
I used ```.Include(...)``` and I want to have SQL generated with ```INNER JOIN``` statement and got the result with included entity.

Why need ef core to ignore my include statement?

This was not the case with net core 2.0.

**Comment by Tbd19** [comment]
I have a similar case doing something like this:
await Entities.AnyAsync(il => il.Name.DE == model.Designation_DE && il.ID != model.Id).ConfigureAwait(false) 
generates this :
|WARN|Microsoft.EntityFrameworkCore.Query|The Include operation for navigation '[il].Name' is unnecessary and was ignored because the navigation is not reachable in the final query results.

As you can see from the code I do not include anything. Shouldn't the EF know that it has done the inclusion by itself and not warn me about it?

**Comment by smitpatel** [comment]
@Tbd19 - You are using `AnyAsync` essentially returning bool value and no entity so include is ignored.

@dalibor983 - Do you receive the results as you expect (with related data loaded)? Is it just ignored include warnings are incorrect or the include is being ignored incorrectly? If it is later can you provide a full repro solution which demonstrate that issue?

**Comment by Tbd19** [comment]
@smitpatel Where exactly do you see an explicit Include in the code that I posted? Should I understand that AnyAsync will generate WARNs in the log? Is there a way to avoid this?

**Comment by dalibor983** [comment]
@smitpatel - Everything is working like it should. Related data is loaded. Only problem is warnings.

**Comment by smitpatel** [comment]
@Tbd19 - You code is incomplete. There is no reference to what is `Entities`. Hence presumably, there is include somewhere. If you have _not_ written any include and _not_ using owned entities and if you see a warning then please file a new bug with full repro code. This issue is specifically about when `Include` is specified and also loads related data but still generates the warning.

**Comment by smitpatel** [comment]
@divega @ajcvickers - Moved this to 3.0 milestone since we are generating correct results, just bug in logging.

**Comment by Tbd19** [comment]
@smitpatel 
The Entities = context.Set<TEntity>(). Should I still open a ticket or it is the same problem?

**Comment by smitpatel** [comment]
@Tbd19 - Please file a new issue with full repro code of the issue you are seeing.

**Comment by mhosman** [comment]
I also get the same incorrect warnings all the time in my includes (the code works okay and the includes are made okay). Using 3.0 preview 4.

**Comment by pantonis** [comment]
Is this a bug only That happens during debugging?

**Comment by smitpatel** [comment]
Since we removed warning for this in new pipeline, tracking in #17498 which is about adding the logging. We will consider not to add erroneous warning while fixing that issue.
