### ISSUE TITLE
Make IQueryOptimizer/QueryOptimizer non-internal

### ISSUE THREAD

**Issue by austindrenski** [aspnet/EntityFrameworkCore#12756]
In the provider for PostgreSQL, we are exploring some complex translations via `IQueryOptimizer`/`QueryOptimizer` which provide an extensibility point for injecting expression visitors.

However, [we are wary](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/444#issuecomment-397958488) of replacing services from the EF Core `Internal` namespaces.

Would it be possible to move `IQueryOptimizer` and `QueryOptimizer` out of the internal namespace?

```
current:  Microsoft.EntityFrameworkCore.Query.Internal
proposed: Microsoft.EntityFrameworkCore.Query
```

Related: 
- https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/431
- https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/444

/cc @roji

**Comment by ajcvickers** [comment]
We are going to consider this as part of the general 3.0 query work, so adding a link to #12795.

**Comment by austindrenski** [comment]
@ajcvickers Thanks for the update—much appreciated!

**Comment by smitpatel** [comment]
The optimizations from IQueryOptimizer has been moved to QueryOptimizer which is public.
