### ISSUE TITLE
Replacing Owned object doesn't trigger RowVersion's concurrency checking

### ISSUE THREAD

**Issue by IvanZheng** [aspnet/EntityFrameworkCore#12758]
I have an entity which has an Owned Object and a Timestamp RowVersion property.
When replacing entity's owned object, the new owned object's state is Added and the entity's state is Unchanged. In this situation, the RowVersion's concurrency checking doesn't work. The SQL generated by efcore is lack of the part of RowVersion checking which should look like 'UPDATE [xxx] SET [yyy] = @p0 WHERE [Id] = @p1 AND [Version] = @p2;SELECT [Version] FROM [xxx]' . (It works well in EF6.)
If I explicitly made the entity's state be Modified by 'dbContext.Entry(entity).State = EntityState.Modified', the RowVersion checking was triggered , but it resulted in that the update SQL was with all the entity's fields to be updated.
Now I have to explicitly update one property (LastModifedTime) in the entity to make the RowVersion checking triggered. 
Could you please give me some other advises? Or will it be improved in the next release?  

I am following DDD in ASPNETCORE2.1, I expect when the Owned Object even the nested Owned Object in Owned Object is replaced, the owner entity's RowVersion concurrency checking still works since they are all in one Table sharing the same RowVersion.

EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.1.1
Operating system:  Visual Studio 2017 15.7.5

**Comment by ajcvickers** [comment]
Triage: we should consider this as part of the aggregate behaviors item in 3.0: #1985
