### ISSUE TITLE
In-Memory provider incorrectly clears foreign key when setting it to a new

### ISSUE THREAD

**Issue by xt0rted** [aspnet/EntityFrameworkCore#12810]
The in-memory provider is, what I believe to be, incorrectly clearing foreign keys when you both update it to a new value and delete the old entity in the same transaction.

### Steps to reproduce

Given the following data:

```
Profile
  Id: 1
  PrimaryPhotoId: 2

Photo
  Id: 1
Photo
  Id: 2
Photo
  Id: 3
```

If you then update the Profile & remove the old Photo in the same transaction like so:

```c#
profile.PrimaryPhotoId = 3;

db.Photos.Remove(photo);

await db.SaveChangesAsync();
```

You're left with `profile.PrimaryPhotoId` being `null` instead of the expected `3`.

Full repro is at https://github.com/xt0rted/ClassLibrary4

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Win10
IDE: Visual Studio 2017 15.7.5

**Comment by ajcvickers** [comment]
Note for triage: I was able to reproduce this also with the SqlServer provider; it looks like an issue with fixup.

@xt0rted A workaround is to force EF to detect changes after setting PrimaryPhotoId to 3:

```C#
// update primary photo & delete the current one
profile.PrimaryPhotoId = 3;

context.ChangeTracker.DetectChanges();

context.Photos.Remove(photo);

context.SaveChanges();
```

**Comment by xt0rted** [comment]
After further investigation this also happens with the Sqlite and SqlSever providers.

I found two workarounds for this, though I'm not sure what the correct default behavior should be here.

1. Remove the following property from the `Photo` class

```c#
public ICollection<Profile> Profiles { get; set; } = new HashSet<Profile>();
```

2. Add `.OnDelete(DeleteBehavior.Restrict)` to the foreign key

**Comment by xt0rted** [comment]
@ajcvickers adding `context.ChangeTracker.DetectChanges();` works too. Of the 3 workarounds which one is the most correct way to handle this?

In my EF6 context I had:
```c#
modelBuilder.Conventions.Remove<OneToManyCascadeDeleteConvention>();
modelBuilder.Conventions.Remove<ManyToManyCascadeDeleteConvention>();
```

That seems to match the `.OnDelete(DeleteBehavio.Restrict)` setting I tried. Is there a way to set that globally  or do I need to add it to each of my foreign keys?
