### ISSUE TITLE
Remove obsolete APIs for 3.0

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#12835]
There are several obsolete APIs that have been accumulated over the versions, and still exist in order to maintain backwards compatibility. I'm hoping it's planned to remove these for version 3.0, to keep the codebase clean and lean.

This could be a matter of going over everything tagged with `[Obsolete]`, but it may be worth listing and tracking in an issue.

* [ ] Old type mapping API (`ITypeMapper` and derived, `FallbackTypeMappingSource`).
* [x] Overload of `MigrationsSqlGenerator.ColumnDefinition` that doesn't accept `FixedLength`
* [ ] `DefaultQuerySqlGenerator.GenerateBinaryOperator(ExpressionType)`

(there are obviously many more).

Some of these could be a bit tricky, as they'd require potentially considerable effort to port to the newer APIs (I'm thinking about the old type mapping for example). It may make sense to carefully evaluate, API by API, whether it's worth it to remove or not.

**Comment by ajcvickers** [comment]
@roji We are planning to remove anything that is marked as Obsolete in 3.0. There should already be a way to replace any of these calls with other, non-obsolete code that achieves the same objective. For example, code that is using the old type mapping API should move to using the new API.

We already did this for 2.0, so there should not be any obsolete APIs that remain from pre-2.0 days, unless we missed some. Also, we tend to create issues [like some of these](https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0.0+label%3Atype-cleanup) for specific cases where we need to do cleanup and just searching for Obsolete is not sufficient to find the case.

Keeping this open as a work item to track doing this work.

**Comment by roji** [comment]
Great!

**Comment by bricelam** [comment]
When we remove `FallbackTypeMappingSource`, we should consider updating `CoreTypeMappingSource` to map value types, `string`, and `byte[]`.

**Comment by bricelam** [comment]
In addition to obsolete methods, we should collapse overloads that were added to prevent breaks around parameter defaults. (They couldn't be marked obsolete)
