### ISSUE TITLE
{SQLCE] Specification tests fail due to SQLCE limitations 

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#12904]
SQLCE fails to do inserts to a table with only an ID column, causing tests to fail.

Solution is to add Filler property to:
HasContextProperty
and HasContextPc
and for QueryFilterFuncletizationSqlCeTest:
PrincipalSetFilter

### Further technical details
EF Core version: 2.1
Database Provider: SQL CE
Operating system: 
IDE: VS 15.7

**Comment by smitpatel** [comment]
@ErikEJ - Can you do a PR? 😄
