### ISSUE TITLE
Is the order of migrations reliable?

### ISSUE THREAD

**Issue by beppemarazzi** [aspnet/EntityFrameworkCore#12966]
AFAIK the order on wich migrations are executed is important and it's derived from lexicographical order of migration id. Since each migration id has a fixed length prefix with the timestamp, then the migrations are supposed to execute in that order.

But digging into the code, i've the suspect that there is no real guaranty about this order: in fact it appears to me that the migrations order relies on the order of insertion in a Dictionary.

https://github.com/aspnet/EntityFrameworkCore/blob/4f65388bf68312e16fe07e62f79d8fad4e242f2a/src/EFCore.Relational/Migrations/Internal/MigrationsAssembly.cs#L49-L73

but [FCL documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=netframework-4.7.2) states:

> For purposes of enumeration, each item in the dictionary is treated as a KeyValuePair<TKey,TValue> structure representing a value and its key. The order in which the items are returned is undefined.

Isn't better to replace 
`var result = new Dictionary<string, TypeInfo>(); `
with
`var result = new SortedList<string, TypeInfo>(); `

IMHO the same issue arises where `MigrationsAssembly.Migrations` is used:

https://github.com/aspnet/EntityFrameworkCore/blob/4f65388bf68312e16fe07e62f79d8fad4e242f2a/src/EFCore.Relational/Migrations/Internal/Migrator.cs#L180-L234

here you can add an explicit `.OrderBy(m => m.Key)` also when calculating `migrationsToApply`

Thanks

**Comment by hmdhasani** [comment]
Another thing is system culture settings, If someone in a team use a calendar other than Georgian, migration orders get mixed. I have created an issue about it (https://github.com/aspnet/EntityFrameworkCore/issues/12978)

**Comment by ajcvickers** [comment]
Triage; putting this into 2.2 since we should be more robust here.
