### ISSUE TITLE
Disallow tracking queries for owned entities without their owners

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#13036]
Querying `Customer.Address` should also bring in the `Customer` for tracking queries as there's no reason to track an owned entity without its owner.

**Comment by ajcvickers** [comment]
Another option discussed in triage is to make queries for non roots of the aggregate always be no-tracking.

Referencing from #1985 to consider as part of the overall aggregate behaviors.

**Comment by AndriySvyryd** [comment]
We will throw for now, until the Include pipeline supports including the owner without a navigation.

**Comment by ajcvickers** [comment]
Decisions:
* Owned entities cannot be tracked without their owner.
* Querying for owned entities without their owners must be no-tracking.
* Throw if the query would have been tracking; don't silently become no-tracking.

**Comment by smitpatel** [comment]
@AndriySvyryd - What is the status of this one. #13579 said to apply decision for here but that issue is closed now. Does that mean this one has been fixed?

**Comment by AndriySvyryd** [comment]
#13579 was about tracking both the owner and the owned, that works now.
We still need to throw if owner is not included.

**Comment by smitpatel** [comment]
Poaching! 😉

**Comment by smitpatel** [comment]
@ajcvickers - Do we need to announce this as breaking change somewhere?

**Comment by ajcvickers** [comment]
@smitpatel We should, but it's a low-impact. I can do it.

**Comment by ajcvickers** [comment]
@smitpatel @AndriySvyryd I started writing it, but it's actually more of a bug that we ever tried to do this--an I couldn't even make it work in simple cases on 2.2, so I think it's fine to treat this as a bug we fixed.
