### ISSUE TITLE
Mismatch between properties mapping to same column in database for owned entities could cause incorrect column configuration

### ISSUE THREAD

**Issue by CodeThumper** [aspnet/EntityFrameworkCore#13069]
When adding a migration part of the configuration seems to be skipped.
```c#
builder.Property(x => x.ProviderKey).HasMaxLength(50).IsUnicode(false); 
```
DOES NOT EQUAL 
```c#
ProviderKey = table.Column<string>(nullable: false)
```
Relevant Code:
```c#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new CustomerConfig());
    }
```

```c#
public class CustomerConfig : IEntityTypeConfiguration<Domain.Customer>
{
    public void Configure(EntityTypeBuilder<Domain.Customer> builder)
    {
        builder.ToTable(nameof(Domain.Customer));
        builder.OwnsOne(
            o => o.Created,
            sa =>
            {
                sa.Property(p => p.Reason).HasMaxLength(255).IsUnicode(false);
            }
        );
builder.Property(x => x.TenantId).IsRequired();
        builder.Property(x => x.RowVersion).IsRowVersion();
builder.HasKey(x => new { x.TenantId, x.ProviderId, x.ProviderKey });
        builder.Property(x => x.ProviderKey).HasMaxLength(50).IsUnicode(false);
builder.Property(x => x.DisplayName).HasMaxLength(255).IsUnicode(false);
    }
}
```

Is generating:
```c#
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Customer",
            columns: table => new
            {
                TenantId = table.Column<Guid>(nullable: false),
                RowVersion = table.Column<byte[]>(rowVersion: true, nullable: true),
                Created_SessionId = table.Column<Guid>(nullable: true),
                Created_At = table.Column<DateTimeOffset>(nullable: true),
                Created_Reason = table.Column<string>(unicode: false, maxLength: 255, nullable: true),
                ProviderId = table.Column<Guid>(nullable: false),
                ProviderKey = table.Column<string>(nullable: false),
                DisplayName = table.Column<string>(unicode: false, maxLength: 255, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Customer", x => new { x.TenantId, x.ProviderId, x.ProviderKey });
            });
    }
```
The Domain.Customer.ProviderKey configuration does not seem to be applied in the migration.
Full project can be found https://github.com/CodeThumper/EFCoreMigrationSample

### Steps to reproduce
Full project can be found https://github.com/CodeThumper/EFCoreMigrationSample

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro Version 1803 build 17134.228
IDE:  Visual Studio 2017 15.7.4

**Comment by ajcvickers** [comment]
Note for triage: reproduces and seems to be related to table splitting--if the owned type is mapped to a separate table, then the issue goes away.

**Comment by smitpatel** [comment]
Issue: The column has facets specified in owner type but not in owned type (where there is shadow PK property mapping to same column). If `Created` is declared before `ProviderKey` in class then column ordering in migration will use the property from owned type to generate column operation. The owner column gets ignored since it has same name/table. Hence we lost configuration.

Work-around: Configure facets for shadow pk property created inside Owned entity too.

Tasks:
- Add validation to verify that max length, unicode, precision, scale are same for properties mapping to same column.
- Propagate facets from owned column to owned column for shadow property created for PK by EF Core.

**Comment by smitpatel** [comment]
@AndriySvyryd - Facets to validate
- `IsUnicode`
- `GetMaxLength`
- `Relational().IsFixedLength`

Anything else? I couldn't find precision/scale
