### ISSUE TITLE
Migration file with small values data seed doesn't build

### ISSUE THREAD

**Issue by artemvalmus** [aspnet/EntityFrameworkCore#13089]
Generated migration file, containing data seed with small values and values in exponential form, doesn't build.

```c#
public class InfluenceLine
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class InfluenceLineValue
{
    public int Id { get; set; }
    public int InfluenceLineId { get; set; }
    public double Value { get; set; }

    public virtual InfluenceLine InfluenceLine { get; set; }
}

public class EFCoreDemoContext : DbContext
{
    public static readonly LoggerFactory MyLoggerFactory
        = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    public DbSet<InfluenceLine> InfluenceLines { get; set; }
    public DbSet<InfluenceLineValue> InfluenceLineValues { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseLoggerFactory(MyLoggerFactory).UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=Test;Trusted_Connection=True");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<InfluenceLine>().HasData(new InfluenceLine {
            Id = 1,
            Name = "InfluenceLine1"
        });

        modelBuilder.Entity<InfluenceLineValue>().HasData(
        new InfluenceLineValue {
            Id = 1,
            InfluenceLineId = 1,
            Value = 6E-14
        }, 
        new InfluenceLineValue
        {
            Id = 2,
            InfluenceLineId = 1,
            Value = 0.00000000000006
        });
    }
}
```

### Further technical details
PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.2"
PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.2"
PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.2"

IDE: 
Microsoft Visual Studio Enterprise 2017 
Version 15.7.6

**Comment by bricelam** [comment]
Code contains: `6E-14.0`

We shouldn't append `.0` when `E` is present (or insert it before the `E` like we do in SQL)

**Comment by bricelam** [comment]
Make [this code](https://github.com/aspnet/EntityFrameworkCore/blob/801b3c02b9cde8808ee795e72642bfaa2d314c00/src/EFCore.Design/Design/Internal/CSharpHelper.cs#L381) look like [this code](https://github.com/aspnet/EntityFrameworkCore/blob/801b3c02b9cde8808ee795e72642bfaa2d314c00/src/EFCore.Relational/Storage/DoubleTypeMapping.cs#L62-L67).

**Comment by AnOxfordDev** [comment]
@bricelam - I'm new here, but this seems like a nice way to get started. Do you mind if I take this task?

**Comment by smitpatel** [comment]
@AnOxfordDev - There is already PR out from @Matthiee to fix this issue. We have to discuss in team how to deal with exact formatting issues as discussed on the PR.
