### ISSUE TITLE
The types of the properties specified for the foreign key do not match the types of the properties in the principal key

### ISSUE THREAD

**Issue by cello99d** [aspnet/EntityFrameworkCore#13108]
This model builds fine in EF Core 2.1.2
If I change the type of C.Id to int?, then the model compiles.

Exception message: 
System.InvalidOperationException: 'The types of the properties specified for the foreign key {'CRefKey'} on entity type 'B' do not match the types of the properties in the principal key {'Id'} on entity type 'C'.'

Stack trace:
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.AreCompatible(IReadOnlyList`1 principalProperties, IReadOnlyList`1 dependentProperties, EntityType principalEntityType, EntityType dependentEntityType, Boolean shouldThrow)
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey.AreCompatible(EntityType principalEntityType, EntityType dependentEntityType, MemberInfo navigationToPrincipal, MemberInfo navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 unique, Nullable`1 required, Boolean shouldThrow)
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddForeignKey(IReadOnlyList`1 properties, Key principalKey, EntityType principalEntityType, Nullable`1 configurationSource)
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.CreateForeignKey(InternalEntityTypeBuilder principalEntityTypeBuilder, IReadOnlyList`1 dependentProperties, Key principalKey, String navigationToPrincipalName, Nullable`1 isRequired, ConfigurationSource configurationSource)
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.GetOrCreateRelationshipBuilder(EntityType principalEntityType, EntityType dependentEntityType, Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Boolean isRequired, Boolean removeCurrent, Nullable`1 principalEndConfigurationSource, Nullable`1 configurationSource, Nullable`1& existingRelationshipInverted)
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 isOwnership, Nullable`1 deleteBehavior, Boolean removeCurrent, Boolean oldRelationshipInverted, Nullable`1 principalEndConfigurationSource, Nullable`1 configurationSource)
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(Nullable`1 configurationSource, InternalEntityTypeBuilder principalEntityTypeBuilder, InternalEntityTypeBuilder dependentEntityTypeBuilder, Nullable`1 navigationToPrincipal, Nullable`1 navigationToDependent, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties, Nullable`1 isUnique, Nullable`1 isRequired, Nullable`1 isOwnership, Nullable`1 deleteBehavior, Boolean removeCurrent, Nullable`1 principalEndConfigurationSource, Boolean oldRelationshipInverted)
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.HasForeignKey(IReadOnlyList`1 properties, EntityType dependentEntityType, Nullable`1 configurationSource)
   bei Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.HasForeignKey(IReadOnlyList`1 propertyNames, EntityType dependentEntityType, ConfigurationSource configurationSource)
   bei Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceCollectionBuilder.HasForeignKeyBuilder(IReadOnlyList`1 foreignKeyPropertyNames)
   bei Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceCollectionBuilder`2.HasForeignKey(String[] foreignKeyPropertyNames)
   bei ConsoleApp1.TestContext.OnModelCreating(ModelBuilder modelBuilder) in D:\PI\Produkte\PIDotNetRoot\ConsoleApp1\ConsoleApp1\Program.cs:Zeile 29.
   bei Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   bei Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   bei Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   bei System.Lazy`1.CreateValue()

### Steps to reproduce
```c#
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1 {

	public class B {
		public int KeyB { get; set; }
		public string Id { get; set; }

		private int CRefKey { get; set; }
		public C CRef { get; set; }
	}

	public class C {
		public int KeyC { get; set; }
		public string Id { get; set; }
		public ICollection<B> CBs { get; set; }
	}

	public class TestContext : DbContext {

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
			optionsBuilder.UseInMemoryDatabase();
			base.OnConfiguring(optionsBuilder);
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder) {
			modelBuilder.Entity<B>().HasKey(b => b.KeyB);
			modelBuilder.Entity<B>().Property("CRefKey").HasColumnName("C_KEY");
			modelBuilder.Entity<B>().Property(b => b.Id).HasColumnName("ID").HasMaxLength(12);
			modelBuilder.Entity<B>().HasOne<C>(b => b.CRef).WithMany(c => c.CBs).HasForeignKey("CRefKey");

			modelBuilder.Entity<C>().HasKey(c => c.KeyC);
			modelBuilder.Entity<C>().Property(c => c.Id).HasColumnName("ID").HasMaxLength(12);
		}
		//entities
		public DbSet<B> SetB { get; set; }
		public DbSet<C> SetC { get; set; }
	}
	class Program {
		static void Main(string[] args) {
			var ctx = new TestContext();
			var c = ctx.SetC.Count();
		}
	}
}
```

### Further technical details
EF Core version: 2.2.0 preview 1
Database Provider: InMemoryDatabase
Operating system: 
IDE: Visual Studio 2017 15.6.6

**Comment by smitpatel** [comment]
The issue here arises because in `Property` call the type is not specified. Which we infer through reflection but don't set configuration source properly hence while using it as FK, we choke.
