### ISSUE TITLE
Entity doesn't get removed from collection when setting reference to null if parent is deleted

### ISSUE THREAD

**Issue by Wain123** [aspnet/EntityFrameworkCore#13110]
If a `Blog` entity is in the state `Deleted`, and I change a `Post`'s navigation property to no longer point at the `Blog`, then the `Post` doesn't get removed from the collection.

It works fine if the parent's state is not `Deleted`, and adding also works, just removing doesn't. The relationship is optional/nullable and all property setters raise `PropertyChanging`/`PropertyChanged`. I'm using `ChangeTrackingStrategy.ChangingAndChangedNotificationsWithOriginalValues`.

```C#
var post = ctx.Posts.Single();
var blog = ctx.Blogs.Single();
ctx.Blogs.Remove(blog); // It works if I skip this line
Assert.That(blog.Posts.Count, Is.EqualTo(0));
post.Blog = blog;
Assert.That(blog.Posts.Count, Is.EqualTo(1)); // Adding works fine
post.Blog = null;
Assert.That(blog.Posts.Count, Is.EqualTo(0)); // This Assert fails, the count is still 1
```

EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.Oracle
Operating system: Windows 10
IDE: Visual Studio Professional 2017 15.6.5

**Comment by ajcvickers** [comment]
Expectations following 3.0 decisions on fix-up:
```C#
var post = ctx.Posts.Single();
var blog = ctx.Blogs.Single();
ctx.Blogs.Remove(blog);
// blog.Posts will remain unchanged, since Deleted entities still point to tracked entities
// post.Blog will be null
post.Blog = blog;
// blog.Posts will remain unchanged, since it already contains the entity (may require `DetectChanges`)
post.Blog = null;
// blog.Posts will be unchanged, since the blog entity is still Deleted
ctx.SaveChanges();
// blog.Posts will be unchanged since it is the entity that has been Deleted
```

**Comment by Wain123** [comment]
That's not `closed-fixed`, it's `closed-by-design`. After setting `post.Blog = null`, the collection will still contain the `post`. That was already the case in 2.1.

I opened this issue because I want to iterate through `blog.Posts` and apply application-specific delete behavior before saving. If the collection doesn't match the tracked FK value, the collection is useless for this purpose.

**Comment by ajcvickers** [comment]
@Wain123 It's possible that I misread the issue when we originally triaged it. The point here is that once the Blog is marked as Deleted, then nothing else is going to bring it back from Deleted. So changing the navigation properties here is very much a corner case from the EF perspective. I just made sure it didn't do anything inconsistent.

**Comment by Wain123** [comment]
In that case, how do I answer the question "which tracked `posts` have a FK that currently points to this `blog`"? The collection answers that question when the `blog` is not deleted, but what do I do if it is? Should I implement a soft-delete flag and never actually go to `EntityState.Deleted`?

Not sure if this question should be in a new issue, I can make one if you want me to.

**Comment by ajcvickers** [comment]
@Wain123 Do that before it is marked as Deleted.
