### ISSUE TITLE
LICENSE.txt not detected by Licensee

### ISSUE THREAD

**Issue by austindrenski** [aspnet/EntityFrameworkCore#13117]
The license file for this repository is not detected by GitHub for display on the repository page, in search results, etc. 

We recently noticed and were able to fix [this for Npgsql](https://github.com/npgsql/npgsql/issues/2016) by adjusting some formatting required by [Licensee](https://help.github.com/articles/licensing-a-repository/#detecting-a-license).

It looks like `LICENSE.txt` is non-standard by design, but wanted to raise this in case it was just overlooked.

### License not detected 

![image](https://user-images.githubusercontent.com/21338699/44619443-7ea10080-a854-11e8-9e34-bfff2b4b0840.png)

### License detected 

![image](https://user-images.githubusercontent.com/21338699/44619557-8a8dc200-a856-11e8-9476-15421a3cb58b.png)

**Comment by roji** [comment]
Maybe try to apply exactly what we did for the Npgsql repo?

**Comment by ajcvickers** [comment]
@Eilon Thoughts?

**Comment by Eilon** [comment]
Hmm we were told in no uncertain terms to use exactly this block of text for the license, with no changes whatsoever. I'll ask around if we can change it to something that would "detect" more easily, but maybe the thing doing the detection could also be updated?

**Comment by roji** [comment]
In case this helps, in some communication with github support I was told to do the following:

> Clone the licensee repo: https://github.com/benbalter/
> cd into the licensee folder and run bundle install
> Use the git-repo script with a repo URL: ./script/git-repo https://github.com/aspnet/EntityFrameworkCore

Apparently they require a 98% match. In my case part of the problem turned out to be line breaks :/

**Comment by Eilon** [comment]
98% match? Sounds like an episode of CSI or something!

**Comment by roji** [comment]
Forensic licensing is the new hot thing...

**Comment by pmiddleton** [comment]
Have you tried enhancing it :)

**Comment by ajcvickers** [comment]
See also https://github.com/aspnet/Home/issues/3483

**Comment by Eilon** [comment]
Closing this issue in favor of https://github.com/aspnet/Home/issues/3483, because this issue applies to almost every repo in the 'aspnet' org. (Yes, this issue is older, sorry!)

**Comment by Eilon** [comment]
OK I fixed EF Core:

![image](https://user-images.githubusercontent.com/202643/45377984-0f940d80-b5b1-11e8-9497-37c2f5070b5d.png)

Now I'll go fix the other repos. Thanx!
