### ISSUE TITLE
Query: Infer TypeMapping for Literals & Parameters correctly

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#13192]
We have been talking in #4978 and various other issues (like #9582 ) to add API to specify store type facet inside query. While all they may be fine but we still need correct inference for all case if we want value converters to work correctly (since it come from actual type mapping). There wouldn't be any easy api to specify value converter to use for literal inside query.

Filing this issue to make inference accurate for all cases in 3.0 time frame. It shouldn't be impossible to decorate whole tree correctly. In case if we find cases which cannot be solved we can look into adding APIs to specify facets.

**Comment by byrnedo** [comment]
Hi, we're having trouble with `x.CompareTo("123") > 0` where x is a varchar column, the sql generated is `x > N'123'`. This is causing big performance issue since it can't use the index. Any idea when this case would be fixed?

**Comment by smitpatel** [comment]
In new query pipeline we have made type mapping first class concept in translated SQL fragment, This gives us opportunity to assign type mapping for literals and parameters correctly at the time of translate only. Type inference is complex task and it would probably never be assumed to be done. Since we have done majority of work to support and it is working correctly, I am marking this issue as closed fixed.
