### ISSUE TITLE
Promote IncludeCompiler into DI services

### ISSUE THREAD

**Issue by crhairr** [aspnet/EntityFrameworkCore#13266]
As a 3rd-party EFCore provider developer/maintainer, I need to be able to modify the behavior of the default IncludeCompiler. The current IncludeCompiler makes several assumptions about the underlying DB provider's capabilities especially with regards to GroupJoins, and results in non-performant runtime query execution.

It is possible to inherit from IncludeCompiler and override some functionality. However, doing so is currently very clunky since there's no service factory, no overridable factory method where it's [used in EntityQueryModelVisitor](https://github.com/aspnet/EntityFrameworkCore/blob/146863a3bdc25c1ea1cb224ba0611594398c8459/src/EFCore/Query/EntityQueryModelVisitor.cs#L325), and IncludeCompiler's nested classes are all private, making it impossible to reuse or override them.

The net is result is that EntityQueryModelVisitor.OptimizeQuery must be completely reproduced, along with several other `internal` types (including IncludeLoadTree/Node/Base and every class that is directly instantiated in OptimizeQuery) for the sole purpose of modifying IncludeCompiler's functionality. This is bad design, since IncludeCompiler handles a public API feature (ie: IncludableQueries), but its functional use is effectively internal, making it very difficult for 3rd party providers to alter the behavior.

I'd like to propose at least one of the following changes:

1) Promote IncludeCompiler to a dependency-level service using proper dependency injection and a factory.

2) Promote IncludeCompiler.IncludeLoadTree and IncludeCompiler.IncludeLoadTreeNode to public interfaces.

3) Expose IncludeLoadTreeNodeBase.CompileReferenceInclude and IncludeLoadTreeNodeBase.CompileCollectionInclude as protected virtuals

These changes will make it much easier to override and modify the behavior of IncludeCompiler without having to re-implement several other EFCore types and services.

```c#
public interface IIncludeCompilerFactory
{
    IIncludeCompiler CreateIncludeCompiler(
        [NotNull] QueryCompilationContext queryCompilationContext,
        [NotNull] IQuerySourceTracingExpressionVisitorFactory
            querySourceTracingExpressionVisitorFactory);
}

public interface IIncludeLoadTreeNode
{
    IReadOnlyCollection<IncludeLoadTreeNode> Children { get; }
    Expression Compile();
}

public interface IIncludeLoadTree : IIncludeLoadTreeNode
{
}

public class IncludeCompiler
{
    /* etc. */

    protected virtual IIncludeLoadTree CreateIncludeNodeTree();
}

public class IncludeLoadTreeNode : IIncludeLoadTreeNode
{
    public virtual Expression Compile() { /* etc. */ }

    protected virtual Expression CompileReferenceInclude() { /* etc. */ }

    protected virtual Expression CompileCollectionInclude() { /* etc. */ }
}
```

### Further technical details
EF Core version: ALL EFCore versions
Database Provider: Non-Specific (problem is in EFCore)

**Comment by ajcvickers** [comment]
Tracking this for 3.0 as part of the the larger query refactoring that is tracked by #12795

**Comment by crhairr** [comment]
Thanks for the timeline! This change will be a huge help for NoSQL providers.

**Comment by ajcvickers** [comment]
3.0 query design should allow this scenario, although with different types. Leaving open to verify in 3.0.

**Comment by smitpatel** [comment]
This has been fixed. There is no separate include compiler. It has been integrated in nav rewrite.
