### ISSUE TITLE
Seeded migrations with RowVersion produces invalid migrations

### ISSUE THREAD

**Issue by mlynam** [aspnet/EntityFrameworkCore#13276]
Migrations where you use HasData to seed the database with entities that use a RowVersion property produces future migrations where the call to DeleteData looks for an entity matching a seeded Id and a null rowversion. Delete then removes nothing from the database and the Insert operation fails.

### Steps to reproduce
```c#
  migrationBuilder.DeleteData(
    table: "Members",
    keyColumns: new[] { "Id", "Version" },
    keyValues: new object[] { 1, null });
```

### Further technical details
EF Core version: 2.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: 15.8.2

**Comment by ajcvickers** [comment]
@AndriySvyryd to find dupe.

**Comment by AndriySvyryd** [comment]
This is related to https://github.com/aspnet/EntityFrameworkCore/issues/11969

**Comment by mlynam** [comment]
Thanks for the tracking info guys.
