### ISSUE TITLE
Sqlite Spatial: Translate GeometryType

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#13280]
Unfortunately, the result of GeometryType is different between NTS and SpatiaLite:

Lib | Result
--- | ---
NTS | Point
SpatiaLite | POINT Z

We really need some way of determining an instance type to enable efficiently querying heterogeneous collections.

We could either:
* Return the value directly--require handling case and dimension in the application; values change between server and client eval.
* Massage the strings to look like NTS
* Don't translate--we should provide an alternative like translating `OgcGeometryType` using a big `CASE` expression

**Comment by ajcvickers** [comment]
Triage: do the `OgcGeometryType` option for 2.2.

**Comment by bricelam** [comment]
Looks like we'll need to add the ability to generate a `CASE` with a base expression before we can do this.

``` sql
CASE rtrim(GeometryType({baseExpression}), ' ZM')
    WHEN 'POINT' THEN 1
    WHEN 'LINESTRING' THEN 2
    WHEN 'POLYGON' THEN 3
    WHEN 'MULTIPOINT' THEN 4
    WHEN 'MULTILINESTRING' THEN 5
    WHEN 'MULTIPOLYGON' THEN 6
    WHEN 'GEOMETRYCOLLECTION' THEN 7
END
```

**Comment by bricelam** [comment]
WIP in branch [bricelam:2moar](https://github.com/aspnet/EntityFrameworkCore/compare/release/2.2...bricelam:2moar)

**Comment by bricelam** [comment]
Translated both. I realized the translation was pretty much the same...
