### ISSUE TITLE
RevEng: Remove infra around underlyingstoretype which was to support type aliases

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#13292]
With #12633 type alises are going away from DatabaseModel level. i.e. providers will find out underlying type for aliased type and swap them out so EF never sees aliases. The infra to support aliases in EF Core design is public and should be removed.

**Comment by bricelam** [comment]
(Mentioned in PR) Let's obsolete it now and encourage provider writers to do the same as SQL Server

**Comment by ajcvickers** [comment]
Re-opening to ensure breaking change is announced.

**Comment by smitpatel** [comment]
@ajcvickers - Customer breaking change happened in #12633 itself where we stopped setting `HasColumnType` to alias. This issue was mainly cleanup in internal code which may break providers.

**Comment by ajcvickers** [comment]
@smitpatel Plan for provider-only breaks is an entry here: https://docs.microsoft.com/en-us/ef/core/providers/provider-log
