### ISSUE TITLE
SqlServer Migrations: Consolidate ValueGenerationStrategy, IdentitySeed & IdentityIncrement

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#13352]
My only regret in Migrations is using this...
``` csharp
.Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
```
...instead of something like this:
``` csharp
.Annotation("SqlServer:Identity", true)
```

Is it worth making this change? We could do it in a way that doesn't break existing migrations.

**Comment by Muppets** [comment]
@bricelam I'm happy to take a look at this as a follow up from [identity properties](https://github.com/aspnet/EntityFrameworkCore/pull/14721). You suggested something like:

`.Annotation("SqlServer:Identity", "1, 1")`

Which works for me. Would you want that even if they don't specify a seed and increment? Default to 1,1?

**Comment by bricelam** [comment]
Defaulting to `1, 1` seems like the simplest way to handle it to me. It avoids having multiple annotations and using an empty string isn't clear (no identity or identity with its default seed and increment).

**Comment by bricelam** [comment]
Note to implementor: Continue to honor the the old annotation in the Migrations SQL generator (so existing migrations still work), but stop generating it in the Migrations annotation provider.
