### ISSUE TITLE
Query: QueryFilters/Defining queries are not applied recursively

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#13361]
As described in #11803, query filters (and also defining queries included), are not applied recursively. Fix for that issue apply recursion at expansion time but it became quite limited in terms of what it can do. Specifically following issues were ignored
- Navigation expansion is not done. So query filters would not be applied on db set coming through navigations.
- FromSql/Include any other query annotations are not extracted. That means we would lose out some info. This also caused regression like #13346 

Effectively the fix only made it possible to apply recursively only when referencing direct dbset or dbquery of entitytype without any annotation. 

Fixing this requires us to apply few operations like extract annotations, nav expansion, query optimizer on expanded part and apply it recursively. Currently it is too fragile to effectively arrive at terminating condition (due to relinq's in-place QueryModel mutation).
Hence reverting the fix for #11803

**Comment by ajcvickers** [comment]
Note from triage: we are okay with a new cache entry when the filter is disabled.

**Comment by ajcvickers** [comment]
We should at least make sure it throws for 3.0 instead of returning incorrect results.

**Comment by AndriySvyryd** [comment]
@maumar Is this fixed/not needed now?

**Comment by smitpatel** [comment]
I believe fixed.

**Comment by maumar** [comment]
fixed indeed, closing
