### ISSUE TITLE
Add .AsTracking(bool track)

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/EntityFrameworkCore#13385]
Here is a very easy/simple requirement.
I have implemented a very simple extension, but I believe it should be part of the framework:

```cs
public static IQueryable<TEntity> AsTracking<TEntity>(this IQueryable<TEntity> source, bool track) where TEntity : class
    => track ? source.AsTracking() : source.AsNoTracking();
```

This allows to specify the tracking status while calling a method depending the use we plan for the data.

**Comment by ajcvickers** [comment]
@JeanCollas We have discussed this API in the past and for various reasons (some historical) we opted for HasTracking and HasNoTracking instead. Feel free to keep using this extension method in your code--seems like a great way to add the sugar you want without impacting the overall API surface.

**Comment by ajcvickers** [comment]
Re-opening to consider adding an optional `tracking` parameter to AsTracking without adding a new API.
