### ISSUE TITLE
Replace service doesn't work correctly for IConventionSetBuilder

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#13479]
When used with a provider (e.g. SqlServer) the replacement service is added twice.

**Comment by ajcvickers** [comment]
@AndriySvyryd Interesting. This is because the service is registered with "allow multiple" and we find two instances to replace. It's not clear to me how/if ReplaceService should work in this case.

**Comment by ajcvickers** [comment]
Proposal from triage discussion:
* By default, replace all occurrences with the single one supplied
* Allow the current _implementation_ type to be passed to ReplaceService as the first generic, and then only replace that implementation with the new type provided.
