### ISSUE TITLE
Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer Warning

### ISSUE THREAD

**Issue by karelz** [aspnet/EntityFrameworkCore#13474]
_From @pgmolloy on September 27, 2018 0:5_

Just started getting a build warning after updating Visual Studio. Can this be disabled as it doesn't seem to affect anything that I can tell, app builds, deploys and runs in Azure without a problem so not sure why this is a warning except maybe for that package developer. CSC : warning AD0001: Analyzer 'Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

I am not using the RawSqlStringInjectionDiagnosticAnalyzer but it may be a dependency so without feedback I am hesitant to do anything besides leave the warning display annoyingly 30 times every build.
Cheers Peter

_Copied from original issue: dotnet/core#1965_

**Comment by ajcvickers** [comment]
@pgmolloy What version of Visual Studio are you using and what version of the .NET Core SDK do you have installed?

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by toddlucas** [comment]
This issue can be repro'd with the following snippet:

```
    int id = 1;
    int status = 1;
    FormattableString sql;

    sql = $"UPDATE Jobs SET Status = {status} WHERE Id = {id}";

    int result = await _context.Database.ExecuteSqlCommandAsync(sql);
```

Note that this exception is not triggered if the string is passed directly to the method, nor if it is assigned to as part of the variable declaration.

**Comment by ajcvickers** [comment]
@toddlucas This looks exactly like the code the analyzer is intended to warn on. Even though it may appear that status and id are passed as parameters, they are in fact inlined.

**Comment by divega** [comment]
@ajcvickers @toddlucas that is a safe pattern that the analyzer doesn’t detect as safe. I filed it at 
https://github.com/aspnet/EntityFrameworkCore/issues/13273 but we decided not to fix.

**Comment by ajcvickers** [comment]
Ah, okay. My mistake. Thanks @divega

**Comment by ajcvickers** [comment]
@divega I missed that the `sql` variable was typed as `FormattableString`.

**Comment by toddlucas** [comment]
Yes, the SQL is emitted parameterized, but instead of getting the warning, I get an exception. Here's what I get if I assign as part of the declaration:

```
FormattableStringTest.cs(59,32,59,77): warning EF1000: The SQL expression passed to 'ExecuteSqlCommandAsync' embeds data that will not be parameterized. Review for potential SQL injection vulnerability. See https://go.microsoft.com/fwlink/?linkid=871170 for more information.
1>
```

and here's what I get if I assign in a statement that is separate from the declaration:

```
CSC : warning AD0001: Analyzer 'Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
1>
```

Thanks!

**Comment by toddlucas** [comment]
Yes, sorry if I wasn't clear. Your example is correct.

**Comment by ajcvickers** [comment]
@toddlucas What versions of EF Core, .NET Core, and Visual Studio are you using?

**Comment by toddlucas** [comment]
I'm running VS Community 15.8.7, .NET Core SDK 2.1.403 (2.1.5), and EF Core 2.1.4
