### ISSUE TITLE
EF benchmarks are failing

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#13493]
We are not getting benchmark results and therefore we cannot publish them. We haven't investigated exactly what broke them but @smitpatel suspects it could have to do with some changes we did to leverage a new feature of Benchmark.NET and/or issues with the .NET Framework installed in the machine.

**Comment by smitpatel** [comment]
Assigning to @roji - our new benchmark guy.

**Comment by roji** [comment]
@smitpatel @divega is there anything to do here? Benchmarks seem to be running and stable.

We should probably investigate if the we're benchmarking the proper scenarios etc. (e.g. I wonder if we're actually exercising query enough) but that's another question.

**Comment by divega** [comment]
@roji No, I guess you fixed this issue. We can create new issues on how to improve out benchmarks.
