### ISSUE TITLE
Client evaluation in query with Contains on an IEnumerable subquery

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#13524]
This is the query pattern that [caused StackOverflow.com to go offline yesterday](https://twitter.com/Nick_Craver/status/1047929955206795267):

![image](https://user-images.githubusercontent.com/1253414/46564945-993caf80-c8bf-11e8-87eb-8269c533495f.png)

There are two separate aspects we need to follow up on:

1. This is a predicate that we could do a better job of translating to SQL. We will use this issue to track that pattern specifically. 

2. The customer was porting their code from LINQ to SQL to EF Core and didn't expect client evaluation to occur for a predicate against a table that contained millions of rows, and did not think of [switching client-eval off](https://docs.microsoft.com/en-us/ef/core/querying/client-eval#optional-behavior-throw-an-exception-for-client-evaluation). Assuming the query was exercised in testing or staging, that could have helped detect the issue before rolling up to production. Based on this and other previous feedback, we are discussing moving the slider for client eval in future versions. Whatever shape this takes, it is likely to be a breaking change, so we will track it as part of the overall 3.0 plan for query in #12795.

## Workaround
If you are hitting client evaluation for this query, you can follow the same pattern @JoshSchreuder described below: split the sub-query into its own variable:

```csharp
var postIds = grp.Select(g => g.PostId); 
var answers = db.Posts.Where(postIds.Contains(p.Id)).Select(...).ToList();
```

**Comment by JoshSchreuder** [comment]
A couple of things I noticed when trying to reproduce this:

* EF6 will throw an error if you use `grp.Select(...)` inside of the predicate

`NotSupportedException: Unable to create a constant value of type 'UserQuery+Group'. Only primitive types or enumeration types are supported in this context.`

* If you pull the `grp.Select(...)` out into a variable before using that variable in the predicate, the query will be translated as expected, eg.

```csharp
var postIds = grp.Select(g => g.PostId); // Doesn't seem to matter if IEnumerable<T> or .ToList() List<T> here
var answers = db.Posts.Where(postIds.Contains(p.Id)).Select(...).ToList();
```

**Comment by divega** [comment]
Updated original post with workaround.

**Comment by smitpatel** [comment]
```C#
            var ids = new List<Customer>
                    {
                        new Customer{ CustomerID = "ABCDE" },
                        new Customer{ CustomerID = "ALFKI" }
                    };

            await AssertQuery<Customer>(
                isAsync,
                cs => cs.Where(
                    c => ids.Select(i => i.CustomerID).Contains(c.CustomerID)), entryCount: 1);
```
Gets Translated to 
```SQL
SELECT [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
FROM [Customers] AS [c]
WHERE [c].[CustomerID] IN (N'ABCDE', N'ALFKI')
```

**Comment by smitpatel** [comment]
Current funcletization has enabled translating `Select` over local `IEnumerable` (Skip/Take etc which doesn't have lambda should just get parameterized)
We need to be more precise only what exactly we allow through funcletization.
We can also support where/OrderBy but doing a Join/GroupJoin/SelectMany (essentially anything which has multiple sequences) may have side effects which can cause erros.

Marking for design meeting.
