### ISSUE TITLE
Consider utilizing "local" detect changes

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#13552]
That is, DetectChanges that only scan a single entry, or possibly only the entries on either side of a given relationship. This may miss cascading changes, but it is likely to avoid the need for full DetectChanges in many scenarios. For example, see #13122 and #12810.

**Comment by yileicn** [comment]
SaveChange () is already called DetectChanges(), so you don't need to call here?
Now call DbContext. Entry () very slowly

**Comment by Prinsn** [comment]
This is linked from https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#dbe as the tracked issue for this.

I'm confused as to why this is closed.

I've seen a 24 second to 50 minute performance degradation in a benchmark.
