### ISSUE TITLE
Cosmos: Track owned entities when included with the owner

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#13579]
Currently from `context.Vehicles.First().Operator` won't be tracked if `Operator` is an embedded owned entity. We should track both `Vehicle` and `Operator`.

**Comment by divega** [comment]
@AndriySvyryd is this different form #13036?

**Comment by AndriySvyryd** [comment]
@divega Yes, this is specifically about nested entities (stored in the same document). The implementation would have to be different.

**Comment by divega** [comment]
@AndriySvyryd ok, thanks. I think the issues are joined at the hip though. We should apply whatever behavior we decide is best to both.

**Comment by ajcvickers** [comment]
Do what we said in #13640

**Comment by ajcvickers** [comment]
Putting this in backlog because #13036 covers what we need for 3.0.
