### ISSUE TITLE
Move discriminator support to Core

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#13603]
This would allow easier implementations of discriminators in non-relational providers

**Comment by ajcvickers** [comment]
Do the move, not enhancing the API. (Unless we do need to do that.)

**Comment by AndriySvyryd** [comment]
Metadata moved to Core. Common Query parts still need to be moved.

**Comment by smitpatel** [comment]
@AndriySvyryd - Can you take a quick look and tell what parts need to be moved from query? Query's materializer utilizes TPH at core level. The only pending thing would be InMemory, but InMemory needs to change it's storage strategy to align with TPH.

**Comment by AndriySvyryd** [comment]
I think that's enough for now. If some other common pattern appears we can move it later.

**Comment by smitpatel** [comment]
Fixed by #15809
