### ISSUE TITLE
Indexed properties mapping support (part of property bag entities)

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFrameworkCore#13610]
From discussion with @divega and @ajcvickers. We would like to support Entity classes with indexers:

```csharp
    public class SomeEntity
    {
        public object this[string propertyName]
        {
            get
            {
                // get value of property named propertyName
            }

            set
            {
                // set value of property named propertyName
            }
        }
    }
```

You can then declare an indexed property in `OnModelCreating()` and have EF use the indexer to access that property, instead of expecting a member. (Note: this addresses parts of issues #2968 and #9914).

Previous Tasks:
- [ ] Update the metadata to allow the model to get and set property values using the indexer
- [ ] Store the `PropertyInfo` in `PropertyBase`
- [ ] Add `ModelBuilder` fluent API so the user does not need to access metadata methods directly
- [ ] Update query pipeline to allow indexer references e.g. `ctx.Entity<SomeEntity>.Property(e => e["PropertyName"])...`

New Tasks:
- [x] Update metadata to allow model to get/set property values using the indexer

**Comment by smitpatel** [comment]
Few questions:
@AndriySvyryd or @ajcvickers if there are already answers or we can discuss in design meeting to decide.
- Should there be `AddIndexedProperty` method on `IMutableEntityType`? Specifying memberInfo is bit cumbersome and if we know we are adding indexed property then we can fetch it from entityType.ClrType directly.
- Fluent API? or to be discussed later?
- Fields
  - Can indexer be field in C# (I really don't know)?
  - Current design assumes it to be always a propertyInfo.
  - Indexer properties can be configured to use backing field just like any other property.
  - Is there a need or should we support mapping indexer to a backing field dictionary which would be accessed directly?

**Comment by AndriySvyryd** [comment]
- You can add `AddIndexedProperty` extension method or default interface implementation as sugar if it's useful.
- `.IndexedProperty<int>("Id")` would be my first suggestion
- Indexers cannot be fields and can't have a backing field
- We don't need to support Dictionary properties at this point

**Comment by smitpatel** [comment]
Only fluent API is left now.
I will start with
> .IndexedProperty<int>("Id") would be my first suggestion

unless someone brings something better in new year.

**Comment by bigworld12** [comment]
will this issue be related to fixing https://github.com/dotnet/efcore/issues/13084 and https://github.com/dotnet/efcore/issues/2968

**Comment by ajcvickers** [comment]
@bigworld12 This issue is unrelated to the two that you mention.
