### ISSUE TITLE
Switch Cosmos to no-ship for RTM

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#13670]
The next Cosmos preview will be with EF Core 3.0 preview1. It should be changed to a non-shipping package for 2.2 RTM.

**Comment by ajcvickers** [comment]
FYI @natemcmaster @Eilon just so you are both aware that this is happening. We'll have @natemcmaster sign-off on the change to make sure we don't miss anything.

**Comment by natemcmaster** [comment]
The new place to make a PR for this is here: https://github.com/aspnet/AspNetCore/blob/release/2.2/build/artifacts.props#L191
