### ISSUE TITLE
Un-list the old Cosmos package on NuGet

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#13671]
Package was Microsoft.EntityFrameworkCore.Cosmos.Sql up to preview2. This package should now be unlisted.

**Comment by divega** [comment]
Unfortunately Microsoft.EntityFrameworkCore.Cosmos.Sql was published as only owned by the aspnet org. so I cannot unlist it. 

Same with the new package Microsoft.EntityFrameworkCore.Cosmos. 

@muratg can you help assign ownership to entityframework?

**Comment by divega** [comment]
Here is the full list of packages we need asssinged to the entityframework org:
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Cosmos/2.2.0-preview3-35497
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Cosmos.Sql/2.2.0-preview2-35157 (should unlist)
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Abstractions/2.2.0-preview3-35497
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Analyzers/2.2.0-preview3-35497
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Proxies/2.2.0-preview3-35497
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Attributes/2.1.0-preview1-final (should unlist)
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite/2.2.0-preview3-35497
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite/2.2.0-preview3-35497

**Comment by muratg** [comment]
> @muratg can you help assign ownership to entityframework?

@divega all done. Let me know if I missed anything.

**Comment by divega** [comment]
@muratg That was fast! Thank you!

**Comment by divega** [comment]
@muratg Just FYI, https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Cosmos.Sql/ was also missing Microsoft as an owner. It should not matter because we unlisted it anyway, but you may want to look at other packages as well that may be missing it.
