### ISSUE TITLE
Hide Object-inherited members on certain APIs

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#1367]
The cleverest way I've seen to do is in Moq which uses an [IHideObjectMembers](https://github.com/Moq/moq4/blob/master/Source/IHideObjectMembers.cs) interface that can easily be added to types.

**Comment by ilmax** [comment]
There is also [this](https://github.com/kzu/IFluentInterface/blob/master/content/IFluentInterface.cs.pp) from @kzu created for the same purpose

**Comment by anpete** [comment]
Agreed. IIRC we tried this for CF early on but it didn't work - I could be mis-remembering.

**Comment by AndriySvyryd** [comment]
Do this for all public *Builder classes

**Comment by kzu** [comment]
You can just install the `IFluentInterface` nuget package :). It even works in SDK-style projects :D

**Comment by ajcvickers** [comment]
Do it for 2.1 or never!
