### ISSUE TITLE
Design: Scan target project for [DesignTimeServicesReference]

### ISSUE THREAD

**Issue by aherrick** [aspnet/EntityFrameworkCore#13690]
I have an existing DB with a Geography column. When running the Scaffold command, it still says it can't support:

```
Scaffold-DbContext "myconnectionstring" Microsoft.EntityFrameworkCore.SqlServer -o "Models\DB" -force
Could not find type mapping for column 'dbo.Venue.Location' with data type 'geography'. Skipping column.
Unable to scaffold the index 'inxVenueLocation'. The following columns could not be scaffolded: Location.
```

I have this package installed:

`Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite`

**Comment by bricelam** [comment]
Do you have multiple projects in your solution?

**Comment by bricelam** [comment]
I suspect you're using a separate startup project from the one where the NTS extension package is installed.

We should consider scanning for design-time services in the target project as well as the startup project.

**Comment by bricelam** [comment]
As a workaround, you can add this code to your startup project:
``` csharp
using Microsoft.EntityFrameworkCore.Design;

[assembly: DesignTimeServicesReference(
    "Microsoft.EntityFrameworkCore.SqlServer.Design.Internal.SqlServerNetTopologySuiteDesignTimeServices, Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite",
    "Microsoft.EntityFrameworkCore.SqlServer")]
```

**Comment by aherrick** [comment]
This work around worked. Thanks!
