### ISSUE TITLE
Group by does not work with DbFunction on property

### ISSUE THREAD

**Issue by ackava** [aspnet/EntityFrameworkCore#13754]
This Linq query with group by does not translate with sql group by.

```c#

var start = DateTime.UtcNow.AddDays(-7);

db.EmailRecipients
                .Where(x => x.DateSent > start && x.Account.AccountType == "Customer")
                .GroupBy(x => Microsoft.EntityFrameworkCore.EF.Functions.DateDiffDay(now, x.DateSent) )
                // .OrderByDescending(x => x.Key)
                .Select(x => new ClickReport {
                    Label = x.Key,
                    Count = x.Count(),
                    OpenCount = x.Count( e => e.TimeRead != null)
                })
```

Translated query,
```sql
SELECT [x].[EmailRecipientID],[x].[AccountID],[x].[DateSent], [x].[EmailAddress], [x].[TimeRead]
FROM [EmailRecipients] AS [x]
LEFT JOIN [Accounts] AS [x.Account] ON [x].[AccountID] = [x.Account].[AccountID]
WHERE ([x].[DateSent] > @__start_0) AND ([x.Account].[AccountType] = N'Customer')
ORDER BY (SELECT 1)
```

This is pretty simple query, I have even tried with `GroupBy( x => x.DateSent.Value.Day )`, still same result. **The worst part is, it is fetching all columns !!!**, I even have body of email which is nvarchar and everything is fetched from database.

### Further technical details
EF Core version: 2.1.4
Database Provide: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 2016 Standard Server
IDE: Visual Studio 2017 15.4

I am aware of the fact that I can generate a view on server and use it to query using DbQuery but regardless, this should work.

**Comment by qqliuyifanqq** [comment]
How did you solve the problem?
