### ISSUE TITLE
Scaffold-DbContext Lazy loading

### ISSUE THREAD

**Issue by aday12345** [aspnet/EntityFrameworkCore#13777]
will Scaffold-DbContext be updated to support lazy loading with a switch or some other flag to tell it to build types with the lazy loading properties defined

**Comment by aday12345** [comment]
sorry, all the foreign key relationships that should be defined as virtual for lazy loading to work like this 'public virtual Region Region { get; set; }' not 'public Region Region { get; set; }'

**Comment by ErikEJ** [comment]
I think they already are in 2.2...

**Comment by ajcvickers** [comment]
@ErikEJ I thought that too, but I couldn't find an issue/PR to confirm it and I haven't tested yet.

**Comment by ErikEJ** [comment]
https://github.com/aspnet/EntityFrameworkCore/blame/release/2.2/src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs#L315 

https://github.com/aspnet/EntityFrameworkCore/commit/10abe9a06e5a6a09f9b3da76effc33a20049fa2a

**Comment by ajcvickers** [comment]
Thanks @ErikEJ!
