### ISSUE TITLE
Microsoft.Data.Sqlite: Persist functions, PRAGMAs, etc. between close and re-open

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#13826]
This was previously discussed in aspnet/Microsoft.Data.Sqlite#61.

There are quite a few things in SQLite that need to be configured every time a connection is opened. (E.g. certain PRAGMAs, user-defined functions, collations, etc.)

The idea would be that you pass some configuration into your `SqliteConnection` instances, and every time the connection is opened, it would be configured appropriately.

**Comment by bricelam** [comment]
We've been thinking about this again. Our current thinking is to make the following calls persist between closing and reopening a connection.

* CreateFunction
* CreateAggregate
* CreateCollation
* EnableExtensions

If performance is significantly degraded after this, we'll consider adding a connection pool (#13837).

We'll consider adding methods/properties/connection string keywords for things like the following based on feedback.

- SELECT load_extension() *(We'd actually implement it using sqlite3_load_extension())*
- PRAGMA recursive_triggers *(Relatively new feature. Hopefully enabled by default in a future version of e_sqlite3. Why turn this off?)*
- PRAGMA case_sensitive_like *(Why turn this on?)*
- PRAGMA foreign_keys *(Enabled by default in e_sqlite3. Why turn this off outside of rebuilds?)*

We're adding a connection string option for `PRAGMA key` (#13828)

**Comment by bricelam** [comment]
I'm opening up to the idea of adding more connection string keywords like `Foreign Keys` and `Recursive Triggers` since you generally don't change them over the lifetime of the connection.

**Comment by bricelam** [comment]
Tentative plan:

Add `Foreign Keys`, `Journal Mode`, `Password`, and `Recursive Triggers` as connection string keywords. Send corresponding PRAGMA statements on connection open.

Add LoadExtension method to SqliteConnection. Keep track of calls to this, CreateFunction, CreateAggregate, CreateCollation, and EnableExtensions. Call corresponding APIs on connection open.

Need to think more about the interaction between EnableExtensions, LoadExtension, Close, and Open.

**Comment by bricelam** [comment]
WIP branch for allowing `Foreign Keys=True` and `Recursive Triggers=True` in the connection string: [bricelam:keywords](https://github.com/aspnet/EntityFrameworkCore/compare/master...bricelam:keywords)

**Comment by bricelam** [comment]
The breaking change here is unlikely to affect many people: If you override a built-in collation or function, that override now remains in effect after closing and re-opening the connection which may affect behavior. But that's more likely to fix you application than break it. 😉

**Comment by bricelam** [comment]
I forgot to mention this here:

Since setting the Journal Mode to Write-Ahead Logging (WAL) is persisted, I decided it would be better for EF just to set it for databases it creates. (See https://github.com/aspnet/EntityFrameworkCore/issues/14059) No need for a connection string keyword yet since this probably covers most scenarios where you want to change it from the default.

**Comment by vhking** [comment]
@bricelam Is it possible to set Synchronous in the connection string in the new .net 3.0.0 preview 4? If so, how would you do that?

**Comment by bricelam** [comment]
No, we haven't added that one. What is your scenario? Maybe what you really want is for e_sqlite3 to define [SQLITE_DEFAULT_WAL_SYNCHRONOUS](https://sqlite.org/compile.html#default_wal_synchronous)=1?

**Comment by vhking** [comment]
We are running on an arm/imx6 SBC where reading/writing to the database is very slow. We were hoping to get better performance by doing some optimization on SQLite, so we could do more logging etc.

**Comment by bricelam** [comment]
Have you seen [this post](https://www.bricelam.net/2017/07/20/sqlite-bulk-insert.html)? It's a good place to start. Issue #14044 will make perf even better with higher-level libraries like EF. Also if you're using encryption, make sure you're not closing a re-openeing the connection a lot--one open connection per thread is a good strategy.

**Comment by darkguy2008** [comment]
So is this done? I'm getting `Keyword not supported: "synchronous"` when trying to set this PRAGMA. Any ideas?

**Comment by bricelam** [comment]
@darkguy2008 Can you submit a new issue and clarify what you are doing when you get this error?

**Comment by ahdung** [comment]
How to disable WAL please?
