### ISSUE TITLE
Microsoft.Data.Sqlite: Adding support for providing an encryption key in SqliteConnectionString class

### ISSUE THREAD

**Issue by brunzefb** [aspnet/EntityFrameworkCore#13828]
I would like to discuss adding the key in the SqliteConnectionString class of the Microsoft.Data.Sqlite project, but am not 100% sure this can be made to work throughout the stack-  If Password were a property of SqliteConnectionString (and passed to the lower dll) and you had a SQLitePCLRaw.core with a provider that supported encryption, and a native dll that also supported encryption, you would get the encryption if you provided the “Password” in the connection string, otherwise it would be unencrypted.  If you used a SQLitePCLRaw.core with a provider that did not support encryption, or if the low-level dll did not support encryption, usage of the “Password” in the connection string would basically be a No-Op or throw an exception.  Effectively - the user of Microsoft.Data.Sqlite could specify encryption without recompiling Microsoft.Data.Sqlite, if the rest of the stack supported it.  From what I can see, we only need to support the ‘sqlite3_key()’ API.

I know that it is possible to use a #PRAGMA in an SQLCommand to specify the encryption key, but that is a pretty un-intuitive way of providing the key.  Adding the Password property makes more sense to me.

**Comment by bricelam** [comment]
I've been thinking more about ways to prevent people from shooting themselves in the foot, and I think  using code like this (don't shoot me @ericsink) would cover most cases:
``` csharp
var providerName = typeof(SQLitePCL.raw)
    .GetField("_imp", BindingFlags.Static | BindingFlags.NonPublic)?.GetValue(null)
    .GetType().Name;
if (providerName == "SQLite3Provider_e_sqlite3")
{
    throw new InvalidOperationException(Resources.EncryptionNotSupported);
}
```
We could consider blocking more providers (e.g. winsqlite3), but chances are, if they're using an non-default provider, they know what they're doing.

**Comment by bricelam** [comment]
WIP branch: [bricelam:keywords](https://github.com/aspnet/EntityFrameworkCore/compare/master...bricelam:keywords)
