### ISSUE TITLE
ValueConverter expressions: Are you really lazy?

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#13844]
https://github.com/aspnet/EntityFrameworkCore/blob/4f470638e0e98a8c60175c524e99792a72640986/src/EFCore/Storage/ValueConversion/ValueConverter%60.cs#L61-L71

ctor initializes them already.

**Comment by ajcvickers** [comment]
Looks like constructor is wrong here, but I guess we could go either way.
