### ISSUE TITLE
Memory leak after disposing SqliteCommand

### ISSUE THREAD

**Issue by v1rusw0rm** [aspnet/EntityFrameworkCore#13898]
aspnet/Microsoft.Data.Sqlite#388 this pull request introduced a list of weak references to commands inside `SqliteConnection`. Commands are disposed and the list are cleared at Connection closing. But if the connection lifetime is long, this list keeps growing. I think the command should be removed from this list on `SqliteCommand.Dispose`.

Microsoft.Data.Sqlite version: 2.1.0

**Comment by v1rusw0rm** [comment]
The problem is not with weak references but with the `Connection._commands` list itself. Every new command adds an item to this list, but then items are never removed from the list, only when Connection is closed.

For example:
```
using Microsoft.Data.Sqlite;

namespace MemoryLeak
{
    class Program
    {
        static void Main(string[] args)
        {
            var connection = new SqliteConnection("Data Source=:memory:");
            connection.Open();
            while(true)
            {
                using (var cmd = new SqliteCommand("SELECT 1", connection))
                {
                }
            }
        }
    }
}
```

Let it run for a few seconds and then put a breakpoint inside the `while` loop and check the `_commands` field of the `connection`. It will contain a lot of items.

I tried to fix it in https://github.com/v1rusw0rm/EntityFrameworkCore/commit/5911ace285db6a045f0ce976472872ef6ce5f21c but can't figure out how to do it better without copying the list.

**Comment by jjxtra** [comment]
Getting out of memory leak in .NET core 2.2 because of this. Is there no way to remove it from internal list? Happy to use reflection or any hacks...
