### ISSUE TITLE
The column 'X' was specified multiple times for 'Y'

### ISSUE THREAD

**Issue by BBGONE** [aspnet/EntityFrameworkCore#13922]
The query with paging with multiple owned entities produces error (but it seems that it is only if i use - UseRowNumberForPaging)

```
optionsBuilder.UseSqlServer(connection, (options)=> {
                // to support SQL SERVER 2008
                options.UseRowNumberForPaging();
            });
```
the resulting select query is
```
exec sp_executesql N'SELECT [t].[CustomerID], [t].[CompanyName], [t].[ModifiedDate], 
[t].[NameStyle], [t].[PasswordHash], [t].[PasswordSalt], [t].[rowguid], 
[t].[SalesPerson], [t].[Suffix], [t].[Title], [t].[CustomerID0], 
[t].[EmailAddress], [t].[Phone], [t].[FirstName], [t].[LastName], [t].[MiddleName]
FROM (
    SELECT [c].[CustomerID], [c].[CompanyName], [c].[ModifiedDate], [c].[NameStyle], [c].[PasswordHash], 
[c].[PasswordSalt], [c].[rowguid], [c].[SalesPerson], [c].[Suffix], [c].[Title], 
[c].[CustomerID] AS [CustomerID0], [c].[EmailAddress], [c].[Phone], 
[c].[CustomerID] AS [CustomerID0], [c].[FirstName], [c].[LastName], 
[c].[MiddleName], 
ROW_NUMBER() OVER(ORDER BY [c].[LastName], [c].[MiddleName], [c].[FirstName]) AS [__RowNumber__]
    FROM [SalesLT].[Customer] AS [c]
) AS [t]
WHERE ([t].[__RowNumber__] > @__p_0) AND ([t].[__RowNumber__] <= (@__p_0 + @__p_1))',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=50
```
which doubles [CustomerID0] column names

the Customer entity has two owned entities  CustomerName  and CustomerContact:

```
public partial class Customer
    {
        public Customer()
        {
            CustomerAddress = new HashSet<CustomerAddress>();
            SalesOrderHeader = new HashSet<SalesOrderHeader>();
        }

        public int CustomerId { get; set; }
        public bool NameStyle { get; set; }
        public string Title { get; set; }
        public CustomerName CustomerName { get; set; }
        public CustomerContact CustomerContact { get; set; }
        public string Suffix { get; set; }
        public string CompanyName { get; set; }
        public string SalesPerson { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public Guid Rowguid { get; set; }
        public DateTime ModifiedDate { get; set; }
  
        public ICollection<CustomerAddress> CustomerAddress { get; set; }
        public ICollection<SalesOrderHeader> SalesOrderHeader { get; set; }
    }
}
```

### Further technical details

EF Core version: Microsoft.EntityFrameworkCore.2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Visual Studio 2017 15.8.8
This bug can be tested on working project (Master-Details Demo): https://github.com/BBGONE/JRIApp.Core/tree/master
Querying  Customers results in error:
at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__174_0(Task`1 result)
Errors = {System.Data.SqlClient.SqlErrorCollection}
Message = SqlException: The column 'CustomerID0' was specified multiple times for 't'.

**Comment by BBGONE** [comment]
the select without  - UseRowNumberForPaging looks well because it has no subquery - the column names are repeated only in subquery:
```
exec sp_executesql N'SELECT [c].[CustomerID], [c].[CompanyName], [c].[ModifiedDate], [c].[NameStyle], [c].[PasswordHash], [c].[PasswordSalt], [c].[rowguid], [c].[SalesPerson], [c].[Suffix], [c].[Title], [c].[CustomerID], [c].[EmailAddress], [c].[Phone], [c].[CustomerID], [c].[FirstName], [c].[LastName], [c].[MiddleName]
FROM [SalesLT].[Customer] AS [c]
ORDER BY [c].[LastName], [c].[MiddleName], [c].[FirstName]
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=50

**Comment by BBGONE** [comment]
The entity was modeled like this (with database AdventureWorksLT2012)
```
 modelBuilder.Entity<Customer>(entity =>
            {
                entity.ToTable("Customer", "SalesLT");

                entity.Ignore(e => e.AddressCount);

                entity.HasIndex(e => e.Rowguid)
                    .HasName("AK_Customer_rowguid")
                    .IsUnique();

                entity.Property(e => e.CustomerId).HasColumnName("CustomerID");

                entity.Property(e => e.CompanyName).HasMaxLength(128);

                #region Owned Types

                entity.OwnsOne(x => x.CustomerContact).Property(c => c.EmailAddress).HasColumnName("EmailAddress").HasMaxLength(50);

                entity.OwnsOne(x => x.CustomerContact).Property(c => c.Phone).HasColumnName("Phone").HasColumnType("Phone")
                    .HasMaxLength(25);

                entity.OwnsOne(x => x.CustomerName).Property(c => c.FirstName).HasColumnName("FirstName").IsRequired()
                    .HasColumnType("Name")
                    .HasMaxLength(50);

                entity.OwnsOne(x => x.CustomerName).Property(c => c.MiddleName).HasColumnName("MiddleName")
                    .HasColumnType("Name")
                    .HasMaxLength(50);

                entity.OwnsOne(x => x.CustomerName).Property(c => c.LastName).HasColumnName("LastName").IsRequired()
                    .HasColumnType("Name")
                    .HasMaxLength(50);

                #endregion

                entity.Property(e => e.ModifiedDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NameStyle).HasColumnType("NameStyle");

                entity.Property(e => e.PasswordHash)
                    .IsRequired()
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.PasswordSalt)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Rowguid)
                    .HasColumnName("rowguid")
                    .HasDefaultValueSql("(newid())");

                entity.Property(e => e.SalesPerson).HasMaxLength(256);

                entity.Property(e => e.Suffix).HasMaxLength(10);

                entity.Property(e => e.Title).HasMaxLength(8);
            });
```

**Comment by duoanfen** [comment]
I also have this problem...

**Comment by duoanfen** [comment]
An exception occurred while reading a database value for property 'TMenu.ImgUrl'. The expected type was 'System.String' but the actual value was of type 'System.Int32'.
System.InvalidOperationException: An exception occurred while reading a database value for property 'TMenu.ImgUrl'. The expected type was 'System.String' but the actual value was of type 'System.Int32'. ---> System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.String'. at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue[TValue](ValueBuffer& valueBuffer, Int32 index, IPropertyBase property) --- End of inner exception stack trace --- at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property) at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue[TValue](ValueBuffer& valueBuffer, Int32 index, IPropertyBase property) at lambdamethod(Closure , MaterializationContext ) at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper
1.Shape(QueryContext queryContext, ValueBuffer& valueBuffer) at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable
1.Enumerator.BufferlessMoveNext(DbContext , Boolean buffer) at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func
3 operation, Func
3 verifySucceeded) at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable
1.Enumerator.MoveNext() at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable
1 results, QueryContext queryContext, IList
1 entityTrackingInfos, IList
1 entityAccessors)+MoveNext() at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor
1.EnumeratorExceptionInterceptor.MoveNext() at System.Collections.Generic.List
1.AddEnumerable(IEnumerable
1 enumerable) at System.Linq.Enumerable.ToList[TSource](IEnumerable
1 source) at GeduService.Implement.SettingService.CrmCarouselList(CrmCarouselListReq req) in D:\whb\GEDUProject\GEDUDistribution\GeduService\Implement\SettingService.cs:line 211 at GeduDistributionApi.Controllers.GeduBaseController._DoInvoke[I,O](I req, Func`2 func) in D:\whb\GEDUProject\GEDUDistribution\GeduDistributionApi\Controllers\GeduBaseController.cs:line 109

**Comment by duoanfen** [comment]
I check the sql EF auto get, It have double same column name too. My code is:

**Comment by duoanfen** [comment]
var query = _menuService.Where(t => t.IsDel == false)
                .Where(t => t.SchoolId == schoolid)
                .Where(t => t.MenuType == req.TypeID);

            var count = query.Count();
            var list = new List<CrmCarouselListItem>();

            if (count > 0)
            {
                var index = req.GetPageIndex();
                var size = req.GetPageSize();

                query = query.OrderBy(t => t.OrderAsc)
                    .Skip((index - 1) * size)
                    .Take(size);

                var rs = query.ToList();// error in this line
                
            }

**Comment by BBGONE** [comment]
I think that you can resolve this issue once and for all, if you would pass all column list through a hashset.

```c#
 public static HashSet<T> ToHashSet<T>(this IEnumerable<T> items, IEqualityComparer<T> equalityComparer)
        {
            return new HashSet<T>(items, equalityComparer);
        }
```

**Comment by ajcvickers** [comment]
@smitpatel to check for duplicate.

**Comment by smitpatel** [comment]
Fixed via https://github.com/aspnet/EntityFrameworkCore/pull/11725 in 2.2.0-preview1 release

**Comment by ajcvickers** [comment]
@BBGONE @duoanfen If you are still using RowNumberForPaging, could you please comment on issue #13959 and let us know why?

**Comment by GilbertoShimokawaFalcao** [comment]
Same problem 2022
