### ISSUE TITLE
CI: cleanup test databases automatically

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFrameworkCore#13925]
The CI machines we using are not necessarily single-use. The tests currently leave behind lots of LocalDB databases in the USERPROFILE. This can cause test failures on subsequent builds of CI. 

For example: https://dev.azure.com/dnceng/internal/_build/results?buildId=41727&view=logs

> System.Data.SqlClient.SqlException : Cannot create file 'C:\Users\dlab14\CreateTest.mdf' because it already exists. Change the file path or the file name, and retry the operation.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.

I tried adding an additional build step which executed tools/CleanMSSQLLocalDB.cmd script before and after tests, but this failed with "sqlcmd not found."

**Comment by ajcvickers** [comment]
@smitpatel @bricelam Any ideas here?

**Comment by bricelam** [comment]
Is anything calling `sqllocaldb d`(elete)? It's unusual that the files exists but the databases don't...

**Comment by bricelam** [comment]
Might be a good opportunity use a different localdb instance and put all the database files under the `bin` folder instead.

**Comment by ErikEJ** [comment]
Install sqlcmd ? https://www.microsoft.com/en-us/download/details.aspx?id=53591

**Comment by ajcvickers** [comment]
@bricelam and @AndriySvyryd will look into how we manage our databases on the new C.I. machines.

**Comment by ajcvickers** [comment]
Note that we don't need to continue using localdb if using some other SQL Server edition would be better.

**Comment by bricelam** [comment]
Fixed by #14522

**Comment by bricelam** [comment]
See also #15122
