### ISSUE TITLE
Finish merging Microsoft.Data.Sqlite

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#13958]
- [x] Create issue templates
  - Bug in Entity Framework Core
  - Bug in Microsoft.Data.Sqlite
  - Feature request
- [x] Clean up samples directory
  - EFCore and Microsoft.Data.Sqlite subdirectories
  - Link to samples in the docs repo
- [x] Update README
  - Highlight both products
  - Link to release planning process #18766
- [ ] Combine Resources.tt files
- [ ] Combine *.ruleset files

Other cleanup:

- [x] Move CONTRIBUTING to .github directory
- [x] Link to [Getting and Building the Code](https://github.com/aspnet/EntityFrameworkCore/wiki/getting-and-building-the-code) from CONTRIBUTING
- [x] Add SUPPORT

**Comment by ajcvickers** [comment]
See also #15821
