### ISSUE TITLE
Static method calls are generated incorrectly in code literal generation

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#13985]
The following type mapping literal code generation method:

```c#
public override Expression GenerateCodeLiteral(object value)
    => Expression.Call(typeof(NpgsqlNodaTimeUtils).GetMethod(nameof(NpgsqlNodaTimeUtils.InstantFromUnixTimeNanoseconds), new[] { typeof(BigInteger) }), ...);
```

Currently generates C# code calling `NodaTime.Instant.InstantFromUnixTimeNanoseconds()` - the call is on the wrong class (which should be `NpgsqlNodaTimeUtils`). The bug is here: https://github.com/aspnet/EntityFrameworkCore/blob/79bf0063bec879ba7f859e5fafbdf9a82b542a91/src/EFCore.Design/Design/Internal/CSharpHelper.cs#L767.

I'll be submitting a PR for this soon.

Originally raised in https://github.com/aspnet/EntityFrameworkCore/pull/13911#issuecomment-439844426.

**Comment by ajcvickers** [comment]
Triage: we will bring this to shiproom for 2.2 patch.
