### ISSUE TITLE
Inheritance: Generated database model contains duplicate base properties 

### ISSUE THREAD

**Issue by MaStr11** [aspnet/EntityFrameworkCore#13998]
### Steps to reproduce

I have a class hierarchy with three inheritance levels:
```CS
    public abstract class EditorOptionsBase
    {
        public EditorType EditorType { get; private set; }
        public bool ReadOnly { get; set; } = false;
    }

    public abstract class EditorOptionsText : EditorOptionsBase
    {
        public string Mask { get; set; }
    }

    public class EditorOptionsTextBox : EditorOptionsText
    {
    }

    public class EditorOptionsTextArea : EditorOptionsText
    {
        public int? MaxLength { get; set; }
    }

    public class EditorOptionsNumberBox : EditorOptionsText
    {
        public string Format { get; set; }
    }

    public class EditorOptionsCalendar : EditorOptionsBase
    {
    }
```

The model is configured like this

```CS
            var editorOptionsBase = modelBuilder.Entity<EditorOptionsBase>();
            editorOptionsBase.HasDiscriminator<EditorType>(nameof(EditorType)).
                HasValue<EditorOptionsNumberBox>(EditorType.dxNumberBox).
                HasValue<EditorOptionsTextBox>(EditorType.dxTextBox).
                HasValue<EditorOptionsTextArea>(EditorType.dxTextArea).
                HasValue<EditorOptionsCalendar>(EditorType.dxCalendar);
```

**Expected:**
There is only one *Mask* property created in the table:

`Mask = table.Column<string>(nullable: true),`

**Actual:**
Three properties are created:

```CS
Mask = table.Column<string>(nullable: true),
EditorOptionsTextArea_Mask = table.Column<string>(nullable: true),
EditorOptionsTextBox_Mask = table.Column<string>(nullable: true),
```

A complete sample project can be found [here](https://github.com/MaStr11/Reproduce-EF-Core-duplicate-columns-problem).

**Remark**
I was able to configure the model to do the right mapping like so:

`modelBuilder.Entity<EditorOptionsTextBox>().Property(eotb => eotb.Mask).HasColumnName(nameof(EditorOptionsText.Mask));`

But this doesn't scale because it needs to be repeated for each concrete type.

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 x64
IDE: Visual Studio 2017 15.9.1

**Comment by ajcvickers** [comment]
Note for triage: If `Mask` is on the base type, then we get only one column. When it's on a middle type of the hierarchy, it seems like any derived types from this middle type should also only get one column.

@MaStr11 A slightly better workaround is to bulk-update the model at the end of `OnModelCreating`. Something like:
```C#
foreach (var entityType in modelBuilder.Model.GetEntityTypes()
    .Where(e => typeof(EditorOptionsText).IsAssignableFrom(e.ClrType)))
{
    entityType
        .FindProperty(nameof(EditorOptionsText.Mask))
        .Relational()
        .ColumnName = nameof(EditorOptionsText.Mask);
}
```

**Comment by ajcvickers** [comment]
Note from triage: EditorOptionsText  is not mapped.

**Comment by AndriySvyryd** [comment]
Related to https://github.com/aspnet/EntityFrameworkCore/issues/12963
