### ISSUE TITLE
Empty C# array literals are generated incorrectly

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#14006]
The code which generates C# array literals omits the element type name, which results in an incorrect expression when the array is empty:

https://github.com/aspnet/EntityFrameworkCore/blob/85a45002e26827cbd4c5f246ba46fcc69943326f/src/EFCore.Design/Design/Internal/CSharpHelper.cs#L524

Originally raised in https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/720

/cc @bricelam

**Comment by ajcvickers** [comment]
@roji What's your impression of the customer impact here? Will many Npgsql users hit it? (Trying to decide whether it should be patched.)

**Comment by roji** [comment]
Database array usage isn't extremely wide-spread, although it's not nothing either. There's a pretty easy workaround - manually edit the generated migration file and add the missing type. On the other hand I expect the fix to be pretty low-risk...

**Comment by ajcvickers** [comment]
@roji Thanks. Putting it in 3.0 for now, but let us know if more people report hitting it--we could still patch at a later date.
