### ISSUE TITLE
EF Diagnostics page fails in Chrome when clicking "Apply Migrations" after File -> New with Identity Auth

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/EntityFrameworkCore#14015]
Reproduced this with 2.2.0 RTM bits, VS 2017 15.9.2, and Chrome 70.0.3538.110 (Official Build) (64-bit). See output of `dotnet --info` below.

## Reproduction Steps
1. In VS, create an app using the "ASP.NET Core Web Application" template, targeting .NET Core, using ASP.NET Core 2.2, and using Individual User Accounts:
   ![image](https://user-images.githubusercontent.com/249088/49046663-b5efb800-f189-11e8-92bb-7d043315e24f.png)
1. Launch it without debugging (Ctrl+F5) in Chrome
1. Once the home page appears, open the Chrome Dev Console (F12)
1. Click the "Accept" link in the cookie/privacy policy alert
1. Click the "Register" link in the main nav bar
1. Enter an email address and compliant password to try and register a new user and click the "Register" button
1. The EF diagnostics page will be displayed as the database doesn't exist yet (this is expected)
1. Click the "Apply Migrations" button

## Expected Results
The migration is applied successfully and the page instructs the user to try refreshing the page to retry the previous operation, without any JS errors in the console.

## Actual Results
Two JS errors are printed in the console, along with a third error from the XHR POST request. Next to the "Apply Migrations" button, an error message is printed: "An error occurred applying migrations, try applying them from the command line".

Note the migrations were actually successfully applied, and refreshing the page results in the user being successfully registered and navigated back to the home page.

Does not seem to reproduce in Edge.

![image](https://user-images.githubusercontent.com/249088/49046978-d2402480-f18a-11e8-94e5-4e8292789efb.png)

@divega 

## Output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100
 Commit:    51868761f2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by javiercn** [comment]
@ajcvickers https://github.com/aspnet/Diagnostics/pull/530

**Comment by javiercn** [comment]
Actually https://github.com/aspnet/AspNetCore/pull/4271

**Comment by ajcvickers** [comment]
@HaoK Can you take over investigation of this? It's an issue with EF and the database error page, but you have more experience of working in this part of the stack than anyone on the EF team does. We wanted to get the fix in 2.2.1, which is tomorrow, but the important thing is to get it right, so if it end up in 2.2.2, then so be it. Sorry to yank you around like this!

**Comment by HaoK** [comment]
No prob I'll take a look

**Comment by Tratcher** [comment]
We have a repro with ANCM in-proc where 204 and 304 responses (which aren't allowed to have bodies) cause this error.

**Comment by pakrym** [comment]
And it reproes only in hrome, edge and Firefox work fine.

**Comment by jkotalik** [comment]
Fixed by https://github.com/aspnet/AspNetCore/issues/4398. Will be in 2.2.1
