### ISSUE TITLE
Fix or suppress xUnit.net analyzer errors

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#14106]
We have a lot of errors we should look into. We currently [opt out](https://github.com/aspnet/EntityFrameworkCore/blob/v3.0.0-preview.18572.1/test/Directory.Build.props#L18-L21) of using the analyzer.

**Comment by roji** [comment]
Do you mind if I poach this @bricelam? It seems like it could have considerable psychological therapeutic value...

**Comment by smitpatel** [comment]
I have already half work done branch. But if you insist....

**Comment by roji** [comment]
Don't want to step on anyone's toes :) If you have some work already done do you want to merge that?

**Comment by roji** [comment]
Seems I was too late :) Did we file issues for the 3 xunit analyzer bugs?

**Comment by smitpatel** [comment]
I did not file issues. I may some day. If you want you can go ahead and file issues.
