### ISSUE TITLE
What should we do with the Oracle sample?

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#14119]
My concern is that the cost of keeping the Oracle sample up-to-date with every change during the 3.0 milestone is not worth the value it would provide. Should we remove the sample from `master` for now, and (if needed) bring it back up-to-date later?

**Comment by ajcvickers** [comment]
Triage: Let's remove it for now and bring it back before 3.0 RTM to validate 3.0 changes.
