### ISSUE TITLE
[metadata] MigrationBuilder.cs has a typo

### ISSUE THREAD

**Issue by Stefanwullems** [aspnet/EntityFrameworkCore#14132]
In the parameter description for the parameter `table` of MigrationBuilder.DeleteData() it says `The table into which the data will be inserted.` which should look more like `The table from which the data will be deleted.`
 version 2.1.0

**Comment by ajcvickers** [comment]
@Stefanwullems Would you consider submitting a PR--it's super easy. Just go to https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Migrations/MigrationBuilder.cs, click on "Edit this file", then follow instructions to submit the PR.

**Comment by Stefanwullems** [comment]
Okay I didn't know. Will do.

**Comment by ajcvickers** [comment]
Thanks!
