### ISSUE TITLE
RevEng: Fixed Length facet incorrect in ScaffoldingTypeMapper

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#14160]
https://github.com/aspnet/EntityFrameworkCore/blob/8e7402701ea1416b7fe55e1863ae65b3147c02c7/src/EFCore.Design/Scaffolding/Internal/ScaffoldingTypeMapper.cs#L117-L125

Above code is supposed to pass in default value for Fixed Length and compare type mapping to figure out if the value is same as default (hence no need to scaffold). Default for Fixed length is false and _not_ true.

**Comment by ajcvickers** [comment]
Presumably we are missing tests for this. Is this because of the general test debt for rev-eng, or was this just something we missed? /cc @bricelam

**Comment by smitpatel** [comment]
We do have tests (I am trying to understand how it is working in SqlServer)
https://github.com/aspnet/EntityFrameworkCore/blob/5d889997ca6496d4aa3e4030bdb02ba351856d47/test/EFCore.Design.Tests/Scaffolding/Internal/ScaffoldingTypeMapperSqlServerTest.cs#L277-L308

**Comment by ajcvickers** [comment]
@smitpatel Looks wrong to me.

**Comment by roji** [comment]
No problem - go ahead and take it, was happy to help uncover it.

**Comment by smitpatel** [comment]
Tests were there, they just did not verify if `IsFixedLength` facet was set correctly.

**Comment by smitpatel** [comment]
@roji - This is going to 3.0 since it's design time change only. User can modify the generated code to fix the issue. (unless bosses decide otherwise)
As for passed value, default is false. The function takes null argument but when you pass in null, it will go back to default values. Following lines in SqlServer shows that. So unless you pass false for unicode, it will be set as unicode.
https://github.com/aspnet/EntityFrameworkCore/blob/af13b52bfc390346551926ca56d5b0703c1eb0e7/src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs#L296-L297

I will update PR to pass in null since it would default to whatever provider default is eventually. I suppose the reason for passing true/false rather null in past may have been parameter not being nullable at some point.
