### ISSUE TITLE
Self referencing regression bug in 2.2 - Unable to determine the relationship represented by navigation property

### ISSUE THREAD

**Issue by MaklaCof** [aspnet/EntityFrameworkCore#14213]
When I run   
```
context.Database.Migrate();
```
or
```
dotnet ef migrations add "UpgradeToNetCore2.2" -c MyContext -o "Migrations"
```
in .`NET Core 2.2` with `EF Core 2.2`, I get exception:

> Unable to determine the relationship represented by navigation property 'EntityCountry.Foreign1' of type 'EntityCountry'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

### Steps to reproduce
This only appears on Entity with self-referencing more then 2 fields.

This works:
```c#
public class EntityCountry
    {
        public string Title { get; set; }

        public int? Foreign1Id { get; set; }
        public EntityCountry Foreign1 { get; set; }


        public int? TestId { get; set; }
        public EntityCountry Test { get; set; }

        //public int? SomethingId { get; set; }
        //public EntityCountry Something { get; set; }

        //public int? HeyId { get; set; }
        //public EntityCountry Hey { get; set; }
    }
```
or this:
```c#
public class EntityCountry
    {
        public string Title { get; set; }

        //public int? Foreign1Id { get; set; }
        //public EntityCountry Foreign1 { get; set; }

        //public int? TestId { get; set; }
        //public EntityCountry Test { get; set; }

        public int? SomethingId { get; set; }
        public EntityCountry Something { get; set; }

        public int? HeyId { get; set; }
        public EntityCountry Hey { get; set; }
    }
```
or any combination (but only 2) but not this:
```c#
public class EntityCountry
    {
        public string Title { get; set; }

        public int? Foreign1Id { get; set; }
        public EntityCountry Foreign1 { get; set; }


        public int? TestId { get; set; }
        public EntityCountry Test { get; set; }

        public int? SomethingId { get; set; }
        public EntityCountry Something { get; set; }

        //public int? HeyId { get; set; }
        //public EntityCountry Hey { get; set; }
    }
```
or this:
```c#
public class EntityCountry
    {
        public string Title { get; set; }

        public int? Foreign1Id { get; set; }
        public EntityCountry Foreign1 { get; set; }


        //public int? TestId { get; set; }
        //public EntityCountry Test { get; set; }

        public int? SomethingId { get; set; }
        public EntityCountry Something { get; set; }

        public int? HeyId { get; set; }
        public EntityCountry Hey { get; set; }
    }
```
It works in `2.1`.

### Further technical details
EF Core version: `<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.0" />`
Database Provider: `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: `Windows 10`
IDE: `Visual Studio 2017 15.9.4`

**Comment by ajcvickers** [comment]
Note for triage. With two navigations/FK pairs, both 2.1 and 2.2 produce the same model:

```
Model: 
  EntityType: EntityCountry
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
      HeyId (Nullable<int>) FK Index 1 1 1 -1 1
      SomethingId (Nullable<int>) 2 2 -1 -1 -1
      Title (string) 3 3 -1 -1 -1
    Navigations: 
      Hey (<Hey>k__BackingField, EntityCountry) ToPrincipal EntityCountry Inverse: Something 0 -1 2 -1 -1
      Something (<Something>k__BackingField, EntityCountry) ToDependent EntityCountry Inverse: Hey 1 -1 3 -1 -1
    Keys: 
      Id PK
    Foreign keys: 
      EntityCountry {'HeyId'} -> EntityCountry {'Id'} Unique ToDependent: Something ToPrincipal: Hey
```

Note that one property is chosen as the FK, and the other navigation becomes the inverse.

In 2.1, with three navigation/FK pairs, none of the navigations/FKs are found, but there is no error:

```
Model: 
  EntityType: EntityCountry
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
      Foreign1Id (Nullable<int>) 1 1 -1 -1 -1
      HeyId (Nullable<int>) 2 2 -1 -1 -1
      SomethingId (Nullable<int>) 3 3 -1 -1 -1
      Title (string) 4 4 -1 -1 -1
    Keys: 
      Id PK
```

**Comment by ajcvickers** [comment]
Notes from triage: Clearly the model from 2.1 is wrong--all the navigations have just been ignored, which means they are all non-functional. Therefore, we don't want to go back to this. In 3.0, we should probably also throw for the two navigations case, since the FK choice is arbitrary--i.e. it's also ambiguous. We thought there was already an issues for this, but we couldn't find it, so using this issue.

**Comment by MaklaCof** [comment]
Hi @ajcvickers   
Is there any workaround. 3.0.0 will not be production ready for quite some time.

**Comment by ajcvickers** [comment]
@MaklaCof Yes, just [configure the relationships explicitly](https://docs.microsoft.com/en-us/ef/core/modeling/relationships). However, given that in 2.1 EF was ignoring all the navigation properties, it would probably good to actually see how these are actually being used in your application, since EF has not been fixing them up to act as navigation properties.
