### ISSUE TITLE
Out of date info

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#14282]
Who owns the text about EF here?

https://dotnetfoundation.org/projects?type=project&ps=10&pn=2

**Comment by ajcvickers** [comment]
@divega?

**Comment by ErikEJ** [comment]
I am working on a PR 😄 (It is Open Source!!)

**Comment by carloscds** [comment]
@ErikEJ I sent a PR yesterday fixing EF page: https://github.com/dotnet/foundation/blob/master/projects/entity-framework.md

**Comment by ErikEJ** [comment]
I also just submitted a PR https://github.com/dotnet/foundation/pull/128 - I will probably get latest and update based on your changes then

**Comment by ErikEJ** [comment]
@carloscds  "Entity Framework Core, for .NET Core" - not true, also runs on .NET Framework (and other .NET platforms)

**Comment by divega** [comment]
Comments made in @ErikEJ PR. I think I prefer to split it into two projects, or keep it the way it was with incremental improvements.

**Comment by ErikEJ** [comment]
I will adjust the existig text in the foundation repo
