### ISSUE TITLE
Refactor table creation in MigrationsSqlGenerator 

### ISSUE THREAD

**Issue by austindrenski** [aspnet/EntityFrameworkCore#14374]
## Background

I've [run into an issue](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/792#discussion_r246877703) while working on https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/792, wherein I have to duplicate (inline) the base method for table creation just to to inject a single keyword between `CREATE` and `TABLE`:

https://github.com/aspnet/EntityFrameworkCore/blob/83e1dc89a59d4bd7d178d75e556eea0c7eef1629/src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs#L573-L628

## Proposal

Would it be possible to refactor the generation of columns and constraints into separate virtual methods, such that the responsibility of `Generate(CreateTableOperation,...)` is reduced? 

The result might look something like this:

```c#
// existing method, refactored:
protected virtual void Generate(
    [NotNull] CreateTableOperation operation,
    [CanBeNull] IModel model,
    [NotNull] MigrationCommandListBuilder builder,
    bool terminate)
{
    Check.NotNull(operation, nameof(operation));
    Check.NotNull(builder, nameof(builder));

    builder
        .Append("CREATE TABLE ")
        .Append(Dependencies.SqlGenerationHelper.DelimitIdentifier(operation.Name, operation.Schema))
        .AppendLine(" (");

    using (builder.Indent())
    {
        GenerateCreateTableColumns(operation, model, builder);

        GenerateCreateTableConstraints(operation, model, builder);

        builder.AppendLine();
    }

    builder.Append(")");

    if (terminate)
    {
        builder.AppendLine(Dependencies.SqlGenerationHelper.StatementTerminator);
        EndStatement(builder);
    }
}

// proposed methods:
protected virtual void GenerateCreateTableConstraints(
    [NotNull] CreateTableOperation operation,
    [CanBeNull] IModel model,
    [NotNull] MigrationCommandListBuilder builder)
{
    Check.NotNull(operation, nameof(operation));
    Check.NotNull(builder, nameof(builder));

    GenerateCreateTablePrimaryKeyContstraint(operation, model, builder);
    GenerateCreateTableUniqueConstraints(operation, model, builder);
    GenerateCreateTableForeignKeys(operation, model, builder);
}

protected virtual void GenerateCreateTablePrimaryKeyContstraint(...) { ... }
protected virtual void GenerateCreateTableUniqueConstraints(...) { ... }
protected virtual void GenerateCreateTableForeignKeys(...) { ... }
```

If something like this makes sense, I can submit a PR with the proposed changes.

/cc @roji

**Comment by ajcvickers** [comment]
@austindrenski This sounds reasonable and is something we would certainly consider a PR for. Breaking changes should be minimized, but some level of breaking changes to providers in 3.0 is okay.

@bricelam I wasn't able to find a dupe.

**Comment by bricelam** [comment]
These methods typically aren't called by applications. What F# project are you writing that uses them?

But in a more general sense, yes! Please file issues to let us know where EF Core is awkward to use from F#.

**Comment by NinoFloris** [comment]
@bricelam It's me from https://github.com/bricelam/EFCore.FSharp/. Would not 3.0 be a good time to see if there are breaks we can make to allow better consumption from F#.

**Comment by bricelam** [comment]
Ah, you mean the code generation equivalents to these. These ones generate SQL. Have any proposals? Also, I think the F# (and VB) generations copied a bit too much of the C# code—the actual contract is fairly minimal leaving a lot of the implementation details up to the extensions.
