### ISSUE TITLE
Where condition is ignored when used EF.Property<object>

### ISSUE THREAD

**Issue by jirikanda** [aspnet/EntityFrameworkCore#14408]
When a query contains Where condition with EF.Property<object> than this condition is ignored.
This breaking change occures starting version 2.2.0. It works as expected in version 2.1.4.

### Steps to reproduce
```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp
{
	public class Blog
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}

	public class BlogDbContext : DbContext
	{
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			base.OnConfiguring(optionsBuilder);
			optionsBuilder.UseSqlServer("Data Source=(localdb)\\mssqllocaldb;Initial Catalog=ConsoleApp");
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);
			modelBuilder.Entity<Blog>();
		}
	}

	public static class Program
	{
		public static void Main(string[] args)
		{
			List<object> ids = new List<object> { 1, 2, 3 };
			using (var dbContext = new BlogDbContext())
			{
				dbContext.Database.Migrate();
				dbContext.Set<Blog>().Where(blog => ids.Contains(EF.Property<object>(blog, "Id"))).ToList();
			}
		}
	}
}
```

Install nuget packages:
* Microsoft.EntityFrameworkCore.Design (version 2.2.1)
* Microsoft.EntityFrameworkCore.SqlServer (version 2.2.1)
* Microsoft.EntityFrameworkCore.Tools (version 2.2.1)

Add a migration: 
* open Package Manager Console
* `add-migration Initial`

### Actual behavior
```sql
SELECT [blog].[Id], [blog].[Name]
FROM [Blog] AS [blog]
```

### Expected behavior
```sql
SELECT [blog].[Id], [blog].[Name]
FROM [Blog] AS [blog]
WHERE [blog].[Id] IN (1, 2, 3)
```

### Further technical details
EF Core version: 2.2.0, 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by jirikanda** [comment]
### Workaround
Change `EF.Property<object>` to `EF.Property<real_type>`.
```c#
dbContext.Set<Blog>().Where(blog => ids.Contains(EF.Property<int>(blog, "Id"))).ToList();
```

**Comment by smitpatel** [comment]
It works same in 2.1.4 also
We changed the behavior from 2.0 in https://github.com/aspnet/EntityFrameworkCore/pull/10092

The reason for that being, we had to make sure the types are matching for list and contains Item both. But in this case, the translated type is int (since it would be sql column) but type of list is object hence failed to translate.

**Comment by jirikanda** [comment]
Thanks for the reply.
I checked it again and I must agree - It really works same in 2.1.4.
