### ISSUE TITLE
Support for CHECK constraints

### ISSUE THREAD

**Issue by Mikilll94** [aspnet/EntityFrameworkCore#14425]
Are there any plans to add support for CHECK constraints in EFCore. It could be useful when you have a column "Gender" and you want to restrict possible values to "Male" and "Female".

Also defining an enum type column type should automatically create a CHECK constraint in database.

### Further technical details
EF Core version: ??
Database Provider: ??
Operating system: Windows
IDE: (e.g. Visual Studio 2017 15.9.4)

**Comment by bricelam** [comment]
Also #2594 and #2595

**Comment by Muppets** [comment]
[I've taken a stab at this](https://github.com/aspnet/EntityFrameworkCore/pull/14673). Probably a bit out of my depth but learnt loads along the way. I've not looked at #2594 or #2595 while doing this, didn't feel I had a good grasp of the requirements there.
