### ISSUE TITLE
Support for IAsyncDisposable on EF Core

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#14427]
Alongside IAsyncEnumerable, C#8/.NET Core 3.0 brings support for disposing resources asynchronously. I see two main points where this can have an impact on EF Core:

1. IAsyncEnumerator instances are IAsyncDisposable
2. DbContext could be made IAsyncDisposable
 
This would make the most sense if async is supported end-to-end, e.g. from DI support (https://github.com/aspnet/Extensions/issues/426) to the operations that often need to execute against underlying data providers on dispose (see https://github.com/aspnet/EntityFrameworkCore/issues/9015 about adding async transaction operations on EF Core, and https://github.com/dotnet/corefx/issues/10975 on the missing async operations on the ADO.NET provider model).

The minimum bar for this is that IAsyncDisposable support will need to happen as part of https://github.com/aspnet/EntityFrameworkCore/issues/12047, but it could still call blocking operations as long as non-blocking versions aren't available.

**Comment by ajcvickers** [comment]
Triage: if there are ADO.NET types that are also IAsyncDisposable, then we should do this in EF to dispose of the ADO.NET objects asynchronously.

**Comment by pakrym** [comment]
In addition to the points above DI instances and DI scopes should be try-cast to IAsyncDisposable and disposed asynchronously if possible.

See https://github.com/aspnet/AspNetCore/pull/7343 and https://github.com/aspnet/AspNetCore/pull/7091

**Comment by ajcvickers** [comment]
@roji Poaching this.

**Comment by roji** [comment]
No problem :)

**Comment by roji** [comment]
Note that once IAsyncDisposable for ADO.NET goes into .NET Standard (https://github.com/dotnet/standard/pull/1283) we'll have to also make those changes (can do as part of #15917, added comment there).

**Comment by ajcvickers** [comment]
@roji Shouldn't be needed for functionality since we dynamically call `AsyncDispose` if the runtime type implements it. However, we should still do it to cleanup the runtime checks.
