### ISSUE TITLE
Ensure TypeMapping is always present on IProperty

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#14433]
For #13192, we need type mapping for every scalar in SQL tree so that we can propagate appropriately and apply inference. The basic building block for it, is columns which corresponds to IProperty. It would be useful to have TypeMapping always present on IProperty.

**Comment by AndriySvyryd** [comment]
Can be implemented with default value conventions https://github.com/aspnet/EntityFrameworkCore/issues/9329
