### ISSUE TITLE
Cleanup databases on C.I. runs

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#14444]
Due to recent bad runs reported here:
* https://github.com/aspnet/AspNetCore-Internal/issues/1641
* https://github.com/aspnet/AspNetCore-Internal/issues/1660
* https://github.com/aspnet/AspNetCore-Internal/issues/1661
* https://github.com/aspnet/AspNetCore-Internal/issues/1662
* https://github.com/aspnet/AspNetCore-Internal/issues/1663
* https://github.com/aspnet/AspNetCore-Internal/issues/1664
* https://github.com/aspnet/AspNetCore-Internal/issues/1681

**Comment by bricelam** [comment]
Resolved by #14522
