### ISSUE TITLE
NotImplementedExceptions in ExpressionEqualityComparer

### ISSUE THREAD

**Issue by bdebaere** [aspnet/EntityFrameworkCore#14509]
There are two lines of code that currently keep me from running a stock version of EF Core. The line at https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore/Query/Internal/ExpressionEqualityComparer.cs#L288 and the line at https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore/Query/Internal/ExpressionEqualityComparer.cs#L430. Because I'm providing support for JSON database columns I have to handle the IndexExpression. I have adjusted DbContext where necessary and injected my own IQueryModelGenerator to handle IndexExpressions. This would be enough if it weren't for the NotImplementedExceptions that are thrown in the lines I linked above. Is there a way around this? Could the ExpressionEqualityComparer be adjusted to simply not do a comparison and not add anything to the cache (because as I understand it, that is its main purpose)? I'd very much like to run a stock version of EF Core instead of the custom one I have now.

### Further technical details
EF Core version: f9a4bbfe20a3abfc394d8d87fa0389652f03466c
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: Visual Studio 2017 15.4

**Comment by smitpatel** [comment]
Make `IndexExpression` - ExpressionType.Extension and override GetHashCode & Equals in your custom expression.

**Comment by bdebaere** [comment]
@smitpatel This is new for me, would you be able to provide an example?

**Comment by tuespetre** [comment]
@smitpatel `IndexExpression` ===> `foo["bar"]`, `ExpressionType.Index`
