### ISSUE TITLE
Not flowing dependency updates for Microsoft.NETCore.App

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFrameworkCore#14501]
This repo is only flowing dependency updates for packages, but not for the actually .NET Core runtime (Microsoft.NETCore.App). That means bot-generated PRs such as https://github.com/aspnet/EntityFrameworkCore/pull/14500 are not actually testing EFCore with the latest .NET Core.

The repo is currently using the runtime version that is baked into the .NET Core SDK. The SDK version is not automatically updated by Arcade, and even if it were, it would often be at least 1 step behind the latest runtime version which will be inserted into the SDK.

@bricelam @ajcvickers - was this an intentional change when converting this repo to Arcade?

**Comment by bricelam** [comment]
Not intentional, but also ...meh.

lol, we’ll discuss. I’m certainly not against doing it.

**Comment by ajcvickers** [comment]
And also turn by on warnings as errors.

**Comment by bricelam** [comment]
I'm reverting this in https://github.com/aspnet/EntityFrameworkCore/pull/14643#issuecomment-469463846. It made things way to complicated.

**Comment by natemcmaster** [comment]
Re-opening. This is now blocking dependency flow for aspnetcore. See https://github.com/aspnet/EntityFrameworkCore/pull/15680
