### ISSUE TITLE
EF Core 2.2.1 update from 2.1, undeclared scalar variable name.

### ISSUE THREAD

**Issue by wasabii** [aspnet/EntityFrameworkCore#14550]
System.Data.SqlClient.SqlException: The variable name '@__courtCase_Court_Organization_0_Id' has already been declared. Variable names must be unique within a query batch or stored procedure.
Must declare the scalar variable "@__efmJudge_EfmId_3".

This seems to happen in a block of code that looks like this:

```
            var ca = jcmsDb.CerberusUsers
                .Where(i => i.Organization == courtCase.Court.Organization)
                .Distinct()
                .Where(i => ut.Contains(i.UserType))
                .Where(i => i.Organization == courtCase.Court.Organization)
                .OrderBy(i => i.UniqueId)
                .Where(i => !exclude.Contains(i));
```

EF Core 2.1 worked fine. Upon upgrading to 2.2, this began breaking. Yes, that's clearly a dumb query. Upon removing the duplicate Where expression, it works fine. Still, a regression, and a bug, somewhere.

**Comment by vassilvk** [comment]
The same issue can be observed in valid cases where the same variable is used multiple times in a `Where` call.

For example:

```c#
...
.Where(i => i.Organization == courtCase.Court.Organization || i.OtherOrganization == courtCase.Court.Organization)
...

```
