### ISSUE TITLE
Invalid configuration when KeyAttribute is overriden by explicit configuration

### ISSUE THREAD

**Issue by iplitt** [aspnet/EntityFrameworkCore#14618]
### Expected behavior
When you use .lnclude(x => x.RelatedEntities) in a query the related records should be returned as an attached list of related entities.

### Description of bug
Related entities are not returned by version 2.2.1 of this NuGet, but they are returned by the older version, 2.1.2.

### Steps to reproduce
I've created a repo in GitHub to demonstrate the bug: https://github.com/iplitt/ef-core-bug-demo

There are two test projects, Data212UnitTests and DataUnitTests, that execute the same code, one using version 2.1.2 EF Core NuGets and the other using the most recent NuGet versions (2.2.1). The one using the 2.1.2 NuGets pass the two tests in the project; the other one fails.

### Further technical details
EF Core version: (found in project.csproj or packages.config)

For Data212UnitTests:
    Microsoft.EntityFrameworkCore Version="2.1.2"
    Microsoft.EntityFrameworkCore.Relational Version="2.1.2"
    Microsoft.EntityFrameworkCore.InMemory Version="2.1.2"

For DataUnitTests:
    Microsoft.EntityFrameworkCore Version="2.2.1"
    Microsoft.EntityFrameworkCore.Relational Version="2.2.1"
    Microsoft.EntityFrameworkCore.InMemory Version="2.2.1"

Operating system: Windows 10
IDE: Visual Studio Enterprise 2017 15.9.2

**Comment by ajcvickers** [comment]
@iplitt This appears to be a bug in model building when the `[Key]` annotation is used and then later overridden by fluent API. As a workaround, remove the `[Key]` annotations from the join table:
```C#
public class CarDriver
{
    [Column(Order = 1), MaxLength(14)]
    public string CarId { get; set; }
    [Column(Order = 2), MaxLength(14)]
    public string DriverId { get; set; }
}
```

Notes for triage: Model with `KeyAttribute`:
```
Model: 
  EntityType: Car
    Properties: 
      CarId (string) Required PK AfterSave:Throw ValueGenerated.OnAdd MaxLength14 0 0 0 -1 0
    Navigations: 
      CarDrivers (<CarDrivers>k__BackingField, List<CarDriver>) Collection ToDependent CarDriver 0 -1 1 -1 -1
    Keys: 
      CarId PK
  EntityType: CarDriver
    Properties: 
      CarId (string) Required PK AfterSave:Throw MaxLength14 0 0 0 -1 -1
      DriverId (string) Required PK FK Index AfterSave:Throw MaxLength14 1 1 1 -1 0
>>>      CarId1 (no field, string) Shadow FK Index 2 2 2 0 1
    Keys: 
      CarId, DriverId PK
    Foreign keys: 
      CarDriver {'CarId1'} -> Car {'CarId'} ToDependent: CarDrivers
      CarDriver {'DriverId'} -> Driver {'DriverId'} ToDependent: CarDrivers
  EntityType: Driver
    Properties: 
      DriverId (string) Required PK AfterSave:Throw ValueGenerated.OnAdd MaxLength14 0 0 0 -1 0
    Navigations: 
      CarDrivers (<CarDrivers>k__BackingField, List<CarDriver>) Collection ToDependent CarDriver 0 -1 1 -1 -1
    Keys: 
      DriverId PK
```
Without:
```C#
Model: 
  EntityType: Car
    Properties: 
      CarId (string) Required PK AfterSave:Throw ValueGenerated.OnAdd MaxLength14 0 0 0 -1 0
    Navigations: 
      CarDrivers (<CarDrivers>k__BackingField, List<CarDriver>) Collection ToDependent CarDriver 0 -1 1 -1 -1
    Keys: 
      CarId PK
  EntityType: CarDriver
    Properties: 
      CarId (string) Required PK FK AfterSave:Throw MaxLength14 0 0 0 -1 0
      DriverId (string) Required PK FK Index AfterSave:Throw MaxLength14 1 1 1 -1 1
    Keys: 
      CarId, DriverId PK
    Foreign keys: 
      CarDriver {'CarId'} -> Car {'CarId'} ToDependent: CarDrivers
      CarDriver {'DriverId'} -> Driver {'DriverId'} ToDependent: CarDrivers
  EntityType: Driver
    Properties: 
      DriverId (string) Required PK AfterSave:Throw ValueGenerated.OnAdd MaxLength14 0 0 0 -1 0
    Navigations: 
      CarDrivers (<CarDrivers>k__BackingField, List<CarDriver>) Collection ToDependent CarDriver 0 -1 1 -1 -1
    Keys: 
      DriverId PK
```
