### ISSUE TITLE
Auto-Increment IDs Are Reset When Using In Memory Database Provider And UseModel()

### ISSUE THREAD

**Issue by alecrodden** [aspnet/EntityFrameworkCore#14646]
An error with a duplicate generated key can occur when using the combination of `UseInMemoryDatabase` and `UseModel` with `DbContextOptionsBuilder`.

I used a single `InMemoryDatabaseRoot` instance with two `DbContext` instances. Because of the shared `InMemoryDatabaseRoot` instance, I would expect database continuity between the two `DbContext` instances. Meaning, a new entity added and saved in the first `DbContext` scope would get ID 1 in the single in-memory database, and a new entity added and saved in the second `DbContext` scope would get ID 2. Instead, both entities are generated ID 1, but get inserted into the same in-memory database, so the key collision occurs.

Looking into it, it looks like the incrementing IDs are managed by `ValueGenerator` instances, and those are cached by `Property` and `EntityType`, which are objects that are part of how Entity Framework represents the entity model. Neither `Property` nor `EntityType` override `GetHashCode`, so when they are used as the parts of the cache key for `ValueGenerator` instances, it's their object identities that make up the key, rather than their values. If you rebuild the model every time you create a new `DbContext` instance (via `UseModel`), new `Property` and `EntityType` instances will be created (new object identities). This results in the cached `ValueGenerator` not being used (cache miss because of unequal cache keys), and so a new `ValueGenerator` instance gets created starting over again at ID 1.

The exception doesn't occur when `DbContext` is extended and `OnModelCreating` is overridden (the style favored by the documentation and most code examples). It would seem that the model built via `OnModelCreating` is cached the first time it is built, presumably to avoid the overhead of rebuilding the model every time the class extending `DbContext` is instantiated. This has the beneficial side effect of allowing the identity of a model object to be used as a unique key to what the model object represents. For example, as long as you keep reusing the same instance of `EntityType` for a given type of entity, the identity of that single object can be used instead of the CLR type represented by the `EntityType`.

I understand that instantiating `ModelBuilder` directly and passing the result of `FinalizeModel()` to `UseModel()` is unusual, but it seems like that is a valid way of doing things. At least, it's not clear that doing it that way would result in different behavior than overriding `OnModelCreating`. I'm not sure if internal logic should be relying on something that only happens when a specific API is used, even if that is the primary API.

```
Exception message: An item with the same key has already been added. Key: 1
Stack trace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key) in E:\A\_work\62\s\src\mscorlib\src\System\ThrowHelper.cs:line 128
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) in E:\A\_work\62\s\src\mscorlib\shared\System\Collections\Generic\Dictionary.cs:line 664
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value) in E:\A\_work\62\s\src\mscorlib\shared\System\Collections\Generic\Dictionary.cs:line 232
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Create(IUpdateEntry entry) in /_/src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs:line 60
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IReadOnlyList`1 entries, IDiagnosticsLogger`1 updateLogger) in /_/src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs:line 172
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChanges(IReadOnlyList`1 entries) in /_/src/EFCore.InMemory/Storage/Internal/InMemoryDatabase.cs:line 60
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave) in /_/src/EFCore/ChangeTracking/Internal/StateManager.cs:line 961
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) in /_/src/EFCore/ChangeTracking/Internal/StateManager.cs:line 782
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) in /_/src/EFCore/DbContext.cs:line 447
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges() in /_/src/EFCore/DbContext.cs:line 412
   at Example.Program.Main(String[] args) in C:\Code\Example\Example\Program.cs:line 25
```

### Steps to reproduce
This throws an exception.

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.InMemory.Metadata.Conventions.Internal;
using Microsoft.EntityFrameworkCore.Storage;

namespace Example
{
    class Program
    {
        class ExampleEntity
        {
            public int Id { get; set; }
        }

        static void Main(string[] args)
        {
            var inMemoryDatabaseRoot = new InMemoryDatabaseRoot();
            using (var dbContext1 = CreateDbContext(inMemoryDatabaseRoot))
            {
                dbContext1.Add(new ExampleEntity());
                dbContext1.SaveChanges();
            }
            using (var dbContext2 = CreateDbContext(inMemoryDatabaseRoot))
            {
                dbContext2.Add(new ExampleEntity());
                dbContext2.SaveChanges(); // Exception is thrown here.
            }
        }

        static DbContext CreateDbContext(InMemoryDatabaseRoot inMemoryDatabaseRoot)
        {
            var modelBuilder = new ModelBuilder(InMemoryConventionSetBuilder.Build());
            modelBuilder.Entity<ExampleEntity>(etb =>
            {
                etb.Property(e => e.Id);
                etb.HasKey(e => e.Id);
            });

            var options = new DbContextOptionsBuilder()
                .UseInMemoryDatabase("InMemoryDatabase", inMemoryDatabaseRoot)
                .UseModel(modelBuilder.FinalizeModel())
                .Options;
            return new DbContext(options);
        }
    }
}
```
This doesn't throw an exception.
```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;

namespace Example
{
    class Program
    {
        class ExampleEntity
        {
            public int Id { get; set; }
        }

        class ExampleDbContext : DbContext
        {
            private readonly InMemoryDatabaseRoot _inMemoryDatabaseRoot;

            public ExampleDbContext(InMemoryDatabaseRoot inMemoryDatabaseRoot)
            {
                _inMemoryDatabaseRoot = inMemoryDatabaseRoot;
            }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseInMemoryDatabase("Database", _inMemoryDatabaseRoot);
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<ExampleEntity>(etb =>
                {
                    etb.Property(e => e.Id);
                    etb.HasKey(e => e.Id);
                });
            }
        }

        static void Main(string[] args)
        {
            var inMemoryDatabaseRoot = new InMemoryDatabaseRoot();
            using (var dbContext1 = new ExampleDbContext(inMemoryDatabaseRoot))
            {
                dbContext1.Add(new ExampleEntity());
                dbContext1.SaveChanges();
            }
            using (var dbContext2 = new ExampleDbContext(inMemoryDatabaseRoot))
            {
                dbContext2.Add(new ExampleEntity());
                dbContext2.SaveChanges();
            }
        }
    }
}
```
### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10.0.17763 Build 17763
IDE: Visual Studio Community 2017 15.9.4

**Comment by ajcvickers** [comment]
@alecrodden This would get fixed by implementation of #6872, which would associated the generated value state with the database. Not marking this as a dupe so we can verify it is fixed after #6872.
