### ISSUE TITLE
DefaultQuerySqlGenerator.VisitPropertyParameter bug allows duplicate parameters

### ISSUE THREAD

**Issue by MaxG117** [aspnet/EntityFrameworkCore#14645]
`DefaultQuerySqlGenerator.VisitPropertyParameter` attempts to avoid duplicates by comparing `InvariantName` with propertyParameterExpression.**PropertyParameterName**, but adds new parameters using propertyParameterExpression.**Name** for `InvariantName`:
```c#
            if (_relationalCommandBuilder.ParameterBuilder.Parameters
                .All(p => p.InvariantName != propertyParameterExpression.PropertyParameterName))
            {
                _relationalCommandBuilder.AddPropertyParameter(
                    propertyParameterExpression.Name,
            ...
```
You can reproduce by making a slight modification to the Where clause of the SimpleQueryTestBase.Where_poco_closure() test case:
```c#
            var customer = new Customer
            {
                CustomerID = "ALFKI",
            };

            await AssertQuery<Customer>(
                isAsync,
                cs => cs
                    .Where(c => c.Equals(customer) && c.Equals(customer))
                    .Select(c => c.CustomerID));
```
Even though the modification is pointless, it's valid syntax and it generates valid CommandText. But when executed against SqlServer EFCore provider, this test throws the following SqlException:
```
System.Data.SqlClient.SqlException : The variable name '@__customer_0_CustomerID' has already been declared. Variable names must be unique within a query batch or stored procedure.)
```

**Comment by MaxG117** [comment]
I think there's a bigger problem here in that the InvariantName is used as a Key to the parameterValues dictionary in `RelationalCommand.CreateCommand`, which uses the Name, not the PropertyParameterName. The LINQ to check for duplicates would have to look at the Name, but the Name is not part of the IRelationalParameter Interface.

**Comment by roji** [comment]
Note: moved this to the 3.0.0 milestone.
