### ISSUE TITLE
"Getting and building the Code" build /t:Compile doesn't work on master

### ISSUE THREAD

**Issue by benmccallum** [aspnet/EntityFrameworkCore#14697]
Getting started wiki page steps don't seem to work on master branch.
https://github.com/aspnet/EntityFrameworkCore/wiki/getting-and-building-the-code

I can't get the `.\build /t:Compile` cmd to work on master, error is that the target doesn't exist.

Have no problems on release/2.2 branch. 

Would be great to get this doc updated as I'd like to look at contributing something and without this working it seems all the projects in the sln fail to load.

### Steps to reproduce
* Git clone
* master should be checked out branch
* Run `.\build /t:Compile` in PowerShell

### Further technical details
EF Core version: n/a
Database Provider: n/a
Operating system: Windows 10
IDE: Visual Studio 2017 15.latest, Visual Studio 2019 Preview latest

**Comment by smitpatel** [comment]
I agree that the wiki page is outdated. We will update it.
In the meantime, 
To open solution in VS, you just need to do `startvs.cmd EFCore.sln`. (you can open any other solution file the same way).
`startvs.cmd` script will take care of restoring required packages and setting env variables appropriately for VS to work.
`restore.cmd` restores packages
`build.cmd` restore packages and build everything. (no packaging)
`test.cmd` should run all tests after building everything.
`build.cmd -pack` should produce nuget packages.

Hope this helps.

**Comment by benmccallum** [comment]
Thanks!

**Comment by smitpatel** [comment]
Updated https://github.com/aspnet/EntityFrameworkCore/wiki/Getting-and-Building-the-Code
Let us know if anything missing

**Comment by benmccallum** [comment]
Awesome. Thanks!

**Comment by benmccallum** [comment]
Ended up running into an issue building (both via cmd or in VS). Basically found I was getting the same "Duplicate assembly attribute" type exception as here: https://github.com/dotnet/cli/issues/4710

Deleted all obj and bin folders, clean and build then worked.
