### ISSUE TITLE
SqlServerRetryingExecutionStrategy is ignored

### ISSUE THREAD

**Issue by shurale85** [aspnet/EntityFrameworkCore#14730]
SqlServerRetryingExecutionStrategy is ignored when the query consists of `AsNotTrackin()` and `ToArrayAsync()`.

`var users = context.Users.AsNoTracking(),ToArrayAsync();  //retrying strategy is NOT called`

However, if `AsNoTracking()` is not used the retrying strategy is called. And, a query like `context.Users.AsNoTRacking.FirstAsync()` also is executed in strategy.

My application is constructed on ASP.NET Core 2.0. But I checked Core 2.1 also - the same problem

I did the following to test the strategy. 

1. I created `CommandListener.cs` to throw `TimeoutException`
```
[DiagnosticName("Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting")]
        public void OnCommandExecuting(DbCommand command, DbCommandMethod executeMethod, Guid commandId, Guid connectionId, bool async, DateTimeOffset startTime)
        {
            if (_throwException)
            {
                throw new TimeoutException("Test exception");
            }
        }
```
2. Subscribed listener to context
```
var listener = context.GetService<DiagnosticSource>();
                (listener as DiagnosticListener).SubscribeWithAdapter(new CommandListener());
```

**Comment by ajcvickers** [comment]
Note for triage: I was able to reproduce this.

**Comment by AndriySvyryd** [comment]
`_FastQuery` doesn't use the execution strategy and it doesn't support buffering, We could disable this code path if a retrying strategy is used.
@smitpatel Will we still have this in 3.0.0?

**Comment by smitpatel** [comment]
In 3.0, there is not _FastQuery (a separate path). Everything will go through same path so retrying strategy should work properly.

**Comment by smitpatel** [comment]
@AndriySvyryd  Should this be closed as _FastQuery is removed?
