### ISSUE TITLE
Stop calling AddLogging and AddMemoryCache in AddDbContext

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#14756]
Because EF no longer needs these services to be added to the application's service provider. However, any application that assumes AddDbContext adds these things will then break. This includes the ASP.NET Identity tests and MusicStore. It's not clear to me that the value of making this break is enough to justify doing it.

**Comment by smitpatel** [comment]
Early break and get feedback?

**Comment by ajcvickers** [comment]
@divega to follow up.

**Comment by ajcvickers** [comment]
Related ASP.NET issue: https://github.com/aspnet/AspNetCore/issues/7728
