### ISSUE TITLE
Update to NetTopologySuite v2

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#14825]
This version of NetTopologySuite has some fairly significant breaking changes. (e.g. splitting Coordinate into types like CoordinateXY, CoordinateXYZ, etc.) If our timelines align, it would be nice to upgrade to the new version during our 3.0.0 release. If not, we may need to consider creating packages like Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite2 or something.

cc @airbreather @FObermaier

**Comment by FObermaier** [comment]
I'm willing to help make it possible to have NTS v2 out before your 3.0.0 release. 
Can you elaborate about your timeline, is it accessible someplace?

**Comment by bricelam** [comment]
We typically follow the [.NET Core Roadmap](https://github.com/dotnet/core/blob/master/roadmap.md). lol, which is even more vague than usual... Let’s sync over email.
