### ISSUE TITLE
Sqlite: Revert breaking changes to SpatialiteLoader

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#14821]
UseNetTopologySuite loads the SpatiaLite extension for open, external connections now. Applications should no longer need to use SpatialiteLoader directly.

**Comment by ajcvickers** [comment]
Triage: Obsolete.

**Comment by bricelam** [comment]
This class lives in the SQLite provider, but is used by the NTS extension. Any additional spatial extension will also use it. Going to revert the breaking changes, but not mark it as obsolete.
