### ISSUE TITLE
Make CoreLoggerExtensions/RelationalLoggerExtensions public

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#14973]
Because providers need to generate logging events, for which there is a lot of infrastructure.

Also consider whether CoreStrings and RelationalStrings should be public. Again, providers may need to throw exceptions that could use these strings. However, in this case there's not a lot of infra and providers could relatively easily duplicate string resources they need. On the other hand, it wouldn't be too hard to not break string resources outside of a major release. We would need to create a new resource if we needed to change the parameters, and we would need a way to mark resources as obsolete.

**Comment by ajcvickers** [comment]
See also #11409

**Comment by ErikEJ** [comment]
Great idea!

**Comment by ajcvickers** [comment]
Public, Diagnostics.
