### ISSUE TITLE
Review conditional tests and make sure they are being run appropriately

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#15016]
Two specifics that I have noticed:
* Our `Conditional` attributes are not working correctly at least in VS; tests that should be skipped are run.
* Ambient database transaction tests are not running against .NET Core

**Comment by ajcvickers** [comment]
@smitpatel to try to create a small repro.

**Comment by smitpatel** [comment]
@AndriySvyryd  to link to VS issue

**Comment by AndriySvyryd** [comment]
See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/814965

**Comment by ajcvickers** [comment]
Triage: Two things:
* We still need to fix the ambient transaction tests
* The R# runner is also not respecting the conditions, so it may not be just a VS issue

Based on this, leaving this open, and assigning to Andriy to:
* Fix the transaction tests
* Track the progress on the VS issue.

**Comment by AndriySvyryd** [comment]
Besides the issue in the VS Test Explorer it's also an issue in the xunit runner, filed https://github.com/xunit/xunit/issues/1915

**Comment by AndriySvyryd** [comment]
@ajcvickers Can we consider this fixed now?
