### ISSUE TITLE
Analyzers: Remove analyzer on FromSql/ExecuteSqlCommand methods

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#15034]
Methods deprecated. Remove/modify analyzer.

**Comment by roji** [comment]
I will be doing this as part of #12104

**Comment by sandersaares** [comment]
What are the replacements for ExecuteSqlCommand? I find I am currently doing this:

```
Find all "executesqlcommand", Subfolders, Find Results 1, Entire Solution, ""
  C:\Source\CmsTinkering\App.DataGenerator\Program.cs(51):                dc.Database.ExecuteSqlCommand("ALTER DATABASE CURRENT SET RECOVERY SIMPLE;");
  C:\Source\CmsTinkering\App.DataGenerator\Program.cs(92):                        dc.Database.ExecuteSqlCommand("ALTER DATABASE CURRENT SET RECOVERY FULL;");
  C:\Source\CmsTinkering\App.DataGenerator\Program.cs(131):            dc.Database.ExecuteSqlCommand($"ALTER INDEX [{index}] ON {table} DISABLE;".ToString());
  C:\Source\CmsTinkering\App.DataGenerator\Program.cs(136):                dc.Database.ExecuteSqlCommand($"ALTER INDEX [{index}] ON {table} REBUILD;".ToString());
  C:\Source\CmsTinkering\App.DatabaseTool\Program.cs(361):            dc.Database.ExecuteSqlCommand(new RawSqlString($@"
```

ExecuteSqlCommand has served well as a nice shortcut. Is there a replacement or do I need to do manual SqlConnection/SqlCommand if I want to do this kind of thing?

**Comment by ajcvickers** [comment]
@sandersaares It's worrying to me that this wasn't obvious once you hit the Obsolete attribute and got the message. Can you provide some details as to why the message in the attribute didn't answer your question?

**Comment by sandersaares** [comment]
Oh the reason is simple: I am still on v2 right now 😄 I am happy to hear that there is an answer to my question in the attribute.

**Comment by ajcvickers** [comment]
@sandersaares In a nutshell, all we did was change the names to make sure the interpolated string version cannot be used in a way that appears to parameterize the query but doesn't. No functionality is gone.
