### ISSUE TITLE
Allow table/column comments to be specified in the model

### ISSUE THREAD

**Issue by QJesus** [aspnet/EntityFrameworkCore#15037]
env:
    EntityFrameworkCore.Tools 2.2.3
	MySql.Data.EntityFrameworkCore 8.0.15

``` SQL

DROP TABLE IF EXISTS `demo`;
CREATE TABLE `demo`  (
  `aaa` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'HOW TO ADD COMMENT',
  --                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  `bbb` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`aaa`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

````

**Comment by roji** [comment]
FWIW this exists on PostgreSQL and is supported by Npgsql (although the SQL is different): https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/135.

**Comment by ajcvickers** [comment]
Notes from triage: It would be good to port this from the Npgsql provider so that it is general relational functionality that can be used by any relational provider.

**Comment by Muppets** [comment]
For SQL Server provider, would we imagine this being supported with extendedproperties?

https://stackoverflow.com/questions/4586842/sql-comments-on-create-table-on-sql-server-2008

**Comment by ErikEJ** [comment]
are there any plans relating to reverse engineering for this?
Is this documented?

**Comment by divega** [comment]
@ErikEJ I think this is a good question. Can you please create a new issue for this? (unless you are able to find one).

**Comment by NeilBostrom** [comment]
I've not added any documentation for it yet.

I also remember seeing some comments on supporting [DescriptionAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.descriptionattribute), but I can't for the life of me find this now.

**Comment by roohial57** [comment]
If you use EF, you can use EFCommenter to automatically add comments from your entity, property, and enum summaries to the corresponding database tables and columns.
Adds table comments from class summaries and column comments from property summaries.
Supports enum types as column comments.
Easy integration via a single extension method in your DbContext.

Install:
`dotnet add package EFCommenter
`

Usage:
Enable XML documentation in your .csproj:
```
<PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>
```

Call in OnModelCreating:
`modelBuilder.AddEntitiesComments();
`
