### ISSUE TITLE
QueryRewrite: implement include and re-enable include tests

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#15064]
- [x] nav expansion reference include
- [x] nav expansion collection include
- [x] nav expansion string based include
- [ ] tracking
- [ ] reference include translation
- [ ] collection include translation
- [ ] async

**Comment by smitpatel** [comment]
Tracking is inbuilt in materialization. Reference include merged. Collection include work is tracked by #15611
