### ISSUE TITLE
Consider renaming FromRawSql and FromInterpolatedSql to FromSqlRaw and FromSqlInterpolated

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#15079]
These are the new methods created by addressing #10996. Today @ErikEJ suggested we can flip some words to make the new methods more discoverable. 

I am not sure how much it improves discoverability (if you have Intellisense), but the proposed names feel better than the ones we landed on, at least for me.

**Comment by roji** [comment]
The proposed names do provide more continuity with the old ones (we append something new to the end) and it does seem like they may help discoverability, +1 from me.

**Comment by divega** [comment]
In addition to FromSql, this would make the methods on databse ExecuteSqlRaw and ExecuteSqlInterpolated.
