### ISSUE TITLE
Types/members with no XML docs no longer error

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#15093]
Incomplete XML docs still cause errors.

**Comment by bricelam** [comment]
Looks like CA1591 is [disabled by Arcade](https://github.com/dotnet/arcade/blob/9800953d3b420fd7f81d88c5332df6d1c38e875e/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L90)...

**Comment by ajcvickers** [comment]
@bricelam Can it be easily re-enabled in our repo?

**Comment by bricelam** [comment]
Yes-ish. Just need to figure out the right MSBuild-fu...

**Comment by ajcvickers** [comment]
@bricelam Sounds good, but please timebox it. (It's not critical enough that we should spend a lot of time on it. Also, it occurred to me  that sending a PR to Arcade to make it optional might be easier/better, but I have course have no idea if that is actually true!)

**Comment by bricelam** [comment]
Honestly I don’t think it belongs in Arcade at all. We should try and get it removed.

**Comment by bricelam** [comment]
I've re-enabled this warning (as error) on EF Core. We just need to follow up with Arcade before closing.

**Comment by bricelam** [comment]
Filed https://github.com/dotnet/arcade/issues/2594
