### ISSUE TITLE
Where are the nightly builds?

### ISSUE THREAD

**Issue by fuocor** [aspnet/EntityFrameworkCore#15100]
The myget drops are 4 months old and nuget are 2 weeks old...

Where do the latest build packages live?

thanks

**Comment by bricelam** [comment]
https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/index.json

**Comment by smitpatel** [comment]
@ajcvickers @divega @bricelam - Do we want to have a myget feed where we mirror generated packages? (given the feed keep changing all the time). Or the only work pending here is to update readme?

**Comment by ajcvickers** [comment]
@smitpatel What would go in MyGet? Just our packages, or also everything we depend on? If it's the latter, I suspect MyGet won't be able to handle it.

**Comment by smitpatel** [comment]
Just our packages. Putting our dependencies is not trivial task. Though it would make it easier for people who install nightly .NET Core sdk to use latest EF.

**Comment by bricelam** [comment]
BTW, we should be publishing to the ASP.NET MyGet feed again...

**Comment by smitpatel** [comment]
Seems like Asp.NET Core nightly also points to same feed. I will update readme.

**Comment by smitpatel** [comment]
Updated ReadMe file to point to page on AspNetCore repo which has instructions on how to use nightly builds.
