### ISSUE TITLE
Add a PMC command that will list all DbContext types

### ISSUE THREAD

**Issue by Ponant** [aspnet/EntityFrameworkCore#15104]
I have 2 dbcontext and Get-DbContext complains that I need to provide one whereas the docs says that it will list the Lists available DbContext types.
it is a bit astonishing that this error occurs whereas one could use the CLI tooling which works with
dotnet ef dbcontext list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22803277-a2a7-0adf-acfc-35ed8e4238c8
* Version Independent ID: 19869482-5737-adff-3f7f-60b4217b977d
* Content: [EF Core tools reference (Package Manager Console) - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#feedback)
* Content Source: [entity-framework/core/miscellaneous/cli/powershell.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/cli/powershell.md)
* Product: **entity-framework**
* GitHub Login: @bricelam
* Microsoft Alias: **bricelam**

**Comment by ajcvickers** [comment]
Moved to product repo since this seems to be a bug.

**Comment by bricelam** [comment]
Get-DbContext is the equivalent of dotnet ef dbcontext info, not dbcontext list.

**Comment by bricelam** [comment]
Huh, the docs are wrong...

**Comment by ajcvickers** [comment]
Submitted docs PR: https://github.com/aspnet/EntityFramework.Docs/pull/1387

@Ponant What was your reason for wanting to list the DbContexts from the package manager console? (Asking to determine whether or not it's worth leaving this open to track doing it.)

**Comment by Ponant** [comment]
Hi @ajcvickers , I was using it as I use VS so that saves me having a console window opened.
In any case, I would highly recommend to put a sentence or two saying that the cli tools are more complete, as it seems to be the case. Until now I thought PMC would be equivalent to the cli tool.

**Comment by ajcvickers** [comment]
@Ponant Yes, but _why_ did you want to list the contexts in the first place?

**Comment by bricelam** [comment]
Note, tab-expansion works for the `-Context` parameters in PMC.

**Comment by Ponant** [comment]
@ajcvickers because I wanted to list the contexts instead of looking up the file names. Yes tab-expansion works too but there is a time lag and it does not list all dbcontexts and it does not always auto-complete...

**Comment by ajcvickers** [comment]
@Ponant Thanks! Putting this on the backlog.

**Comment by ErikEJ** [comment]
@bricelam Considering this - what would the command name be? Get-DbContexts ??

**Comment by bricelam** [comment]
In hindsight, Get-DbContext should have been named Get-DbContextInfo, and this one should be named Get-DbContext...

List-DbContext seems OK for now. As usual, we'll discuss the actual name ad nauseam in a design meeting.

**Comment by ErikEJ** [comment]
I will give it a shot

**Comment by ErikEJ** [comment]
How about a breaking change?

```
function Get-DbContext
{
    [CmdletBinding(PositionalBinding = $false)]
    param([string] $Context, [string] $Project, [string] $StartupProject)

    $dteProject = GetProject $Project
    $dteStartupProject = GetStartupProject $StartupProject $dteProject

    if ($Context)
    {
       $params = 'dbcontext', 'info', '--json'
       $params += GetParams $Context
    }
    else
    {
       $params = 'dbcontext', 'list', '--json'
       $params += GetParams
    }

    # NB: -join is here to support ConvertFrom-Json on PowerShell 3.0
    return (EF $dteProject $dteStartupProject $params) -join "`n" | ConvertFrom-Json
}

```

**Comment by bricelam** [comment]
👍 Definitely worth discussing

**Comment by ErikEJ** [comment]
I will await the discussion outcome

**Comment by bricelam** [comment]
You don't have to; we can merge it however you send the PR. After discussing, we're happy to do the rename/combine/split ourselves.

**Comment by ErikEJ** [comment]
OK, I will investigate how I can get it tested (manually)

**Comment by ErikEJ** [comment]
@bricelam Any hints on how to get this tested?

**Comment by ErikEJ** [comment]
Managed to get it tested - does this make sense or should the output be modified?

```
PM> Get-DbContext

fullName                                                      safeName          name              assemblyQualifiedName                                                                    
--------                                                      --------          ----              ---------------------                                                                    
Sws.ConfigurationProvider.Persistence.Azure.AzureDbContext    AzureDbContext    AzureDbContext    Sws.ConfigurationProvider.Persistence.Azure.AzureDbContext, Sws.ConfigurationProvider....
Sws.ConfigurationProvider.Persistence.Azure.AzureOtherContext AzureOtherContext AzureOtherContext Sws.ConfigurationProvider.Persistence.Azure.AzureOtherContext, Sws.ConfigurationProvid...


PM> Get-DbContext  -Context AzureDbContext
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.2.4-servicing-10062 initialized 'AzureDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None

providerName                            databaseName dataSource             options
------------                            ------------ ----------             -------
Microsoft.EntityFrameworkCore.SqlServer AzureData    (localdb)\MSSQLLocalDB None   

```

**Comment by bricelam** [comment]
I think we can use a [formatting file](https://docs.microsoft.com/en-us/powershell/developer/format/writing-a-powershell-formatting-file) to make it display prettier... But I've never done it.

**Comment by bricelam** [comment]
By default, I think we should just display `safeName`

**Comment by ajcvickers** [comment]
Merged, but we may want to discuss in a design meeting.
