### ISSUE TITLE
Unstable sort for Correlated_collection_with_top_level_FirstOrDefault test

### ISSUE THREAD

**Issue by cincuranet** [aspnet/EntityFrameworkCore#15164]
The test `Correlated_collection_with_top_level_FirstOrDefault` does not have an explicit _unique_ sort and hence [the loop](https://github.com/aspnet/EntityFrameworkCore/blob/2439d272bacb88e7ef04f1e4d741bfa87b1a0a43/test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs#L5503) will trigger false negative when the order is different.

To be precise, the query returns 2 rows with IDs 7 and 8. And the order isn't defined because the `Nickname`, `SquadId` and `FullName` are same (i.e. [here](https://github.com/aspnet/EntityFrameworkCore/blob/3e53e943d67996071b8c86cdcf89102766343697/test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs#L6207)).

**Comment by ajcvickers** [comment]
@cincuranet Can you submit a PR to fix this?

**Comment by cincuranet** [comment]
I can. But I have my own work to do, so it's going to take a while.

**Comment by j-rewerts** [comment]
I'm open to handling this. I just want to make sure @cincuranet hasn't started on it yet.

**Comment by cincuranet** [comment]
Go for it.

**Comment by j-rewerts** [comment]
@cincuranet Which version of EF Core are you using?

**Comment by j-rewerts** [comment]
It looks like this test is related to #15043 . Digging deeper, it looks like this test was disabled for the query rewrite effort. @maumar Would it be best for me to hold off on this until work is further along?

**Comment by maumar** [comment]
@j-rewerts we can take the PR now. The test has been disabled preemptively, as the first phase of query rewrite changes will break it, but for now the scenario works. You can enable the test on your box to make sure the fix is correct and disable it back for the PR. Once #15043 is fixed we can get the test online and it will have the proper fix already.
