### ISSUE TITLE
Query: book keeping before calling into client code in top level projection

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#15181]
- Materialization
- Tracking
- All includes + relationships

**Comment by Wain123** [comment]
Can you please explain this issue in slightly more detail? I can't figure out what you mean based on just the keywords you posted.

"client code in top level projection" means the delegate I pass into the `Select` part of a LINQ query, right? That delegate used to be called on entities that are not tracked by the context and don't have access to relationships. You mention the keywords "tracking" and "all includes + relationships", does this mean those entities will now be tracked and have access to relationships?

If yes, then this fixes issue #10471. That issue talks about `Where`, but it also applies to `Select`, and client-evaluation will be changed in 3.0 so `Where` can't be client-evaluated, only `Select` can.

**Comment by smitpatel** [comment]
Yes, this fixes #10471 for projection case.
