### ISSUE TITLE
Update API docs for internal code to align with message from analyzer

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#15235]
See https://github.com/aspnet/EntityFrameworkCore/pull/15087#discussion_r270992793

Specifically, the message we have does not really convey how we think about internal code. Proposal:
>  This is an internal API that supports the Entity Framework Core infrastructure and not subject to the same compatibility standards as public APIs. It may be changed or removed without notice in any release. You should only use it directly in your code with extreme caution and knowing that doing so can result in application failures when updating to a new Entity Framework Core release.

**Comment by ajcvickers** [comment]
Re-opening since it looks like a lot of the type summary comments were not updated.

**Comment by roji** [comment]
Oops, looks like my search-and-replace-fu wasn't strong that morning... Submitting another PR.
