### ISSUE TITLE
Match a subset of the PK as FK properties

### ISSUE THREAD

**Issue by deadalusai** [aspnet/EntityFrameworkCore#15250]
We've noticed a regression in EF Core's FK property discovery convention when upgrading from 2.1.8 to 2.2.0. We're using composite keys across our entities.

I've put together a reduced testcase here: https://gist.github.com/deadalusai/b49ecb2fe55a72fe2b42ff34e1caa817

### Steps to reproduce
1. Clone the above gist (just a .csproj and Program.cs)
2. `dotnet restore`
3. `dotnet run`
4. See the FK relationships printed out for `EntityType: Subscription`

Under EF Core 2.2.0 EF unnecessarily generates a shadow property when building the FK for the `Subscription -> Product` relationship. EF Core 2.1.8 uses the existing key properties.

Under 2.2.0 (broken):
```
EntityType: Subscription
  Foreign keys:
    Subscription {'TenantId'} -> Tenant {'TenantId'} ToPrincipal: Tenant
    Subscription {'ProductTenantId', 'ProductId1'} -> Product {'TenantId', 'ProductId'} ToDependent: Subscriptions ToPrincipal: Product
    Subscription {'TenantId', 'SubscriberId'} -> Subscriber {'TenantId', 'SubscriberId'} ToDependent: Subscriptions ToPrincipal: Subscriber
```

Under 2.1.8 (working):
```
EntityType: Subscription
  Foreign keys:
    Subscription {'TenantId'} -> Tenant {'TenantId'} ToPrincipal: Tenant
    Subscription {'TenantId', 'ProductId'} -> Product {'TenantId', 'ProductId'} ToDependent: Subscriptions ToPrincipal: Product
    Subscription {'TenantId', 'SubscriberId'} -> Subscriber {'TenantId', 'SubscriberId'} ToDependent: Subscriptions ToPrincipal: Subscriber
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

From my testing it looks like the bug was introduced in https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/2.2.0-preview3-35497 (last good working version was 2.2.0-preview2-35157).

**Comment by deadalusai** [comment]
This may be the offending commit? https://github.com/aspnet/EntityFrameworkCore/commit/2f8ad9f7e49d83abad71f1b2229acc5a446265dc#diff-e8ed8db3fc3f2caf18444491b47e577c

**Comment by ajcvickers** [comment]
@AndriySvyryd to look for dupe/workaround and to consider for patch.

**Comment by AndriySvyryd** [comment]
@deadalusai Fixing this in 2.2.x would be a breaking change, so for now you'll have to specify the foreign key properties explicitly:
```C#
modelBuilder.Entity<Subscription>().HasOne(d => d.Product).WithMany(d => d.Subscriptions)
     .HasForeignKey(d => new { d.TenantId, d.ProductId });
```
In general we'll no longer match the principal key names exactly to find foreign keys (see #13274), but we'll consider supporting this pattern in particular (when it's a subset of the dependent PK)

**Comment by deadalusai** [comment]
Thanks for your investigation @AndriySvyryd 👍

I'd like to make a suggestion that a feature like [this one](https://github.com/aspnet/EntityFrameworkCore/issues/1414) would be extremely helpful when building complex models - EFCore's current behavior of occasionally silently making up new FK columns is very difficult to debug.

**Comment by AndriySvyryd** [comment]
@deadalusai With https://github.com/aspnet/EntityFrameworkCore/issues/214 it will be possible to remove most conventions.
Also you can see every shadow property created in the log under the `DbLoggerCategory.Model` category in `Debug` level

**Comment by deadalusai** [comment]
Thanks @AndriySvyryd !
