### ISSUE TITLE
QueryRewrite: incorporate query filters into nav rewrite

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#15264]
Query filters can have navigations, so we need to make sure nav expansion ran on them recursively. Currently when producing joins or collection subqueries we generate simple EntityQueryables, completely disregarding any potential filters.

**Comment by maumar** [comment]
fixed in 8bf8a4ca25eeb3a8c78672b3951456c2a28e1337

**Comment by filipbekic01** [comment]
@maumar i tested preview8 but function HasQueryFilter is not wroking. Is that okay?

**Comment by smitpatel** [comment]
@filipbekic01 - This issue is not closed in 3.0-preview8 milestone. That means it is not included in preview8. Though it is closed for 3.0 so it would finally be available in RTM release. The milestone may change in future to reflect exactly which preview it will be part of.

**Comment by DUWENINK** [comment]
This issue is not closed in 3.0 20190929. we need help

**Comment by smitpatel** [comment]
@DUWENINK - Please file a new issue with repro steps.
