### ISSUE TITLE
QueryRewrite: correctly handle weak/owned entities

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#15285]
Currently weak entities are not handled properly - we lose type entity type information when we generate entity queryable for the expanded entity. In the old pipeline we keep track of them using dictionary. ~We can do similar thing in the new pipeline or embed the entity type information directly into expression tree~

**Comment by ajcvickers** [comment]
Note: Be sure to re-enable test disabled for #16360
