### ISSUE TITLE
DBFunctions.CreateDateTime

### ISSUE THREAD

**Issue by paulovila** [aspnet/EntityFrameworkCore#15283]
Hi, I'd like to be able to do queries like the following:  
  
 ```C#
_context.Shifts  
    .Include(w => w.ShiftDefinition)  
    .Select(w => new  
    {  
        w,  
        dt = DbFunctions.CreateDateTime(  
            w.ShiftDay.Year,  
            w.ShiftDay.Month,  
            w.ShiftDay.Day,  
            w.ShiftDefinition.StartTime.Hours,  
            w.ShiftDefinition.StartTime.Minutes,  
            w.ShiftDefinition.StartTime.Seconds)  
        })  
    .Where(w => currentDate < w.dt)  
    .OrderBy(w => w.dt)  
    .Select(q => q.w)  
    .FirstOrDefault();  
```
But it seems that **DBFunctions.CreateDateTime**  missing.   
Is it planned to get that function back, or is there any equivalent?  
Regards. PV

**Comment by nmichels** [comment]
Hi @divega and @ajcvickers 
I've opened a PR with an initial attempt to implement some similiar functionality as we used to have at EF6 with DBFunctions.CreateDate, please let me know if I'm going the right way. Initially this is targeting SqlServer only.
