### ISSUE TITLE
QueryRewrite: re-enable non-query tests related to tracking

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#15318]
Disabled for now since tracking is not working correctly. Affected tests:

GraphUpdates,
ProxyGraphUpdates
Load

**Comment by ajcvickers** [comment]
Remaining work here is in-memory tests:
* GraphUpdatesInMemoryTest
* ProxyGraphUpdatesInMemoryTest
* LoadInMemoryTest
* InMemoryComplianceTest
* FixupTest.Collection_nav_props_remain_fixed_up_after_manual_fixup_and_DetectChanges

**Comment by ajcvickers** [comment]
Closed in favor of #16963
