### ISSUE TITLE
SqlServer: Char with converter does not work well in query

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#15330]
SqlServer does not support char so we use char to string converter. When comparing character to constant/parameter, we run the value through converter so we get a string constant/parameter. But char is always wrapped in conversion to int on client side. So we also generate cast in SQL query. Which works well for SQLite but on SqlServer it fails to convert "varchar" to "int" and throws.

- Funcletizers leaves convert around char because of https://github.com/aspnet/EntityFrameworkCore/issues/14159
- Convert nodes cannot be identified if implicit or explicit. We could just make a guess that char to int convert is always implicit and we can remove convert on both side while translating to SQL. @roji with regards to #14159 do you see any issue with this approach?
- SqlServer can intercept such conversions and generate parameter/constant of required type directly. May have to constraint on char to int since some explicit conversions may be used for truncation by user.

**Comment by roji** [comment]
@smitpatel always removing char->int conversion nodes would certainly fix #14159 for me. I'm a little concerned that this would silently disallow explicit casts which may be legitimately used by the user in some cases - but I don't have a good scenario in mind. On the other hand I'm not sure there's a database out there which supports ASCII casting char->int (when text of any kind is cast to int, PostgreSQL attempts to parse it numerically and throws if a non-digit is found).

So removing the cast node seems to make sense... Assuming I've understood everything correctly :)

**Comment by smitpatel** [comment]
Same for ushort (and probably all types which upcast to int for equality operator)

**Comment by dmitry-lipetsk** [comment]
> So removing the cast node seems to make sense... Assuming I've understood everything correctly :)

I remove all impicit cast (Convert nodes) in my data provider.

One problem - need rebuild the functions and binary operations nodes. I say about local calculations.

For example, the call of datetime.AddYears(int) may transformed into extension method AddYears(this DateTime, int?) or vice versa.

Plus, I'm losing the call "NullableValue.Value" - EFCore (or linq?) translates this call to Convert node.
