### ISSUE TITLE
Consecutive calls to FirstOrDefault() in a projection not translatable

### ISSUE THREAD

**Issue by peterwurzinger** [aspnet/EntityFrameworkCore#15363]
We got a model that's set up as a 1:n and 1:n
- `Foo` has many `Intermediate`s - `Intermediate` has exactly one `Foo`
- `Intermediate` has many `Bar`s - `Bar` has exactly one `Intermediate`

The use case is to select the first `Bar` from the first `Intermediate` from every `Foo`. Sounds weird, but the query should be self-explanatory:
```Foos.Select(foo => foo.Intermediates.FirstOrDefault().Bars.FirstOrDefault())```

This query won't get translated:
```
Exception message: Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'FirstOrDefault()' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
Stack trace:    at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam arg, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.QueryClientEvaluationWarning(IDiagnosticsLogger`1 diagnostics, QueryModel queryModel, Object queryModelElement)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ProjectionExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFCoreBug.Program.Main() in C:\Users\Path\to\Project\EFCoreBug\Program.cs:line 17
```

### Steps to reproduce
The following domain-model was used to reproduce the issue.
```c#
public class Foo
{
    [Key]
    public Guid Id { get; set; }

    public ISet<Intermediate> Intermediates { get; } = new HashSet<Intermediate>();
}

public class Intermediate
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public Foo Foo { get; set; }
    
    public ISet<Bar> Bars { get; } = new HashSet<Bar>();
}

public class Bar
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public Intermediate Intermediate { get; set; }
}
```
The context was set up as shown below
```c#
public class MyContext : DbContext
{
    public DbSet<Foo> Foos { get; set; }

    private const string ConnectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=efbug-integration;Integrated Security=true;";

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.ConfigureWarnings(warnings =>
        {
            warnings.Throw(RelationalEventId.QueryClientEvaluationWarning);
        });

        optionsBuilder.UseSqlServer(ConnectionString);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Foo>();
    }
}
```
And a test program
```c#
public class Program
{
    public static void Main()
    {
        using (var ctx = new MyContext())
        {
            ctx.Database.EnsureCreated();

            //Ok
            var query1 = ctx.Foos.Select(foo => foo.Intermediates.FirstOrDefault()).ToList();

            //Ok
            var query2 = ctx.Foos.Select(foo => foo.Intermediates.FirstOrDefault().Bars).ToList();

            //Not translatable - exception see above
            var query3 = ctx.Foos.Select(foo => foo.Intermediates.FirstOrDefault().Bars.FirstOrDefault()).ToList();
        }

    }
}
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 and 2019

cc @axelheer

**Comment by maumar** [comment]
This should work in the new pipeline. Currently we don't have support for projecting correlated entity, but if query is modified to project only a scalar, we generate the following query:

```sql
SELECT (
    SELECT TOP(1) [l].[Name]
    FROM [LevelThree] AS [l]
    WHERE [l].[OneToMany_Optional_Inverse3Id] = (
        SELECT TOP(1) [l0].[Id]
        FROM [LevelTwo] AS [l0]
        WHERE [l1].[Id] = [l0].[OneToMany_Optional_Inverse2Id]
        ORDER BY [l0].[Id]
    )
    ORDER BY [l].[Id]
)
FROM [LevelOne] AS [l1]
ORDER BY [l1].[Name]
```

**Comment by peterwurzinger** [comment]
@maumar Alright, thanks for picking this one up. I'm not sure about what do you mean by "scalar" in this context. How would we need to rewrite our LINQ-Statement so that it can be translated by EF-Core < 3? Or how would the LINQ-Statement look, that corresponds to your SQL example?

**Comment by maumar** [comment]
@peterwurzinger by scalar I mean projecting only one property from the entity, rather than the entire entity. You can see that in the sql query above there is a sub-select projecting l.Name. You can only do this when projecting one property. If you need to project multiple properties, (e.g. to materialize entire entity) the translation needs to be different (using join or cross apply) - see https://github.com/aspnet/EntityFrameworkCore/issues/10001 for more context. 

Wrt how to write the linq query to produce the different translation:

"old" translation:

```cs
ctx.Customers.OrderBy(c => c.CustomerID).Select(c => c.Orders.OrderBy(o => o.OrderId).FirstOrDefault().OrderDetails.OrderBy(od => od.ProductID).FirstOrDefault())
```

"new" translation:

```cs
from c in ctx.Customers
order by c.CustomerID asc
select 
    (from od in ctx.OrderDetails
    where od.OrderID == (Nullable<int>)
        (from o in ctx.Orders
        where  c.CustomerID == o.CustomerID 
        order by o.OrderID asc
        select o.OrderID).FirstOrDefault() ?? 0
    order by od.ProductID asc
    select od).FirstOrDefault()
```

you should get a sql that looks somewhat like this:

```sql
SELECT [c].[CustomerID]
FROM [Customers] AS [c]
ORDER BY [c].[CustomerID]

@_outer_CustomerID='ALFKI' (Size = 5)

SELECT TOP(1) [od].[OrderID], [od].[ProductID], [od].[Discount], [od].[Quantity], [od].[UnitPrice]
FROM [Order Details] AS [od]
WHERE [od].[OrderID] = COALESCE((
    SELECT TOP(1) [o].[OrderID]
    FROM [Orders] AS [o]
    WHERE @_outer_CustomerID = [o].[CustomerID]
    ORDER BY [o].[OrderID]
), 0)
ORDER BY [od].[ProductID]

@"@_outer_CustomerID='ANATR' (Size = 5)

SELECT TOP(1) [od].[OrderID], [od].[ProductID], [od].[Discount], [od].[Quantity], [od].[UnitPrice]
FROM [Order Details] AS [od]
WHERE [od].[OrderID] = COALESCE((
    SELECT TOP(1) [o].[OrderID]
    FROM [Orders] AS [o]
    WHERE @_outer_CustomerID = [o].[CustomerID]
    ORDER BY [o].[OrderID]
), 0)
ORDER BY [od].[ProductID]
```

This will still be N+1 queries, in the old pipeline, so not sure if it will be helpful.

The idea is to "flip" the navigations - project directly from the DbSet that has the final result (OrderDetails) and filter its elements.

You can also try breaking the scenario into 2 queries - first query fetches first Intermediate from each Foo (essentially query1 from your example), and then foreach Intermediate, fetch it's corresponding Bar. It will also issue N+1 queries so performance is not great, but to do this in 1 query we need to fix #10001

**Comment by maumar** [comment]
member pushdown part is fixed - scenario works when projecting a single scalar. We still need to fix materialization for case where entire entity is projected. Assigning to @smitpatel

**Comment by peterwurzinger** [comment]
Since this issue was mentioned as getting fixed by a [commit](https://github.com/aspnet/EntityFrameworkCore/commit/6ca745d619ca3d635a1c8968139d0d32af08c2f7) in June is this issue still open? And has it yet been released in a Beta/Preview of EFCore3?

**Comment by smitpatel** [comment]
@peterwurzinger - It should be fixed in daily builds. Back in june it fixed issue when projecting a scalar column. The pending task (for which this issue was still open) was to fix the issue when projecting entity and not just a scalar column. The issue should be fixed in daily builds, we will need to add a regression test to close this issue.

**Comment by peterwurzinger** [comment]
@smipatel Thanks for the clarification. So it needs to be verified whether the issue is fixed, and, if so, the fix will be included in EF.Core 3.1.0 (according to its new label). Did I get that right?

**Comment by smitpatel** [comment]
Verification is planned for 3.1.0 as of now. Fix may be already part of 3.0.0 (in which case verification succeeds and we will update the milestone to reflect that), or verification fails and we may need to fix it depending on complexity of it, we may fix it in 3.1.

I would consider all verify-fixed issues to be potentially working in 3.0.

**Comment by peterwurzinger** [comment]
@smitpatel Alright, I'll verify if 3.0.0 RTM can fullfill our concrete use cases and post feedback in this trhread to give everybody stumbling over that a hint where to go.

Thanks!

**Comment by maumar** [comment]
verified in 1bd4e85c8dbe62d4c73bd216826bbfd18f126dec closing
