### ISSUE TITLE
Verify experience when global tool is not installed

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#15390]
As per direction from @DamianEdwards, an understandable error message must be displayed that indicates you need to go install the global tool.

**Comment by divega** [comment]
Should this be tracked as part of the “improve the experience” issue I filed before? I am ok either way, whatever makes it easier to discuss with partner teams.

**Comment by ajcvickers** [comment]
@divega Not sure--let's do the investigation first. If we need them to add something for this specifically, then it's likely that a separate tracking issue will be useful, but then we can always create that lazily. So...I don't mind, but we do need to remember to do this investigation.
