### ISSUE TITLE
Overall tracking issue for breaking changes in 3.0

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#15407]
The first place to look for information on breaking changes is in the [breaking changes page](https://docs.microsoft.com/ef/core/what-is-new/ef-core-3.0/breaking-changes) maintained in the documentation.

At the issue level, breaking changes are tracked using the [`breaking-change`](https://github.com/aspnet/EntityFrameworkCore/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Abreaking-change) label.

Breaking change issues break down for 3.0:
* Breaking changes currently [planned to be fixed for EF Core 3.0](https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0.0+label%3Abreaking-change)
  * Please note that this is not a guarantee that the issue will be fixed in the 3.0 release. Re-evaluation of the plan throughout the release cycle sometimes results in issues being pushed out to a later release.
* Breaking changes [fixed for EF Core 3.0](https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aissue+milestone%3A3.0.0+is%3Aclosed+label%3Abreaking-change) but not yet shipped
* Breaking changes [fixed in EF Core 3.0-preview4](https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aissue+milestone%3A3.0.0-preview4+is%3Aclosed+label%3Abreaking-change)
* Breaking changes [fixed in EF Core 3.0-preview3](https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aissue+milestone%3A3.0.0-preview3+is%3Aclosed+label%3Abreaking-change)
* Breaking changes [fixed in EF Core 3.0-preview2](https://github.com/aspnet/EntityFrameworkCore/issues?q=is%3Aissue+milestone%3A3.0.0-preview2+is%3Aclosed+label%3Abreaking-change)

**Comment by popcatalin81** [comment]
Please consider fixing #7089 for breaking changes. This was one of the most controversial features of EF core needs revisiting. Needing to have a nullable boolean (tristate), where only two values are needed at the application level is not ideal.

**Comment by ajcvickers** [comment]
@popcatalin81 We plan to support the pattern shown in #15182. This allows two values to be used at the application level, while still allowing the store-generated value to be used when no value was explicitly set. I believe all other cases are covered by appropriate configuration. (That is, either not configuring a store-generated value, or configuring it only for migrations and not using at update time, possibly coupled with moving the default to the client code.)
