### ISSUE TITLE
Query: Navigation rewrite does not preserve the type of result

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#15535]
Failing test 
FindSqlServerTestNonGeneric.Find_base_type_using_derived_set_tracked_async
When we do FindAsync, we generate `FirstOrDefault<object>`, That information has to be flown to translation pipeline so our final result is of type `Task<object>` (Our Async contract just takes TResult now). Nav expansion is eating up that type somehow so our final result is of type `Task<DerivedType>` which cannot be used to return `Task<object>`. (This works for sync because of implicit casting).

**Comment by maumar** [comment]
fixed in db9bca31f053cf043fd442edf59e7c689b914275
