### ISSUE TITLE
Add a convention to update check constraints

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#15551]
We should update the schema/table name for the constraint when it changes for the entity type.

**Comment by MarinaRybalko** [comment]
Can you provide more details? 
I would like to do it.

**Comment by AndriySvyryd** [comment]
You would need to create a convention that implements `IEntityTypeAnnotationChangedConvention` and reacts to any schema/table changes, finds any check constraints associated with that table and updates its schema/table to the new values.
But I am currently changing the conventions API, so it's best to hold of for about a week.

**Comment by AndriySvyryd** [comment]
An alternative solution would be to store the check constraint annotations on entity types instead of the model.

**Comment by Muppets** [comment]
As @AndriySvyryd mentioned, I believe the work I did in [this PR](https://github.com/aspnet/EntityFrameworkCore/pull/15688) to store constraint annotations on entity types will resolve this issue.

**Comment by AndriySvyryd** [comment]
Fixed in #15688
