### ISSUE TITLE
Move to Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#15636]
Now that the [preview of Microsoft.Data.SqlClient is available in NuGet](https://www.nuget.org/packages/Microsoft.Data.SqlClient/), we should be able to use it.

**Comment by ralmsdeveloper** [comment]
Wonderful!

[https://github.com/dotnet/SqlClient/blob/master/release-notes/1.0/1.0.0.md](https://github.com/dotnet/SqlClient/blob/master/release-notes/1.0/1.0.0.md)

**Comment by Tim-Bijnens** [comment]
Following this since we could realy use this to help port our current website to an Always Encrypted .Net Core app

**Comment by kedarchinchvalkar** [comment]
Waiting for Microsoft.Data.SqlClient to be integrated in preview of Microsoft.Entity.SqlServer. Currently its using System.Data.SqlClient as dependency.

Badly needed it to take advantage of column encryption feature of SQL Server 2016 in .net core project using entity core.

**Comment by ErikEJ** [comment]
@kedarchinchvalkar @Tim-Bijnens You can use the new client with EF Core 2.x as described here: https://github.com/dotnet/SqlClient/issues/11#issuecomment-493091283
