### ISSUE TITLE
3.0 API Review Feedback

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#15662]
### Pass 1:
- [x] @ajcvickers Add a breaking change note for ILazyLoader.SetLoaded
- [x] Remove DiagnosticsLoggers parameter from RelationalModelValidator
- [x] @ajcvickers Should the constructor of ColumnModification be documented as pubternal?
- [x] ~~@roji Add Clone or With methods to AlterColumnOperation~~ Moved to #16224

### Pass 2:
- [x] Review PropertyExtensions/MutablePropertyExtensions.FindPrincipal()
  - Better name? Return IEnumerable or include *First* in the name?
- [x] @ajcvickers Rename PropertyExtensions.FindMapping()
  - FindTypeMapping? RelationalTypeMapping? Start with *Get*?
- [x] @ajcvickers ~~Add breaking change note for ChangeTracker.TrackGraph()~~ This wasn't a breaking change after all
- [x] Whatever @AndriySvyryd thinks is best: NavigationEntry.GetTargetEntry() returns `null`. Do we still want to rename CollectionEntry.GetTargetEntry() to FindEntry()?
- [x] Review IModelSource.GetModel() break. Would a parameter object help? Can we decouple logging?
- [x] Make AnnotationNames pubternal (again)
- [x] Review IConvention metadata. (e.g. IConventionEntityType.AddForeignKey() should take IProperty not IConventionProperty)
- [x] @smitpatel Move IEntityMaterializerSource to a better namespace
- [x] @AndriySvyryd Propose a better design for IMutableEntityType.AddIndexedProperty()
- [x] @ajcvickers Should IConventionSetCustomizer be renamed to *Plugin*?

### Pass 3:
- [x] @ajcvickers Rename IdentifierHelpers
- [x] @bricelam Test diffing old model snapshots (e.g. Are old discriminator attributes ignored?)
- [x] @ajcvickers Should IConstructorBindingFactory.TryBindConstructor take IEntityType instead?
- [x] @ajcvickers Review IParameterBindingFactories, IParameterBindingFactory, IPropertyParameterBindingFactory & ParameterBindingInfo
  - Should IPropertyParameterBindingFactory.TryBindParameter be *Find*?
  - Is ParameterBindingInfo.GetValueBufferIndex needed?

### Pass 4:
- [x] ~~Document removal of IQueryable.ToLookupAsync() breaking change~~ was added in 3.0
- [x] ~~Remove IParameterBindingFactory.Bind(IMutableEntityType)~~ Reviewed and this is used and needed
- [x] ~~@smitpatel Remove async parameter of IDatabase.CompileQuery() (infer when TResult is Task)~~ Covered by #14551

### Pass 5:
- [x] @ajcvickers Query
  - [x] Remove indexMap parameter of IEntityMaterializerSource.CreateMaterializeExpression()
  - [x] Make Microsoft.EntityFrameworkCore.Query.NavigationExpansion and .Visitors namespaces pubternal
  - [x] Make these types public
    - CollectionShaperExpression
    - EntityShaperExpression
- [x] Make a pass over `IList` and `ISet` and consider read-only. Also, check for concrete `List`
- [x] Add static factory methods to `SqlFunctionExpession`
- [x] Seal `NodeType` for all extension expessions
- [x] Consider dependency object for QueryCompliationContext

**Comment by ajcvickers** [comment]
@ajcvickers to look at 1 and 3. @roji to look at 4.

**Comment by ajcvickers** [comment]
`ColumnModification` seems fine the way it is.

**Comment by bricelam** [comment]
(updated with 2nd pass)

**Comment by bricelam** [comment]
(Updated with pass 4 and a bit of pass 5)
