### ISSUE TITLE
Store check constraints in the snapshot as Fluent API

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#15676]

**Comment by ajcvickers** [comment]
@Muppets This is something that was missed in your PR. Would you consider sending a PR to rectify this?

**Comment by Muppets** [comment]
@ajcvickers Sure thing. Are you able to provide some more details on it? Still learning my way around the code base. Any good examples where we do this already?

**Comment by AndriySvyryd** [comment]
@Muppets You'd have to modify `Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator` to look for the annotation and generate Fluent API calls on the corresponding EntityTypeBuilder.
It would be easier to find the correct entity type if the check constraint annotation [is stored on the entity type itself](https://github.com/aspnet/EntityFrameworkCore/issues/15551#issuecomment-490250934)

Note there's already a disabled test for this - `ModelSnapshotSqlServerTest.CheckConstraint_is_stored_in_snapshot_as_fluent_api()`

**Comment by Muppets** [comment]
@AndriySvyryd Raised a PR for that change. For this change, I just added a method to get check constraints by table and schema. 

Moving a check constraint annotations dictionary to each entity type sounds like a good plan. I can probably rework that since I've had my fingers in it recently. Want me to raise a separate issue for it?

**Comment by AndriySvyryd** [comment]
@Muppets It's up to you whether to do it in a separate PR or not. But note that the code in https://github.com/aspnet/EntityFrameworkCore/pull/15688 would generate duplicate check constraints for entity types mapped to the same table.

**Comment by Muppets** [comment]
@AndriySvyryd Just to check I've got the scenario correct for the duplicate checks. I [added this test](https://github.com/aspnet/EntityFrameworkCore/pull/15688/commits/6ab3cd145920a2b8cfac60f51258d54dcba04cfd) which adds a check constraint on a derived type. Right now, this fails as the current code generates duplicate HasCheckConstraint calls. This correct?

I'll start the work to refactoring check constraint annotations to be stored on the entity. I'll ping you if I have any questions.
