### ISSUE TITLE
Queryable methods translation progress

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#15711]
Relational:
- [x] All
- [x] Any
- [x] Average
- [x] Cast
- [x] Concat
- [x] Contains
- [x] Count
- [x] DefaultIfEmpty
- [x] Distinct
~- [ ] ElementAt (#17066)~
~- [ ] ElementAtOrDefault (#17066)~
- [x] Except
- [x] First
- [x] FirstOrDefault
- [x] GroupBy
~- [ ] GroupJoin (#17068)~
- [x] Intersect
- [x] Join
- [x] LeftJoin
- [x] Last
- [x] LastOrDefault
- [x] LongCount
- [x] Max
- [x] Min
- [x] OfType
- [x] OrderBy
- [x] OrderByDescending
- [x] Reverse
- [x] Select
- [x] SelectMany
- [x] Single
- [x] SingleOrDefault
- [x] Skip
~- [ ] SkipWhile (#17065)~
- [x] Sum
- [x] Take
~- [ ] TakeWhile (#17065)~
- [x] ThenBy
- [x] ThenByDescending
- [x] Union
- [x] Where

InMemory:
- [x] All
- [x] Any
- [x] Average
~- [ ] Cast (#16963)~
- [x] Concat
- [x] Contains
- [x] Count
~- [ ] DefaultIfEmpty (#16963)~
- [x] Distinct
~- [ ] ElementAt (#17066)~
~- [ ] ElementAtOrDefault (#17066)~
- [x] Except
- [x] First
- [x] FirstOrDefault
~- [ ] GroupBy (#16963)~
~- [ ] GroupJoin (#17068)~
- [x] Intersect
- [x] Join
- [x] LeftJoin
- [x] Last
- [x] LastOrDefault
- [x] LongCount
- [x] Max
- [x] Min
~- [ ] OfType (#16963)~
- [x] OrderBy
- [x] OrderByDescending
~- [ ] Reverse (#16963)~
- [x] Select
~- [ ] SelectMany (#16963)~
- [x] Single
- [x] SingleOrDefault
- [x] Skip
~- [ ] SkipWhile (#17065)~
- [x] Sum
- [x] Take
~- [ ] TakeWhile (#17065)~
- [x] ThenBy
- [x] ThenByDescending
- [x] Union
- [x] Where

Cosmos:

Unknowns:
~- [ ] Aggregate (Not Needed)~
- [x] AsQueryable
~- [ ] SequenceEqual (Not Needed)~
~- [ ] Zip (Not Needed)~
~- [ ] SkipLast (#17065)~
~- [ ] TakeLast (#17065)~

**Comment by ajcvickers** [comment]
@roji @smitpatel Should this be updated for set operations?

**Comment by roji** [comment]
I think we're still waiting in progress - PR #16249 is still outstanding, and even after that we'd ideally complete #16298 (set operations over different entity types).

**Comment by Jehoel** [comment]
It's not included in the list above, but it seems `Include( x => x.Property )` doesn't currently work in InMemoryDatabase either, as reported in https://github.com/aspnet/EntityFrameworkCore/issues/16106

**Comment by roji** [comment]
@Jehoel [as the preview6 announcement explained](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-6-and-entity-framework-6-3-preview-6/), InMemory is temporary not working as we're working to get the entire query pipeline working well. This page is about generic support for LINQ operators (not specific to any one database).

**Comment by roji** [comment]
Have checked off the set operations - we've probably done what we intend to support for 3.0,

**Comment by smitpatel** [comment]
Moved this Epic to 3.0, submitting PR to wrap up work here.
