### ISSUE TITLE
 Microsoft.EntityFrameworkCore.Cosmos 3.0.0-preview5.19227.1  Cause  Memory leak

### ISSUE THREAD

**Issue by dongshengfengniaowu** [aspnet/EntityFrameworkCore#15784]
using (DeviceCosmosDbContext deviceCosmosDbContext = new DeviceCosmosDbContext(cosmosDataOptions, loggerFactory))
   {
     Query---
   }
, repeat 30000 times, the Memory keep growing .

![image](https://user-images.githubusercontent.com/39110620/58230250-62d87580-7d66-11e9-8824-37cf7f383e04.png)

**Comment by AndriySvyryd** [comment]
Fixed in 98fe04febee96f733bbfd9c4e3c819a2cbe56a5b

**Comment by AndriySvyryd** [comment]
@dongshengfengniaowu This should be fixed in preview8 or nightly builds. If you still experiencing it please provide a full repro.

**Comment by dongshengfengniaowu** [comment]
Glad to hear that !
