### ISSUE TITLE
dotnet-ef: Consider showing output that the project is building

### ISSUE THREAD

**Issue by nphmuller** [aspnet/EntityFrameworkCore#15787]
My project takes a while to build. When running `dotnet ef` commands like `dotnet ef migrations add MyMigration` the project often gets build first. At the stage when the project starts building `dotnet ef` has not written any output to the console yet, and it will not write anything to the console until the build has finished. I know that I can see the build output via `-v` or `--verbose`, but it would be more clear to me if the non-verbose version output a single line of text like `Project is building...`. It would make the `dotnet ef` tool feel more responsive, at least for me.

So please consider showing output indicating that the project is building.

### Further technical details
`dotnet ef --version` output:
```
Entity Framework Core .NET Command-line Tools
2.2.4-servicing-10062
```

**Comment by bricelam** [comment]
I have an [old branch](https://github.com/aspnet/EntityFrameworkCore/compare/master...bricelam:respond) with this change I've been meaning to get back to...

**Comment by nphmuller** [comment]
Looks perfect! :)

**Comment by bricelam** [comment]
#12049 is also about making sure we’re not doing anything that slows it down.

**Comment by ajcvickers** [comment]
For anyone choosing to implement this, please see @bricelam's branch above for a starting point.

**Comment by skalpin** [comment]
@bricelam, I am considering working on this issue. How can I test the output of `dotnet ef`?

**Comment by bricelam** [comment]
@skalpin Type `dotnet ef` :trollface:

Just kidding. I do this:
``` cmd
cd C:\Path\To\EntityFrameworkCore
restore
.dotnet\dotnet run -p src\dotnet-ef -- dbcontext list -p C:\Path\To\DummyProject --verbose
```

**Comment by skalpin** [comment]
> ```batchfile
> cd C:\Path\To\EntityFrameworkCore
> restore
> .dotnet\dotnet run -p src\dotnet-ef -- dbcontext list -p C:\Path\To\DummyProject --verbose
> ```
I am getting
`The application to execute does not exist: 'C:\dev\EntityFrameworkCore\artifacts\bin\dotnet-ef\Debug\netcoreapp5.0\tools\netcoreapp2.0\any\ef.dll'`

I checked and this directory `C:\dev\EntityFrameworkCore\artifacts\bin\dotnet-ef\Debug\netcoreapp5.0\` doesn't have a `tools` folder.

Do I need to build a specific project?

**Comment by bricelam** [comment]
That's expected--you need to run from the global tool package to make it work end to end.

But, if you get that error, all the dotnet-ef logic has executed.

**Comment by skalpin** [comment]
I rebased your branch onto release/3.0-preview9 [here](https://github.com/aspnet/EntityFrameworkCore/compare/release%2F3.0-preview9...skalpin:bug%2F15787_cli_output?diff=split). 

What needs to change to complete it?
Why use `args.Add("/verbosity:detailed");` instead of `args.Add("/verbosity:quiet");` ?

**Comment by bricelam** [comment]
That change (detailed) was to debug the build perf. You can revert it

**Comment by skalpin** [comment]
I tried to capture the output in a unit test
```cs
[Fact]
        public void Build_started_note()
        {
            using (var sw = new StringWriter())
            {
                var eol = Environment.NewLine;
                Console.SetOut(sw);
                Reporter.IsVerbose = true;
                var project = new Project(@"DummyProject\DummyProject.csproj", null, null, null);
                project.Build();
                var output = sw.ToString();
                Assert.True(output.Contains("Build started"));
                Assert.True(output.Contains("Build succeeded."));
            }
        }
```
but I'll need a dummy project.
Is there another way to unit test the output of Project.Build()?
Should I make the PR without a unit test?

**Comment by bricelam** [comment]
No need for a unit test—they get too flakey. Just verify manually.
