### ISSUE TITLE
Value converter for Uri

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/EntityFrameworkCore#15816]
This is a feature request. I would like to propose the addition of a value converter for the [Uri](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=netcore-2.2) type.

**Comment by Muppets** [comment]
I'm liking the look of this. Taking a stab at raising a PR for it.

**Comment by vanillajonathan** [comment]
Silly list of value converter candidates for possible consideration or more likely outright rejection.
* [ContentType](https://docs.microsoft.com/en-us/dotnet/api/system.net.mime.contenttype?view=netcore-2.2)
* [CultureInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=netcore-2.2)
* [DirectoryInfo](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo?view=netcore-2.2)
* [DriveInfo](https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo?view=netcore-2.2)
* [FileInfo](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo?view=netcore-2.2)
* [HashAlgorithmName](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithmname?view=netcore-2.2)
* [HttpMethod](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmethod?view=netcore-2.2)
* [IPAddress](https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress?view=netcore-2.2)
* [IPEndPoint](https://docs.microsoft.com/en-us/dotnet/api/system.net.ipendpoint?view=netcore-2.2)
* [ProcessStartInfo](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo?view=netcore-2.2)
* [Regex](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex?view=netcore-2.2)
* [RegionInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.regioninfo?view=netcore-2.2)
* [SecureString](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netcore-2.2)
* [Version](https://docs.microsoft.com/en-us/dotnet/api/system.version?view=netcore-2.2)
* [X509Certificate2](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2?view=netcore-2.2)

A candidate could have a public constructor taking a single primitive type, or a have a static `Parse` method taking a single primitive type.

With your own [value converter](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions):
```cs
var uriConverter = new ValueConverter<Uri, string>(v => v.ToString(), v => new Uri(v));
```

Or with [backing fields](https://docs.microsoft.com/en-us/ef/core/modeling/backing-field) for those who want.
```cs
public class Server
{
    private string _iPAddress;

    public IPAddress IPAddress
    {
        get { return IPAddress.Parse(_iPAddress); }
        set { _iPAddress = value.ToString(); }
    }
}
```

**Comment by vanillajonathan** [comment]
The `IPAddress` is now in EF Core thanks to @ralmsdeveloper with pull request #20679.

**Comment by vanillajonathan** [comment]
`PhysicalAddress` is now in EF Core thanks to @ralmsdeveloper.

https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#physicaladdress-mapping

**Comment by vanillajonathan** [comment]
Somle more possible candidates:
- [Half](https://docs.microsoft.com/en-us/dotnet/api/system.half.parse?view=net-5.0)
- JsonValue
- JsonDocument
- MediaTypeHeaderValue
- TimeSpan
