### ISSUE TITLE
React to changes in metadata about nullable reference types

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#15830]
There is some churn expected on the attributes you can get for nullable reference types via reflection, and even possibly on the ability to get them for private members. 

Creating this issue so that we can track this and coordinate with partner teams to make sure we look for the right things for 3.0 RTM.

cc @roji @ajcvickers @jaredpar

**Comment by roji** [comment]
Any specific external issue? In any case we have the basic tests so we'll know if something breaks there.

**Comment by roji** [comment]
https://github.com/dotnet/corefx/issues/38087
