### ISSUE TITLE
Accessing properties on closure parameters or inline instantiated types fails

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#15855]
After enabling entity equality, property access on closure parameters or inline instantiated types fail with InvalidOperationException.

See test `Entity_equality_local` for the former, `Where_query_composition_entity_equality_multiple_elements_FirstOrDefault` for the latter.

/cc @smitpatel

**Comment by smitpatel** [comment]
While implementing this, please keep #14645  in mind and other related issues.

**Comment by smitpatel** [comment]
Also condense the property access on constants. They are not in the scope of translation pipeline.

**Comment by roji** [comment]
Am going to give this a try
