### ISSUE TITLE
Query: Identity query failures

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#15866]
With the new pipeline, queries of the following form are failing:
```C#
await UserClaims.Where(uc => uc.UserId.Equals(user.Id)).Select(c => c.ToClaim()).ToListAsync(cancellationToken);
```

Issues of the following form may also be failing, but this may be a red herring:
```C#
Users.SingleOrDefaultAsync(u => u.NormalizedEmail == normalizedEmail, cancellationToken);
```

**Comment by smitpatel** [comment]
#15927 fixes first failure.
Second failure is duplicate of #15559 which does not throw at present.
