### ISSUE TITLE
Create repro for failures after database creation with Azure SQL Database and SQL Server

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#15874]
We are working with the SQL Server team to diagnose failures that we have observed when trying to use a database immediately after creation. 

The guidance from the SQL Server team is that creating an database in Azure SQL Database using T-SQL should be resolved synchronously. I.e. by the time the operation completes, the database should be ready to use. But this is not what we have been seeing, for either Azure SQL Database or other flavors of SQL Server.

We will use this issue to track putting together a repro that they can use to diagnose it.

### Details

Some time ago we started adding retry logic to handle some failures that commonly occur when we connect to a database immediately after creating it.  Our logic for this lives in the SqlServerDatabaseCreator class. 

Basically, we have a database existence API that tries to connect to a database, and if it gets any of the following errors, assume the database really doesn’t exists:

_4060:_ Cannot open database "X" requested by the login. The login failed.
_1832:_ Unable to Attach database file as database xxxxxxx.
_5120:_ Unable to open the physical file xxxxxxx.

We have a separate API for creating databases, that after creating the database tries to connect to it and retries if any of the following errors occur (note that this list is a super-set of the previous one):

_233:_ A connection was successfully established with the server, but then an error occurred during the login process. (provider: Named Pipes Provider, error: 0 - No process is on the other end of the pipe.) It appears that this happens when the database has just been created but has not yet finished opening or is auto-closing when using the AUTO_CLOSE option. The workaround is to flush the pool for the connection and then retry the Open call.
_-2:_ Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgment. This could be because the pre-login handshake failed or the server was unable to respond back in time.
_4060:_ Cannot open database "X" requested by the login. The login failed.
_1832:_ Unable to Attach database file as database xxxxxxx.
_5120:_ Unable to open the physical file xxxxxxx.
            
This approach has evolved based on failures experience by customers and in our own tests. We started with an API that just tried to create the database without trying to connect to it. But we keep hearing from customers that SQL Server produces other errors that we haven’t considered, like recently in https://github.com/aspnet/EntityFrameworkCore/issues/15644.

**Comment by AndriySvyryd** [comment]
Repro project at https://github.com/AndriySvyryd/SqlServerCreationRepro
