### ISSUE TITLE
Consider moving AsAsyncEnumerable<T>() from internal QueryableExtensions to public EntityFrameworkQueryableExtensions

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#15998]
It should be useful for anyone to make the switch between EF Core queries and the new standard `IAsyncEnumerable<T>` interface, e.g. to take advantage of System.Async.Linq without having to cast explicitly.

**Comment by divega** [comment]
cc @smitpatel

**Comment by ajcvickers** [comment]
@divega Will we end up clashing with a BCL method?

**Comment by divega** [comment]
It could, somewhat clash. Note that this is also true about the rest of our async extension methods, including ToListAsync(), ToArrayAsync(), CountAsync(), FirstAsync(), etc. 

However, we define our extension methods on IQueryable<T\>, which is not something I expect to see on the BCL any time soon. Some day, if we invest on making async LINQ more of a fleshed out reality in the BCL, I believe we will have to rethink how we type our queries to yield a similar experience anyway. 

PS: I noticed that the the current [AsAsyncEnumerable()](https://github.com/dotnet/reactive/blob/master/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/AsAsyncEnumerable.cs) implementation on System.Linq.Async assumes the source is already statically an IAsyncEnumerable<T\> (hence no need to cast it really), and the implementation of [ToAsyncEnumerable()](https://github.com/dotnet/reactive/blob/master/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToAsyncEnumerable.cs) assumes that the source **isn't** an IAsyncEnumerable<T\>. So current implementations aren't doing the simple casting that what we need. I am not sure if this is by design or an oversight. Cc: @bartdesmet @onovotny.
