### ISSUE TITLE
Nested owned entity not populated when no other property in first owned entity has a value

### ISSUE THREAD

**Issue by DieDrachenfaenger** [aspnet/EntityFrameworkCore#16032]
We are working with a nested owned type. We recognized that the nested owned type gets NULL if it's the only property having a value in the first owned type. When there is another property having a value in the first owned entity the nested type is also loaded.

### Steps to reproduce
We created a little application to reproduce the problem.

SQL-Script to create table and some data:
```SQL
CREATE DATABASE EfCore_NestedOwnedTypes;
Use EfCore_NestedOwnedTypes;
CREATE TABLE Invoice
(
	InvoiceId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ShippingAddress_Street NVARCHAR(50) NULL,
	ShippingAddress_Recipient_Name NVARCHAR(50) NOT NULL
)

INSERT INTO [dbo].[Invoice] (ShippingAddress_Recipient_Name) VALUES ('Bob');
```

C# Console application:
```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace EfCore_NestedOwnedTypes
{
  public class Program
  {
    public static void Main(string[] args)
    {
      using (var context = new Context())
      {
        var invoice = context.Invoices.First();
        Console.WriteLine("Recipient name is: " + (invoice.ShippingAddress.Recipient.Name ?? "Null!"));
        Console.ReadLine();
      }
    }

    public class Context : DbContext
    {
      public virtual DbSet<Invoice> Invoices { get; set; }

      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
        if (!optionsBuilder.IsConfigured)
          optionsBuilder.UseSqlServer("data source=(local);initial catalog=EfCore_NestedOwnedTypes;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework", options => options.EnableRetryOnFailure(3));
      }

      protected override void OnModelCreating(ModelBuilder modelBuilder)
      {
        modelBuilder.Entity<Invoice>(entity =>
        {
          entity.HasKey(e => e.InvoiceId);
          entity.Property(e => e.InvoiceId).HasColumnName("InvoiceId");
          entity.ToTable("Invoice");
          entity.OwnsOne(e => e.ShippingAddress, shippingAddress =>
          {
            shippingAddress.Property(e => e.Street).HasColumnName("ShippingAddress_Street");
            shippingAddress.OwnsOne(sa => sa.Recipient, recipient =>
            {
              recipient.Property(r => r.Name).HasColumnName("ShippingAddress_Recipient_Name");
            });
          });
        });
      }
    }

    public class Invoice
    {
      public Invoice() { ShippingAddress = new ShippingAddress(); }

      public int InvoiceId { get; set; }
      public ShippingAddress ShippingAddress { get; set; }
    }

    public class ShippingAddress
    {
      public ShippingAddress() { Recipient = new Recipient(); }

      public string Street { get; set; }
      public Recipient Recipient { get; set; }
    }

    public class Recipient
    {
      public string Name { get; set; }
    }
  }
}
```
Output: "Recipient name is: NULL!".
Note: when adding a value to ShippingAddress.Street everything works fine (Output: "Recipient name is: Bob").

### Further technical details
EF Core version: 3.0.0prev5
Operating system: Windows 10
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment]
Note for triage: this looks like a consequence of optional owned types. /cc @AndriySvyryd

**Comment by AlbertoPa** [comment]
This still seems to affect p7. Poperties of owned entities are not populated in queries. Is there any workaround?

**Comment by GerritBergen** [comment]
@AlbertoPa I'm using the Preview 5 nuget packages for now. They said in another thread that this is working in the nightly builds, so I'm guessing we'll see this fixed in the next release.

**Comment by AlbertoPa** [comment]
@GerritBergen thank you! This sounds good.

**Comment by ajcvickers** [comment]
@AlbertoPa Please use the [nightly builds](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md) rather than down-grading to preview 5.

**Comment by AlbertoPa** [comment]
Thank you @ajcvickers. Will do.

**Comment by GerritBergen** [comment]
@ajcvickers I'll probably do the same as soon as I have a few minutes. Any idea when the next preview/release drops?

**Comment by ajcvickers** [comment]
@GerritBergen Yes, it should be soon...but because it takes so long to go from branching to release it means preview 8 will be significantly out-of-date (it is already) by the time it is published. The only realistic way to get current EF Core 3.0 bits right now is to use the nightlies.

**Comment by GerritBergen** [comment]
@ajcvickers alright! Thanks for the info
