### ISSUE TITLE
ApplyServices() in DbContextOptionsBuilder.IsConfigured is problematic for perf

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#16045]
Commit 188dbf4e changed the `DbContextOptionsBuilder.IsConfigured` property to call `ApplyServices()` on all options extensions, in order to fix #13228. Calling TryAdd on all EF services has a significant perf cost.

Discovered as a result of #15173, where `ApplyServices()` also caused a DiagnosticListener leak.

---

Here are some benchmark results:

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17763.437 (1809/October2018Update/Redstone5)
Intel Xeon W-2133 CPU 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=2.2.103
  [Host]     : .NET Core 2.2.4 (CoreCLR 4.6.27521.02, CoreFX 4.6.27521.01), 64bit RyuJIT
  DefaultJob : .NET Core 2.2.4 (CoreCLR 4.6.27521.02, CoreFX 4.6.27521.01), 64bit RyuJIT

## Current IsConfiguring (with ApplyServices)

| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
|     Go | 257.9 us | 0.5106 us | 0.4263 us |

Previous (light):

## Previous IsConfiguring (without ApplyServices)

| Method |     Mean |     Error |    StdDev |
|------- |---------:|----------:|----------:|
|     Go | 156.8 us | 0.4933 us | 0.4373 us |

## Benchmark code

```c#
class Program
{
    static void Main(string[] args) => new BenchmarkSwitcher(typeof(Program).GetTypeInfo().Assembly).Run(args);
}

public class IsConfigured
{
    private static DbContextOptions<BlogContext> _options;

    [GlobalSetup]
    public void Setup()
    {
        var builder = new DbContextOptionsBuilder<BlogContext>();
        builder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Initial Catalog=DiagnosticListenersEverywhere");
        _options = builder.Options;

        using (var ctx = new BlogContext(_options))
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();
        }
    }

    [Benchmark]
    public void Go()
    {
        using (var ctx = new BlogContext(_options))
        {
            var entities = ctx.Blogs.ToList();
        }
    }

    public class BlogContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }

        public BlogContext(DbContextOptions<BlogContext> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            _ = options.IsConfigured;   // Calling the getter triggers the issue
        }
    }

    public class Blog
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
    }
}
```

**Comment by ajcvickers** [comment]
Broke out the breaking change into a separate issue: #16119
