### ISSUE TITLE
RevEng: nameof syntax error 

### ISSUE THREAD

**Issue by Hursev** [aspnet/EntityFrameworkCore#16083]
Describe what is not working as expected.
I have a table in Azure SQL server like
```
CREATE TABLE [dbo].[ConfigMetaObject] (
    [ConfigFileId] INT NOT NULL,
	...
    CONSTRAINT [FK_ConfigMetaObject_ConfigFile] FOREIGN KEY ([ConfigFileId]) REFERENCES [dbo].[ConfigFile] ([Id]) ON DELETE CASCADE,
	...
);
```
When I [re]generate the model files using 
```
Scaffold-DbContext "..." Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Force -DataAnnotations
```
The generated class looks like 
Using preview 5:
```
public partial class ConfigMetaObject
{
	public int ConfigFileId { get; set; }
	...	
	[ForeignKey("ConfigFileId")]
	[InverseProperty("ConfigMetaObject")]
	public virtual ConfigFile ConfigFile { get; set; }
	...
}
```
Which works OK.

But using preview 6:
```
public partial class ConfigMetaObject
{
	public int ConfigFileId { get; set; }
	...	
	[ForeignKey(nameof(ConfigFileId))]
	[InverseProperty(nameof(ConfigFile.ConfigMetaObject))]
	public virtual ConfigFile ConfigFile { get; set; }
	...
}
```
The problem is that both the class name (ConfigFile) and the member name are ConfigFile and as result when the compiler see the 'ConfigFile' in 
```
[InverseProperty(nameof(ConfigFile.ConfigMetaObject))]
```
it thinks it is the member variable, not the class.

The solution, as I see, will be in these cases to prefix the class name with the namespace. Like 
```
[InverseProperty(nameof(myNamespace.ConfigFile.ConfigMetaObject))]
```

### Further technical details
EF Core version: 3.0.0-preview6.19304.10
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 preview 2

**Comment by bricelam** [comment]
I can see why our tests missed this: 😁

https://github.com/Muppets/EntityFrameworkCore/blob/4aba1717d297003b63a7ab58d4a7d5bbec7f44cb/test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs#L57-L58
