### ISSUE TITLE
More flexible database creation and existence check methods

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#161]
It is common with some database systems (in particular SQL Azure) to get an empty database provisioned and only create tables. With the current Create and Exists method this situation is not easy to handle, Exists will respond that the database exists but the application cannot use it without the tables.

Create already does both database and table creation but looking at this scenario we are worried about muddying the semantics of Exists (there are are actually very possible variations for checking tables, e.g. it could check if there "any table" or "any table from the model" or even "all tables of the model").

Tentative plan for now is (from Arthur's email):
- context.Database.Exists => True if database exists regardless of whether it has tables or not
- context.Database.HasTables => True if database exists and has tables (any tables, not just mapped ones)
- context.Database.Create => Creates the database but not the tables
- context.Database.CreateTables => Creates the tables in the database

Then one wrapper method for common case:
- context.Database.EnsureCreated => Creates the database and tables if necessary

Method names will be revisited, as well support for shared databases scenarios.

**Comment by ErikEJ** [comment]
@rowanmiller The current design does not work well with several DbContexts pointing to the same database https://github.com/ErikEJ/EntityFramework7.SqlServerCompact/issues/205
