### ISSUE TITLE
Only 1 entity materalized although generated SQL returns more rows

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#16165]
While working on set operations, I ran into a situation where generated SQL properly fetches 7 customers, but only one gets materialized. This can be reproduce with test Union_Include from https://github.com/roji/EntityFrameworkCore/tree/StateOfTheUnion.

Related to #15611 which generally tracks materialization.

/cc @maumar who already did some investigation on this.

**Comment by smitpatel** [comment]
outer key selector is busted.

**Comment by roji** [comment]
This went away in the new implementation of the nav expanding support for set operations (probably because there's no attempt to not terminate).
