### ISSUE TITLE
Query: collection.ToArray in projection

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#16318]
```C#
        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Cast_ordered_subquery_to_base_type_using_typed_ToArray(bool isAsync)
        {
            return AssertQuery<City>(
                isAsync,
                cs => cs.Where(c => c.Name == "Ephyra").Select(
                    c => c.StationedGears.OrderByDescending(g => g.Nickname).Select(
                        g => new Officer
                        {
                            CityOrBirthName = g.CityOrBirthName,
                            FullName = g.FullName,
                            HasSoulPatch = g.HasSoulPatch,
                            LeaderNickname = g.LeaderNickname,
                            LeaderSquadId = g.LeaderSquadId,
                            Nickname = g.Nickname,
                            Rank = g.Rank,
                            SquadId = g.SquadId
                        }).ToArray<Gear>()),
                assertOrder: true,
                elementAsserter: CollectionAsserter<Gear>(e => e.Nickname, (e, a) => Assert.Equal(e.Nickname, a.Nickname)));
        }
```
How our collection materialization in relational goes over multiple rows is,
We create the result and inject empty list (or collection if coming from navigation) for parts.
Then we iterate over and populate those collections. Once that is done, we return the result.

ToArray call is problematic since we create a list but ToArray is called on list before we populate it. So we need to call ToArray after populating collection. But the way to find out collection is populated is when we reach row for next result. So we don't have data to compute non-collection part of result. We could potentially create Array directly and resize it as we add elements.
Work-around: do anonymous projection followed by AsEnumerable. Then it can be converted to whichever is desired shape.

**Comment by ajcvickers** [comment]
Marking for triage, since ASP.NET app is hitting this.

**Comment by DamianEdwards** [comment]
We're seemingly getting hit by this in the ASP.NET Core app-building workshop codebase too:
https://github.com/dotnet-presentations/aspnetcore-app-workshop/blob/8d82b2482a47dca35b00f6a33d7202b3e018e939/src/BackEnd/Controllers/SessionsController.cs#L31
