### ISSUE TITLE
Remove cancellation token from CloseAsync APIs

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#16353]
This is my conclusion on the conversation started on https://github.com/dotnet/standard/pull/1283#discussion_r298295697. 

All in all, it seems that we are using CloseAsync for *cleanup* (e.g. in finally blocks) and it is hard to figure why passing the same cancellation token that you are passing to everything else is the wrong thing to do. Hence it is a pit of failure to have CancellationToken in the API. 

This should needs to be removed from the System.Data.Common types, but the removal should propagate to EF Core APIs as well. 

- In [MigrationCommandExecutor.ExecuteNonQueryAsync](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs#L142), we are using DbConnection.CloseAsync(CancellationToken) as part of finally block, and we are effectively passing the same CancellationToken we passed before to DbCommand.ExecuteNonQueryAsync. 

- In [RelationalTransaction.ClearTransactionAsync](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Storage/RelationalTransaction.cs#L352) we call CloseAsync(CancellationToken) on the connection, also passing the same cancellation token we pass to the previous call that does some work. 

- In [BatchExecutor.ExecuteAsync](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Update/Internal/BatchExecutor.cs#L168) same problem.

- In all the execute methods in [RelationalCommand](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Storage/RelationalCommand.cs) same problem.

- In [SqlServerDatabaseCreator.ExistsAsync](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs#L242) we call IRelationalConnection.CloseAsync without passing the cancellation token! I am not sure if we should call it an oversight :smile:

**Comment by roji** [comment]
PR for token removal in corefx: https://github.com/dotnet/corefx/pull/39070
