### ISSUE TITLE
Max<Valuetype?>/Min<ValueType?> throw when no rows

### ISSUE THREAD

**Issue by John0King** [aspnet/EntityFrameworkCore#16542]
using .net core Preview6 and EF Core 3.0.0-preview6.19304.10
```C#
var maxOrder = _db.Fields.Max(f=>(int?)f.Order);
```
This line of code throw  `sequence contains no element`

**Comment by smitpatel** [comment]
Throw on min/max should depend on type being nullable or not. Also check Avg/Sum.
