### ISSUE TITLE
EntityEquality generates type mismatch

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#16564]
Test: Contains_over_entityType_with_null_should_rewrite_to_identity_equality
```
                var query
                    = context.Orders.Where(o => o.CustomerID == "VINET")
                        .Contains(null);
```
```
bool Contains(
|__ source: IQueryable<Order> Where(
|   |__ source: DbSet<Order>, 
|   |__ predicate: (Order o) => o.CustomerID == "VINET"), 
|__ item: (Unhandled parameter: __p_0))

// Gets rewritten into

bool Contains(
|__ source: IQueryable<int> Select(
|   |__ source: IQueryable<Order> Where(
|   |   |__ source: DbSet<Order>, 
|   |   |__ predicate: (Order Param_0) => Param_0.CustomerID == "VINET"), 
|   |__ selector: (Order Param_0) => Property(Param_0, "OrderID")), 
|__ item: (Unhandled parameter: __entity_equality_p_0_OrderID))
```
here p0 is null so runtime generated parameter is also null. But value is being cast to int which is NRE. When rewriting key access on potentially null expression, it should convert the types to nullable.

**Comment by smitpatel** [comment]
Another case
```
IQueryable<Customer> Where(
|__ source: DbSet<Customer>, 
|__ predicate: (Customer c) => Order FirstOrDefault(IOrderedEnumerable<Order> OrderBy(
    |__ source: c.Orders, 
    |__ keySelector: (Order o) => o.OrderID)) == Order 10243)

**Comment by roji** [comment]
Sorry, my github email notifications are clearly not working well - missed this. Will check it out as soon as the preview7 port is done.

**Comment by roji** [comment]
@smitpatel I see the issue you're describing. However, the first test (Contains_over_entityType_with_null_should_rewrite_to_identity_equality) passes correctly - do you have another repro in mind for relational?

Will investigate the second failure.

Regardless, will wait on #16791 to get merged to avoid conflicts.

**Comment by smitpatel** [comment]
InMemory failure. The test is disabled for InMemory provider with this bug number.
