### ISSUE TITLE
Eager loaded navigations should apply Include during expansion phase

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#16619]
This happens in reduce phase. If we apply Count at the end then we don't need includes but projection still has them causing Count to fail since we are in client eval phase.

**Comment by maumar** [comment]
You need to apply include after you know the final projection, otherwise we will sometimes apply unnecessary ones. We have logic that clears includes from NavigationTree for some operations (e.g. All/Any) - perhaps it’s missing for count?

**Comment by smitpatel** [comment]
Apply here is in the sense of populating the tree. Which is happening in reduce phase so even though count removes the includes, reduce phase adds them back. The Include tree should be populated before reduce phase and generation of IncludeExpression should happen during reduce.
