### ISSUE TITLE
EF Core PS Module Manifest is duplicated internally 29 times

### ISSUE THREAD

**Issue by Psypher9** [aspnet/EntityFrameworkCore#16616]
Describe what is not working as expected.

I have been getting errors on the PMC when starting up my project for testing the work I'm doing for #577 and the first error is coming from `EFCore.Tools\tools\init.ps1`. The error says that `EntityFrameworkCore.psd1` did not result in a valid module manifest.
![image](https://user-images.githubusercontent.com/15854173/61306565-79bda600-a7b2-11e9-9c96-330a4bbe20a1.png)

I went and looked at the `.psd1` file in that location to see why it wasn't valid and the Manifest object was duplicated 29 times inside of the file. 

![image](https://user-images.githubusercontent.com/15854173/61307431-f00ed800-a7b3-11e9-8af7-426154670969.png)

The projects I've mainly been working in have been EFCore.Design and EFCore.Tools inside the .psm1 file, but I've not been doing anything with the build process. Could there be something I've done to affect the output module manifest?

### Steps to reproduce
The steps I took were:
- run `build -pack` in the EFCore folder
- Set `C:\<path_to_EFCore_dir>\artifacts\packages\Debug\Shipping` to my only package feed in VS
- close and re-open my test solution
- re-install the local packages I needed 
- Restart VS again
- Open the PMC

### Further technical details
EF Core version: 3.0.0-dev
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.1.3

**Comment by ajcvickers** [comment]
@Psypher9 Sorry for being slow responding to this. I've never seen this while working on EF. @bricelam might have some pointers, but it sounds like however you are changing the module it is not happening in a clean way.

**Comment by Psypher9** [comment]
Okay, cool. I'm not sure what I would be doing to cause that, but I will take another look. Any pointers on where to start would be very welcome! Thank you for looking in to it.

**Comment by ajcvickers** [comment]
@Psypher9 The workaround for now is to clean (e.g. `git clean -xdf`) and then re-build. We will look into fixing the underlying issue probably after 3.0 ships.

**Comment by bricelam** [comment]
I ran into this too when trying to port the replacement code to EF6. It might be as simple as adding `Overwrite="True"` to [this line](https://github.com/aspnet/EntityFrameworkCore/blob/8cf395bcae0e12563414a9477c6274066c50b555/src/EFCore.Tools/EFCore.Tools.csproj#L55).

I might make additional changes to the way we do this in EF6. I'll be sure to port my changes (and fixes) back to EF Core

**Comment by Psypher9** [comment]
Okay cool. I will give that a shot and let you know!

Thanks @bricelam!
