### ISSUE TITLE
Consolidate overloads in MigrationsSqlGenerator

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#16654]
I noticed that in MigrationsSqlGenerator we still have two overloads per operation, one receiving a `terminate` flag, and another which doesn't (and delegates to the first). Should we take this opportunity to clean this up, or is there some reason for this?

/cc @bricelam

**Comment by bricelam** [comment]
Hmm, in my head there are reasons, but they may be artificial. lol, we should investigate.

**Comment by roji** [comment]
@ajcvickers note that I added this to the 3.0 milestone and added labels. PR has already been merged.
