### ISSUE TITLE
Eliminate nullability-only Convert nodes 

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#16653]
Given the following query:

```c#
await AssertQuery<Order>(isAsync, os =>
    os.Select(o => new Order { OrderDate = o.OrderDate.Value }));
```

we get the following tree (since OrderDate is nullable):

```
value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Microsoft.EntityFrameworkCore.TestModels.Northwind.Order]).Select(o => new Order() {OrderDate = Convert(o.OrderDate.Value, Nullable`1)})
```

which makes us generate the following over-complicated SQL:

```sql
SELECT CAST(o."OrderDate" AS timestamp without time zone) AS "OrderDate" FROM "Orders" AS o
```

FWIW I think the old pipeline didn't have this useless cast.

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs#L543

There is already check in place to make sure if the convert node is converting from T to T?.

**Comment by smitpatel** [comment]
Fix reverted due to un-updated SQL baselines.
