### ISSUE TITLE
Nullable property is required if there is another not-nullable string property in model

### ISSUE THREAD

**Issue by SonicGD** [aspnet/EntityFrameworkCore#16760]
Hello. After i upgraded to preview7 from preview5 some of my queries started to throw exceptions cause of null values in database for nullable properties. I reproduced this in test project and there is something strange. I have `Nullable reference types` enabled.

### Steps to reproduce

Define model class

```c#
public class Bar
{
    [Key] public Guid Id { get; set; }
    public Guid? EmptyId { get; set; }
}
```
Now generate migration:
```c#
migrationBuilder.CreateTable(
    name: "Bars",
    columns: table => new
    {
        Id = table.Column<Guid>(nullable: false),
        EmptyId = table.Column<Guid>(nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Bars", x => x.Id);
    });
```

Property `EmptyId` has `nullable: true` as it should.

Now let's create another model with additional sting property

```c#
public class Foo
{
    [Key] public Guid Id { get; set; }
    public Guid? EmptyId { get; set; }
    public string SomeString { get; set; }
}
```
and generate new migration
```c#
migrationBuilder.CreateTable(
    name: "Foos",
    columns: table => new
    {
        Id = table.Column<Guid>(nullable: false),
        EmptyId = table.Column<Guid>(nullable: false),
        SomeString = table.Column<string>(nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Foos", x => x.Id);
    });
```
**Here property `EmptyId` has `nullable: false` for some reasons.**

If we change `SomeString` to nullable string

```c#
public class FooBar
{
    [Key] public Guid Id { get; set; }
    public Guid? EmptyId { get; set; }
    public string? SomeString { get; set; }
}
```
then both properties are correctly nullable:

```c#
migrationBuilder.CreateTable(
    name: "FooBars",
    columns: table => new
    {
        Id = table.Column<Guid>(nullable: false),
        EmptyId = table.Column<Guid>(nullable: true),
        SomeString = table.Column<string>(nullable: true)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_FooBars", x => x.Id);
    });
```

and if we move `EmptyId` to base class:

```c#
public abstract class BaseBaz
{
    public Guid? EmptyId { get; set; }
}

public class Baz : BaseBaz
{
    [Key] public Guid Id { get; set; }
    public string SomeString { get; set; } = default!;
}
```

it will be nullable:

```c#
migrationBuilder.CreateTable(
    name: "Bazes",
    columns: table => new
    {
        Id = table.Column<Guid>(nullable: false),
        EmptyId = table.Column<Guid>(nullable: true),
        SomeString = table.Column<string>(nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Bazes", x => x.Id);
    });
```

### Further technical details
EF Core version: 3.0.0-preview7.19362.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer and Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10 18941
IDE: dotnet cli

**Comment by ajcvickers** [comment]
@roji Looks like our first bug with nullable reference types!

**Comment by roji** [comment]
@SonicGD thanks for reporting! Your sample indeed exposed some bugs in the nullability handling, have submitted a PR with the fixes. Hopefully you can continue testing with the preview8 nightlies once that's merged!
