### ISSUE TITLE
Remove provider prefix from low-level metadata APIs

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#16773]
In #16686 we removed all provider prefixes from builder extension methods, but the low-level metadata APIs have been left as-is. Discuss and decide whether we want to drop the prefix there as well.

**Comment by ajcvickers** [comment]
@AndriySvyryd Thoughts?

**Comment by AndriySvyryd** [comment]
I think it makes even more sense for this API as collisions are very unlikely.
