### ISSUE TITLE
Cleanup or back-out support for column/table comments

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#16819]
Several issues with the implementation have been found--see #16800 #16799 #16808

Given where we are in the 3.0 schedule, we may need to back this out since this is not a priority feature.

**Comment by bricelam** [comment]
TODO:
- [ ] Remove MigrationsSqlGenerator.GenerateComment() (let providers handle comments however is best for them)
- [ ] Test model differ with comments more
- [ ] Update AlterTableOperation.OldTable to return TableOperation (mirroring ColumnOperation)

**Comment by roji** [comment]
Cleaned up the implementation, fixing #16800, #16794.

We have #16798 for tracking AlterTableOperation.OldTable.

**Comment by ErikEJ** [comment]
How about the reverse engineering part?

**Comment by roji** [comment]
@ErikEJ for now I think support can stay in, including the reverse engineering - the important issues have been fixed AFAIK, it's mostly a matter of better table alteration with AlterTableOperation.OldTable. So I wouldn't worry about it..

**Comment by bricelam** [comment]
@ErikEJ Your RevEng changes looked great to me, and Andriy did a through review of the metadata changes. Somehow, I failed to properly review the Migrations changes. (Too heads-down on EF6)

**Comment by smitpatel** [comment]
Missing labels
