### ISSUE TITLE
InMemory: FirstOrDefault is not working

### ISSUE THREAD

**Issue by razfriman** [aspnet/EntityFrameworkCore#16825]
`FirstOrDefault` linq on queries (`InMemory`) is still not working in preview 7.

I assumed since preview-7 was released this would be fixed. If not, is there anywhere that this is being tracked?

If you are seeing an exception, include the full exceptions details (message and stack trace).
```
Exception message:  System.NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
System.NullReferenceException: Object reference not set to an instance of an object.
    at lambda_method(Closure , QueryContext , ValueBuffer )
    at Microsoft.EntityFrameworkCore.InMemory.Query.Pipeline.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
    at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
    at RazzleServer.Login.Maple.LoginAccount.Load() in /Users/razfriman/CODE/razzle-server/RazzleServer.Login/Maple/LoginAccount.cs:line 21
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Created a branch in my open project for reproducing the issue, also extracted out the single passing/failing test for simplicity.

https://github.com/razfriman/RazzleServer/blob/raz/update-7/RazzleServer.Tests/LoginClientIntegrationTest.cs#L25

```c#
        [TestMethod] // Fails
        public void testFirstOrDefault()
        {
            using var dbContext = new MapleDbContext();
            var account = dbContext.Accounts.FirstOrDefault(x => x.Username == "abc");

        }
        
        [TestMethod] // Passes
        public void testFirstOrDefaultAfterMaterializing()
        {
            using var dbContext = new MapleDbContext();
            var account = dbContext.Accounts.ToList().FirstOrDefault(x => x.Username == "abc");

        }
```

### Further technical details
.NET Core version: `preview 7`
EF Core version: (found in project.csproj or packages.config)
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0-preview7.19362.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="3.0.0-preview7.19362.6" />
        <PackageReference Include="System.ComponentModel.Annotations" Version="4.6.0-preview7.19362.9" />
```
Operating system: Mac `OSX 10.14.5`
IDE: (e.g. Visual Studio 2017 15.4) `.NET Core CLI`

**Comment by smitpatel** [comment]
This should be fixed in nightlies.

**Comment by smitpatel** [comment]
SingleOrDefault is implementation detail and not the translation.

**Comment by Euphoric** [comment]
@smitpatel Hi. Can you link to the PR that fixes this?

**Comment by ajcvickers** [comment]
Verified fixed with nightlies.

@Euphoric There are many PRs that have contributed to this, but I suspect #16576 is the main one for this specific issue.
