### ISSUE TITLE
SqliteConnection.RemoveCommand() does not appear to work

### ISSUE THREAD

**Issue by pHr34kY** [aspnet/EntityFrameworkCore#16903]
When SqliteConnection.CreateCommand() is called, it calls the internal AddCommand() function. When the SqliteCommand is disposed of, RemoveCommand() is called.

It seems that RemoveCommand() does not actually remove the command, causing SqliteConnection._commands to grow over the life of the connection. For my purposes, the connection lifetime can be months, with multiple transactions each second. This makes the leak quite noticeable (I've seen >1GB per day).

To replicate the problem:

```
for (var i = 0; i < 100; i++)
{
    var command = connection.CreateCommand();
    command.Dispose();
}
```
After running this code, connection._commands has 100 more commands in the list, despite all the commands being disposed of.

The behaviour of RemoveCommand() iterates this entire list each time it is called, so this likely leaks CPU as well as memory.

### Further technical details
EF Core version: 2.2.6
Database Provider: Sqlite
Operating system: Windows 10 Pro for Workstations 1903 x64
IDE: Visual Studio 2017 15.9.12

**Comment by ajcvickers** [comment]
@pHr34kY Could you try your code against the 3.0 preview 7 release? We has been considerable work in this area since 2.2.6. If you still see a problem, then please create a small, runable project/solution or complete code listing so that we can fully investigate.

**Comment by pHr34kY** [comment]
> @pHr34kY Could you try your code against the 3.0 preview 7 release? We has been considerable work in this area since 2.2.6. 

I don't have VS2019 or NetCore3.0 installed on my dev PC, so it would be a considerable effort to test this. A quick 'git blame' shows the related functions haven't been touched in years.

**Comment by bricelam** [comment]
I'm not able to repro this on the latest codebase.
``` csharp
[Fact]
public void Issue16903()
{
    using (var connection = new SqliteConnection("Data Source=:memory:"))
    {
        for (var i = 0; i < 100; i++)
        {
            var command = connection.CreateCommand();
            command.Dispose();
        }

        var commands = (IEnumerable)typeof(SqliteConnection)
            .GetField("_commands", BindingFlags.Instance | BindingFlags.NonPublic)
            .GetValue(connection);

        Assert.Empty(commands);
    }
}
```

**Comment by pHr34kY** [comment]
Thanks, Brice.

The same assertion fails on v2.2.6. Perhaps it is already fixed.
