### ISSUE TITLE
Coalesce with not equal unexpected SQL translation

### ISSUE THREAD

**Issue by ickers** [aspnet/EntityFrameworkCore#16955]
Evaluation of simple LINQ expression involving null coalescing operator and subsequent primitive not-equals comparison within predicate returns an unexpected result set.

Given data saved:
```c#
context.Data.Add( new Data { Name = "HasTestId", TestId = 123 } );
context.Data.Add( new Data { Name = "ZeroTestId", TestId = 0 } );
context.Data.Add( new Data { Name = "NullTestId", TestId = null } );
context.SaveChanges( );
```
the LINQ
```c#
context.Data.Where( o => (o.TestId ?? 0) != 0 ).Select( o => o.Name )
```
evaluates to the result `[ "HasTestId", "NullTestId" ]` instead of the expected `[ "HasTestId" ]`. This is because the above LINQ is compiled by EF Core to the SQL:
```sql
SELECT "o"."Name"
FROM "Data" AS "o"
WHERE (COALESCE("o"."TestId", 0) <> 0) OR "o"."TestId" IS NULL
```
The extraneous `OR "o"."TestId" IS NULL` added to the `WHERE` clause seems incorrect IMHO. Interestingly, by switching the predicate from `!=` to `==` the LINQ evaluates to the expected result `[ "ZeroTestId", "NullTestId" ]`.

### Steps to reproduce

Clone repro project at ickers/ef-core-coalesce-not-equal-query@6d5af16c61465fe444922cfbb4dd6f33a6f33bd7 (multi-targeted project for `netcoreapp2.0/ef-core-2.0.3`, `netcoreapp2.1/ef-core-2.1.11`, `netcoreapp2.2/ef-core-2.2.6` - issue is reproducible in all three runtime/EF Core versions).

### Further technical details
EF Core version: `2.2.6`, `2.1.11`, `2.0.3`
Database Provider: `Microsoft.EntityFrameworkCore.Sqlite` (originally observed with `Microsoft.EntityFrameworkCore.SqlServer`)
Operating system: Linux Mint 18
IDE: VS Code 1.36 (originally observed with Visual Studio 2017 15.4)

**Comment by maumar** [comment]
Looks like Bug in null semantics

**Comment by maumar** [comment]
fixed in https://github.com/aspnet/EntityFrameworkCore/commit/dd92ba3dc60186cb1a36a925824f660da92d8f42
