### ISSUE TITLE
Query: Should weak entites be tracked?

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#16999]
#13036 made them non-trackable without "owner". We need to re-discuss when @AndriySvyryd  is back.

**Comment by salaros** [comment]
[This PR breaks](https://github.com/aspnet/EntityFrameworkCore/pull/16997/files#r311329201) completely scenarios when entity inherit owned entities from the base class:

```csharp
[Owned]
public class OwnedEntity
{
	public string Prop { get; set; }
}

public class A 
{
	public string Foo { get; set; }
}

public class B : A
{
	public string Bar { get; set; }
}

// ...

builder
	.OwnsOne(a => a.AuditLog); //<-- works only for base type

// ...

await dbContext.Set<B>().SingleOrDefaultAsync(e => e.Bar == bar); //<-- throws InvalidOperationException
```

**Comment by smitpatel** [comment]
@salaros - Thanks for reporting. Filed #18024 to track the bug.
