### ISSUE TITLE
Query: Service scope for new query dependency objects

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#17000]
`ShapedQueryOptimizerDependencies` is scoped but
`RelationalShapedQueryOptimizerDependencies` is singleton.
Some of them are empty for future breaks. What should be scope for such empty service?

And issue 17k.

**Comment by ajcvickers** [comment]
@smitpatel Almost always the dependency object should have the same scoping as the service that uses it.

**Comment by smitpatel** [comment]
How would you define scope of the service which has no dependencies right now? It can be made Singleton but should be made scoped for future-proofing? Should the decision be made based on the another service which utilizes this service?
