### ISSUE TITLE
HasCheckConstraint() in model is entirely missing in SQL database

### ISSUE THREAD

**Issue by SidShetye** [aspnet/EntityFrameworkCore#17052]
ModelBuilder's Entity's HasCheckConstraint() is not reflected in the SQL database.

### Steps to reproduce

```c#
// example
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    // ...
    modelBuilder.Entity<MyEntity>(entity =>
    {
        // ...
        entity.HasCheckConstraint("CK_ONLY_ONE_NULL", "[Column1] IS NULL AND [Column2] IS NOT NULL OR [Column1] IS NOT NULL AND [Column2] IS NULL");
        // ...
    }
}
```
### Result
The `CK_ONLY_ONE_NULL` constraint isn't in the local db database

### Expectation
The `CK_ONLY_ONE_NULL` constraint is reflected in the database tables

The `HasCheckConstraint` extension (undocumented anywhere so far) is in `.nuget\packages\microsoft.entityframeworkcore.relational\3.0.0-preview7.19362.6\lib\netstandard2.1\Microsoft.EntityFrameworkCore.Relational.dll` namespace `Microsoft.EntityFrameworkCore` extension class `RelationalEntityTypeBuilderExtensions`

### Further technical details
EF Core version: `3.0.0-preview7.19362.6`
Database Provider: `Microsoft.EntityFrameworkCore.SqlServer`
Operating system: Windows 10 x64 v1904
IDE: Visual Studio 2019 16.2.1

**Comment by ajcvickers** [comment]
Note for triage: I was able to reproduce this; nothing is generated in to the migration.

**Comment by ajcvickers** [comment]
@roji to check for any additional tests.

**Comment by roji** [comment]
Reopening to track a final review of checked constraint support for any bugs/missing tests.

**Comment by roji** [comment]
Gave this another look and it seems OK to me.

**Comment by SidShetye** [comment]
@roji - How did you verify this was fixed before closing this issue? Even on preview 8 the check constraint is NOT reflected in the SQL database as per the original bug report.

```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0-preview8.19405.11" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0-preview8.19405.11" />


> dotnet ef --version
Entity Framework Core .NET Command-line Tools
3.0.0-preview8.19405.11
```

If you need more information to support your efforts, where are the progressive stages on how the check constraints are flowing ...

1. `ApplicationDbContext.cs` : Entities have `HasCheckConstraint(..)` 
2. `ApplicationDbContextModelSnapshot.cs`: Entities have `HasCheckConstraint(..)` 
3. `<date_migration_name>.Designer.cs`: Entities have `HasCheckConstraint(..)` 
4. SQL database tables do **NOT** have check constraint (as per original bug report)

For step 4, you can try either `dotnet ef migrations script -o MigrationScript.sql` to examine the SQL script or directly issue `dotnet ef database update` and look at the database directly. Either ways, the check constraint is missing.

Please re-open.

**Comment by ajcvickers** [comment]
@SidShetye This is not fixed in preview 8. Please try the [daily builds](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md)

**Comment by ajcvickers** [comment]
@SidShetye FYI, if it were fixed in preview 8, then the milestone would be "3.0.0-preview8".

**Comment by SidShetye** [comment]
@ajcvickers : Thanks, tried daily `3.0.0-preview9.19419.2` and confirmed that the bug is fixed there.

**Comment by Pzixel** [comment]
Have this issue in 5.0.5. Any suggestions?
