### ISSUE TITLE
Query: Can't always override RelationalQueryableMethodTranslatingExpressionVisitor

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#17156]
[This line](https://github.com/aspnet/EntityFrameworkCore/blob/22711701cc41d53cb21350634246b30caf57033b/src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs#L78) creates a `RelationalQueryableMethodTranslatingExpressionVisitor` directly and doesn't let the provider use its own implementation.

**Comment by ajcvickers** [comment]
Try using a factory.
