### ISSUE TITLE
please add feature `DateDiffWeek` extension for mssql

### ISSUE THREAD

**Issue by WeihanLi** [aspnet/EntityFrameworkCore#17170]
Please add feature `DateDiffWeek` DbFunctions extension for mssql

<https://github.com/aspnet/EntityFrameworkCore/blob/release/3.0/src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs>
<https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-2017>

**Comment by ralmsdeveloper** [comment]
@ajcvickers 

can i pull this for me?

**Comment by ajcvickers** [comment]
@ralmsdeveloper Go for it, but keep in mind that it won't be included in 3.0 (closing down) or 3.1 (new features are not allowed 🤷‍♂).

**Comment by ErikEJ** [comment]
No new feature in 3.1 ??

**Comment by arek-avanade** [comment]
@bricelam Is this going to be included in EF Core 5? Why so late?

**Comment by bricelam** [comment]
EF Core 5 is then next release after 3.1
