### ISSUE TITLE
Query: Disallow client evaluation of queryable methods in projection

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#17264]
If subquery in projection fails to translate we try to client eval outside of Select in subquery. Which is against the design. (As a where which did not go to server will fetch extra data).

**Comment by smitpatel** [comment]
This may have been fixed by @ajcvickers changes for client eval exception. Relevant tests are in `BuiltInDataTypesSqliteTest` tagged with issue #15249

**Comment by smitpatel** [comment]
Also this needs to go in 3.0

**Comment by ajcvickers** [comment]
Taking a look.

**Comment by smitpatel** [comment]
After re-thinking, realized that existing change wouldn't fix this. 
https://github.com/aspnet/EntityFrameworkCore/blob/ba5c3f768bb2cefcf6d84e0a6edc7dc1a12c6649/src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs#L298-L313

Above block is supposed to throw when failing to translate. (It is bit different pattern though we are also short-circuiting using queryable method translator when translating queryable methods)
