### ISSUE TITLE
Query: FirstOrDefault on anonymous type in subquery gives wrong results

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#17287]
We initialize the new Expression with default values rather than returning null.
Uncovered while discovering that we didn't take care of returning default part. It worked on top level since there was no row.

**Comment by fschlaef** [comment]
I ran into this issue with 3.0.0-rc1, it is very annoying.
Can a fix be expected before 3.1.0 ? This seems like a major regression.

**Comment by yepeekai** [comment]
we came accross this.  happy to see it will be corrected for 3.1.  Do you know if there is a quick fix I could use in the meanwhile?

**Comment by fschlaef** [comment]
@smitpatel Confirmed fixed as of `3.1.0-preview3.19554.8` 👍
