### ISSUE TITLE
Contains on IList/HashSet/ImmutableHashSet will throw exception

### ISSUE THREAD

**Issue by andtii** [aspnet/EntityFrameworkCore#17342]
Describe what is not working as expected.

When using the interface IList instead of List and doing Contains you will get the exception

```
Exception message:
Operation is not valid due to the current state of the object.
Stack trace:
```

### Steps to reproduce

```c#
This code will throw the exception since its an IList we use Contains against
  var rolesId = new List<Guid> {
                new Guid("cb6b6945-15d7-4596-b3cb-52ab3560600e"),
                new Guid("b5f963cd-a24a-45be-bc9f-60f30ac1af89"),
            } as IList<Guid>;

            var res = _dbSet
            .Where(r => rolesId.Contains(r.Id));

This code works since its a List
  var rolesId = new List<Guid> {
                new Guid("cb6b6945-15d7-4596-b3cb-52ab3560600e"),
                new Guid("b5f963cd-a24a-45be-bc9f-60f30ac1af89"),
            };

            var res = _dbSet
            .Where(r => rolesId.Contains(r.Id));
```

### Further technical details
EF Core version: 3.0.0-preview8.19405.11
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.0 Preview 2.0

**Comment by smitpatel** [comment]
Our current code indeed work on IList rather than List.
https://github.com/aspnet/EntityFrameworkCore/blob/cd072b6bd2bcab1d692377de3431c30405bc0c68/src/EFCore.Relational/Query/Internal/ContainsTranslator.cs#L33-L34
Would need investigation to understand why it is not translated.

**Comment by ajcvickers** [comment]
@andtii Can you post the stack trace?

**Comment by smitpatel** [comment]
So `IList<T>` does not implement `IList` but implements `ICollection<T>` hence we fail to translate.

**Comment by smitpatel** [comment]
And List<T> implements `IList<T>` and `IList` both. I guess better match to check for IList<T>.Contains

**Comment by andreichuk** [comment]
@smitpatel the latest code (3.1 preview) still fails when `Contains` method of `HashSet<>`, `ImmutableHashSet<>` collections is used in LINQ.

I changed `Translate` method of `Microsoft.EntityFrameworkCore.Query.Internal.ContainsTranslator` class to support types that are `IList` or `ICollection<>` or implement those interfaces. Please check the code below:

```csharp
public virtual SqlExpression Translate(SqlExpression instance, MethodInfo method, IReadOnlyList<SqlExpression> arguments)
{
    if (method.IsGenericMethod
        && method.GetGenericMethodDefinition().Equals(EnumerableMethods.Contains))
    {
        return _sqlExpressionFactory.In(arguments[1], arguments[0], false);
    }

    // early return
    if (string.Equals(method.Name, nameof(IList.Contains)) == false)
    {
        return null;
    }

    // check if it is or has IList interface
    if (typeof(IList).IsAssignableFrom(method.DeclaringType))
    {
        return _sqlExpressionFactory.In(arguments[0], instance, false);
    }

    // check if it is ICollection<> interface
    if (method.DeclaringType.IsGenericType
        && method.DeclaringType.GetGenericTypeDefinition() == typeof(ICollection<>))
    {
        return _sqlExpressionFactory.In(arguments[0], instance, false);
    }

    // check if it has ICollection<> interface
    var hasICollectionInterface =
        method.DeclaringType.GetInterfaces()
            .Where(t => t.IsGenericType)
            .Select(t => t.GetGenericTypeDefinition())
            .Any(t => t == typeof(ICollection<>));

    if (hasICollectionInterface)
    {
        return _sqlExpressionFactory.In(arguments[0], instance, false);
    }

    return null;
}
```

**Comment by smitpatel** [comment]
@roji - Can you look into above? We want to make sure that ContainsTranslator handles all generic collection types. (no need to put a lot of effort for exhaustive search, just the ones mentioned in this thread should be good enough)

**Comment by roji** [comment]
Sure @smitpatel, will do that tomorrow.

**Comment by roji** [comment]
@smitpatel ended up simply implementing what you originally proposed: https://github.com/aspnet/EntityFrameworkCore/issues/17342#issuecomment-525417356. Now any one-argument method names Contains on any type which implements ICollection<> will be matched.

Continuing to track via this issue, but tell me if you prefer a new one.
