### ISSUE TITLE
EF.Functions.Like no longer works when casted.

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/EntityFrameworkCore#17389]
Describe what is not working as expected.
`EF.Functions.Like(*,*)` is no longer working in version Version="3.0.0-preview8.19405.11" but only if the firstparameter is casted for example:
```cs
context.Set<MyEntity>().Where(e => EF.Functions.Like((string)(object)e.IntCol, "%1%"))
```
Further technical details
EF version:Version="3.0.0-preview8.19405.11
Database Provider: EntityFramework.SqlServer
Operating system: 10

**Comment by lauxjpn** [comment]
I just stumbled across this bug while upgrading the Pomelo provider to 3.0 and was just about to suggest something like changing this line
https://github.com/aspnet/EntityFrameworkCore/blob/130fe39bed1c9351ba73a829aa14a6112108a6b2/src/EFCore.Relational/Query/ExpressionExtensions.cs#L16
into this
```c#
if (sql?.TypeMapping != null)
```
I will apply the `match` type mapping manually for now, but is the fix commit still making the 3.0 release?

**Comment by smitpatel** [comment]
It will be part of 3.1 release.

**Comment by zulander1** [comment]
I am running Entity Framework Core 3.1.0-preview2.19525.5. I don't think this is resolved !

```
   var test = await _dbContext.Imports.Select(x => new
            {
                x.Id
            }).Where(x => EF.Functions.Like(x.Id.ToString(), "%1%")).ToListAsync();

```


Microsoft.EntityFrameworkCore.Infrastructure: Information: Entity Framework Core 3.1.0-preview2.19525.5 initialized 'dbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Object reference not set to an instance of an object.

Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Object reference not set to an instance of an object.

**Comment by ajcvickers** [comment]
@zulander1 I am not able to reproduce this--see my code below. Please open a _new_ issue and include a small, runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

```C#
public class Import
{
    public int Id { get; set; }
}

public class BloggingContext : DbContext
{
    private readonly ILoggerFactory Logger = LoggerFactory.Create(c => c.AddConsole());

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    public DbSet<Import> Imports { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Import());
            context.SaveChanges();
        }

        using (var context = new BloggingContext())
        {
            var test = await context.Imports.Select(x => new
            {
                x.Id
            }).Where(x => EF.Functions.Like(x.Id.ToString(), "%1%")).ToListAsync();
        }
    }
}
```

SQL:
```sql
SELECT [i].[Id]
FROM [Imports] AS [i]
WHERE CONVERT(VARCHAR(11), [i].[Id]) LIKE N'%1%'
```

**Comment by zulander1** [comment]
@ajcvickers nerve mind. There was something wired going with the project... Re-installed package to all project.. all working thanks

**Comment by Xriuk** [comment]
I feel like I have something similar here, not sure if I can provide a reproduction, though.
I have a `Dictionary<string, string>` property with a value converter to a string
And if I have a query like this:
```csharp
.Select(s => ((string)(object)s.Parameters).IndexOf("..."))
```
it throws a NullReferenceException:
Object reference not set to an instance of an object.
   in Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerStringMethodTranslator.TranslateIndexOf(SqlExpression instance, MethodInfo method, SqlExpression searchExpression, SqlExpression startIndex) in /_/src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs: riga 315

Generally, if ExpressionExtensions.InferTypeMapping returns null [here](https://github.com/dotnet/efcore/blob/8bf0f7f2a920e697fffe3c2c9945321859fb550e/src/EFCore.SqlServer/Query/Internal/Translators/SqlServerStringMethodTranslator.cs#L223) no default type mapping is created/retrieved.

**Comment by roji** [comment]
@Xriuk this issue has been closed for 7 years; if you can do a minimal repro for this, please open a new issue.
