### ISSUE TITLE
Entity comments overwrites property comments

### ISSUE THREAD

**Issue by smint80** [aspnet/EntityFrameworkCore#17474]
In EF Core 3.0.0-rc1.19426.7 when adding an entity comment like:
``` cs
public void Configure(EntityTypeBuilder<Country> builder)
{
builder.HasComment("Table of countries with ISO 3166 codes");
}
````
the generated migration will have this comment on every column not only on the table:

``` cs
            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false, comment: "Table of countries with ISO 3166 codes")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.Id)
                        .Annotation("SqlServer:Clustered", true);
                },
                comment: "Table of countries with ISO 3166 codes");
```

Also if comments are added to properties/columns they will be overwritten.

**Comment by smint80** [comment]
I just noticed that the snapshot is correct. The error is only in the migration

**Comment by bricelam** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/a6760b64ec175acda64beb5c2d1f185657cf0304/src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs#L1064-L1069

**Comment by 404Prachi** [comment]
Migration is not getting added due to "Object reference not set to an instance of an object" error ..
please help

**Comment by omidrah** [comment]
please **remove** **HasComment** from DBContext
