### ISSUE TITLE
Update external dependencies to latest GA releases

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#17482]
- ~~System.Threading.Tasks.Extensions (4.5.2)~~
https://github.com/aspnet/EntityFrameworkCore/blob/release/3.0/src/EFCore/EFCore.csproj#L27

- Castle.Core (4.2.1)
https://github.com/aspnet/EntityFrameworkCore/blob/release/3.0/src/EFCore.Proxies/EFCore.Proxies.csproj#L19

- Microsoft.Azure.Cosmos (3.0.0)
https://github.com/aspnet/EntityFrameworkCore/blob/release/3.0/src/EFCore.Cosmos/EFCore.Cosmos.csproj#L25

- SQLitePCLRaw (2.0.1)

**Comment by ajcvickers** [comment]
/cc @AndriySvyryd for Cosmos
@bricelam Can you take a look at the other two?

/cc @JunTaoLuo

**Comment by AndriySvyryd** [comment]
Cosmos is already at 3.0.0 https://github.com/aspnet/EntityFrameworkCore/blob/release/3.0/eng/Versions.props#L15

**Comment by ajcvickers** [comment]
@AndriySvyryd Right, but there is a 3.1.1 package now.

**Comment by AndriySvyryd** [comment]
I'm not sure we should upgrade unless we need to, users can always bump it up manually.

**Comment by ajcvickers** [comment]
@AndriySvyryd Can you try to find out what they fixed between 3.0 and 3.1.1? There might be critical issues that we should update for.

**Comment by bricelam** [comment]
System.Threading.Tasks.Extensions is for downlevel ValueTask. We can dump it.

**Comment by ajcvickers** [comment]
@bricelam Looks like our Castle.Core is quite old; given that it only impacts proxies and test coverage is pretty good I think we should update this for 3.0 as well. Thoughts?

**Comment by bricelam** [comment]
Agreed, fine to leave. Release notes:
https://github.com/castleproject/Core/releases/tag/v4.3.0
https://github.com/castleproject/Core/releases/tag/v4.3.1
https://github.com/castleproject/Core/releases/tag/v4.4.0

**Comment by ajcvickers** [comment]
@bricelam So you think we _should_ or _should not_ update our Castle reference?

**Comment by bricelam** [comment]
Oh, lol. Either way--it's low risk *and* low value. 😉

**Comment by ajcvickers** [comment]
@bricelam I read through the release notes in more detail. Let's leave as is for now, but we should update for 3.1 or at the latest 5.0.

**Comment by bricelam** [comment]
Our analyzer depends on Microsoft.CodeAnalysis.CSharp.Workspaces. Is it safe to update this package? We really only need to work with the version of Roslyn that ships in VS2019 16.3 and the .NET Core 3.0 SDK, right?

**Comment by bricelam** [comment]
Filed #17625
