### ISSUE TITLE
Not sure about the "returns", isn't this method meant to re-enable tracking?

### ISSUE THREAD

**Issue by AndrewMutation** [aspnet/EntityFrameworkCore#17532]
Returns
IQueryable&lt;TEntity&gt;
A new query where the result set will not be tracked by the context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70c79f4-2309-e89f-1e6c-36cc32b414bd
* Version Independent ID: 5aa3fc5e-a518-6940-13e8-76f14a483d93
* Content: [EntityFrameworkQueryableExtensions.AsTracking(IQueryable&lt;TEntity&gt;) Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.astracking?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by divega** [comment]
Fixed this in 5ff0281. Unfortunately there isn't a good way to make the change retroactive to previous versions, AFAIK.
