### ISSUE TITLE
Re-introduce detection for non-composable SQL in FromSql

### ISSUE THREAD

**Issue by JulienM28** [aspnet/EntityFrameworkCore#17558]
.Net core 3 preview 8

````csharp
  HomeCarouselViewModel viewModel = await _context.Set<HomeCarouselViewModel>().FromSqlRaw("EXEC GetHomeCarousel").AsNoTracking().FirstOrDefaultAsync(); 
````
I get this exception:
Incorrect syntax near the keyword 'EXEC'

Worked perfectly with ef core 2.2

**Comment by ErikEJ** [comment]
Maybe need to use **dbo.GetHomeCarousel**

**Comment by JulienM28** [comment]
No it doesn't change anything.

Thanks.

**Comment by ajcvickers** [comment]
Notes from triage: The code to detect non-composable SQL was removed in 3.0, since ideally we would not parse any SQL. However, if this catches enough people out, then we will consider re-introducing it. Putting this in backlog to gather votes/feedback.

**Comment by JulienM28** [comment]
Thanks,
Since you do that, how to use stored procedure through EF ?

**Comment by ajcvickers** [comment]
Re-marking for triage. What is the composition here? I assume it's `FirstOrDefault`? But then I'm left thinking that `FirstOrDefault` is not an unreasonable thing to "client-eval" here, since it means take the first result from the reader, if there is one, and return it.

**Comment by ethos-tim** [comment]
I am porting and running into this with `FirstOrDefault` AND `Select` on a `FromSqlRaw` it is trying to add a `SELECT TOP(1)` or change the column list ON TOP of my stored procedure. Adding an `AsEnumerable `or `ToList` before the  `FirstOrDefault` or `Select` fixes the issue - however it was very frustrating to find and I had to run SQL Profiler to figure it out. The error it was throwing was `Incorrect syntax near '@p0'`. Perhaps have a flag that allows the user to indicate "Don't mess with my SQL - just run it as is"

**Comment by ethos-tim** [comment]
> Thanks,
> Since you do that, how to use stored procedure through EF ?

Try: 

 HomeCarouselViewModel viewModel = await _context.Set<HomeCarouselViewModel>()
.FromSqlRaw("EXEC GetHomeCarousel")
.AsNoTracking()
.AsEnumerable()
.FirstOrDefaultAsync();

**Comment by smitpatel** [comment]
> "Don't mess with my SQL - just run it as is".

There is very easy way to do this.
`_context.Set<T>().FromSqlRaw(.....).AsEnumerable()`
Put AsEnumerable right after FromSqlRaw and EF will not try to do any composition.

**Comment by JulienM28** [comment]
Thanks.
In effect it works:
````csharp
 HomeCarouselViewModel viewModel =  _context.HomeCarouselViewModel.FromSqlRaw("EXECUTE GetHomeCarousel").AsNoTracking().AsEnumerable().FirstOrDefault();
````

But it's synchronous. In order to use Asynchronous operation I Thought I could use AsEnumerableAsync() but 

````csharp
    HomeCarouselViewModel viewModel = _context.HomeCarouselViewModel.FromSqlRaw("EXECUTE GetHomeCarousel").AsNoTracking().AsAsyncEnumerable().GetAsyncEnumerator().Current;
````
returns null.

**Comment by ErikEJ** [comment]
Did you forget await ?

**Comment by smitpatel** [comment]
Step-by-step
- `AsAsyncEnumerable()` gives you `IAsyncEnumerable<>`, an async enumerable
- `GetAsyncEnumerator()` gives you `IAsyncEnumerator<>`, an async enumerator over previous enumerable
- Calling into `Current` will give you current element in enumerator but before you call into `Current` you need to call `MoveNextAsync`.

You have initialized your enumerator but haven't moved it yet so `Current` is null (or default value).

**Comment by paillave** [comment]
FYI there is no way what so ever to get any dataset from a stored procedure that returns a type that inherits from another one:
``` csharp
var result = this.Context.Set<MyEntity>().FromSqlRaw($"EXECUTE MyStoredProcedure").AsEnumerable().ToList();
```
The definition looks like this:
``` csharp
```
Whatever I do, it will always compose the call of my stored procedure:
FYI: I suppose it tries to compose it feels the need to wrap it in such a way to ensure it gets the right type, but it is obviously wrong:
``` sql
SELECT 
  [p].blabla1, 
  [p].blabla2
FROM (
    EXECUTE MyStoredProcedure
) AS [p]
WHERE ([p].[Discriminator] = N'MyEntity')
```

> Is there a way to have the code executed **AS IS** (no `sort`, no any `where` clause that would disturb the order of the dataset...), and blindly map to the columns that are setup in the entity setup?

Prior EF core 3.0, wrapping the sql statement within a `sql_execute` did the trick. But this doesn't work anymore as it tries to compose anyway.

I perfectly get the point of composition, and it is a fantastic feature to combine custom code with Linq operators. But it happens *(in some specific cases)* that we actually simply need EF mapping feature. 

I understand that amending existing freshly neat and clear methods would jeopardize stability and clarity of its behavior, so I suppose it is very reasonable to assume that `FromSqlRaw`, `FromSqlInterpolated` or `FromSql` will always be composed as they are meant to be combined with Linq operations.

For everything else, you could simply expose another method that permits to build a collection of entities from a DataTable, a **free** sql statement (or anything that you believe is better) based EF mapping specifications as this feature must already already exist somewhere within EF core. No confusion as the distinction would be crystal clear, and everybody (EF team and developers) would be satisfied.

**Comment by thassan1977** [comment]
this worked for me just fine

 string sqlQuery = "EXEC [dbo].[PaperBatch_INSERT] @UserName,@SupplierID,@OrderNo,@RecvDat,@FromNo,@ToNo,@Notes";
 
resp = this.SPResponse.FromSqlRaw(sqlQuery, 
                                                 p_UserName, p_SupplierID,
                                                 p_OrderNo, p_RecvDat, 
                                                 p_FromNo, p_ToNo, p_Notes)
                    .AsNoTracking().AsEnumerable().FirstOrDefault();

**Comment by lixaotec** [comment]
> Re-marking for triage. What is the composition here? I assume it's `FirstOrDefault`? But then I'm left thinking that `FirstOrDefault` is not an unreasonable thing to "client-eval" here, since it means take the first result from the reader, if there is one, and return it.

It should works like that. It seem so odd to workaround with AsEnumarable.
