### ISSUE TITLE
Adding multiple entities before SaveChanges() results in only the last one being saved

### ISSUE THREAD

**Issue by ite-klass** [aspnet/EntityFrameworkCore#17577]
I am so confused why `Add()` `Add()` `SaveChanges()` will only save the last added entity, and not all of them.
Is that intended and expected behavior?

It should be documented here, either as defined behavior, or as a warning with a suggestion for an alternative approach.

I have a table with a PK Identity column, which consequently has a generator identity setting for the entity.
I use `DbSet<T>.Create()` to create the entity, and immediately add it with `DbSet<T>.Add();`, and then set additional properties as required.

Calling SaveChanges after every Add adds all of them as expected. But my understanding is that Add should add them for tracking, and then SaveChanges persists them. So Add Add Save should be more consistent and performant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89716248-d156-03c6-4fc2-efc777a16fe1
* Version Independent ID: 9b136a86-684e-ac46-4adb-199ebaf5e086
* Content: [DbSet.Add(Object) Method (System.Data.Entity)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.dbset.add?view=entity-framework-6.2.0#System_Data_Entity_DbSet_Add_System_Object_)
* Content Source: [EF/xml/System.Data.Entity/DbSet.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity/DbSet.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@ite-klass Please post a simplified, runnable project or complete code listing so that we can reproduce what you are seeing and investigate.
