### ISSUE TITLE
Data corruption during reads on Linux/OSX

### ISSUE THREAD

**Issue by rmja** [aspnet/EntityFrameworkCore#17592]
The currentlly released version of Microsoft.Data.SqlClient (1.0.19239.1) has a severe issue (https://github.com/dotnet/SqlClient/issues/145#issuecomment-526625414) where data corruption happens for read values that spans two packets. The error only happens when the managed tds parser is used which it is on Linux and OSX.

Corrupted reads may throw an exception because it can cause an invalid state in the internal tds parser, but _it can also happen that corrupted values can be silently read_.

A fix is merged to master (https://github.com/dotnet/SqlClient/pull/171) but is scheduled for a 1.1 release which is likely after the release of EF Core 3.

This issue is intended to track the release of M.D.SqlClient and to make sure that the dependency is upgraded if it happens that a patch release out before the release of EF Core 3.

### Further technical details
EF Core version: 3.0 preview 8
Database Provider: SqlServer with M.D.SqlClient
Operating system: Linux and OSX

**Comment by rmja** [comment]
@ajcvickers this have now been released I M.D.SqlClient so it is now ready to be fixed

**Comment by ajcvickers** [comment]
@rmja Thanks. @bricelam is working on a PR, which we will then need to get approved.

**Comment by rmja** [comment]
@ajcvickers @bricelam Is it correct that this change is not included in rc1?

![image](https://user-images.githubusercontent.com/2112306/65020383-643d3780-d92d-11e9-89b0-a7a9cb9f57ac.png)

**Comment by smitpatel** [comment]
@rmja - That is true. It will be included in 3.0 release.
