### ISSUE TITLE
Cosmos: Could not update entities in a Cosmos Container with partition key

### ISSUE THREAD

**Issue by NetGH** [aspnet/EntityFrameworkCore#17616]
There are two entities , Graph and Node, Graph owns Node, and Graph has partition key.

``` C#
        modelBuilder.Entity<Graph>().Property(g => g.Name);
        modelBuilder.Entity<Graph>().HasPartitionKey(g => g.Name);

        modelBuilder.Entity<Graph>().OwnsMany(g => g.Nodes,
            navigationBuilder =>
            {
           }
```

Just tested the nightly build 5.0.0-alpha1.19454.1, it succeed to save entities . but some update scenarios do not work.

Scenario one. Given that there is an existing graph (master entity) with an existing node (which is a owned entity) in Cosmos DB. now Add a new node to graph
Expected Result: the new node is inserted into the graph in Cosmos DB
Actual Result: no update

Scenario Two. Given that there is an existing graph, and it has a property Name, and Name is the partition key. Update the Name, and save the Graph
Expected Result: the Graph name should be updated.
Actual Result: The Graph Name property value is not updated.

Scenario There: Remove a node from existing graph. --- Works!

Scenario Four: Update a property of an existing node. --- Works!

**Comment by AndriySvyryd** [comment]
#### Description
The value of the partition key cannot be updated.
Embedded entities cannot be added to entities with partition keys.

#### Customer impact
Some of the common scenarios for entities with partition keys are blocked.

#### Regression
N/A, 3.0 will be the first RTM release for the Cosmos provider

#### Risk
Low

**Comment by AndriySvyryd** [comment]
@NetGH I wasn't able to repro the issue for scenario one, perhaps it was already fixed.
Scenario two is not supported, partition key is immutable, we'll throw an error instead of failing silently.

**Comment by NetGH** [comment]
Thanks Andriy, just testing the against the latest build.

Scenario one. Add a new node to an existing graph -- Works!

Scenario Two. Update the Name of an existing Graph -- Pending fix.

Scenario There: Remove a node from existing graph. --- Works!

Scenario Four: Update a property of an existing node. --- Works!
