### ISSUE TITLE
GroupBy wants to execute on client when performed on DbQuery (View)

### ISSUE THREAD

**Issue by DizzyDeveloper** [aspnet/EntityFrameworkCore#17635]
I am not sure if this issue has been discussed somewhere else before, but I haven't found anything related to it not being able to work.

I have this simple few lines of code. I am want to be able to perform a series of aggregate to simply replicate an SQL query as below:

```sql
SELECT COUNT(*) as Total, SUM(Value) as Amount FROM MyCustomView;
```  

### Steps to reproduce

Attempt to run a code below where MyCustomView is a View on Sql.

``` c#
const int a = 1;
var result = context
.MyCustomView
.GroupBy(p => a)
.Select(grp => new {
   Total = grp.Count(),
   Amount = grp.Sum(p=>p.Value)
 // Some other aggregates removed for brevity  
}).First();
```

As a sketchy work around I managed to get the query to work by adding in a select before the group by.

``` c#
const int a = 1;
var result = context
.MyCustomView
// For some reason adding a Select prevents the complaint
.Select(p=>new 
{
    p.Value
    // Some other properties removed for brevity  
})
//
.GroupBy(p => a)
.Select(grp => new {
   Total = grp.Count(),
   Amount = grp.Sum(p=>p.Value)
   // Some other aggregates removed for brevity  
}).First();
```

###

If ```MyCustomView``` was a table this would be fine, however the GroupBy clause gives the warning below.

```
'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'GroupBy(1, [p])' could not be translated and will be evaluated locally.'.
```

### Further technical details
EF Core version: 2.2.6
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 10
IDE: Visual Studio 2017 15.9.4

**Comment by smitpatel** [comment]
Can you try 3.0 preview9 package. The scenario should already be working.

**Comment by DizzyDeveloper** [comment]
@smitpatel Ah. Unfortunately I may not have the luxury of upgrading to 3.0 in the current project :(

**Comment by ajcvickers** [comment]
Note from triage: additional test coverage needed.

**Comment by maumar** [comment]
Verified this has been fixed
