### ISSUE TITLE
One or more errors occurred. (The entity type '' requires a primary key to be defined.)

### ISSUE THREAD

**Issue by MohammadElKhatib** [aspnet/EntityFrameworkCore#17699]
I am trying to use an existing database with my Asp.Net Core (2.2.0) application that includes also Individual Authentication.

I created my database then I scaffolded the models in the application, but I am facing several errors, that leads me to the conclusion that the DBContext registration not working.

first, am registering my DBContext in Startup ConfigureServices:

```
services.AddDbContext<ApplicationContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DataContextConnection")));
```

then, the model is including two foreign keys representing a composite primary key:

```
public class ManOfTheMatchPrediction
    {
        public int ManOfTheMatchId { get; set; }
        public string UserId { get; set; }
        public int PlayerId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime LastModifiedDate { get; set; }

        public ManOfTheMatch ManOfTheMatch { get; set; }
        public Player Player { get; set; }
        public KhatiboUser User { get; set; }
    }
```

after that on DBContext class am declaring the relations properties:
```

 modelBuilder.Entity<ManOfTheMatchPrediction>(entity =>
            {
                entity.ToTable("ManOfTheMatch_Prediction");

                entity.HasKey(e => new { e.ManOfTheMatchId, e.UserId });

                entity.HasOne(d => d.ManOfTheMatch)
                    .WithMany(p => p.ManOfTheMatchPrediction)
                    .HasForeignKey(d => d.ManOfTheMatchId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ManOfTheMatch_Prediction_ManOfTheMatch");

                entity.HasOne(d => d.Player)
                    .WithMany(p => p.ManOfTheMatchPrediction)
                    .HasForeignKey(d => d.PlayerId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ManOfTheMatch_Prediction_Player");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.ManOfTheMatchPredictions)
                    .HasForeignKey(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ManOfTheMatch_Prediction_AspNetUsers");
            });

```
whether I remove or keep the DBContext registration on the startup, the issue is still there and nothing change, the DBContext class is never called even when registring it on startup.

while when triggering the Identity DBContext it is been called once application startup before throwing an error.

**Comment by divega** [comment]
@MohammadElKhatib could you please provide a repro project showing these symptoms.

**Comment by MohammadElKhatib** [comment]
@divega  
I added you to this repro project:

https://github.com/MohammadElKhatib/Khatibo

**Comment by MohammadElKhatib** [comment]
@divega note that I am using visual studio for mac with docker and mssql container on docker

**Comment by divega** [comment]
@MohammadElKhatib could you please add @AndriySvyryd as well? He will take over investigating this issue.

**Comment by MohammadElKhatib** [comment]
@divega just added Andriy
By the way i upgraded to core 2.6 and the issue looks disappeared.

**Comment by AndriySvyryd** [comment]
@MohammadElKhatib Ok, then I am going to close this. If you happen to run into it again on 2.6 or 3.0 just leave a comment.
