### ISSUE TITLE
IsTemporary not always properly set ( ChangeTracker)

### ISSUE THREAD

**Issue by manvydasu** [aspnet/EntityFrameworkCore#17700]
### Issue
Attribute "IsTemporary" of PropertyEntry object is not always properly set.

### Steps to reproduce

Have a entity relationship like this
```
    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public Post Post { get; set; }
        public int PostId { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    }
```
1. Create a Blog with a Post and save it the database.
2. Get that specific blog from DbContext and attach a completely new Post ( id = 0) to it.
3. Check results of ChangeTracker: CurrentValue for PostId property will have negative value like "-2147482647" but "IsTemporary" will be set to false.

EF Core version: 2.2.6

### Note: 
I noticed this while trying to implemented audit ( logging changed properties in database) using EF core.
After encountering this issue I searched on google a bit and found someone else complained about this a month ago - [Stackoverflow Url](https://stackoverflow.com/questions/57373946/changetracker-properties-have-currentvalue-of-2147482646-but-istemporary-is-fal)

**Comment by marcnet80** [comment]
Hello, @manvydasu. Could you please provide a code sample or a project? 
I've tried to reproduce issue on enviroment with Asp.Net Core 2.2 and EFCoreSqlServer version 2.2.6 without success.
Thank you.

**Comment by manvydasu** [comment]
Hello @marcnet80 
I've created repository, which shows how to reproduce this issue.
https://github.com/manvydasu/IsTemporary-issue-on-EF-core-17700-

Let me know if you can successfully reproduce it.

**Comment by roji** [comment]
Confirmed that this occurred in 2.2.6 and no longer occurs in 3.0.0.

```c#
class Program
{
    static void Main(string[] args)
    {
        using (var ctx1 = new BlogContext())
        {
            ctx1.Database.EnsureDeleted();
            ctx1.Database.EnsureCreated();

            ctx1.Blogs.Add(new Blog
            {
                Post = new Post()
            });

            ctx1.SaveChanges();
        }

        using var ctx2 = new BlogContext();
        var blog = ctx2.Blogs.FirstOrDefault();
        blog.Post = new Post();
        var postIdProperty = ctx2.ChangeTracker.Entries()
            .Single(e => e.Entity is Blog)
            .Properties
            .Single(p => p.Metadata.Name == "PostId");
        Console.WriteLine($"PostId: orig={postIdProperty.OriginalValue}, value={postIdProperty.CurrentValue}, isTemporary={postIdProperty.IsTemporary}");
    }
}

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }
    public DbSet<Post> Posts { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }
    public Post Post { get; set; }
    public int PostId { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
}
```

Running this against the two versions outputs:

```
PostId: orig=1, value=-2147482646, isTemporary=True  // 3.0.0
PostId: orig=1, value=-2147482646, isTemporary=False  // 2.2.6
```
