### ISSUE TITLE
Better maintainable solution for providers to supply their own RelationalDataReader

### ISSUE THREAD

**Issue by lauxjpn** [aspnet/EntityFrameworkCore#17712]
To add custom behavior to a `DbDataReader`, a `RelationalDataReader` derived class can be used in conjunction with `RelationalCommand`, `RelationalCommandBuilder` and `RelationalCommandBuilderFactory`.

To inject this `RelationalDataReader` derived class into `RelationalCommand`, the methods `ExecuteReader` and `ExecuteReaderAsync` (or `Execute` and `ExecuteAsync` prior to 3.0) have to be overridden and basically copy paste inherited, which is a maintenance problem.

I propose a simpler solution, e.g. the method calls
https://github.com/aspnet/EntityFrameworkCore/blob/22d5f2e5f42bb3eae87e39df3fc72d53ab19e3d8/src/EFCore.Relational/Storage/RelationalCommand.cs#L417-L422
https://github.com/aspnet/EntityFrameworkCore/blob/22d5f2e5f42bb3eae87e39df3fc72d53ab19e3d8/src/EFCore.Relational/Storage/RelationalCommand.cs#L506-L511
could be refactored into virtual (factory) method, like
```c#
protected virtual RelationalDataReader CreateRelationalDataReader(
            [NotNull] IRelationalConnection connection,
            [NotNull] DbCommand command,
            [NotNull] DbDataReader reader,
            Guid commandId,
            [NotNull] IDiagnosticsLogger<DbLoggerCategory.Database.Command> logger)
    => new RelationalDataReader(
                    connection,
                    command,
                    reader,
                    commandId,
                    logger);
```

that can easily be overridden without fully implementing `ExecuteReader` and `ExecuteReaderAsync`.

**Comment by divega** [comment]
@lauxjpn we are curious about why you need to extend RelationDataReader. That said, we would consider a good PR for this.

**Comment by lauxjpn** [comment]
@divega I use it as a workaround in `Pomelo.EntityFrameworkCore.MySql` to get around MySQL's very limited `CAST()` support. (https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/571)
I basically funnel some of the DataReader calls (like `GetBool()` or `GetDouble()`) through their corresponding `System.Convert` methods.

```c#
private class MySqlConverterDataReader : DbDataReader
{
    private readonly DbDataReader _dataReader;

    public MySqlConverterDataReader(DbDataReader dataReader)
    {
        _dataReader = dataReader;
    }

    /* ... */
    public override bool GetBoolean(int ordinal)
            => Convert.ToBoolean(_dataReader.GetValue(ordinal));
    public override double GetDouble(int ordinal)
            => Convert.ToDouble(_dataReader.GetValue(ordinal));
    /* ... */

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _dataReader.Dispose();
        }

        base.Dispose(disposing);
    }
}
```

**Comment by AndriySvyryd** [comment]
Fixed in https://github.com/aspnet/EntityFrameworkCore/commit/6640d584f1c4984de3482469ab0b3091b45148de

**Comment by divega** [comment]
@lauxjpn I am also curious if you work around the issue outside of the Pomelo driver or if you are planning to contribute it to the project.

**Comment by lauxjpn** [comment]
It's part of the PR for updating Pomelo to EF Core 2.2.6, and basically fix as much tests that did not work before as possible (the `CAST()` tests where a large chunk of that), to provide a solid foundation to test against, for the upcoming 3.0 upgrade.
The PR will be online in < 24h.

**Comment by lauxjpn** [comment]
@divega I opened the PR: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/820
