### ISSUE TITLE
Build script not running due to space in path name

### ISSUE THREAD

**Issue by AsifulNobel** [aspnet/EntityFrameworkCore#17831]
Build script does not run, if there is space in any of the parent directory name.

### Steps to reproduce

1. Open cmd in EntityFrameworkCore directory
2. Run `build.cmd` or any of the other `.cmd` file

Make sure that the working directory path looks like the following path containing space in any of the parent directory - *D:/foo & bar/aspnet/EntityFrameworkCore*. You will see an error that *powershell is missing the terminator "*.

### Further technical details

EF Core branch: release/3.1
Operating system: Windows 10 version 1903

**Comment by bricelam** [comment]
It's actually the & that's causing problems. I fixed what I could in our repo. It looks like there are additional failures now in some scripts from [dotnet/arcade](https://github.com/dotnet/arcade).
