### ISSUE TITLE
Combining queries with a Union, then doing Includes and then ToList results in include being ignored.

### ISSUE THREAD

**Issue by frankbjr** [aspnet/EntityFrameworkCore#17855]
I'm too much of a rook to know if this is intentional behavior or not, but I found it strange, so thought I would mention it.  I basically 'Union' three queries, then try to do an Include statement to pick up child records.  When I issue the ToList() command, EFCore emits in the debug log that it chose not to include my include statements as they weren't reachable.

### Steps to reproduce
``` C#
// simplified pseudo code

var query1 = _db.Parents.Where(x => x.Age == 50);
var query2 = _db.Parents.Where(x => x.Age == 40);
var query3 = _db.Parents.Where(x => x.Age == 30);

var combinedQuery = query1.Union(query2).Union(query3);

var finalQuery = combinedQuery.Include(x => x.Children);

var results = finalQuery.ToList();
// Debugger shows 'The include operation for navigation [x].Children is unnecessary 
// and was ignored...'
```

On the other hand if I do the below, it works:

``` C#
var query1 = _db.Parents.Include(x => x.Children).Where(x => x.Age == 50)
var query2 = _db.Parents.Include(x => x.Children).Where(x => x.Age == 40);
var query3 = _db.Parents.Include(x => x.Children).Where(x => x.Age == 30);

var combinedQuery = query1.Union(query2).Union(query3);

var results = combinedQuery.ToList();
// Include is not ignored and I get my object graph including Children
```

EF Core version: 2.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net Core 2.2
Operating system: Win 10Pro
IDE: VS2019 16.2.5

**Comment by divega** [comment]
Triage: This works on 3.0. We don't have plans for improving it in previous versions.
