### ISSUE TITLE
SqlFragmentExpression needs public constructor

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#17918]
Current constructor is internal and customers need to use it for custom translation of DbFunction.

Further, it may be useful to create some abstraction or helper methods to facilitate writing custom translation.

**Comment by kinosang** [comment]
I wanna why the `SqlFragmentExpression` was made internal (and also the `ConstantExpression`)

**Comment by roji** [comment]
@kinosang SqlFragmentExpression will have a public constructor in 3.1 (SqlConstantExpresion is already public).

You can use SqlExpressionFactory, but it's intended for provider use rather than for users.

**Comment by kinosang** [comment]
@roji thx for your comment, I'll move forward once 3.1 published.

though `SqlConstantExpresion` is public, the `ConstantExpresion` doesn't, so we cannot use the constructor of `SqlConstantExpresion`.

**Comment by roji** [comment]
`ConstantExpression` isn't part of EF Core in any way - it's part of System.Linq.Expressions. All expression types there are created by calling `Expression.Constant()` (and other various factory methods). However, if you're using these with EF Core be sure you understand exactly what needs to go where.

**Comment by kinosang** [comment]
@roji gotcha
