### ISSUE TITLE
Bracket [ not escape in string.StartsWith

### ISSUE THREAD

**Issue by bradlis7** [aspnet/EntityFrameworkCore#17948]
Not sure if this has been fixed, but my searching for "brackets" didn't turn up anything on the bug list.

```C#
dbSet.Where(x => x.StartsWith("Test[Brackets]")).ToList();
```

I think it's not escaping the `[` for my SQL LIKE statement.

```
[@__p_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT [x].[Id], [x].[CreatedDate], [x].[LastUpdated], [x].[Value]
FROM [AppConfigurations] AS [x]
WHERE ([x].[Id] LIKE @__p_0 + N'%' AND (LEFT([x].[Id], LEN(@__p_0)) = @__p_0)) OR (@__p_0 = N'')
```

Possibly related: #474

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: (e.g. .NET Core 3.0): 2.2.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.2.4

**Comment by smitpatel** [comment]
Verified bug in 3.0 too.
3.0 has some other issue too like `[b].[Value] LIKE [b].[Value] + N'%'`
Generated SQL
```SQL
SELECT [b].[Id], [b].[Value]
FROM [Blogs] AS [b]
WHERE ((@__testString_0 = N'') AND @__testString_0 IS NOT NULL) OR ([b].[Value] IS NOT NULL AND (@__testString_0 IS NOT NULL AND (([b].[Value] LIKE [b].[Value] + N'%') AND (((LEFT([b].[Value], LEN(@__testString_0)) = @__testString_0) AND (LEFT([b].[Value], LEN(@__testString_0)) IS NOT NULL AND @__testString_0 IS NOT NULL)) OR (LEFT([b].[Value], LEN(@__testString_0)) IS NULL AND @__testString_0 IS NULL)))))
```

The parameter in the like expression needs to be escaped but we don't know parameter value when compiling. One possible solution is to remove Like optimization here.

**Comment by smitpatel** [comment]
One possible generation of SQL
```SQL
Declare @__testString_0 nvarchar(4000)
Set @__testString_0 = N'Test\[Brackets]'

Declare @__testString_1 nvarchar(4000)
Set @__testString_1 = N'Test[Brackets]'

SELECT [b].[Id], [b].[Value]
FROM [Blogs] AS [b]
WHERE ([b].[Value] LIKE @__testString_0 + N'%' ESCAPE N'\' AND (LEFT([b].[Value], LEN(@__testString_1)) = @__testString_1)) OR (@__testString_1 = N'')
```

**Comment by smitpatel** [comment]
Any LikeExpression where pattern is parameter can run into this issue if not properly escaped.
