### ISSUE TITLE
Compute Hash for MemberMemberBinding in ExpressionEqualityComparer

### ISSUE THREAD

**Issue by miegir** [aspnet/EntityFrameworkCore#17959]
https://github.com/aspnet/EntityFrameworkCore/blob/03503351c9dd3daf05a1ff66520c00aba3e372eb/src/EFCore/Query/Internal/ExpressionEqualityComparer.cs#L238

I think that this line is supposed to be
``` C#
throw new NotImplementedException($"Unhandled binding type: {memberBinding.BindingType}");
```

However, textual representation of the binding (that is output currently) will be helpful too, especially because only one binding type is not supported currently.

**Comment by smitpatel** [comment]
It should take care of MemberMemberBinding & throw exception for BindingType. (Follows what VisitMemberBinding does in base visitor)

**Comment by mithileshz** [comment]
I am guessing this is fixed now and isn't available to be picked up?

**Comment by ajcvickers** [comment]
@smitpatel Did the PR you merged fix this issue?

**Comment by smitpatel** [comment]
Error message improved. The issue is open to actually take care of MemberMemberBinding.

**Comment by smitpatel** [comment]
#18685
