### ISSUE TITLE
Property X is not defined for type Y

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/EntityFrameworkCore#17986]
I need to be able to create a reusable query that returns a graph of a given object - in this example a `Series` object.
In the provided example I am calling `SeriesGraph()` and it works fine however when I try to join to it it throws an error.
Shouldn't I be able to re-use an `IQueryable` and build on it?  

BTW I cannot create proper foreign keys for certain tables in my db because the data is provided by third parties and can be deleted by them at will.

Please see attached project.

	// Works - Entire graph for Series is populated including NativeFrequency and ReportingFrequency:
	var series = SeriesGraph(db).ToList();        

	// Fails - Try to join on SeriesGraph():
	var query = (from sc in db.SeriesCategories
				 join s in SeriesGraph(db) on new { SeriesID = sc.Symbol, DPID = sc.SeriesDataProviderID } equals new { SeriesID = s.NativeID, DPID = s.DataProviderID }
				 where sc.ParentNativeID == categoryNativeID && sc.ParentDataProviderID == dataProviderID
				 select s);

	var result = await query.ToListAsync().ConfigureAwait(false);  // throws here

EF core 2.2.6

[EFPropertyNotFoundTest.zip](https://github.com/aspnet/EntityFrameworkCore/files/3638970/EFPropertyNotFoundTest.zip)

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Property 'EFAddTest.ReportingFrequency ReportingFrequency' is not defined for type 'EFAddTest.Series'
Parameter name: property)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at EFAddTest.Program.Main(String[] args) in C:\Projects\EFPropertyNotFoundTest\EFAddTest\Program.cs:line 22

Inner Exception 1:
ArgumentException: Property 'EFAddTest.ReportingFrequency ReportingFrequency' is not defined for type 'EFAddTest.Series'
Parameter name: property

**Comment by sam-wheat** [comment]
The code below works.  It is what I expect the code in my original post to do.  However I have manually copy the `SeriesGraph` to many places in my code.  Hopefully I can avoid having to maintain many copies of this:

	public async Task<List<Series>> GetSeriesForCategoryAsync(string categoryNativeID, int dataProviderID)
	{
		//IQueryable<Series> query = (from sc in db.SeriesCategories
		//             join s in SeriesGraph() on new {SeriesID = sc.Symbol, DPID = sc.SeriesDataProviderID } equals new { SeriesID = s.NativeID, DPID = s.DataProviderID }
		//             where sc.ParentNativeID == categoryNativeID && sc.ParentDataProviderID == dataProviderID
		//             select s);
		//var result = await query.ToListAsync().ConfigureAwait(false);


		var query =
			from sc in db.SeriesCategories
			join s in db.Series.Include(x => x.DataProvider) on new { SeriesID = sc.Symbol, DPID = sc.SeriesDataProviderID } equals new { SeriesID = s.NativeID, DPID = s.DataProviderID }
			join nf in db.NativeFrequencies.Include(x => x.ReportingFrequency) on new { NF = s.NativeFreqNativeID, DP = s.NativeFreqDataProviderID } equals new { NF = nf.NativeID, DP = nf.DataProviderID }

			select new Series
			{
				NativeID = s.NativeID,
				Units = s.Units,
				SeasonalAdj = s.SeasonalAdj,
				LastUpdated = s.LastUpdated,
				Popularity = s.Popularity,
				RTStart = s.RTStart,
				Notes = s.Notes,
				SystemAttributes = s.SystemAttributes,
				LastDataUpdate = s.LastDataUpdate,
				DataProviderID = s.DataProviderID,
				DataProvider = s.DataProvider,
				Name = s.Name,
				IsDiscontinued = s.IsDiscontinued,
				NativeFreqDataProviderID = s.NativeFreqDataProviderID,
				NativeFreqNativeID = s.NativeFreqNativeID,
				NativeFrequency = nf
			};

		return await query.ToListAsync(); 
	}

**Comment by smitpatel** [comment]
This is fixed in 3.0 release

**Comment by leaderanalytics** [comment]
Awesome! Thank you.
