### ISSUE TITLE
Query: Owned entity throws incorrect tracking error

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#18024]
When Owned navigation is in base class and querying for derived type
```C#
public class Blog
    {
        public int Id { get; set; }
        public OwnedEntity OwnedEntity { get; set; }
    }

    public class SpecialBlog : Blog
    {

    }

    [Owned]
    public class OwnedEntity
    {
        public string OwnedProperty { get; set; }
    }

var query = db.Set<SpecialBlog>().ToList();
```

**Comment by mortzi** [comment]
@smitpatel For now, is there a workaround to make the query work somehow?

**Comment by myersBR** [comment]
> @smitpatel For now, is there a workaround to make the query work somehow?

for now i'm using AsNoTracking

**Comment by BickelLukas** [comment]
As a workaround I have replaced the DBSet in the context with 
``` cs
public IQueryable<Machine> Machines => Devices.Where(x => x is Machine).Cast<Machine>();
```

This allows me to query the Machines like before. Only adds now have to use the `Devices` DbSet.

**Comment by MaximMikhisor** [comment]
Dear @ajcvickers ,

I also have same error, but in other scenario.
I am trying to load owned property trough 'ReferenceEntry.Load()'

`ReferenceEntry reference = entityEntry.Reference("OwnedPropertyName");
 var value = reference.Load();`
 
How can I use `AsNoTracking` in this scenario?

**Comment by AndriySvyryd** [comment]
@MaximMikhisor Since you are starting with an entity entry, there's no API to issue a non-tracking query. You could write a query with an explicit join on the foreign key properties (they are likely in shadow state).

https://github.com/dotnet/efcore/issues/10787 could make this easier
