### ISSUE TITLE
Foreign keys of owned types are regenerated in migrations

### ISSUE THREAD

**Issue by marcin-dardzinski** [aspnet/EntityFrameworkCore#18045]
I have a following model, a parent owning multiple children. Children are configured as owned entities.
``` C#
class Parent
{
    public Guid Id { get; set; }
    public List<Child> Children { get; set; }
}

class Child
{
    public Guid Id { get; set; }
    public Guid ParentId { get; set; }
}

class MyDbContext : DbContext
{
    public DbSet<Parent> Parents => Set<Parent>();

    protected override void OnConfiguring(DbContextOptionsBuilder options)
    {
        options
            .UseSqlServer("Server=server;Database=db;User Id=sa;Password = password;");
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<Parent>(cfg =>
        {
            cfg.OwnsMany(e => e.Children, child =>
            {
                child.WithOwner()
                    .HasForeignKey(e => e.ParentId);
            });
        });
    }
}
```

The initial migration for this model looks like this
``` C#
migrationBuilder.CreateTable(
    name: "Parents",
    columns: table => new
    {
        Id = table.Column<Guid>(nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Parents", x => x.Id);
    });

migrationBuilder.CreateTable(
    name: "Child",
    columns: table => new
    {
        Id = table.Column<Guid>(nullable: false),
        ParentId = table.Column<Guid>(nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Child", x => new { x.ParentId, x.Id });
        table.ForeignKey(
            name: "FK_Child_Parents_ParentId",
            column: x => x.ParentId,
            principalTable: "Parents",
            principalColumn: "Id",
            onDelete: ReferentialAction.Cascade);
    });
```

Now, if I try to add another migration, the `FK_Child_Parents_ParentId` key is dropped and recreated in new migration:
```
migrationBuilder.DropForeignKey(
    name: "FK_Child_Parents_ParentId",
    table: "Child");

migrationBuilder.AddForeignKey(
    name: "FK_Child_Parents_ParentId",
    table: "Child",
    column: "ParentId",
    principalTable: "Parents",
    principalColumn: "Id",
    onDelete: ReferentialAction.Cascade);
```

The issue doesn't occur if I don't use owned types (classic `HasMany` approach). 

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Arch Linux & Ubuntu

**Comment by ChristopherHaws** [comment]
This seems like it may be similar to #15681

**Comment by bricelam** [comment]
@AndriySvyryd Is the DeleteBehavior for ownership navigations configured in a convention? How do we preserve it in the model snapshot?

**Comment by briman0094** [comment]
I'm seeing similar behavior in my solution, in addition to the fact that immediately after updating everything to 3.0.0, some part of my application is triggering a "pending model changes" error at runtime. If I add a migration like suggested in the error, the only thing that changes is the FK of the owned type being recreated.

**Comment by AndriySvyryd** [comment]
@bricelam Yes, it's configured by the `CascadeDeleteConvention`. We could fix this by just hardcoding it in `InternalRelationshipBuilder.IsOwnership()`

**Comment by AndriySvyryd** [comment]
@bricelam I'll take this one
