### ISSUE TITLE
3.0 leaving Includes null (worked with 2.2)

### ISSUE THREAD

**Issue by hallidev** [aspnet/EntityFrameworkCore#18098]
The following was working properly in 2.2:

``` C#
var userId = 1;
var areaId = 1;
var pageInfo = new OffsetPageInfo(20, 0); // Limit 20, Offset 0

var areaModMail = await _dbContext
    .ModMails
    .Include(mm => mm.Area)
    .Include(mm => mm.User)
    .Where(mm => mm.UserId == userId && mm.AreaId == areaId)
    .OrderByDescending(mm => mm.CreatedUtc)
    .ToOffsetPagedResultAsync(pageInfo);
```

Where ToOffsetPagedResultAsync is defined as:

``` C#
public static async Task<OffsetPagedResult<T>> ToOffsetPagedResultAsync<T>(this IQueryable<T> query, OffsetPageInfo pageInfo)
{
    var result = await query.Select(item => new OffsetPagedItem<T>
    {
        Item = item,
        TotalCount = query.Count()
    })
    .Skip(pageInfo.Offset)
    .Take(pageInfo.Limit)
    .ToListAsync();

    return new OffsetPagedResult<T>(result.Select(pi => pi.Item).ToList(),
        result.First().TotalCount);
}
```
In 3.0, "Area" and "User" (the two Includes) are always null. If I modify ToOffsetPagedResultAsync like so, "Area" and "User" are loaded properly:

``` C#
public static async Task<OffsetPagedResult<T>> ToOffsetPagedResultAsync<T>(this IQueryable<T> query, OffsetPageInfo pageInfo)
{
    // **Forcing the query here "fixes" it**
    var tmpThrowawayResult = await query.ToListAsync();

    var result = await query.Select(item => new OffsetPagedItem<T>
    {
        Item = item,
        TotalCount = query.Count()
    })
    .Skip(pageInfo.Offset)
    .Take(pageInfo.Limit)
    .ToListAsync();

    return new OffsetPagedResult<T>(result.Select(pi => pi.Item).ToList(),
        result.First().TotalCount);
}
```

This is just one concrete example - I use the above ToOffsetPagedResultAsync extension method everywhere, and all Includes are being left null unless I throw in the "tmpThrowawayResult", which forces the query to be realized / run twice.

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

**Comment by smitpatel** [comment]
Include seems to be getting ignored.

**Comment by tomasbruckner** [comment]
Same issue

**Comment by smitpatel** [comment]
@hallidev - Doing `query.Count()` inside Select actually does not help you in anyway, other than allocating more memory.
In 2.2, it sent a separate query to compute `Count` on server for each outer item causing N+1 queries to server.
In 3.0 we identify that query.Count is not associated to range variable so we evaluate it beforehand in funcletizer and use the computed value while generating result for each item. (hence only 2 queries). But because they are split query you can do that manually yourself else, EF will just put the same count value for every result hence allocating more memory than needed.

**Comment by hallidev** [comment]
I'm not sure I follow your suggestion (if you're indeed making a suggestion). The temporary workaround I've had in place since I reported this looks like:

``` C#
public static async Task<OffsetPagedResult<T>> ToOffsetPagedResultAsync<T>(this IQueryable<T> query, OffsetPageInfo pageInfo)
{
    // Query 1: Get the total count
    var totalCount = await query.CountAsync();

    // Query 2: Get the actual results
    var result = await query.Select(item => new OffsetPagedItem<T>
    {
        Item = item
    })
    .Skip(pageInfo.Offset)
    .Take(pageInfo.Limit)
    .ToListAsync();

    return new OffsetPagedResult<T>(result.Select(pi => pi.Item).ToList(),
        totalCount);
}
```

If I'm interpreting you correctly. you're saying that this is the best way? Is there any way to do this with one query?

**Comment by smitpatel** [comment]
@hallidev - Essentially, that query only. It is a bug and I have submitted a fix but under the hood EF Core is also going to generate 2 queries (but with data repeated). So doing 2 queries separately yourself is better. With my fix in, your query would work correctly without ignoring include but not most performant.
