### ISSUE TITLE
Simple QueryFilter breaks Linq-to-sql queries in EntityFrameworkCore

### ISSUE THREAD

**Issue by MintPlayer** [aspnet/EntityFrameworkCore#18158]
Reference to https://github.com/aspnet/EntityFrameworkCore/issues/13517
https://github.com/MintPlayer/QueryFilterIssue

**Migration from EntityFrameworkCore 2.2 to 3.0**
I'm using a QueryFilter in my DbContext to filter out the soft-deleted entities.

```
internal class MyDbContext : DbContext
{
	public DbSet<Person> People { get; set; }
	public DbSet<User> Users { get; set; }

	public MyDbContext() : base()
	{
	}

	public MyDbContext(DbContextOptions options) : base(options)
	{
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		base.OnConfiguring(optionsBuilder);
		var connection_string = @"Server=(localdb)\mssqllocaldb;Database=QueryFilterIssue30;Trusted_Connection=True;ConnectRetryCount=0";
		optionsBuilder.UseSqlServer(connection_string);
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);

		// The following line breaks the app
		modelBuilder.Entity<Person>().HasQueryFilter(p => p.UserDelete == null);
	}
}
```

- EFCore 2.2: This code works
- EFCore 3.0: This code isn't working because of the QueryFilter.

However, imagine following QueryFilter:
`modelBuilder.Entity<Person>().HasQueryFilter(p => (p.FirstName != "") & (p.LastName != ""));`
This code is in fact working.

Suppose the QueryFilters applied to the DbSet are also included in the Linq-to-sql conversion, and not being run client-side, this code should be executed without a problem.

### Summary:
It appears that since EF Core 3.0 applying a QueryFilter containing a relationship condition breaks EF.

- Applying a QueryFilter based on fields works perfectly fine
- Removing the QueryFilter and moving the statement to the LINQ query explicitly works as expected
- Running the same code in EFCore 2.2 works.
- You can even combine AspNetCore 3.0 and EFCore 2.2

### Steps to reproduce

- git clone https://github.com/MintPlayer/QueryFilterIssue.git
- cd QueryFilterIssue/DotNetCore22/QueryFilterIssue22.Data
- dotnet ef database update
- cd QueryFilterIssue/DotNetCore30/QueryFilterIssue30.Data
- dotnet ef database update
- Add data to the databases
- Set **QueryFilterIssue22.Web** as startup project and run
- The people are successfully fetched from the database
- Set **QueryFilter30.Web** as startup project and run
- Notice the following error

> InvalidOperationException: The LINQ expression 'Where<TransparentIdentifier<Person, User>>(
> source: LeftJoin<Person, User, Nullable<int>, TransparentIdentifier<Person, User>>(
> outer: DbSet<Person>,
> inner: DbSet<User>,
> outerKeySelector: (p) => Property<Nullable<int>>(p, "UserDeleteId"),
> innerKeySelector: (u) => Property<Nullable<int>>(u, "Id"),
> resultSelector: (o, i) => new TransparentIdentifier<Person, User>(
> Outer = o,
> Inner = i
> )),
> predicate: (p) => p.Inner == (Unhandled parameter: __ef_filter__p_0))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

- Disable the QueryFilter in `MyDbContext`. Optionally enable the other QueryFilter.
- Run the project again. Notice the working app.
- Optionally enable the Where clause in the PersonRepository.
- Run the project again. Notice the working app.

### Further technical details

EF Core version: 2.2.0 versus 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer 2.2.0 versus 3.0.0
Target framework: .NET Core 2.2 versus 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.1

**Comment by smitpatel** [comment]
cc: @roji @maumar - This is happening because we would also need to entity equality after introducing query filters in expression tree.

**Comment by roji** [comment]
Makes sense... But IIRC we can't move the EE visitor to after navigations expander... So run it a second time?

**Comment by smitpatel** [comment]
Run it second time just on the filter part. We would need to re-run a bunch of visitors like that on filter part. Do we think it is better pre-processed or processed else where?

**Comment by maumar** [comment]
We can do it in nav expansion, where we already do some processing on filters & defining queries

**Comment by roji** [comment]
Sounds good to me.

**Comment by DUWENINK** [comment]
it is the same in [#18084](https://github.com/aspnet/EntityFrameworkCore/issues/18084)

**Comment by MintPlayer** [comment]
A simple solution off course is to just declare the UserDeleteId (Nullable<int>) explicitly on the entity, and use following QueryFilter:

    modelBuilder.Entity<Subject>().HasQueryFilter(s => s.UserDeleteId == null)

This would only be possible for simple cases as a temporary workaround (no navigation).
