### ISSUE TITLE
Logging query execution time for LogLevel=INFO

### ISSUE THREAD

**Issue by oakio** [aspnet/EntityFrameworkCore#18203]
It will be useful logging query execution time also when LogLevel is set INFO

For example:

> Executed DbCommand **(16ms)** [Parameters=[], CommandType='Text', CommandTimeout='30']

**Comment by ajcvickers** [comment]
We should be logging command _executed_ rather than command _executing_ at Info level. This was an unintentional break; we plan to fix it in 3.1.
