### ISSUE TITLE
Violation of PRIMARY KEY constraint

### ISSUE THREAD

**Issue by patricka2** [aspnet/EntityFrameworkCore#18357]
I think this error it's not logical, i can fix this by changing statement to "movie.Genre = dbContext.Genres.Where(x => x.Title == "Action").FirstOrDefault();", but i find for a way that Lest I have to retrieve "genre" from database.

"Genre" class:
![hub1](https://user-images.githubusercontent.com/46094177/66722679-a7e86b80-ee1d-11e9-80d8-47bbaacfe435.png)
"Movie" class:
![hub2](https://user-images.githubusercontent.com/46094177/66722680-b040a680-ee1d-11e9-8e9d-269ffeffd729.png)
"DbContext"
![hub77](https://user-images.githubusercontent.com/46094177/66722685-ba62a500-ee1d-11e9-96e0-ec0e349a7c9e.png)
Error
![error2](https://user-images.githubusercontent.com/46094177/66722694-ee3dca80-ee1d-11e9-9b2a-99147316912d.png)

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: Windows
IDE: Visual Studio 2019 16.3

**Comment by ajcvickers** [comment]
@patricka2 It's not clear what is not logical here. The code is attempting to insert a new entity instance that has the same primary key value as an existing entity instance. Can you explain what the expected behavior is?

**Comment by patricka2** [comment]
> Can you explain what the expected behavior is?

I expected this code add new movie with "Action" genre to Database without that need to
 retrieving data (genre) from Database. (Map genre to exists genre in Database)

**Comment by patricka2** [comment]
Is there any way to add this without retrieving data from Database

**Comment by smitpatel** [comment]
```C#
var action = new Genre("Action");
                db.Attach(action);
                var movie = new Movie
                {
                    Title = "Something",
                    Year = 1997,
                    Genre = action
                };

                db.Movies.Add(movie);

                db.SaveChanges();
```
Use `Attach` API to mark that `action` is already exist in database and mark it as Unchanged.

**Comment by patricka2** [comment]
Thanks @smitpatel , im looking for this.
