### ISSUE TITLE
Query: clean-up expression printer when we can do breaking changes

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#18413]
We can make expression printer internal, since we expose Print method on `ExpressionExtensions`

Also, currently we repurposed 'generateUniqueParameterIds' to mean general optimized vs debug output. We should rename it to something more appropriate.

**Comment by ajcvickers** [comment]
Note from triage: make sure not to break providers and not to force providers to use internal code when doing this.
