### ISSUE TITLE
DbFunction translation considers two classes the same if they have the same name

### ISSUE THREAD

**Issue by Wain123** [aspnet/EntityFrameworkCore#18425]
Consider two different classes which are both called "Inner" and both have a method called "Min".
```C#
public static class OuterA {
	public static class Inner {
		public static decimal? Min(decimal? a, decimal? b) {
			throw new Exception();
		}
	}
}
public static class OuterB {
	public static class Inner {
		public static decimal? Min(decimal? a, decimal? b) {
			throw new Exception();
		}
	}
}
```
```C#
var methodA = typeof(OuterA.Inner).GetMethod(nameof(OuterA.Inner.Min));
var methodB = typeof(OuterB.Inner).GetMethod(nameof(OuterB.Inner.Min));
modelBuilder.HasDbFunction(methodA).HasTranslation(parameters => new SqlFunctionExpression("TestA", methodA.ReturnType, parameters));
modelBuilder.HasDbFunction(methodB).HasTranslation(parameters => new SqlFunctionExpression("TestB", methodB.ReturnType, parameters));
```
```C#
ctx.TestTable.Select(z => OuterA.Inner.Min(1, 2)).First();
ctx.TestTable.Select(z => OuterB.Inner.Min(1, 2)).First();
```
Both of the above queries translate to
```SQL
SELECT "TestB"(1.0, 2.0)
FROM "TEST_TABLE" "z"
FETCH FIRST 1 ROWS ONLY
```
If I rename one of the Inner classes, then the first query correctly calls TestA instead of TestB.

EF Core version: 2.2
Database provider: Microsoft.EntityFrameworkCore.Oracle
Target framework: .NET Framework 4.7
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.6

**Comment by smitpatel** [comment]
Repros for 3.0 in SQLServer.

**Comment by smitpatel** [comment]
Root cause:
https://github.com/aspnet/EntityFrameworkCore/blob/edf5b27d5065c330cc47fd6d1fff55890a5ac54e/src/EFCore.Relational/Metadata/Internal/DbFunction.cs#L121-L124

We don't consider full type information for method's declaring type so we end up overwriting the DbFunction in the model.
