### ISSUE TITLE
Entity framework does not interpret .Equals in the query right

### ISSUE THREAD

**Issue by NicolasDorier** [aspnet/EntityFrameworkCore#18472]
Using `.Equals` instead of `==` in a query result in an empty list. Tested in 3.0. Breaking change from 2.1.

![image](https://user-images.githubusercontent.com/3020646/67194082-65341e00-f431-11e9-8bc8-4a684e0dd6d1.png)

**Comment by roji** [comment]
Seems like EqualsTranslator is improperly identifying `string.Equals(string, StringComparison)` and eliding it.

**Comment by smitpatel** [comment]
I am going to fix issue just for the awesome post by the OP! 😄
