### ISSUE TITLE
Query: Incorrect match for Value?

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#18486]
Following repro: https://github.com/aspnet/EntityFrameworkCore/issues/14180#issuecomment-544193017
Following seems to be matching `.Value` to our nullable.Value and ignoring that Value is a property which we cannot translate.
```C#
context.Entities.SingleOrDefault(e => e.Name == name && e.Version.Value == version)
```

**Comment by smitpatel** [comment]
@roji - If you want to grab this. 😉

**Comment by roji** [comment]
Thanks! Will take a look.
