### ISSUE TITLE
Scaffolding column with `ValueGenerated.OnUpdate` generates invalid C# code

### ISSUE THREAD

**Issue by lauxjpn** [aspnet/EntityFrameworkCore#18579]
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/877 for an example (issue 2).

The issue is, that the following `switch` is missing the handling of `ValueGenerated.OnUpdate`:

https://github.com/aspnet/EntityFrameworkCore/blob/27c8d56284a641ef0836972ced08db8f7433674d/src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs#L701-L730

It will therefore generate `entity.Property(e => e.MyProperty).()` for properties with `ValueGenerated.OnUpdate`.

Is that an oversight or a deliberate choice?

**Comment by smitpatel** [comment]
It's a bug. SHould generate correct methodName for all the enum values and throw for default case.
