### ISSUE TITLE
Obsolete UseRowNumberPaging

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#18667]
If we are not doing it for 3.1, it should at least be obsoleted so user gets error that it is not supported anymore.

**Comment by smitpatel** [comment]
@aspnet/efteam - We should consider this for 3.1

**Comment by ajcvickers** [comment]
Indeed. I'll do it if nobody gets to it first.

**Comment by ajcvickers** [comment]
See also #18700
