### ISSUE TITLE
ExpressionEqualityComparer cleanup

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#18685]
Use switch on Type rather than NodeType.
Add hashcode computation for missing nodes
- BlockExpression
- AssignExpression

**Comment by ramanathanv** [comment]
Hi @smitpatel , @ajcvickers ,
I would like to resolve this issue as a first contribution. 
I noticed that there are 5 places in 4 classes where there is a switch statement against NodeType. 
ExpressionPrinter.cs, ExpressionEqualityComparer.cs, CSharpHelper.cs, RelationalSqlTranslatingExpressionVisitor.cs. 
Can you provide some additional explanation on the issue to help me get going with this?
