### ISSUE TITLE
Race condition in SpatialiteLoader.FindExtension()

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#18724]
`GetEnvironmentVariable` is not thread-safe and can return `null` if `SetEnvironmentVariable` is being executed concurrently.

>(System.NullReferenceException) -----
    SpatialiteLoader.FindExtension() line 182
    SpatialiteLoader.Load(DbConnection connection) line 98
    SpatialiteLoader.TryLoad(DbConnection connection) line 68
    SqliteTestStore.ctor(String name, Boolean seed, Boolean sharedCache, Boolean shared) line 44
    SqliteTestStore.GetExisting(String name) line 26

**Comment by ajcvickers** [comment]
Poaching
