### ISSUE TITLE
Split SimpleQuery tests into different classes

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#18786]
We currently have a mammoth SimpleQueryTestBase, split across several files with partial classes. We could maintain the same split (Where, Select, Functions...) but using actual classes instead. This seems like it would improve IDE performance (will confirm this if people are OK with the idea), would make it much easier to filter tests via the command (i.e. by class name), etc. Of course we'd still use Northwind exactly as today etc.

Any thoughts/objections?

**Comment by smitpatel** [comment]
I discussed this idea with @maumar last week. If we have good infra to make sure database is initialized only once, we should split even other classes like complexnavs/gearsofwar too. Earlier we split only based on the runtime it took but it would be a good time we start splitting into smaller classes to group tests better and manageable.

**Comment by AndriySvyryd** [comment]
@smitpatel Just use `IClassFixture` and everything will work fine

**Comment by roji** [comment]
@smitpatel @AndriySvyryd thanks for the input!

Unless I'm mistaken we already have several test suite classes working on Northwind (Simple isn't the only one), so I was assuming this problem is already solved... Anyway I'll pay close attention to this.
