### ISSUE TITLE
Cannot translate Contains method call

### ISSUE THREAD

**Issue by ygoe** [aspnet/EntityFrameworkCore#18807]
My application has a query string parser that translates a user-provided search query string into an `IQueryable` expression that can be handed to the database for a database query. Now this search also considers data that isn't in the database. It's a list of selected items that comes from elsewhere but can be part of the search query by the user. So it has to be available in the SQL WHERE clause.

My code currently looks like this:

```c#
var result = context.Entries
    // Project to the form needed for the search query string and result
    .Select(e => new
    {
        // This is from local memory
        isSelected = selectedEntryIds.Contains(e.Id),
        // Now follows all table columns
        id = e.Id,
        name = e.Name,
        // and so on, other Entry properties
    }
    // This is my search-query-to-expression extension method
    .Where(queryExpression)
    // Now regular Linq methods again
    .OrderBy(e => e.name)
    .ToList();
```

The problem is with the `Contains` method at the top of the select.

Let `selectedEntryIds` contain (1, 3, 6, 7) and the user-provided search string be `"isSelected name:Demo"`.

I'd expect this to translate to some thing like this:

```sql
select id in (1, 3, 6, 7) as isSelected, id, name, ...
from table
where isSelected and name = 'Demo'
order by name
```

Or maybe this: (not sure how the SQL syntax would be exactly)

```sql
select id case when 1 then 1 when 3 then 1 when 6 then 1 when 7 then 1 else 0 end as isSelected, id, name, ...
```

But it cannot be translated at all.

### Further technical details

EF Core version: 2.2 (and probably earlier)
Database provider: PostgreSQL (Npgsql)
Target framework: .NET Core 2.2 (will be upgraded to 3.0/3.1)
Operating system: all (Windows 10, Ubuntu 16.04)
IDE: all (Visual Studio 2017)

**Comment by roji** [comment]
Can you please try this with 3.1.0-preview2 and report on the results?

**Comment by ygoe** [comment]
I'm having trouble upgrading my code to work with EF Core 3.0.

`IMutableProperty.Relational()` is gone. Where can I find it?

**Comment by ygoe** [comment]
Okay, I could replace these calls with `SetTableName()`, `GetTableName()` and similar.

Now my test code runs, but it doesn't work correctly. The isSelected part is completely ignored. All rows have this property false and the selection doesn't select anything from this condition. Not sure if there's a warning, I don't have the logging part set up yet.

I'll work my way through to getting the SQL that went to the database. This has been close to impossible in EF Core 2.x. Is it now finally easier?

**Comment by ygoe** [comment]
Okay, I could replace these calls with `SetTableName()`, `GetTableName()` and similar.

Sorry for the comment noise. Now my code runs as expected. I could see the SQL query after configuring logging, so EF printed its queries to the console. Seems this translation is already included in EF Core 3.0. It uses something like `id in (1, 2)`. Haven't tested later previews.

The only issue I could find is that it puts this `id in (1, 2)` part two times, in the `select` and in the `where` clause. If this list gets long, maybe a column alias would be more appropriate. But I'm not sure how much of a problem this is to Postgres. And in my application, these lists never get longer than a dozen items.

**Comment by roji** [comment]
> The only issue I could find is that it puts this id in (1, 2) part two times, in the select and in the where clause

@smitpatel any comment? This seems like an interesting question which we may want to track separately.

**Comment by roji** [comment]
Closing as it seems that the original issue no longer exists in 3.0. @ygoe aside from the question of the repetition above, if anything else is still problematic let us know.

**Comment by ygoe** [comment]
There's another occurrence of this type:

```c#
dbContext.Entries
    .Select(e => new
    {
        enumText =
            e.EnumField == EnumType.A ? "A" :
            e.EnumField == EnumType.B ? "B" :
            e.EnumField == EnumType.C ? "C" :
            ((int)e.EnumField).ToString()
    });
```

This produces this massive case/when construct that is repeated a number of times in the SQL query.

**Comment by smitpatel** [comment]
> @smitpatel any comment? This seems like an interesting question which we may want to track separately.
