### ISSUE TITLE
Index.IsUnique error with ChangingAndChangedNotifications TrackingStrategy

### ISSUE THREAD

**Issue by Samoulou** [aspnet/EntityFrameworkCore#18859]
It seems that with the ChangingAndChangedNotifications tracking strategy when trying to delete an entity that has one of its property set as index.IsUnique, generate a tracking error
![image](https://user-images.githubusercontent.com/18678619/68651381-89ae8200-0527-11ea-8a29-15eca60301ef.png)

### Steps to reproduce
I reproduce the case in this console app.
https://github.com/Samoulou/indexUniqueTrackingError

When launching the console app, I just create the DB and delete the concerned entity, after 5 seconds the error should be throw.

NB: the problem occurs when updating the index property too

### Further technical details
EF Core version: not working with our project in 2.2.6 and with my console app in 3.0.0
Target framework: .NET Core 2.2.6, 3.0.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.1

**Comment by ajcvickers** [comment]
@Samoulou Thanks for filing this. I have confirmed we are able to reproduce and we will discuss in our next triage meeting.
