### ISSUE TITLE
Replacement for GeneratePseudoFromClause

### ISSUE THREAD

**Issue by cincuranet** [aspnet/EntityFrameworkCore#18926]
What's the recommended way to replace `GeneratePseudoFromClause` now missing in 3.1? Do I really have to override `VisitSelect` and copy the whole logic only for [this](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/Query/QuerySqlGenerator.cs#L145) case handling?

**Comment by smitpatel** [comment]
Probably in 3.1 you need to override VisitSelect. We will be adding more extensibility point in next release.

**Comment by cincuranet** [comment]
That's sad. Especially given it was already there? Out of curiosity, is there any reason it was removed? Or plain obliviousness?

**Comment by smitpatel** [comment]
Old query pipeline had a lot of APIs which were design errors. So we decided to prune surface and make sure that we expose only things which are needed and makes sense. This got removed because it was not used. We are willing to add surface as it is needed and specifically if it is right way to go.

**Comment by cincuranet** [comment]
> This got removed because it was not used.

Firebird provider used it. And the Oracle sample too (but I know that was dropped even before this).

What sucks in current design, with overriding whole `VisitSelect`, is that if something unrelated is fixed there, I have to first notice it and then obviously copy it. But it's what it is now.
