### ISSUE TITLE
Use exact instead of topological comparison when comparison spatial types

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#18921]
Our GeometryValueComparer currently compares geometry values by calling EqualsTopologically. Aside from the fact that this fails for GeometryCollection since that's unimplemented by NetTopologySuite (https://github.com/NetTopologySuite/NetTopologySuite/issues/213), it's not clear that this is the correct behavior: two geometry instances may cover the same space but be different, and for the purposes of tracking that difference seems relevant. Should we be calling EqualsExact instead?

/cc @bricelam

**Comment by bricelam** [comment]
Given our changes to client eval, and since we ended up deciding to throw in NetTopologySuite.IO.SqlServerBytes (instead of auto-correcting geometries), I agree that we should probably be more strict here.

**Comment by bricelam** [comment]
I double checked that SpatiaLite and SQL Server are correct (they only support EqualsTopologically)
