### ISSUE TITLE
Cosmos DB duplicating OwnsMany relationships

### ISSUE THREAD

**Issue by elmt1** [aspnet/EntityFrameworkCore#18948]
I was having trouble with OwnsMany relationships in my first Entity Framework Core application that uses Cosmos DB. I can replicate what I am seeing in a very simple application. Keep in mind, this application is not supposed to be complete or correct but just the simplest application I could create to show the issue.

### Steps to reproduce
Create a new .net Core 3.0 project with the following code or clone [this repository](https://github.com/elmt1/DemoEFCosmosDB.git) and use the single-class branch:

```
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace DemoEFCosmos
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new DemoContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
                var children = new HashSet<Child>()
                {
                    new Child() { ChildName = "Name1 " + DateTime.Now },
                    new Child() { ChildName = "Name2 " + DateTime.Now }
                };

                var addParent = new Parent()
                {
                    Id = Guid.NewGuid(),
                    Singleton = new Singleton() { SingletonName = "Name " + DateTime.Now },
                    Children = children
                };

                context.Parent?.Add(addParent);
                context.SaveChanges();

                Debug.WriteLine("Count Before: " + addParent.Children?.Count);
                Debug.WriteLine("Count Before: " + children.Count);

                // Reading the parent seems to double up the children 
                var dummy = context.Parent.ToList();
                Debug.WriteLine("Count Middle: " + addParent.Children?.Count);
                Debug.WriteLine("Count Middle: " + children.Count);

                // 2nd read doesn't change anything
                var dummy2 = context.Parent.ToList();
                Debug.WriteLine("Count After: " + addParent.Children?.Count);
                Debug.WriteLine("Count After: " + children.Count);
            }
        }
    }
    public class DemoContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseCosmos(
                "https://localhost:8081",
                "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
                databaseName: "Locations");

        public DbSet<Parent>? Parent { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultContainer("Demo");
            modelBuilder.Entity<Parent>().OwnsOne(b => b.Singleton);
            modelBuilder.Entity<Parent>().OwnsMany(b => b.Children);
        }
    }
    public class Parent
    {
        public Guid Id { get; set; }
        public Singleton? Singleton { get; set; }
        public ICollection<Child>? Children { get; set; }
    }
    public class Singleton
    {
        public string SingletonName { get; set; } = string.Empty;
    }
    public class Child
    {
        public string ChildName { get; set; } = string.Empty;
    }
}

```

Run the sample and you will see that the Children of Parent go from 2 Children to 4 Children on access.

If I set a break point in the Child constructor I see the following stack trace when the duplicate children are being created:

> DemoEFCosmos.dll!DemoEFCosmos.Child.Child() Line 5
> 	at C:\Workspace\demo\DemoEFCosmos\Child.cs(5)
> [Lightweight Function]
> System.Linq.dll!System.Linq.Enumerable.SelectIterator<Newtonsoft.Json.Linq.JObject, DemoEFCosmos.Child>(System.Collections.Generic.IEnumerable<Newtonsoft.Json.Linq.JObject> source, System.Func<Newtonsoft.Json.Linq.JObject, int, DemoEFCosmos.Child> selector)
> Microsoft.EntityFrameworkCore.Cosmos.dll!Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.PopulateCollection<DemoEFCosmos.Child, System.Collections.Generic.ICollection<DemoEFCosmos.Child>>(Microsoft.EntityFrameworkCore.Metadata.IClrCollectionAccessor accessor, System.Collections.Generic.IEnumerable<DemoEFCosmos.Child> entities)
> [Lightweight Function]
> Microsoft.EntityFrameworkCore.Cosmos.dll!Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable<DemoEFCosmos.Parent>.Enumerator.MoveNext()
> System.Private.CoreLib.dll!System.Collections.Generic.List<DemoEFCosmos.Parent>.List(System.Collections.Generic.IEnumerable<DemoEFCosmos.Parent> collection)
> System.Linq.dll!System.Linq.Enumerable.ToList<DemoEFCosmos.Parent>(System.Collections.Generic.IEnumerable<DemoEFCosmos.Parent> source)
> DemoEFCosmos.dll!DemoEFCosmos.Program.Main(string[] args) Line 36
> at C:\Workspace\demo\DemoEFCosmos\Program.cs(36)
> 

### Further technical details

EF Core version: 3.0
Database provider: Cosmos DB
Target framework: (e.g. .NET Core 3.0)
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.8

**Comment by elmt1** [comment]
Greetings @AndriySvyryd, I see that this issue is now closed. Is there a way that I can test to make sure the fix addresses the issues I am seeing in my applications?

Thank you!

**Comment by AndriySvyryd** [comment]
@elmt1 You can either wait for 3.1.1 to be released or use the daily build produced tomorrow.
