### ISSUE TITLE
OnModelCreating instead of OnConfiguring...

### ISSUE THREAD

**Issue by pieterphilippaerts** [aspnet/EntityFrameworkCore#19304]
The sentence "This default implementation builds the model for a given context by calling OnConfiguring(DbContextOptionsBuilder) on the context." is wrong. It should read: "This default implementation builds the model for a given context by calling OnModelCreating(ModelBuilder) on the context."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f0b7b04-0699-e9f2-d756-4129b318ba20
* Version Independent ID: 94ad0f7c-6593-b4b2-3f72-42f7960abe57
* Content: [ModelCustomizer.Customize(ModelBuilder, DbContext) Method (Microsoft.EntityFrameworkCore.Infrastructure)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.modelcustomizer.customize?view=efcore-3.0#feedback)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/ModelCustomizer.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore.Infrastructure/ModelCustomizer.xml)
* Product: **ef-core-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
@pieterphilippaerts - Thanks for pointing out. Transferred issue to source code repo. Changes should be made in XML docs in source code, which will regenerate and propagate to API Docs.
