### ISSUE TITLE
Allow creation of a DbCommand from an EF IQueryable

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#19358]
See #19335

For example:
```C#
var query = context.Blogs.Where(b => b.Published);
var command = query.CreateDbCommand();
```

Things to note:
* The command providers access to the SQL query string and parameters.
* The created command is not the actual command that EF will use if the query is then executed. A new command will be created for this, but using the same mechanism.
* The created command can likely be executed, but will be doing so outside of the normal EF environment and so may not have exactly the same behavior.

**Comment by Giorgi** [comment]
Looking at the [Source of CreateDbCommand](https://github.com/dotnet/efcore/blob/master/src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs#L49) it looks like that the command must be executed before the cache is populated. Is there a way to get the command without actually executing the `IQueryable` ?

**Comment by ajcvickers** [comment]
@Giorgi What "cache" are you referring to?

**Comment by Giorgi** [comment]
I mean this code: https://github.com/dotnet/efcore/blob/b3a89d0f0ead4ce2e98a3fdf0bce214171b27cb3/src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs#L88

**Comment by Giorgi** [comment]
The code that I linked to in my first comment calls source.Provider.Execute so I guess that is needed to populate the `_relationalCommandCache`

**Comment by ajcvickers** [comment]
@Giorgi The code for CreateDbCommand does not execute the command. Also, as far as I can tell, it will populate/use the command cache.
