### ISSUE TITLE
Perf: Consider using entity instances for value buffer

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#2079]
Currently the query pipeline always reads values from the data reader into an object array buffer, then binds that object array to the materializer which reads values from the buffer and sets properties/fields in the entity.

We should consider instead binding the entity materialization directly to the data reader, which would potentially eliminate the use of one object array and remove a substantial value boxing. IValueReader was designed to allow this, but it didn't end up being used in this way because query always requires a buffer for a data reader, since values can be read again after the reader has been closed.

However, if that buffer was kept but instead changed to use materialized entities instead of an object array, then query would have the buffer it needs, and materialization could again be bound directly to the data reader.

Note that if we do this, then entities may be materialized that are then not returned in the query due to identity resolution kicking in. However, unlike in the old stack, this can happen anyway in EF Core because of client evaluation. Also, this could potentially be optimized away as well if the materializer code is made aware of the identity map.

Doing this also likely means that the GetValues method, which is currently used by SQL Server, would not be used anymore because the read of each value would be bound directly to property/field materialization. This might break Mono until the Mono bug is fixed, but this could likely be worked around.

**Comment by FransBouma** [comment]
> Doing this also likely means that the GetValues method, which is currently used by SQL Server, would not be used anymore because the read of each value would be bound directly to property/field materialization. This might break Mono until the Mono bug is fixed, but this could likely be worked around.

You mean, this method can be removed from the API? because it's very useful (I use it to materialize entities, as we simply keep the object array around inside the entity, so no property get/set needed)

**Comment by anpete** [comment]
@FransBouma, No we will not be removing that method.

**Comment by ajcvickers** [comment]
Marking for re-triage since I don't think we're going to get to this in v1.

**Comment by natemcmaster** [comment]
FWIW Mono > 4.3 (not yet released) will support SqlDataReader.GetFieldValue.

**Comment by smitpatel** [comment]
The latest Mono release is: 5.0.1 Stable (5.0.1.1)
Also according to this chart https://github.com/dotnet/standard/blob/master/docs/versions.md
We would have never supported anything below mono 4.6
& mono 4.6 has APIs

**Comment by smitpatel** [comment]
This has been done in new query pipeline. We do not have buffering yet but we can buffer the results directly rather than underlying object arrays. (or something similar)
