### ISSUE TITLE
Update pipeline: Add more logging

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFrameworkCore#220]

**Comment by smitpatel** [comment]
I wonder what @bricelam means by consider this for current release and also proposing to close. Should we implement it and close ? :trollface:

**Comment by ajcvickers** [comment]
@smitpatel Assuming it means if we don't do it now, then we'll probably never do it.

**Comment by AndriySvyryd** [comment]
This is probably for provider-specific code, like batching

**Comment by bricelam** [comment]
Yep. "Now or never."
