### ISSUE TITLE
EventNotification Support?

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/EntityFrameworkCore#2281]
With the advent of https://github.com/aspnet/EventNotification coming, I'm wondering when EF will start supporting/publishing notifications? This is now supposed to be the supported way of getting insights out from the frameworks and it would be great to start getting some thinking going about what details will be given, when, etc. // @rynowak

**Comment by rowanmiller** [comment]
We're going to do some minimal work initially but full fledged support will probably need to wait until after 7.0.0. @avanderhoorn it would be good to know if there is some minimal set of things we could do to support Glimpse (would also make a great PR :smile:).
