### ISSUE TITLE
Reverse Engineer: Allow reading connection strings from configuration

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#2464]
Currently the reverse engineering command line tools require the user to provide a full database connection string on each command. 

It would be nice to enable users to place the connection string in configuration and then reference the configuration key in the commands.

Since for DNX-based applications there isn't a fixed pattern for how the configuration files look like the feature would need to rely on some convention to work, e.g.:
1. We could try instantiating a Startup class with the right environment and look for a Configuration property on it.
2. We could setup an IConfiguraton at design time with some well-know configuration sources, e.g. config.json and the secrets file if they are present in the application. 

cc @Eilon

**Comment by Eilon** [comment]
Yeah I think the second option is a great place to start because it's super easy to implement and likely covers all the common scenarios. Later we could always get fancier and implement other options.

**Comment by rowanmiller** [comment]
This would be particularly good for re-scaffolding an existing model (since you'll have the connection string in config already)

**Comment by mhenderson442** [comment]
@divega Thanks for pointing out issue. As I mentioned on #2952, I would like the generated code in the context file to reference a config file, as apposed to hard coding the connection string in the `*Context.cs` file. 

Some off the cuff suggestions might be adding an option to the RevEng command that reads a config file. Similar to the [dtexec](https://technet.microsoft.com/en-US/library/ms162810%28v=SQL.105%29.aspx?f=255&MSPPError=-2147217396) utility in SSIS.

I have not seen this used for C# code, but could one edit C# code from a Grunt task? I am thinking of something like a search and replace activity on the `*Context.cs` file.

**Comment by divega** [comment]
@mhenderson442 just to double check, are you only referring to ASP.NET 5.0 style configuration or also .Config files?

**Comment by mhenderson442** [comment]
@divega 

Yes. I am referring to ASP.Net 5 style configuration. And to get extra fancy, I am reverse engineering against an Azure SQL database.

**Comment by mhenderson442** [comment]
Following the [Read the docs](http://ef.readthedocs.org/en/latest/getting-started/aspnet5.html) documentation, I set the connection in the startup.cs class. 

````
var connection = Configuration["Data:DefaultConnection:ConnectionString"];
		
services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<MercurySchoolContext>(options => options.UseSqlServer(connection));	
````
Wondering if you could leave out the `override void OnConfiguring(...` method from the code generated for the `*Context.cs` class.

Another thing I've seen in `.cs` files generated for SSIS custom script transformations is methods stubbed out and commented out. I am thinking something like this:

````
        //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        //{
        //    optionsBuilder.UseSqlServer(<your connection string here>}
        //}		

````

Looks like the rub you're faced with is when the model changes and one has to re-execute RevEng.

**Comment by bricelam** [comment]
In ASP.NET Core 2.0, `IConfiguration` is added to the application's service provider. Tools can access the application services if they're using the new `BuildWebHost` pattern. We could easily support the `name=` syntax (see #8641) on the `dotnet ef dbcontext scaffold` and `Scaffold-DbContext` commands.

**Comment by bricelam** [comment]
Marking for re-triage in case we want to try and fit this into 2.0

**Comment by ajcvickers** [comment]
Marking for re-triage; not sure why I assigned it to myself.
