### ISSUE TITLE
Support async extension methods on IQuerayble

### ISSUE THREAD

**Issue by kichalla** [aspnet/EntityFrameworkCore#256]
I am using InMemory store where I use the "SingleOrDefaultAsync" api to retrieve an item…I am noticing that even though the item with the given id is present, it is not retrieving it…the sync version “SingleOrDefault” retrieves it fine…

```
// GET api/suggestions/5
public async Task<IActionResult> Get(int id)
{
    Suggestion suggestion = await dataContext.Suggestions.SingleOrDefaultAsync(sug => sug.Id == id);
    if (suggestion == null)
    {
        return new CustomHttpStatusCodeResult(404);
    }

    return new CustomJsonResult(suggestion);
}
```

It seems this is a known issue...creating issue for tracking...

**Comment by weitzhandler** [comment]
Would love to see this feature implemented.

**Comment by divega** [comment]
@weitzhandler EF7 defines and support several async extension methods for IQueryable<T> (see https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/Extensions/EntityFrameworkQueryableExtensions.cs). Is there anything you are missing there or that you have found isn't working correctly? 

In case you are asking for the support for async operators over IQueryable<T> to become more first class as opposed to an EF extension, it might help to file an issue at https://github.com/dotnet/corefx.

**Comment by weitzhandler** [comment]
@divega  I got it all wrong. Sorry for interupting, I've deleted my previous post. I'm deleting this post too. Just sending it so you get notified.
