### ISSUE TITLE
Test Subquery_with_Distinct_Skip_FirstOrDefault_without_OrderBy is non-deterministic

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#26353]
It seems this test generates non-deterministic results by design (omitting OrderBy), and ordering on the client isn't an option here. Should we convert this test to not use AssertQuery?

/cc @maumar @smitpatel

**Comment by smitpatel** [comment]
We can still use AssertQuery for ease of writing and add element asserter to skip the check of elements inside collection.

**Comment by maumar** [comment]
I was thinking that too @smitpatel
