### ISSUE TITLE
Identity: SqlServer adding a string ForeignKey throws exception regarding length

### ISSUE THREAD

**Issue by HaoK** [aspnet/EntityFrameworkCore#275]
Both properties are strings, so I'm not sure what the issue is. (Note: the foreignkeys work fine using InMemoryDataStore)

```
    protected override void OnModelCreating(ModelBuilder builder)
    {
        builder.Entity<TUser>()
            .Key(u => u.Id)
            .Properties(ps => ps.Property(u => u.UserName))
            .ToTable("AspNetUsers");

        builder.Entity<IdentityUserClaim>()
            .Key(uc => uc.Id)
            // TODO: this throws a length exception currently, investigate
            .ForeignKeys(fk => fk.ForeignKey<TUser>(f => f.UserId))
            .ToTable("AspNetUserClaims");
    }
```

Results in:
      System.Data.SqlClient.SqlException : Column 'AspNetUsers.Id' is not the same length or scale as referencing column
 'AspNetUserClaims.UserId' in foreign key 'FK_AspNetUserClaims_AspNetUsers_UserId'. Columns participating in a foreign k
ey relationship must be defined with the same length and scale.\r\nCould not create constraint. See previous errors.

```
public class IdentityUserClaim : IdentityUserClaim<string> { }
public class IdentityUserClaim<TKey> where TKey : IEquatable<TKey>
{
    /// <summary>
    ///     Primary key
    /// </summary>
    public virtual int Id { get; set; }

    /// <summary>
    ///     User Id for the user who owns this login
    /// </summary>
    public virtual TKey UserId { get; set; }

public class User
{
    public virtual string Id { get; set; }
```

**Comment by tenchy72** [comment]
public class Department
    {
        [Key]
        [Required]
        [MaxLength(50)]
        [Display(Name = "Department")]
        public String DeptName { get; set; }


        [MaxLength(6)]
        [Display(Name = "Fund")]
        public String FundID { get; set; }


        [MaxLength(6)]
        [Display(Name = "Department Number")]
        public String DeptNumber { get; set; }
    }
  
  public class Department_AKA
    {
        [Key]
        [Required]
        [MaxLength(50)]
        [Display(Name = "AKA Department Desc/Name")]
        public String AKA { get; set; }

        [Required]
        [MaxLength(50)]
        [Display(Name = "Department")]
        public String DeptName { get; set; }
        public virtual IEnumerable<Department> lstDepartment { get; set; }

    }

Throws error :

SqlException: Column 'Department_AKAs.AKA' is not the same length or scale as referencing column 'Departments.Department_AKAAKA' in foreign key 'FK_Departments_Department_AKAs_Department_AKAAKA'. Columns participating in a foreign key relationship must be defined with the same length and scale.

Am I missing something?
