### ISSUE TITLE
Is there an example in which --project switch is mandatory when invoking dotnet ef database update?

### ISSUE THREAD

**Issue by mauler2025** [aspnet/EntityFrameworkCore#28390]
I have  a  solution consisting of 4 projects:

 - `EntityProject` :  contains POCO classes.
 - `ContextProject` : contains database context derived from `DbContext`, has a reference to `EntityProject`.
 - `MigrationProject` : contains `public class Empty{}`, has a reference to `ContextProject`.
 - `StartupProject` :  for example Asp.Net Core Webapi, has references to `ContextProject` and `MigrationProject`.
 
In `StartupProject`, I invoke `MigrationAssembly(typeof(MigrationProject.Empty).Assembly.GetName().Name)` to change the migration assembly project from the default `ContextProject` to `MigrationProject`.
 

 If the current working directory is the solution directory, I usually do the following and it works.

- migration with 
```dotnet ef migrations add Initial --project MigrationProject --startup-project StartupProject```
  where `--project` is mandatory.

- updating database with 
```dotnet ef database update --startup-project StartupProject```
  where `--project` is omitted.

Now I am wondering why `dotnet ef database update` also has `--project` switch, what is it for? Is there an example in which `--project` is mandatory?

Any comments are always welcome!

**Comment by pstricks-fans** [comment]
I see. It is a reserved switch which is currently not in use.
