### ISSUE TITLE
Equivalent to ObjectContext.CreateDatabaseScript

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#2943]
This is one of my favorite features of the EF Power Tools, and I think we should have similar functionality in EF Core.

My proposal is an `db.Database.GenerateCreateScript()` extension method. Here's the implementation. :wink:

``` C#
public static string GenerateCreateScript(this DatabaseFacade database)
{
    var model = database.GetService<IModel>();
    var differ = database.GetService<IMigrationsModelDiffer>();
    var generator = database.GetService<IMigrationsSqlGenerator>();
    var sql = database.GetService<ISqlGenerationHelper>();

    var operations = differ.GetDifferences(null, model);
    var commands = generator.Generate(operations, model);

    var builder = new StringBuilder();
    foreach (var command in commands)
    {
        builder
            .Append(command.CommandText)
            .AppendLine(sql.BatchTerminator);
    }

    return builder.ToString();
}
```

**Comment by bricelam** [comment]
Note to implementer: Common logic should be shared with IRelationalDatabaseCreator and Migrator.

**Comment by ErikEJ** [comment]
I will try to get this added to EF Core Power Tools https://github.com/ErikEJ/SqlCeToolbox/issues/521

**Comment by bricelam** [comment]
@ErikEJ, we'd also accept a PR here too. It feels like a generally useful thing to have in Relational.

**Comment by ErikEJ** [comment]
@bricelam  Considering a PR for this - you wrote:

>> Common logic should be shared with RelationalDatabaseCreator and Migrator. 

What "common logic" are you referring to? Or is that comment obsolete?

**Comment by bricelam** [comment]
1. The logic to get the current model and turn it into commands (in `RelationalDatabaseCrator`)
2. The logic of combining commands with a `BatchTerminator` (in `Migrator`)

I imagine the extension method on `DatabaseFacade` will call an implementation like `RelationalDatabaseCreator.GenerateCreateScript()`.

**Comment by ErikEJ** [comment]
@bricelam Thanks, all I can see in Migrator is this private, unused (?) method:
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational/Migrations/Internal/Migrator.cs#L360

**Comment by bricelam** [comment]
I suppose I was thinking the [GenerateScript](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational/Migrations/Internal/Migrator.cs#L234) method, but it doesn't look like much can be reused there.
