### ISSUE TITLE
SqlQuery doesn't support scalar values but works with unmapped types

### ISSUE THREAD

**Issue by Misiu** [aspnet/EntityFrameworkCore#30447]
Preview 1 of EF8 supports Raw SQL Queries, but we must create class to be able to get a single scalar value.

so this works: 
```
var id = "5A83F3C3-A88F-4A56-934C-FFB8D0E682C1";
var product = context.Database.SqlQuery<Product>($"SELECT name FROM dbo.test_table WHERE entity_id={id}").FirstOrDefault();
Console.WriteLine(product?.Name);
```

and this throws error:
```
var name = context.Database.SqlQuery<string>($"SELECT name FROM dbo.test_table WHERE entity_id={id}").FirstOrDefault();
Console.WriteLine(name);
```

full example:

```C#
using Microsoft.EntityFrameworkCore;

class Program
{
    static void Main(string[] args)
    {
        // specify the connection string to your SQL Server database
        var connectionString = "Server=192.168.0.20;Database=TEST;User Id=test;Password=secret;TrustServerCertificate=True;Application Name=TEST;";

        var options = new DbContextOptionsBuilder<MyDbContext>()
            .UseSqlServer(connectionString)
            .Options;

        using (var context = new MyDbContext(options))
        {
            //this works
            var id = "5A83F3C3-A88F-4A56-934C-FFB8D0E682C1";
            var product = context.Database.SqlQuery<Product>($"SELECT name FROM dbo.test_table WHERE entity_id={id}").FirstOrDefault();
            Console.WriteLine(product?.Name);

            /*
            exec sp_executesql N'SELECT TOP(1) [p].[Name]
            FROM (
                SELECT name FROM dbo.test_table WHERE entity_id=@p0
            ) AS [p]',N'@p0 nvarchar(4000)',@p0=N'5A83F3C3-A88F-4A56-934C-FFB8D0E682C1'
             */

            //this throws error with message "Invalid column name 'Value'."

            var name = context.Database.SqlQuery<string>($"SELECT name FROM dbo.test_table WHERE entity_id={id}").FirstOrDefault();
            Console.WriteLine(name);


            /*
            exec sp_executesql N'SELECT TOP(1) [t].[Value]
            FROM (
                SELECT name FROM dbo.test_table WHERE entity_id=@p0
            ) AS [t]',N'@p0 nvarchar(4000)',@p0=N'5A83F3C3-A88F-4A56-934C-FFB8D0E682C1'
            */

        }

        Console.ReadLine();
    }
}

public class MyDbContext : DbContext
{
    public MyDbContext(DbContextOptions<MyDbContext> options) : base(options) { }
}

public class Product
{
    public string Name { get; set; }
}
```

### Error code

```
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Invalid column name 'Value'.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) in /_/src/EFCore.Relational/Storage/RelationalCommand.cs:line 533
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator) in /_/src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs:line 240
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator) in /_/src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs:line 168
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in /_/src/EFCore.SqlServer/Storage/Internal/SqlServerExecutionStrategy.cs:line 57
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext() in /_/src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs:line 171
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found) in /_/src/libraries/System.Linq/src/System/Linq/Single.cs:line 88
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in /_/src/EFCore/Query/Internal/QueryCompiler.cs:line 68
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in /_/src/EFCore/Query/Internal/EntityQueryProvider.cs:line 63
   at Program.Main(String[] args) in D:\GitHub\EF8Tests\EF8Tests\Program.cs:line 30

```

### Include provider and version information

EF Core version: 8.0.0-preview.1.23111.4
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 7.0
Operating system: Windows 10
IDE: Visual Studio 2022 17.5.1

**Comment by andriysavin** [comment]
Have you tried as a workaround to add column name EF is expecting in your query, e.g. `"SELECT name AS Value FROM..."`

**Comment by Misiu** [comment]
> Have you tried as a workaround to add column name EF is expecting in your query, e.g. `"SELECT name AS Value FROM..."`?

That works, but as you wrote, this is a workaround. It should work without `as value`.

**Comment by roji** [comment]
This behavior is by design. [As the docs explain](https://learn.microsoft.com/en-us/ef/core/querying/sql-queries#querying-scalar-non-entity-types), when you compose LINQ operators over your SQL query, EF must know what the column name is that's coming out of it - your SQL query is integrated as a subquery in the larger query. In your code above, you're composing FirstOrDefault on top of the SqlQuery, so it's your responsibility to add the `AS Value` on the output column, so that EF can reference it outside the subquery.

**Comment by goenning** [comment]
Why is "as value" not needed in this example?

```charp
var ids = context.Database
    .SqlQuery<int>($"SELECT [BlogId] FROM [Blogs]")
    .ToList();
```

**Comment by roji** [comment]
@goenning because no operators are being compared on top of SqlQuery. ToList simply loads all of the query results, whereas FirstOrDefault composes a `SELECT TOP(1) [t].[Value] ...` on top of it.

**Comment by angelaki** [comment]
@goenning I guess the DbReader just uses the first column no matter what name it has.

While theSQL builder needs to know the columns name. So for scalars just assumes `value`.

@roji why not just use * for scalars? Would it mean a too expensive internal implementation / changes for this single usecase? I'm excited in the design decision. Not parsing the actual name from the querx I totally agree - not worth the effort.

**Comment by roji** [comment]
Star (*) might work in this very particular case, but depending what exactly you compose, it might not. Star in SQL can mean multiple columns, which wouldn't work in various other SQL contexts - in this scenario there's only ever a single column coming out etc.

We generally avoid star because when reading results back, we'd have to read them by name (since ordering isn't known/clear); and that's slightly less efficient than reading by index.

**Comment by angelaki** [comment]
@roji Yeah sure, totally agree! Bin since you can read (the not sub selected) scalar value query with every column name, I guess in this case you say: just the first / single column. And so the SQL generator could say: scalar? Star (*) is just fine, since there can only be a single value. But yeah, followi g sub querys might fail. So I guess you just decided: call it value and the reader just takes the first column?

**Comment by Misiu** [comment]
Hmm...
so the correct query (which works) is:
```$"SELECT name as value FROM dbo.test_table WHERE entity_id={id}"```
but this also works:
```$"SELECT name as value, 1 as id FROM dbo.test_table WHERE entity_id={id}"```
```$"SELECT name as not_value, 'fake data' as value FROM dbo.test_table WHERE entity_id={id}"```

I think that we need a proper scalar function that will return  the first column of the first row in the result set returned by the query,  just like https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.executescalar?view=dotnet-plat-ext-8.0

I use this workaround:
```
public static T? SqlQueryScalar<T>(this DatabaseFacade facade, FormattableString sql)
{
    using var cmd = facade.GetDbConnection().CreateCommand();
    cmd.CommandText = sql.ToString();

    if (cmd.Connection != null && cmd.Connection.State != ConnectionState.Open)
    {
        cmd.Connection.Open();
    }

    var result = cmd.ExecuteScalar();

    if (result is null)
    {
        return default;
    }

    return (T)result;
}
```

but as I wrote this is a workaround and with this, I must change my query from to:
```$"SELECT name as value FROM dbo.test_table WHERE entity_id='{id}'"``` <- extra apostrophes around the parameter

**Comment by goenning** [comment]
And it seems like `Value` might not be the best name for it? Postgres doesn't like it:

```sql
SELECT t."Value"
      FROM (
          SELECT id as Value FROM app_environments WHERE app_key = @p0
      ) AS t
```

Npgsql.PostgresException (0x80004005): 42703: column t.Value does not exist

And I'm forced to wrap it on double quotes :(

**Comment by roji** [comment]
Yep, you indeed need the double-quotes since PG folds unquoted identifiers to lowercase.

**Comment by roji** [comment]
@IanKemp that's always easy to say, but what do you suggest?

**Comment by ltbyun** [comment]
> [@IanKemp](https://github.com/IanKemp) that's always easy to say, but what do you suggest?

if it returns primitive and ends by Single or SingleOrDefault, then just get the first row and first column value. i don't believe it is very hard to do this.

**Comment by roji** [comment]
> if it returns primitive and ends by Single or SingleOrDefault, then just get the first row and first column value. i don't believe it is very hard to do this.

OK, can you provide the SQL you'd expect EF to generate for that case?

**Comment by IanKemp** [comment]
> > if it returns primitive and ends by Single or SingleOrDefault, then just get the first row and first column value. i don't believe it is very hard to do this.
> 
> ~OK, can you provide the SQL you'd expect EF to generate for that case?~
> 
> Well, f one thing, FirstOrDefault()'s job is to make sure only 1 row actually gets fetched from the database. If we allow a query to download the entire contents of some huge table, only to take the first row and discard the rest, we'll have done our users a very big dis-service by hiding a potentiialy critical performance problem. Unless I'm mistaken, Dapper has a different approach here - it sends your SQL as-is, and any operators are executed in memory on the results, which can cause exactly this problem if users aren't careful (in other words, EF's composed operators are IQueryable, while Dapper's are IEnumerable).
> 
> So FirstOrDefault() must impact the SQL which EF sends to the database, adding e.g. `LIMIT 1` (depending on the database) - that instructs the database to send back just one row. But since the SQL here is a string provided by the user, we can't manipulate it, since that would require us to be able to parse SQL, which EF cannot do (parsing SQL is a hugely complex task that varies considerably across dialects).
> 
> This is why when you compose operators, EF takes the user's SQL string, and integrated it as a subquery within a larger SQL:
> 
> SELECT ...
> FROM (
>     -- User SQL
> )
> 
> But once there's a subquery, the SQL outside of the subquery (which EF generates) needs to know the name of the column(s) projected out from that subquery - that's just how SQL works. So we're left with no alternative but to require that some specific name be used, i.e. `Value`.
> 
> This is just the somewhat unfortunate consequence of trying to mix arbitrary user-provided SQL (which EF cannot understand or manipulate) with additional EF LINQ operator composed on top.

I fully understand the limitations and vagaries from the SQL side, but... does this problem absolutely have to be solved via SQL? Is it not possible to instead implement a solution in C# that optimises `SqlQuery<TValue>(<sql string>).First()` to use a `SqlDataReader` and pull out the first row + column of data from the latter?

**Comment by angelaki** [comment]
> > > if it returns primitive and ends by Single or SingleOrDefault, then just get the first row and first column value. i don't believe it is very hard to do this.
> > 
> > 
> > ~OK, can you provide the SQL you'd expect EF to generate for that case?~
> > Well, f one thing, FirstOrDefault()'s job is to make sure only 1 row actually gets fetched from the database. If we allow a query to download the entire contents of some huge table, only to take the first row and discard the rest, we'll have done our users a very big dis-service by hiding a potentiialy critical performance problem. Unless I'm mistaken, Dapper has a different approach here - it sends your SQL as-is, and any operators are executed in memory on the results, which can cause exactly this problem if users aren't careful (in other words, EF's composed operators are IQueryable, while Dapper's are IEnumerable).
> > So FirstOrDefault() must impact the SQL which EF sends to the database, adding e.g. `LIMIT 1` (depending on the database) - that instructs the database to send back just one row. But since the SQL here is a string provided by the user, we can't manipulate it, since that would require us to be able to parse SQL, which EF cannot do (parsing SQL is a hugely complex task that varies considerably across dialects).
> > This is why when you compose operators, EF takes the user's SQL string, and integrated it as a subquery within a larger SQL:
> > SELECT ...
> > FROM (
> > -- User SQL
> > )
> > But once there's a subquery, the SQL outside of the subquery (which EF generates) needs to know the name of the column(s) projected out from that subquery - that's just how SQL works. So we're left with no alternative but to require that some specific name be used, i.e. `Value`.
> > This is just the somewhat unfortunate consequence of trying to mix arbitrary user-provided SQL (which EF cannot understand or manipulate) with additional EF LINQ operator composed on top.
> 
> I fully understand the limitations and vagaries from the SQL side, but... does this problem absolutely have to be solved via SQL? Is it not possible to instead implement a solution in C# that optimises `SqlQuery<TValue>(<sql string>).First()` to use a `SqlDataReader` and pull out the first row + column of data from the latter?

@roji made his answer a bit more constructive (eventhough the first one had the same message / was quite funny). I guess your mistake is that you only see the issue from one side. Sure, if e.g. `First()` was the last call EF _could_ wrap something around it to make it work. But don't forget you're able to even put this somewhere else in your `IQueryable`. EF needs to be able to build an SQL for every expression.

And imho the team is totally right if they decide not to start implementing exceptions for special use-cases. Thing would get way more confusing, if a Queryable runs under some circumstances and won't if called differently.

If the SQL syntax would allow something like this (like `SELECT *[0] AS value FROM Data`, but there is nothing like this) the team could implement it. But there's no chance to do it. And that's what @roji was asking for if he asked to supply an SQL - at least I think so.

**Comment by roji** [comment]
> Is it not possible to instead implement a solution in C# that optimises SqlQuery<TValue>(<sql string>).First() to use a SqlDataReader and pull out the first row + column of data from the latter?

Sure, we could do that - but that would still ask the database to produce - and send - **all** the rows. On the client side, the fact that you only pull the first row out of the SqlDataReader doesn't change any of that - there are still many other rows coming back over the network from the database, and the database is still doing a lot of totally unneeded work to produce them.

I know this looks like a silly "this must be easy/possible" kind of situation, but sometimes that's simply not the case. EF's contract to users is super simple: we never cause more data to be sent from the database then we have to, as expressed by the query. This is very important, and helps avoid cases where suddenly tons of data is being transferred without it being obvious.
