### ISSUE TITLE
WinUI 3 Scaffold-DbContext error

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFrameworkCore#30758]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WinUI-3-Scaffold-DbContext-error/10344494)._

---
[severity:I'm unable to use this version]
Hello,

I want to scafffold-DbContext it works well for WPF, but there is a problem for WinUI 3 Blank App, Packaged and Template for WinUI 3.

Edition	Windows 11 Pro
Version	22H2
Installed on	‎3/‎27/‎2023
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0

Visual Studio Professional 2022
17.5.3

How to reproduce an error:
1. Create a new project Blank App, Packaged (WinUI 3 in Desktop) or Template for WinUi 3
2. NuGet install:
	- Microsoft.EntityFrameworkCore.SqlServer 7.0.5
	- EntityFrameWorkCore.Tools 7.0.5
3. Run Scaffold-DbContext in Package Manager Console
Scaffold-DbContext -provider Microsoft.EntityFrameworkCore.SqlServer -connection "Data Source=...

```
Failed to load the dll from [C:\git\winUiSqlTest\App1\App1\bin\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\hostpolicy.dll], HRESULT: 0x800700C1
An error occurred while loading required library hostpolicy.dll from [C:\git\winUiSqlTest\App1\App1\bin\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\]
```

How to fix the problem?
Thank you in advance.

---
#### Feedback Bot on 4/20/2023, 09:36 AM: 

(private comment, text removed)
#### marekp18 on 4/21/2023, 11:51 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by bricelam** [comment]
Do you have the 32-bit .NET runtime installed?

Or did you intend to run as 64-bit instead?

![image](https://user-images.githubusercontent.com/1226749/234700485-8126d9bb-5e4a-453f-936a-53ed35afc3d9.png)
