### ISSUE TITLE
Generic type converters for property types.

### ISSUE THREAD

**Issue by fiseni** [aspnet/EntityFrameworkCore#33497]
Hi,

This is related to an old issue #31392. The issue is closed as not planned.
Here I just want to ask about possible workarounds on this topic. We need this in the `SmartEnum` library, and it's implemented as shown [here](https://github.com/ardalis/SmartEnum/blob/main/src/SmartEnum.EFCore/SmartEnumConverterExtensions.cs). Some further discussions on this topic can be found [here](https://github.com/ardalis/SmartEnum/pull/296#pullrequestreview-1079568928).

In a nutshell, this is what we're doing

```csharp
protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
{
    var modelBuilder = configurationBuilder.CreateModelBuilder(null);

    var propertyTypes = // find the property types

    foreach (var propertyType in propertyTypes)
    {
        // Register a converter for the property type
    }
}
```

So, the question is how dangerous is it to build the model at this stage? Does this mean that model building will happen twice (which might be acceptable somehow), or it also can affect the actual model building afterward (through the internal caches)?

**Comment by AndriySvyryd** [comment]
> So, the question is how dangerous is it to build the model at this stage? Does this mean that model building will happen twice (which might be acceptable somehow), or it also can affect the actual model building afterward (through the internal caches)?

Calling `configurationBuilder.CreateModelBuilder` in `ConfigureConventions` has no effect on the model that will be used by the context. Note that a model created this way won't necessarily contain all entity types since `OnModelCreating` isn't called.

Additionaly, you can invoke `modelBuilder.FinalizeModel()` to finish invoking the conventions.
