### ISSUE TITLE
Support for database enums

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFrameworkCore#3620]
PostgreSQL allows defining enums as first-class database types, which can then be used in regular columns. Npgsql exposes this by allowing users to define a mapping between a PostgreSQL enum and a CLR enum.

EF7's type mapping now allows arbitrary types to be mapped to supported database types, this works very well with PostgreSQL types - types such as `macaddr` are successfully mapped in EF7 to .NET PhysicalAddress. However, when trying to add enum mapping support I ran into trouble - it seems that in various areas of the EF7 core enums are unwrapped and treated as their underlying numeric type instead (e.g. int).

I'm guessing this is to allow enums to be saved to numeric columns for databases which don't support enums natively (e.g. SqlServer). Am I understanding the situation correctly, is database enum support currently impossible in EF7?

**Comment by dlogik** [comment]
Hi, would it be possible to give some pointers where this unwrapping behavior for Enums occurs in the EntityFramework code? I would be interesting in forking and trying to get something working (at least hacking together a soltuion if possible) Thanks

**Comment by ryancole** [comment]
I see this was removed from a certain priority label awhile back. Is this still on any radar anywhere, or has this been shelved for now?

**Comment by rowanmiller** [comment]
We will look at it again post v1.0.0

**Comment by vankooch** [comment]
Would be great to get this working.

**Comment by stevenxi** [comment]
How I get it work around is creating standard structured tables for each Enum.
And sync name/id when seeding / upgrading db.

So this would work no matter if db supports enum, the column in db is still number, but there's the foreign key that link to a proper table for the enum.

And with attribute on enum fields, you could even add description to it.

**Comment by karldodd** [comment]
Looking forward to this.

**Comment by kernel-io** [comment]
Also looking forward to this, right now I'm also doing what @stevenxi does.

**Comment by CoffeeDreamLabs** [comment]
Any news on this matter?
As stated by @rowanmiller above this will be addressed post v1.0.0
Just want to know if we can expect some changes on this topic in the near future!?

**Comment by ajcvickers** [comment]
@CoffeeDreamLabs I believe that the updates to the type mapper in 2.1 should allow the Postgres driver to support this starting in 2.1. /cc @roji

**Comment by markusschaber** [comment]
Is there any way to verify this? Is the ball on the npgsql side now?

**Comment by vankooch** [comment]
I think the ball is on the EF team right now, as the npgsql team is [waiting](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/27) for a fix

**Comment by roji** [comment]
Thanks for this work @ajcvickers, I'll take a look as soon as I can for preview2 and will post back here if I run into any further trouble.

For anyone interested in PostgreSQL native enums, please follow progress in https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/27.

**Comment by ajcvickers** [comment]
@roji Wanted to let you know that @anpete uncovered an issue where enum literals in queries are being sent to the provider as literals of the underlying numeric type because of the expression tree created by the compiler. But we think it can be fixed.

**Comment by roji** [comment]
Thanks for the heads-up, I'll work on non-literal functionality until this is resolved, is there an issue tracking this (or maybe just reopen this)?
