### ISSUE TITLE
[Conventions] Validating conventions should be moved to ModelValidator

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#4016]
Presently the conventions we run after model is built includes
1. `KeyConvention` - throws for shadow key defined by convention
2. `KeyAttributeConvention` - throws for composite PK defined using data-annotations and not overridden by fluent api
3. `PropertyMappingValidationConvention` - throws for primitive properties which cant be mapped or properties not added to the model
4. `ForeignKeyPropertyDiscoveryConvention` - throws for ambiguos foreign key properties

None of above makes any changes to the model, they were defined as convention since they use configuration source and needed to be run on builder. But now we have configuration source defined on metadata instead of builder so we can move above task to ModelValidator step.

Motivation behind this, if there is no primary key defined on entity type then foreignkey which references such entity type will create alternate key by convention. This conventional key will throw exception before ModelValidator is run stating that foreign key references conventional key whereas the real issue with the model is lack of PK.

**Comment by AndriySvyryd** [comment]
Also rename `Model.Validate()` to `Model.Build()`

**Comment by AndriySvyryd** [comment]
Refactor the methods in ModelValidator to improve perf

**Comment by ajcvickers** [comment]
Poaching
