### ISSUE TITLE
SQLite Query: Translate more methods

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#4108]
Comparing the [method translation support in our SQL Server provider](https://github.com/aspnet/EntityFramework/tree/substringOffByOne/src/EntityFramework.MicrosoftSqlServer/Query/ExpressionTranslators/Internal) with [what we have in our SQLite provider](https://github.com/aspnet/EntityFramework/tree/substringOffByOne/src/EntityFramework.Sqlite/Query/ExpressionTranslators/Internal) and [the functions that SQLite can support](http://www.sqlite.org/lang_corefunc.html) it seems to me that there a few translations that should be inexpensive to add to SQLite because it should be a matter of copying the SQL Server implementation and tests, in some cases generating a different function name.

Note that I am not trying to make any value judgement on the things that are missing in SQL Server or [on relational](https://github.com/aspnet/EntityFramework/tree/substringOffByOne/src/EntityFramework.Relational/Query/ExpressionTranslators). That is a separate conversation and as everybody knows "LINQ is never done" :trollface:

**Comment by bricelam** [comment]
Easy wins:
- Math.Max ➡️ max
- Math.Min ➡️ min
- Math.Round ➡️ round
- string.IndexOf ➡️ instr
- string.Replace ➡️ replace
- string.Substring ➡️ substr

I started doing this in [bricelam:sqlite](https://github.com/aspnet/EntityFramework/compare/dev...bricelam:sqlite), but probably won't have any time soon to finish it.

**Comment by smitpatel** [comment]
@bricelam - Want me to finish this?

**Comment by bricelam** [comment]
Yes please, if you have some spare time.

**Comment by fujiy** [comment]
Hi @smitpatel,

If you are not in a hurry, I plan to work on it. Just let me know so we don't do the same thing.

**Comment by smitpatel** [comment]
@fujiy - I am not in rush. Feel free to submit a PR for this.

**Comment by bricelam** [comment]
Here are some `DateTime` ones:

CLR | SQLite
--- | ------
DateTime.AddDays(X) | strftime('%Y-%m-%d %H:%M:%f', $original, 'X days')
DateTime.AddHours(X) | strftime('%Y-%m-%d %H:%M:%f', $original, 'X hours')
DateTime.AddMinutes(X) | strftime('%Y-%m-%d %H:%M:%f', $original, 'X minutes')
DateTime.AddMonths(X) | strftime('%Y-%m-%d %H:%M:%f', $original, 'X months')
DateTime.AddSeconds(X) | strftime('%Y-%m-%d %H:%M:%f', $original, 'X seconds')
DateTime.AddYears(X) | strftime('%Y-%m-%d %H:%M:%f', $original, 'X years')
DateTime.Date | strftime('%Y-%m-%d %H:%M:%f', $original, 'start of day')
DateTime.Day | strftime('%d', $original)
DateTime.DayOfWeek | strftime('%w', $original)
DateTime.DayofYear | strftime('%j', $original)
DateTime.Hour | strftime('%H', $original)
DateTime.Minute | strftime('%M', $original)
DateTime.Month | strftime('%m', $original)
DateTime.Now | strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime')
DateTime.Second | strftime('%S', $original)
DateTime.TimeOfDay | strftime('%H:%M:%f', $original)
DateTime.Today | strftime('%Y-%m-%d %H:%M:%f', 'now', 'localtime', 'start of day')
DateTime.UtcNow | strftime('%Y-%m-%d %H:%M:%f', 'now')
DateTime.Year | strftime('%Y', $original)

Note 1: `strftime` returns `TEXT` so some operations may need to `CAST` to `INTEGER` or `REAL`.
Note 2: `%f` only returns three decimal places so these results may be lossy.

**Comment by fujiy** [comment]
Hi @bricelam, I couldn't start working in this issue yet, if you want to assign it to somebody else

**Comment by bricelam** [comment]
Oh no, I'm just adding notes. 😄 Not working on it. Feel free to pick it up in your spare time. You can break it up into multiple PRs too--no need to add all of them at once.

**Comment by smitpatel** [comment]
Also discuss about `DateTimeOffset` functions.
According to @bricelam 
>See my notes on DateTime functions, but these won't work on DateTimeOffset without losing timezone information.

**Comment by bricelam** [comment]
Personally, I don't think we should translate any `DateTimeOffset` methods.
I'm also on the fence about whether we should translate `DateTime` methods that would be lossy.

**Comment by bricelam** [comment]
Some `TimeSpan` methods could be enabled in 2.1 by setting `parameter.SqliteType = SqliteType.Real`. See [the sample](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/17e4cd22d7c43c721eb51925ab0864187fa3ffd0/samples/DateAndTimeSample/Program.cs).

**Comment by smitpatel** [comment]
@bricelam - "%f" is causing an issue here. SQLite parameters don't append .000 if they are all 0s but %f does causing string mismatch.

**Comment by bricelam** [comment]
Ugg... we definitely ***don't*** want the `.000` since our goal was to stay compatible with `datetime()` when there are no fractional seconds. Can we conditionally generate `%f`? If not, we should discuss whether it's acceptable to lose sub-second precision.

**Comment by bricelam** [comment]
lol, we could: `rtrim(strftime(...), '.0')`

**Comment by smitpatel** [comment]
Ugly as hell but works
```
            AssertSql(
                @"@__myDatetime_0='1998-05-04T00:00:00' (DbType = String)

SELECT ""o"".""OrderID"", ""o"".""CustomerID"", ""o"".""EmployeeID"", ""o"".""OrderDate""
FROM ""Orders"" AS ""o""
WHERE rtrim(rtrim(strftime('%Y-%m-%d %H:%M:%f', ""o"".""OrderDate"", 'start of day'), '0'), '.') = @__myDatetime_0");
```

cc: @anpete

**Comment by smitpatel** [comment]
@bricelam - Since there is no native support for DateTime.Millisecond,
how about fractional and taking last 3 digits and convert to int?

**Comment by ralmsdeveloper** [comment]
%Y-%m-%d %H:%M:%f ?
Why not:
%Y-%m-%d %H:%M:%S

**Comment by bricelam** [comment]
`%Y-%m-%d %H:%M:%S` is the same as `datetime`. If we're ok loosing milliseconds, we should use `datetime`. The queries will be a lot prettier.

**Comment by bricelam** [comment]
Looks like SQL CE has "an accuracy of one three-hundredth second, or 3.33 milliseconds. Values are rounded to increments of .000, .003, or .007 milliseconds."

So rounding to full seconds might be relatively bad.

**Comment by ralmsdeveloper** [comment]
When I started to do, I thought about using SQLite date and datetime, but I was confused with %f (fraction), so I decided to use strftime.
As smitpatel, we also realize, we have a limitation with this, it is wiser to eliminate the possibility of milliseconds.

In any case we will not have the same results compared to the SQLITE server

**Comment by smitpatel** [comment]
#10528 Implements most of the DateTime members & DateDiff function implementation. I have filed separate issues to track rest of the functions mentioned here.

**Comment by bricelam** [comment]
Separate issues: #10522, #10525, #10526, #10527
