### ISSUE TITLE
[SqlServer] when generating table, we should generate PKs first and FKs last (just like in EF6) - at the moment it is all in alphabetical order

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#412]
I noticed that for models generated with EF7 the table view in SSMS is slightly different than it was in EF6. We used to create something like this:

Id (PK, int, not null)
Color (int, not null)
isLinked (bit, not null)
Item_Id (FK, int, not null)

with EF7 we generate:
Color (int, not null)
Id (PK, int, not null)
Item_Id (FK, int, not null)
isLinked (bit, not null)

We should consider following the old behaviour.

**Comment by jmalatia** [comment]
The rest of the columns should be created in the same order as written in the model... not alphabetical.... Just created a db with 7.0.0-beta7-15540 and it created the table columns in alphabetical order!  I would expect it to create the table in the same order as the model is written as in EF6.
