### ISSUE TITLE
Query: InvalidCastException when initializer inside Select has assignment with different types

### ISSUE THREAD

**Issue by cybermv** [aspnet/EntityFrameworkCore#4222]
I'm testing EF Core a bit and I encountered a bug when performing a selection over a DbSet. I've simplified the code down to this:

```
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.Data.Entity;

namespace TestProject
{
    public class TestModelContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(" ... ");
        }

        public DbSet<TestEntity> TestEntities { get; set; }
    }

    public class TestEntity
    {
        [Key]
        public int Id { get; set; }

        public string FirstText { get; set; }

        public string SecondText { get; set; }
    }

    public class TestEntityDto
    {
        public long Id { get; set; }

        public string Text { get; set; }
    }

    public static class Program
    {
        public static void Main(string[] args)
        {
            TestModelContext context = new TestModelContext();

            IQueryable<TestEntityDto> selection = context.TestEntities
                .Select(t => new TestEntityDto
                {
                    Id = t.Id,
                    Text = t.FirstText
                });

            List<TestEntityDto> list = selection.ToList();
        }
    }
}
```

An InvalidCastException occurs on the last line:
`List<TestEntityDto> list = selection.ToList();`

When running in .NET Framework the exception message is:
`Specified cast is not valid.`
and running in .NET Core the message is:
`Unable to cast object of type 'System.Int32' to type 'System.Int64'.`

The culprit is the `Id` property, which is of type `int` on the entity and `long` on the DTO. This used to work in EF6; I don't know if this is expected behavior or an actual bug.

**Comment by rowanmiller** [comment]
First up, thanks for the high quality bug report! Having a runnable example makes my job so much easier :+1:.

>  I don't know if this is expected behavior or an actual bug. 

We think we should make this work. It's lower priority than some other bugs we have, so putting it on the backlog to tackle post-7.0.0

**Comment by smitpatel** [comment]
Generated SQL in 3.0
```SQL
      SELECT CAST([t].[Id] AS bigint) AS [Id], [t].[FirstText] AS [Text]
      FROM [TestEntities] AS [t]
```
