### ISSUE TITLE
Cleanup SqlServerTestStore.CreateDatabase()

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#4553]
The `SqlServerTestStore.CreateDatabase()` method (and the async version) in our tests has [some funky code](https://github.com/aspnet/EntityFramework/blob/2a8fbe32e6948003ae2eea49cfa70a107d8aab7b/test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs#L126-L136) to probe for SQL files. After we've fully transitioned to the .NET Core CLI, someone should cleanup this logic.

**Comment by bricelam** [comment]
I believe @AndriySvyryd did this.

**Comment by AndriySvyryd** [comment]
@bricelam No
