### ISSUE TITLE
Query: Allow EF.Property to be used for navigations.

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFrameworkCore#4834]
E.g.

``` c#
var orders = context.Set<Customer>().Where(c => c.CustomerId == "ANATR")
                    .Select(c => EF.Property<ICollection<Order>>(c, "Orders")).First();
```

Useful for dynamic query scenarios.

**Comment by ajcvickers** [comment]
@maumar To check whether this now works for both reference and collection navigation properties, and if it is not working for collection navs, then either describe why it is failing or link to another issue if there is something already tracking the problem.

**Comment by maumar** [comment]
This works in current bits, both for reference and collection navs
