### ISSUE TITLE
Hanging tests on single threaded Ubuntu environment

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/EntityFrameworkCore#5308]
It seems like some tests in EF are hanging consistently on agent projectk-tc-ag6, see http://aspnetci/viewLog.html?buildId=90832&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR&tab=buildLog#_focus=115519. I took a brief look at the test set up in https://github.com/aspnet/EntityFramework/blob/f732e3c7c1a680a944b9aafaf34bef88ed8a19c4/test/Microsoft.EntityFrameworkCore.FunctionalTests/DatabaseErrorLogStateTest.cs and it seems very similar to the problem I ran into in https://github.com/aspnet/Hosting/pull/523. Probably needs some investigation.

**Comment by divega** [comment]
One of the tests that is failing is  [`DatabaseErrorLogStateTest.Query_logs_DatabaseErrorLogState_during_LINQ_enumeration_async`](https://github.com/aspnet/EntityFramework/blob/dev/test/Microsoft.EntityFrameworkCore.FunctionalTests/DatabaseErrorLogStateTest.cs#L87) which is a sync test that is testing an async query method with a Wait() at the end (so it is not very surprising that it hangs when running single threaded). 

There are many more tests in the same class that use the same pattern. I am not sure there is a reason we haven't made the tests async. @anpete?

**Comment by anpete** [comment]
cc @rowanmiller who wrote this originally.

**Comment by anpete** [comment]
@divega I think the reason here is to DRY-up the result verification. Suggest we split async into different tests like we do usually. NB. I have seen this pattern in some of our other tests, too.

**Comment by divega** [comment]
Talked to @smitpatel trying to figure out what the resolution was for this issue. We actually haven't changed these sync tests that invoke async APIs with `.Wait()` to be async, but these particular tests haven't hanged or deadlocked recently, hence "no repro". cc @anpete, @ajcvickers

**Comment by ajcvickers** [comment]
@divega I would actually like to open this for backlog/cleanup. It's easy to write tests that can be run twice, once sync, once not, without using Wait. It would be good to cleanup all our tests to do that (where we need to test both sync/async). Let's discuss if you feel strongly it should remain closed.

**Comment by divega** [comment]
@ajcvickers sounds great.

**Comment by divega** [comment]
@smitpatel do you think we should do this clean up task now?

**Comment by smitpatel** [comment]
Yes we should. It would be easy. And I suspect some day xUnit will start acting up seeing `Wait()`

**Comment by smitpatel** [comment]
Note for implementer: Look at `SqlServerDatabaseCreatorExistsTest` which utilizes common method for sync/async both testing without using `Wait()`

**Comment by AndriySvyryd** [comment]
Sync helpers in `QueryTestBase.cs` should still return `Task` to be awaited upon

**Comment by ajcvickers** [comment]
See also #9959
