### ISSUE TITLE
Query: 'as' operator is evaluated on client causing exception

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#5783]
```
//Model
public class MyContext : DbContext
{
    public DbSet<Inventory> Inventory { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

    }
}

public class Purchase
{
    public Purchase()
    {
        Inventory = new List<Inventory>();
    }

    public int Id { get; set; }
    public int Count { get; set; }
    public IList<Inventory> Inventory { get; }
}

public class Inventory
{
    public int Id { get; set; }
    public int PurchaseId { get; set; }
    public int? SaledCount { get; set; }
    public Purchase Purchase { get; set; }
}
```

Repro code (causes one query for each `Purchase`)

```
using (var ctx = new MyContext())
{
    var query = from p in ctx.Set<Purchase>().Include(p => p.Inventory)
                where p.Count > (p.Inventory.Select(i => (i.SaledCount as int?)).Sum() ?? 0)
                select p;
    query.ToList();
}
```

Work-around

```
using (var ctx = new MyContext())
{
    var query = from p in ctx.Set<Purchase>().Include(p => p.Inventory)
                where p.Count > (p.Inventory.Select(i => (int?)(i.SaledCount)).Sum() ?? 0)
                select p;
    query.ToList();
}
```

**Comment by rowanmiller** [comment]
@smitpatel workaround looks the same as repro code? Is there a reason you needed the `as`, `SaledCount` seems to be an `int?` already?

**Comment by smitpatel** [comment]
@rowanmiller - updated work-around. copy paste error.
My thought was also same on casting, but without it, it throws exception. (saw a few different). I haven't been able to make a self-containing repro of it.

**Comment by diegoalejandrogomez** [comment]
It can be reproduced using the following test:


ComplexNavigationsQueryTestBase.cs


        [ConditionalFact]
        public virtual void Select_with_type_casting_using_as()
        {
            List<Level1> expected;
            using (var context = CreateContext())
            {
                var queryExpected = context.LevelOne.Include(l1 => l1.OneToMany_Optional)
                                    .Where(l1 => l1.Id > l1.OneToMany_Optional.Select(i => (int?)i.Id).Sum());
                expected = queryExpected.ToList();
            }

            ClearLog();

            using (var context = CreateContext())
            {
                var query = context.LevelOne.Include(l1 => l1.OneToMany_Optional)
                            .Where(l1 => l1.Id > l1.OneToMany_Optional.Select(i => i.Id as int?).Sum());
                var result = query.ToList();

                Assert.Equal(expected.Count, result.Count);
                for (var i = 0; i < result.Count; i++)
                {
                    Assert.True(expected.Contains(result[i]));
                }
            }
        }

**Comment by smitpatel** [comment]
Error in 3.1
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'EmptyProjectionMember' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.GetMappedProjection(ProjectionMember projectionMember)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSum(ShapedQueryExpression source, LambdaExpression selector, Type resultType)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
```

**Comment by svengeance** [comment]
@smitpatel Desired behavior here is that type casting via `x.Bar as Foo` or `(Foo) x.Bar` is equivalent, correct?

**Comment by smitpatel** [comment]
@svengeance - That is true.
