### ISSUE TITLE
Reverse Engineer: Table/Schema Exclusion

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFrameworkCore#6182]
Have the ability to specify tables/schemas to be excluded, useful for excluding AapNet\* tables etc.

**Comment by lajones** [comment]
See also this comment from issue #5126: https://github.com/aspnet/EntityFramework/issues/5126#issuecomment-213009189

**Comment by Starkie** [comment]
Are there any news on the implementation of this functionality?

I think it would be useful, for example, when a table causes an error in the generation of the scaffold. I had this happen in #13528. As a workaround, all tables had to be referenced manually using the `--table` flag, excluding the two that caused the exception.

**Comment by ErikEJ** [comment]
Maybe EF Core Power Tools can help you? (Persists the table selection)

**Comment by ajcvickers** [comment]
While there is some value in doing this at the command line (i.e for cross-plat), that value is diminished by the Power Tools, which seem to be the preferred choice of most people doing reverse engineering. This combined with table/schema selection being possible anyway means that we've decided not to implement this.

However, we would not be against a well-written and robust community contribution to implement this.

**Comment by Starkie** [comment]
After looking up the code, I think that with a bit of guidance, this could be an easy implementation. I'll give it a shot over the weekend.

**Comment by Starkie** [comment]
I have been working on it over the weekend, with the idea of adding a parameter `--exclude-tables`.  This parameter "flows" alongside the values of `--tables`. 

To propagate these values to the database providers, the `IDatabaseModelFactory` interface must be modified: the `excludeTables ` parameter must be added to the `Create` methods. This will be a breaking change for every provider, and I'm a bit worried about that.

https://github.com/aspnet/EntityFrameworkCore/blob/45cbc40aee746e27d69d391dc6457ecfc008a1b4/src/EFCore.Relational/Scaffolding/IDatabaseModelFactory.cs#L37

Could it be implemented as an optional parameter, to avoid the breaking change? Or is it prefered to update the providers to support this feature? 

If needed, a PR could be created to better review the change.

**Comment by ajcvickers** [comment]
@bricelam @smitpatel Is breaking `IDatabaseModelFactory` the way to go here?

**Comment by ErikEJ** [comment]
Being able to get the table list would be great, in Power Tools I currently have to use a custom way per ADO.NET provider to get the table list.

**Comment by Starkie** [comment]
Could a `list` subcommand be added to the `database` command, that returns the list of tables (and/or schemas)? It could also have an option to return unformatted output, so it might be used as an API by the PowerTools.

The command woud be invoked internally before a scaffolding operation if the `--exclude-tables` or `--exclude-schemas` parameters were used.

**Comment by ajcvickers** [comment]
@Starkie We discussed this in triage and it seems like a reasonable idea. The only caveat is if it is too slow, but if the command specifically gets just table/schema name, and not everything else associated with the table, then it's probably okay.

Also, see #14602 which is about allowing new command functionality without always breaking the interface.

**Comment by ErikEJ** [comment]
@ajcvickers Is this still open for a reason? (closed-wont-fix) ?
Is this about adding a feature to get a list of all tables/schemas ?

**Comment by ajcvickers** [comment]
@ErikEJ I believe it is about getting a list, yes. This could potentially be used by tooling to automate more things. I think somebody said that your tooling already does this, but maybe it makes sense to move the code you have into EF?
/cc @bricelam

**Comment by bricelam** [comment]
We should probably file a new issue for adding a command (and API) to get a list of tables...

**Comment by ErikEJ** [comment]
@bricelam I would like to have a look at this, but before I begin it raises a number of design questions.

**Comment by bricelam** [comment]
If you draft a proposal, I can present it to the team in a design meeting.

**Comment by ErikEJ** [comment]
The purpose of this feature is to provide a list of available tables and views in the specified database. This list can be used by tools to help the user pick what tables/views to scaffold.

    Powershell: 

     Get-Database "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer

   dotnet ef:

     dotnet ef database list "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer

The list can be provided in two ways (one must be chosen for implementation)

1: The command calls the current Create() method on the relevant IDatabaseModelFactory implementation, and gets the DatabaseModel back, and can produce the list from it.

2: A new, more lightweight method is added to the IDatabaseModelFactory, and must be implemented by each provider. This lightweight method returns 
A: either a "light" DatabaseModel with just the needed information,
B: a new structcture just for this purpose
C: a modified version of DatabaseModel with a new HasPrimaryKey bool property on each Table object.

(I vote for 1, despite some performance concerns)

The result should be a list of: schemaName, tableName, hasPrimaryKey (bool)

**Comment by ErikEJ** [comment]
@bricelam Any news?

**Comment by bricelam** [comment]
Still on my TODO list. Been busy locking down 3.0

**Comment by loganmarshall1** [comment]
Can I also suggest, in addition to exclude schema, tables that we add columns ?

For Us, We add prefix to columns/tables 'zz' for ones we're eventually deprecating but we still want to keep the data in the db.  Would be nice to not pull these into our vs projects to force devs to use new columns.  I think the old Reverse Poco tt generator for .NET 4.7 had regex include/exclude.

Is it easier & more robust to users to add --excludeTableRegex foo --excludeSchemaRegex foo2 --excludeColumnRegex foo3 ?

**Comment by bricelam** [comment]
@ErikEJ I discussed this with the team, and we like the idea of re-using the existing DatabaseModel and IDatabaseModelFactory. We should also add something to DatabaseModelFactoryOptions to let providers know we only need the schemas and names of objects so they can optimize for perf if they need to.

**Comment by ikuntalb** [comment]
Hi 
Any update ?are you add a option for exclude table?the option If we can write like bellow format its better ,
--<option> table1,table2,table3....etc

Thankx

**Comment by ajcvickers** [comment]
@ikuntalb This issue is in the Backlog milestone. This means that it is not going currently scheduled for the next release. We have not finished planning for 5.0, so this may change. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by robinNode** [comment]
Hi,
How do I ignore views when i run scaffold?
In EF core 3 migration, it will generate table for view.  thanks

**Comment by ErikEJ** [comment]
@robinNode you can specify -table options to include only the tables you want. You can also use EF Core Power Tools, gives you a GUI to select tables/views, and persists your selection.

**Comment by florinciubotariu** [comment]
Hi.
Unfortunately I couldn't use EF Core Power Tools so I've decided to go on another route. I'll post here my solution, maybe it will help others with the same problem.

 Since I'm using SQL Server, I've decorated `SqlServerDatabaseModelFactory` using Scrutor. Extend the functionality as you like:

 ```
public class CustomSqlServerDatabaseModelFactory : IDatabaseModelFactory
  {
    private IDatabaseModelFactory databaseModelFactory;

    private static readonly List<string> ExcludedTables = new List<string>
    {
      "__MigrationHistory",
      "Exceptions"
    };

    public CustomSqlServerDatabaseModelFactory(IDatabaseModelFactory databaseModelFactory)
    {
      this.databaseModelFactory = databaseModelFactory;
    }

    public DatabaseModel Create(string connectionString, DatabaseModelFactoryOptions options)
    {
      var databaseModel = databaseModelFactory.Create(connectionString, options);

      RemoveTables(databaseModel);

      return databaseModel;
    }

    public DatabaseModel Create(DbConnection connection, DatabaseModelFactoryOptions options)
    {
      var databaseModel = databaseModelFactory.Create(connection, options);

      RemoveTables(databaseModel);

      return databaseModel;
    }

    private static void RemoveTables(DatabaseModel databaseModel)
    {
      var tablesToBeRemoved = databaseModel.Tables.Where(x => ExcludedTables.Contains(x.Name)).ToList();

      foreach (var tableToRemove in tablesToBeRemoved)
      {
        databaseModel.Tables.Remove(tableToRemove);
      }
    }
  }
```

And the implementation of `IDesignTimeServices`:

```
public class CustomEFDesignTimeServices : IDesignTimeServices
{
    public void ConfigureDesignTimeServices(IServiceCollection serviceCollection)
    {
      serviceCollection.Decorate<IDatabaseModelFactory, CustomSqlServerDatabaseModelFactory>();
    }
}
```

I've also created a blog post with more details which can be read [here](https://www.florinciubotariu.com/exclude-tables-when-using-entity-framework-core-reverse-engineering/).

**Comment by ErikEJ** [comment]
@florinciubotariu why were you unable to use EF Core Power Tools?

**Comment by florinciubotariu** [comment]
I had to implement a custom pluralizer (to be as similar as possible to EF 6) and I saw the EF Core Power Tools didn't pick up my implementation of `IDesignTimeServices`. If I recall correctly, I had problems with tables ending in `Data` and `Media`, even though I was using the EF 6 Pluralizer. Is this a limitation of your extension?

**Comment by ErikEJ** [comment]
@florinciubotariu You can opt in to use the Legacy pluralizer, should be 100% EF6 compatible.

**Comment by ErikEJ** [comment]
@florinciubotariu If it is not compatible with the EF6 pluralizer, let me know (via a repro) and I will get it fixed

**Comment by florinciubotariu** [comment]
@ErikEJ 

EF Core 5 preview - checked
Use tables and column names directly from the database - checked
EF 6 Pluralizer - checked 


EF 6:
```
    public virtual DbSet<XItemMedia> XItemMedias { get; set; }
    public virtual DbSet<XTestDrive> XTestDrives { get; set; }
    public virtual DbSet<XCSS> XCSSes { get; set; }
```

EF Core Power Tools:
```
    public virtual DbSet<XItemMedium> XItemMedia { get; set; }
    public virtual DbSet<XTestDrife> XTestDrives { get; set; }
    public virtual DbSet<XCSS> XCSSes { get; set; }
```

last one is ok but when using:

EF Core 5 preview - checked
Pluralize and singularize generated object names - checked
EF 6 Pluralizer - checked 

I get:

EF 6:
```
    public virtual DbSet<XCSS> XCSSes { get; set; }
    public virtual DbSet<XBundlePurchas> XBundlePurchases { get; set; }
```
EF Core Power Tools
```
     public virtual DbSet<XCss> XCsses { get; set; }
     public virtual DbSet<XBundlePurcha> XBundlePurchas { get; set; }
```

I hope that next week I will come with a repro on EF Core Power Tools repository.

**Comment by ErikEJ** [comment]
In the latest daily, you can combine UseDatabaseNames and Pluralization with EF Core 5. Looking forward to your repro in the EF Power Tools repository

**Comment by jcummings2** [comment]
> Hi Any update ?are you add a option for exclude table?the option If we can write like bellow format its better , -- [option] table1,table2,table3....etc
> 
> Thankx

Good question and after reading through all the comments I am still a bit confused on what this issue is trying to do. The title still indicates an exclude option but some of the discussion seems to go in different directions. [Based](https://github.com/dotnet/EntityFramework.Docs/issues/3862) on [numerous](https://github.com/dotnet/efcore/issues/6148) other [issues](https://github.com/dotnet/efcore/issues/10149) that [have](https://github.com/dotnet/efcore/issues/26277) been [closed](https://github.com/dotnet/efcore/issues/17184) as [duplicates](https://github.com/dotnet/efcore/issues/19183), I gather the point may still be adding an exclude option. In any case, I sure hope the exclude option is still the point.

**Comment by MikeMcWilliams** [comment]
Is this feature ready?  I need to exclude a table.

**Comment by ErikEJ** [comment]
It is in EF Core Power Tools CLI, yes. But not in the standard CLI tooling @MikeMcWilliams

**Comment by MikeMcWilliams** [comment]
> It is in EF Core Power Tools CLI, yes. But not in the standard CLI tooling @MikeMcWilliams

Thanks @ErikEJ.  That unfortunately is not an option for me, I am using `Microsoft.AspNetCore.DataProtection.EntityFrameworkCore` in my partial because scaffolding does not include `using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore;` in its dbcontext output.  

I am only looking to skip the `DataProtectionKeys` table; but I wouldn't need it if the scaffolding detected the `DataProtectionKeys` table and then added the supporting `using` statement.


![image](https://github.com/dotnet/efcore/assets/90723734/fd5158d7-0152-4078-90ab-1d04aae502c4)


See, I have a partial dbcontext that inherits from `IDataProtectionKeyContext` which resides in the 'Microsoft.AspNetCore.DataProtection.EntityFrameworkCore' namespace.  Since the scaffolding does not seem to support this natively, the `DataProtectionKeys` table is scaffolded; so I am trying to tell scaffolding to skip `DataProtectionKeys`

**Comment by ErikEJ** [comment]
@MikeMcWilliams How would the naive tooling support help here???

**Comment by MaherJendoubi** [comment]
Is there any update for this feature?

**Comment by ajcvickers** [comment]
This issue is in the Backlog milestone. This means that it is not planned for the next release (EF Core 8.0). We will [re-assess the backlog](https://docs.microsoft.com/ef/core/what-is-new/release-planning) following the this release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources. Make sure to vote (👍) for this issue if it is important to you.

**Comment by orchidoris** [comment]
This can be achieved with PowerShell script:
- pick tables to scaffold with SQL query, add necessary filters
- run query with `Invoke-Sqlcmd`
- build ```dotnet ef dbcontext scaffold ...``` command with extracted table names

A **tested** example of `scaffold.ps1` file you would put into a project folder and execute to run scaffolding from now on:

```ps1
Set-Location -Path $PSScriptRoot

$server = "(localdb)\MSSQLLocalDB"
$database = "YourApplicationDB"

# Leverage flexibility of SQL to pick tables you wanna include in scaffolding
$scaffoldingTablesQuery = @"
DECLARE @Tables VARCHAR(8000) 
SELECT @Tables = COALESCE(@Tables + ' ', '') + '-t [' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']' 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE='BASE TABLE'
    AND TABLE_SCHEMA <> 'identity'
    AND TABLE_NAME <> '__EFMigrationsHistory';

SELECT @Tables AS Tables;
"@

$scaffoldingTablesQueryResult = Invoke-Sqlcmd -ServerInstance $server -Database $database -Query $scaffoldingTablesQuery
$scaffoldingTables = $($scaffoldingTablesQueryResult.Tables)

$scaffoldCommand= "dotnet ef dbcontext scaffold ""Data Source=$server;Initial Catalog=$database"" Microsoft.EntityFrameworkCore.SqlServer " `
    + "--force --no-onconfiguring " `
    + "--output-dir Scaffolded " `
    + $scaffoldingTables

Write-Host ""
Write-Host "Running scaffolding with the following command:"
$scaffoldCommand
Write-Host ""

Invoke-Expression $scaffoldCommand
```

You're welcome!

**Comment by orchidoris** [comment]
This can be achieved with a PowerShell script:
- pick tables to scaffold with SQL query, add necessary filters
- run query with `Invoke-Sqlcmd`
- build ```dotnet ef dbcontext scaffold ...``` command with extracted table names

A **tested** example of `scaffold.ps1` file you would put into a project folder and execute to run scaffolding from now on:

```ps1
Set-Location -Path $PSScriptRoot

$server = "(localdb)\MSSQLLocalDB"
$database = "YourApplicationDB"

# Leverage flexibility of SQL to pick tables you wanna include in scaffolding
$scaffoldingTablesQuery = @"
DECLARE @Tables VARCHAR(8000) 
SELECT @Tables = COALESCE(@Tables + ' ', '') + '-t [' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']' 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE='BASE TABLE'
    AND TABLE_SCHEMA <> 'identity'
    AND TABLE_NAME <> '__EFMigrationsHistory';

SELECT @Tables AS Tables;
"@

$scaffoldingTablesQueryResult = Invoke-Sqlcmd -ServerInstance $server -Database $database -Query $scaffoldingTablesQuery
$scaffoldingTables = $($scaffoldingTablesQueryResult.Tables)

$scaffoldCommand= "dotnet ef dbcontext scaffold" ` 
    + """Data Source=$server;Initial Catalog=$database"" Microsoft.EntityFrameworkCore.SqlServer " `
    + "--force --no-onconfiguring " `
    + "--output-dir Scaffolded " `
    + $scaffoldingTables

Write-Host ""
Write-Host "Running scaffolding with the following command:"
$scaffoldCommand
Write-Host ""

Invoke-Expression $scaffoldCommand
```

You're welcome!

**Comment by orchidoris** [comment]
This can be achieved with a PowerShell script:
- pick tables to scaffold with SQL query
- *exclude unwanted tables using WHERE filter in the query*
- run query with `Invoke-Sqlcmd`
- build ```dotnet ef dbcontext scaffold ...``` command with extracted table names

A **tested** example of `scaffold.ps1` file you would put into a project folder and execute to run scaffolding from now on:

```ps1
Set-Location -Path $PSScriptRoot

$server = "(localdb)\MSSQLLocalDB"
$database = "YourApplicationDB"

# Leverage flexibility of SQL to pick tables you wanna include in scaffolding
$scaffoldingTablesQuery = @"
DECLARE @Tables VARCHAR(8000) 
SELECT @Tables = COALESCE(@Tables + ' ', '') + '-t [' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']' 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE='BASE TABLE'
    AND TABLE_SCHEMA <> 'identity'
    AND TABLE_NAME <> '__EFMigrationsHistory';

SELECT @Tables AS Tables;
"@

$scaffoldingTablesQueryResult = Invoke-Sqlcmd -ServerInstance $server -Database $database -Query $scaffoldingTablesQuery
$scaffoldingTables = $($scaffoldingTablesQueryResult.Tables)

$scaffoldCommand= "dotnet ef dbcontext scaffold" ` 
    + """Data Source=$server;Initial Catalog=$database"" Microsoft.EntityFrameworkCore.SqlServer " `
    + "--force --no-onconfiguring " `
    + "--output-dir Scaffolded " `
    + $scaffoldingTables

Write-Host ""
Write-Host "Running scaffolding with the following command:"
$scaffoldCommand
Write-Host ""

Invoke-Expression $scaffoldCommand
```

You're welcome!

**Comment by mateli** [comment]
@orchidoris That's right. While this specific solution only works on windows it's easy to implement in something else than PowerShell. I don't know why I haven't thought scripting this before as I do write a lot of scripts and tooling but I can only slap myself on the forehead and move on.
