### ISSUE TITLE
Query: When doing optional nav expansion, we can sometimes avoid nullability safeguards, if the user has performed them already

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#6203]
In query like this:

``` cs
_db.EntityA.Where(c => c.EntityC != null && c.EntityC.IsActive);
```

we apply nullability safeguards on IsActive column because EntityC is optional navigation, like so:

``` cs
_db.EntityA.Where(c => c.EntityC != null && (bool)(c.EntityC != null ? (bool?)c.EntityC.IsActive : null ));
```

We don't need them in this case, because query already constrained the results rows where EntityC is not null. We could detect this pattern and avoid some unnecessary complications. It doesn't matter much for relational, since the safeguards are optimized out anyway, but this could be of some value for InMemory store.

See #6195 for the full repro of the scenario

**Comment by smitpatel** [comment]
Similar #4267

**Comment by smitpatel** [comment]
Generated SQL
```SQL
      SELECT [b].[Id]
      FROM [Blogs] AS [b]
      LEFT JOIN [Address] AS [a] ON [b].[Id] = [a].[BlogId]
      WHERE [a].[Id] IS NOT NULL AND ([a].[IsActive] = CAST(1 AS bit))
```
