### ISSUE TITLE
EF.Property<T>() should work for navigation properties, also in Include()/ThenInclude()

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#6412]
This is an addition to https://github.com/aspnet/EntityFramework/issues/3921 which will allow paths of navigation properties to be passed as a string to `Include()` to work but without strong typing.

This would make the API work uniformly for more query scenarios and also enable specifying the name of a property to traverse more dynamically but without losing strong typing. 

Potentially we can make this pattern work for "shadow" navigation properties.

**Comment by ajcvickers** [comment]
This is now fixed navigation properties in Include/ThenInclude. We will revisit this if other important cases come up in the future.
