### ISSUE TITLE
Allow changing the connection string for a DbContext instance

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#6525]
Add methods to `IRelationalConnection` to set a new connection string or `DbConnection` when the current connection state is closed.

This would allow to fallback to a different server without losing the state in the context

**Comment by rowanmiller** [comment]
Putting in 1.1 on the basis that this is needed for connection resiliency.

**Comment by AndriySvyryd** [comment]
It's not required, but will add more functionality.

**Comment by ajcvickers** [comment]
Consider also #9244 when working on this.

**Comment by ismcagdas** [comment]
Hi,

Are you planning to work on this issue in the near future ?

**Comment by ajcvickers** [comment]
@ismcagdas This issue is in the Backlog milestone. This means that it is not going to happen for the 3.0 release. We will re-assess the backlog following the 3.0 release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by prashantchoudhary** [comment]
I am using a Per Company Database for one of Desktop Application and Based on User Login the Company Database would change. As login needs the app to be running, My ServiceLocator would already be built and ready by then. And Pointing to CompanyDatabase then needs changing the ConnectionString. This feature will be a great relief for this app.

**Comment by RubberChickenParadise** [comment]
> I am using a Per Company Database for one of Desktop Application and Based on User Login the Company Database would change. As login needs the app to be running, My ServiceLocator would already be built and ready by then. And Pointing to CompanyDatabase then needs changing the ConnectionString. This feature will be a great relief for this app.

I solved this by having two different service providers (service locators).  the first was built for the main database which holds the user login information and available databases (application shards).  Once the user has logged in and selected a database I build a service provider specifically for that DB connection string.  Lets me do exactly what you are trying to do.

**Comment by prashantchoudhary** [comment]
Yes, that is the alternative I have been thinking of using.
