### ISSUE TITLE
Query: Funcletize accessing an array element

### ISSUE THREAD

**Issue by marcioqmaciel** [aspnet/EntityFrameworkCore#6859]
### Steps to reproduce

In SSMS:
Select \* From Person Where Name = 'marcio'
return Márcio, its ok!

In EF7
string name = "marcio";
Person person = context.Persons.FirstOrDefault(p => p.Name == name);
if(person == null)    <<< yep, person is null.... 

What I'm doing wrong?

Windows 10 Pro Insider Preview build 14951
SQL Server 2016 Latin1_General_CI_AI
WPF .Net 4.6.1
VS 2015
EF Core 1.0.1
EF SQLServer 1.0.1

**Comment by maumar** [comment]
Most likely it's because special character in the name (in the database) that is not there in the 'name' string you used in your Linq query

**Comment by benaadams** [comment]
Should be dealt with by the collation? `Latin1_General_CI_AI` Case insensitive, accent insensitive?

**Comment by midnait** [comment]
Oh, I got it, ARRAY! oO   Its not a problem with database collation.

Warning as error exception for warning 'RelationalEventId.QueryClientEvaluationWarning': The LINQ expression '([a].Name == __8__locals1_names_0[__i_1])' could not be translated and will be evaluated locally.

My original code:

string[] names = ......;
for(int i = 1; i < names.Count(); i+)
  Person person = context.Persons.FirstOrDefault(p => p.Name == name[i]);  << Throw

My workaround:

string[] names = ......;
for(int i = 1; i < names.Count(); i+)
  string actualName = names[i];
  Person person = context.Persons.FirstOrDefault(p => p.Name == actualName);

Or name[i].ToString();

Working now, selecting in database and with CI_AI.

**Comment by benaadams** [comment]
👍

**Comment by divega** [comment]
Reopening. We should consider making this workaround unnecessary, i.e. we can parametrize a reference to an array element.

**Comment by smitpatel** [comment]
We should evaluate impact here. If it is just not funcletizing (but returning correct result) then it should be up-for-grabs or closed.

**Comment by smitpatel** [comment]
This causes client evaluation. We should fix it,
