### ISSUE TITLE
Query: extensive client evaluation for queries with navigations defined as interfaces

### ISSUE THREAD

**Issue by mdavisJr** [aspnet/EntityFrameworkCore#7123]
### Models:

public interface IBlog
{
&nbsp;&nbsp;&nbsp;&nbsp;int Id { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;string Url { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;List&lt;IPost&gt; Posts { get; set; }
}
public class Blog : IBlog
{
&nbsp;&nbsp;&nbsp;&nbsp;public int Id { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;public string Url { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;public List&lt;IPost&gt; Posts { get; set; }
}

public interface IPost
{
&nbsp;&nbsp;&nbsp;&nbsp;int Id { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;string Title { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;string Content { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;int BlogId { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;IBlog Blog { get; set; }
}
public class Post : IPost
{
&nbsp;&nbsp;&nbsp;&nbsp;public int Id { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;public string Title { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;public string Content { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;public int BlogId { get; set; }
&nbsp;&nbsp;&nbsp;&nbsp;public IBlog Blog { get; set; }
}

### Mapping:

modelBuilder.Entity&lt;Blog&gt;().HasMany(typeof(Post), "Posts").WithOne("Blog").HasForeignKey("BlogId");

### Code:

var posts = await db.Posts.Include(x =&gt; x.Blog).ToListAsync();  **Works**

var posts = await db.Posts.Where(x =&gt; x.Blog.Title == "Hi").ToListAsync();  **Works**

var blogs = await db.Blogs.Include(x =&gt; x.Posts).ToListAsync();  **Works**

var blogs = await db.Blogs.Where(x =&gt; x.Posts.Any(y =&gt; y.Title == "Hi")).ToListAsync(); **Throws error below**

If I change "List&lt;**IPost**&gt; Posts" to "List&lt;**Post**&gt; Posts" in Blog and IBlog, I don't get the error below.

### Error:

An unhandled exception occurred while processing the request.

**ArgumentException: must be reducible node
System.Linq.Expressions.Expression.ReduceAndCheck()**

Stack Query Cookies Headers
ArgumentException: must be reducible node
System.Linq.Expressions.Expression.ReduceAndCheck()
System.Linq.Expressions.Expression.ReduceExtensions()
System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.Add(Expression node)
System.Linq.Expressions.Compiler.StackSpiller.RewriteBinaryExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.Rewrite&lt;T&gt;(Expression&lt;T&gt; lambda)
System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.Add(Expression node)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.AddArguments(IArgumentProvider expressions)
System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.Add(Expression node)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.AddArguments(IArgumentProvider expressions)
System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.Add(Expression node)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.AddArguments(IArgumentProvider expressions)
System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.Add(Expression node)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.AddArguments(IArgumentProvider expressions)
System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.Add(Expression node)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.AddArguments(IArgumentProvider expressions)
System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.Rewrite&lt;T&gt;(Expression&lt;T&gt; lambda)
System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.Add(Expression node)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.AddArguments(IArgumentProvider expressions)
System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.Add(Expression node)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.AddArguments(IArgumentProvider expressions)
System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.Add(Expression node)
System.Linq.Expressions.Compiler.StackSpiller+ChildRewriter.AddArguments(IArgumentProvider expressions)
System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
System.Linq.Expressions.Compiler.StackSpiller.Rewrite&lt;T&gt;(Expression&lt;T&gt; lambda)
System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
System.Linq.Expressions.Expression.Compile(bool preferInterpretation)
Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda&lt;TResults&gt;()
Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor&lt;TResult&gt;(QueryModel queryModel)
Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore&lt;TFunc&gt;(object cacheKey, Func&lt;Func&lt;QueryContext, TFunc&gt;&gt; compiler)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync&lt;TResult&gt;(Expression query)
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable.System.Collections.Generic.IAsyncEnumerable&lt;TResult&gt;.GetEnumerator()
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions+&lt;ToListAsync&gt;d__129.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()...

**Comment by maumar** [comment]
This works in current bits, however the query is executed mostly on the client (due to interfaces and subsequent Cast operators that are being introduced by relinq)

**Comment by maumar** [comment]
initiali query:

```cs
ctx.Blogs.Where(x => x.Posts.Any(y => y.Title == "Hi"))
```

initial query model
```
from Blog x in DbSet<Blog>
where 
    (from IPost y in [x].Posts
    where [y].Title == "Hi"
    select [y]).Any()
select [x]
```

after nav rewrite:
```
from Blog x in DbSet<Blog>
where 
    (from IPost y in DbSet<Post>
    where [y].Title == "Hi"
    where Property([x], "Id") == Property([y], "BlogId")
    select [y]).Any()
select [x]
```

query plan:
```
(QueryContext queryContext) => IEnumerable<Blog> _InterceptExceptions(
    source: IEnumerable<Blog> _TrackEntities(
        results: IEnumerable<Blog> _Where(
            source: IEnumerable<Blog> _ShapedQuery(
                queryContext: queryContext, 
                shaperCommandContext: SelectExpression: 
                    SELECT [x].[Id], [x].[Url]
                    FROM [Blogs] AS [x], 
                shaper: BufferedEntityShaper<Blog>), 
            predicate: (Blog x) => bool Any(IEnumerable<Post> _Where(
                    source: IEnumerable<Post> _InjectParameters(
                        queryContext: queryContext, 
                        source: IEnumerable<Post> _Where(
                            source: IEnumerable<Post> _ShapedQuery(
                                queryContext: queryContext, 
                                shaperCommandContext: SelectExpression: 
                                    SELECT [y].[Id], [y].[BlogId], [y].[Content], [y].[Title]
                                    FROM [Posts] AS [y], 
                                shaper: BufferedEntityShaper<Post>), 
                            predicate: (Post y) => y.Title == "Hi"), 
                        parameterNames: new string[]{ "_outer_Id" }, 
                        parameterValues: new object[]{ (object) Nullable<int> GetValueFromEntity(
                                clrPropertyGetter: ClrPropertyGetter<Blog, int>, 
                                entity: x) }), 
                    predicate: (Post y) => int GetValueFromEntity(
                        clrPropertyGetter: ClrPropertyGetter<Blog, int>, 
                        entity: x) == int GetValueFromEntity(
                        clrPropertyGetter: ClrPropertyGetter<Post, int>, 
                        entity: y)))), 
        queryContext: queryContext, 
        entityTrackingInfos: { itemType: Blog }, 
        entityAccessors: List<Func<Blog, object>> 
        { 
            Func<Blog, Blog>, 
        }
    ), 
    contextType: Repro7123.MyContext, 
    logger: InterceptingLogger<Query>, 
    queryContext: queryContext)
```

**Comment by mdavisJr** [comment]
###This Might Be Fixed Now

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace EF2Test
{
    class Program
    {
        static void Main(string[] args)
        {
            //All the below queries work now.
            using (var db = new TestContext())
            {
                var posts = db.Posts.Include(x => x.Blog).ToListAsync().Result;
            }
            using (var db = new TestContext())
            {
                var posts = db.Posts.Where(x => x.Blog.Title == "Title1").ToListAsync().Result;
            }
            using (var db = new TestContext())
            {
                var posts = db.Posts.Where(x => x.Blog.Title == "Title1").Include(x => x.Blog).ToListAsync().Result;
            }
            using (var db = new TestContext())
            {
                var blogs = db.Blogs.Include(x => x.Posts).ToListAsync().Result;
            }
            using (var db = new TestContext())
            {
                var blogs = db.Blogs.Where(x => x.Posts.Any(y => y.Title == "Hi2")).ToListAsync().Result;
            }
        }
    }

    public class TestContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\MyInstance;Database=EFCore2Test;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>().ToTable("Blog");
            modelBuilder.Entity<Post>().ToTable("Post");
            modelBuilder.Entity<Blog>().HasMany(typeof(Post), "Posts").WithOne("Blog").HasForeignKey("BlogId");
        }
    }

    public interface IBlog
    {
        int Id { get; set; }
        string Url { get; set; }
        string Title { get; set; }
        IList<IPost> Posts { get; set; }
    }
    public class Blog : IBlog
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public IList<IPost> Posts { get; set; }
    }

    public interface IPost
    {
        int Id { get; set; }
        string Title { get; set; }
        string Content { get; set; }
        int BlogId { get; set; }
        IBlog Blog { get; set; }
    }
    public class Post : IPost
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int BlogId { get; set; }
        public IBlog Blog { get; set; }
    }
}

###EF Core version: 2.0.1

**Comment by maumar** [comment]
The exception was fixed a while ago - the problem was that we were evaluating too much on the client.

However currenly the query plan looks better - the predicate on the inner query is now translated.

```
(QueryContext queryContext) => IEnumerable<Blog> _InterceptExceptions(
    source: IEnumerable<Blog> _TrackEntities(
        results: IEnumerable<Blog> _Where(
            source: IEnumerable<Blog> _ShapedQuery(
                queryContext: queryContext, 
                shaperCommandContext: SelectExpression: 
                    SELECT [x].[Id], [x].[Title], [x].[Url]
                    FROM [Blogs] AS [x], 
                shaper: BufferedEntityShaper<Blog>), 
            predicate: (Blog x) => bool Any(IEnumerable<Post> _Where(
                    source: IEnumerable<Post> _InjectParameters(
                        queryContext: queryContext, 
                        source: IEnumerable<Post> _Where(
                            source: IEnumerable<Post> _ShapedQuery(
                                queryContext: queryContext, 
                                shaperCommandContext: SelectExpression: 
                                    SELECT [y].[Id], [y].[BlogId], [y].[Content], [y].[Title]
                                    FROM [Posts] AS [y]
                                    WHERE @_outer_Id = CASE
                                        WHEN 1 = 1
                                        THEN [y].[BlogId] ELSE NULL
                                    END, 
                                shaper: BufferedEntityShaper<Post>), 
                            predicate: (Post y) => y.Title == "Hi"), 
                        parameterNames: new string[]{ "_outer_Id" }, 
                        parameterValues: new object[]{ (object)Nullable<int> GetValueFromEntity(
                                clrPropertyGetter: ClrPropertyGetter<Blog, int>, 
                                entity: x) }), 
                    predicate: (Post y) => (Nullable<int>)int GetValueFromEntity(
                        clrPropertyGetter: ClrPropertyGetter<Blog, int>, 
                        entity: x) ?= True ? (Nullable<int>)int GetValue(
                        queryContext: queryContext, 
                        entity: (Post)y, 
                        property: Post.BlogId) : null))), 
        queryContext: queryContext, 
        entityTrackingInfos: { itemType: Blog }, 
        entityAccessors: List<Func<Blog, object>> 
        { 
            Func<Blog, Blog>, 
        }
    ), 
    contextType: QueryBugsTest+MaumarDbContext, 
    logger: DiagnosticsLogger<Query>, 
    queryContext: queryContext)
```

@mdavisJr  thanks for looking into this!

**Comment by maumar** [comment]
Actually, even though we translate the inner predicate, we still keep the client eval on top of it, we should be able to remove it now.

**Comment by maumar** [comment]
Casting to interface type forces client evaluation on everything that gets composed on top of it.

```
                    var query = context.Employees
                        .OfType<IEmployee>().Where(i => i.Name != "foo")
                        .ToList();
```

produces the following query plan:

```
(QueryContext queryContext) => IEnumerable<IEmployee> _InterceptExceptions(
|__ source: IEnumerable<IEmployee> _Where(
|   |__ source: IEnumerable<IEmployee> OfType(IEnumerable<Employee> _ShapedQuery(
|   |   |__ queryContext: queryContext, 
|   |   |__ shaperCommandContext: SelectExpression: 
|   |   |       SELECT [e0].[Id], [e0].[Name]
|   |   |       FROM [Employees] AS [e0], 
|   |   |__ shaper: (MaterializationContext materializationContext) => 
|   |       {
|   |           instance = new Employee()
|   |           instance.<Id>k__BackingField = int TryReadValue(ValueBuffer materializationContext.get_ValueBuffer(), 0, Employee.Id)
|   |           instance.<Name>k__BackingField = string TryReadValue(ValueBuffer materializationContext.get_ValueBuffer(), 1, Employee.Name)
|   |           return instance
|   |       })), 
|   |__ predicate: (IEmployee i) => i.Name != "foo"), 
|__ contextType: MyContext, 
|__ logger: DiagnosticsLogger<Query>, 
|__ queryContext: queryContext)
```

**Comment by maumar** [comment]
@divega

**Comment by smitpatel** [comment]
@maumar - Is this still the case? We added support for properties based on interface. Though using OfType on interface can throw off our logic that it is indeed entityType.

**Comment by smitpatel** [comment]
Generated SQL in 3.1
```SQL
      SELECT [b].[Id], [b].[Url]
      FROM [Blogs] AS [b]
      WHERE EXISTS (
          SELECT 1
          FROM [Posts] AS [p]
          WHERE ([b].[Id] = [p].[BlogId]) AND ([p].[Title] = N'Hi'))
```
All above queries work and evaluate on server side.
