### ISSUE TITLE
Use Task.FromResult consistently

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#7445]
For methods returning a non-generic `Task` we should always use Task.FromResult(true)

**Comment by benaadams** [comment]
Use task cache? https://github.com/aspnet/Common/blob/dev/shared/Microsoft.Extensions.TaskCache.Sources/TaskCache.cs

**Comment by AndriySvyryd** [comment]
@benaadams Yeah, that's even better

**Comment by bricelam** [comment]
Use `Task.CompletedTask`

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/blob/24b9aa1d2e14fe2e737255ede9b2a7a623fcf2af/src/EFCore/ChangeTracking/NavigationEntry.cs#L131

Unable to find any other place where we are returning non-generic task and not using Task.CompletedTask.

**Comment by roji** [comment]
Close?

**Comment by smitpatel** [comment]
Who will update that one reference? :trollface:

**Comment by roji** [comment]
Well I'm technically assigned to it, so......

**Comment by smitpatel** [comment]
Unassigned. I think we can leave it to good-first-issue or if someone in the team wants to do this.

**Comment by AsifulNobel** [comment]
@smitpatel Can I take on this issue? Also should the following `Task.FromResult(0)` replaced be replaced as well, as the methods are returning non-generic `Task`?

https://github.com/aspnet/EntityFrameworkCore/blob/567a2e94d5a764c61ac2ddb364e9e74a356f0b75/src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs#L94
https://github.com/aspnet/EntityFrameworkCore/blob/567a2e94d5a764c61ac2ddb364e9e74a356f0b75/src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs#L115

**Comment by smitpatel** [comment]
@AsifulNobel - Go ahead. Yes, those methods should also be updated. I must have missed them in GitHub search.

**Comment by AndriySvyryd** [comment]
Fixed in https://github.com/aspnet/EntityFrameworkCore/pull/17846/commits/7a00ca7d450987fb86b78b694ac63da6ae359803
