### ISSUE TITLE
Decide whether non-generic DbSet is needed

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#747]
If it is, consider how it should work with particular reference to LINQ implementation.

**Comment by knyzorg** [comment]
If you don't mind me asking, what was the rational behind this decision? Would you be open to revisiting this?

My use-case is that I need to dynamically work with with DBSets whose type is unknown at compile-time and as such I am forced to do the following:

```cs
dbContext.GetType().GetMethod("Set").MakeGenericMethod(new[] { masterType }).Invoke(dbContext);
```

The above has two problems:

1) It's really messy, and an overload with an argument could make it much more pleasant to work with
2) I am forced to use reflection any time I touch it, as I cannot cast it to a `DbSet` type.

Ideally, I could write the following:
```cs
DbSet myDbSet = dbContext.Set(masterType);
```

@rowanmiller @ajcvickers

**Comment by ajcvickers** [comment]
@knyzorg It's based on three things:
* A `DbSet` is not needed for `Add/Attach/etc.`, unlike EF6
* Querying requires LINQ, and LINQ is heavily generic
* Not having it removes complexity in the implementation and API surface.

**Comment by knyzorg** [comment]
@ajcvickers 

I am avoiding the LINQ generics problem by using `Enumerable.Cast` as such:

```cs
var currentDbSet = Enumerable.Cast<object>((IEnumerable)dbContext.GetType().GetMethod("Set").MakeGenericMethod(new[] { type }).Invoke(dbContext, new object[] { }));
```

Maybe something along similar strokes could be done with DbSet? 
Maybe the non-generic DbSet could present itself as `DbSet<object>` to LINQ?

I understand that the use-case is somewhat niche, but I think (without looking at the relevant code) there would be ways to implement it without significant complexity.

**Comment by ajcvickers** [comment]
@knyzorg A `IQueryable<object>` also doesn't seem very useful. How are you then further composing queries with this?
