### ISSUE TITLE
Query: include is ignored if the entity is inside binary operation (and others), which may cause problems for client-eval scenarios

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/EntityFrameworkCore#7658]
I encounter a very strange behavior that I am not able to explain.

I have an extension method:

        public static string UrlSuffix( this Place s)
        {
            var nameUrlPref =s.Name.ToUrlPrefix();
            var countryUrlPref = s.Location.Country.ToUrlPrefix();
            var cityUrlPref = s.Location.City.ToUrlPrefix();
            return countryUrlPref + cityUrlPref + nameUrlPref + s.Id;
        }

And I call the following code:

    var places = (from s in DbContext.Places.Include(ss=>ss.Location)
                          where s.PublishedStatus == PublishedStatus.Published &&s.PublishedUntil > DateTime.Today
                              && s.Location!=null
                          select s);
            return new FileContentResult(System.Text.Encoding.UTF8.GetBytes( String.Join("\n",from s in places select s.Location != null ? "https://mysite.com/Places/" + s.UrlSuffix() : "") +"\n"), "text/plain");

This is the result of several tries, but like this, the s.UrlSuffix throws an exception because s.Location is null (even if I test if not null before in the select!).
The only way I found to solve this issue is to apply a ".ToList()" to the initial query to force executing it.

I use the following versions:
    "Microsoft.EntityFrameworkCore": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Relational": "1.0.1",
    "Microsoft.EntityFrameworkCore.Design": "1.0.1",
    "Microsoft.EntityFrameworkCore.Design.Core": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.AspNetCore.HttpOverrides": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.Server.Kestrel.Https": "1.0.1",
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },

and SQL Server, VS 2015

**Comment by maumar** [comment]
problem here is that include gets ignored because we don't detect that it is actually needed (since its behind client method). Workaround could also be to explicitly project place, like so:

```cs
                var places = (from s in ctx.Places.Include(ss => ss.Location)
                    where s.PublishedStatus == PublishedStatus.Published && s.PublishedUntil > DateTime.Today
                          && s.Location != null
                    select s);

                var query = from s in places
                            select new {s, foo =  s.Location != null ? "https://mysite.com/Places/" + s.UrlSuffix() : "" };

                var result = query.ToList();
```

**Comment by maumar** [comment]
sending for re-triage
