### ISSUE TITLE
Query/Cleanup : Rewrite Navigation rewriter

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#7773]
Currently we need to run entity equality before nav rewrite for some cases. We also need to run it after nav rewrite for some others. We should look into refactoring that code.

**Comment by smitpatel** [comment]
Same goes for `SubQueryMemberPushdownExpressionVisitor`

**Comment by AndriySvyryd** [comment]
Also applies for `IncludeCompiler`. Perhaps `NavigationRewritingExpressionVisitorFactory` should accept the visitors that need the information that is lost during the rewrite and provide them with it each time a rewrite happens.
