### ISSUE TITLE
Calling static method in select and applying ToList produces wrong results.

### ISSUE THREAD

**Issue by dmitryshunkov** [aspnet/EntityFrameworkCore#7983]
Inconsistent behavior when calling extension method for projection (f.e. for mapping to DTO) with and without ToList. Looks like closure behavior. If call ToList on Select with static extension method call it produces duplicate values.

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace TestEF
{
    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseInMemoryDatabase();

        //=> optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=WonkyVB;Trusted_Connection=True;");
    }

    public class Blog
    {
        public int Id { get; set; }
        public string Title { get; set; }

        public ICollection<Post> Posts { get; set; }
    }

    public class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }

        public int? BlogId { get; set; }
        public Blog Blog { get; set; }
    }

    public class PostDTO
    {
        public string Title { get; set; }
    }

    public static class Mappings
    {
        public static PostDTO From(this PostDTO dto, Post post)
        {
            dto.Title = post.Title;
            return dto;
        }
    }

    public class Program
    {
        public static void Main()
        {
            using (var context = new BloggingContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.Add(new Blog
                {
                    Posts = new List<Post> { new Post { Title = "First" }, new Post { Title = "Second" }, new Post { Title = "Third" } }
                });
                context.SaveChanges();
            }

            using (var context = new BloggingContext())
            {
                var list = context.Posts.Select(p => new PostDTO().From(p)).ToList(); // Produces: Third Third Third
                //var list = context.Posts.Select(p => new PostDTO().From(p)); // Produces: First Second Third
                foreach (var item in list) Console.WriteLine(item.Title);
            }
        }
    }
}
```

### Further technical details
EF Core version: 1.1.1
Database Provider: (Microsoft.EntityFrameworkCore.InMemory, Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10
IDE: (e.g. Visual Studio 2017)

**Comment by smitpatel** [comment]
I investigated into this and this is bug in ReLinq's QueryParser.

When we get the expression tree (after ParameterExtraction) the LambdaExpression in Select has `NewExpression` for `PostDTO` which converts to `ConstantExpression` of `PostDTO` in QueryModel.SelectClause after ReLinq parses the query.

Generated QueryModel.ToString
```
{from Post p in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QueryBugsTest+Post]) select value(Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QueryBugsTest+PostDTO).From([p])}
```

@MichaelKetting

**Comment by smitpatel** [comment]
@dmitryshunkov - As a workaround you can move defining new PostDTO from select clause. Effectively write query like this
```
var list = db.Posts.Select(p => From(p)).ToList();

public static PostDTO From(Post post)
{
    var dto = new PostDTO { Title = post.Title };
    return dto;
}
```

**Comment by maumar** [comment]
@smitpatel to file a relinq bug on this

**Comment by MichaelKetting** [comment]
@smitpatel Yes, an issue would be much approciated for bookkeeping.

PS: Sorry, I thought that I already responded here but looks like it got lost in the inbox queue. I try to do a repro for this in the re-linq tests over the weekend but the next couple of weeks will be crazy for me so I can't make promises and I'll apologize in advance for any delays :)

**Comment by smitpatel** [comment]
Filed issue on Re-Linq https://www.re-motion.org/jira/browse/RMLNQ-112

**Comment by MichaelKetting** [comment]
@smitpatel Just for bookkeeping: Thanks for the repro, it was a great tool for reminding me this can (and is meant to) be solved in EntityFramework using exisitng re-linq parsing infrastructure (IEvaluatableExpressionFilter). Please check the RMLNQ-112 issue for details.

**Comment by ajcvickers** [comment]
Closing this for now since the pattern is not super common and there is no easy solution that would not negatively impact other scenarios. We would consider re-opening this based on feedback from others hitting it.

**Comment by smitpatel** [comment]
Re-opening this. Since we are getting rid of ReLinq, we should look into supporting this kind of scenario. While this particular pattern may not be common, it is just a small subset of large scenario, in which user can call `new class()` which does not depend on range variable.

**Comment by divega** [comment]
@smitpatel to provide workaround.
