### ISSUE TITLE
Query: Sum should return zero for empty collections regardless of the type

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#800]
This is to match the behavior of LINQ to Objects and expectation expressed here:

https://entityframework.codeplex.com/workitem/2449
http://data.uservoice.com/forums/72025/suggestions/2410716
http://stackoverflow.com/questions/3274196

**Comment by smitpatel** [comment]
@maumar - Is this something we already did or tracking somewhere else?

**Comment by maumar** [comment]
somewhat related to https://github.com/aspnet/EntityFramework/issues/6061

**Comment by anpete** [comment]
Verified this is already working.

**Comment by anpete** [comment]
Scratch that, I see that we don't return 0 for nullable types.
