### ISSUE TITLE
Overall plan for diagnostics

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#8009]
We need to have an overall plan for the who/what/where of diagnostics messages. Specifically,
* Where should new code be writing do--just the diagnostics package, or also integration with APIs?
* What is the plan for different layers sending the same info? For example, if ADO.NET layer is triggering for queries, then should EF not do so? Or is it up to the consumer to filter?
* Do we need to do anything special for App Insights?
* What about tracing from application through to end-point?

Assigning to @divega who may have other things to add to this list. (Or may just know the answer!)

**Comment by divega** [comment]
@ajcvickers @anpete given it is unlikely that we will add in 2.0 RTW more than what we have in preview2 and that the work on App Insights will continue beyond 2.0, I would like to move this issue to the backlog for now and repurpose it to cover the actual "overall" plan for diagnostics on .NET data. Thoughts?

**Comment by ajcvickers** [comment]
Sounds fine.
