### ISSUE TITLE
Query: Improve how SelectExpression performs join to preserve sufficient metadata for binding

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#8094]
At present our code to lift subquery is not streamlined. We have `QueryModelVisitor.IsLiftable` flag after which we also have other checks which determines if we can lift subquery or not. And even after all these checks, we still sometimes fails to lift subquery during joins.

Moreover the way our AddJoinFamily works is, it takes the first table from inner select expression and add it as joinexpression. This is in a way side effect of `LiftSubQuery` method which pushes down the select expression if is not identity query. When joins are lifted this all works fine but when join is not lifted, we end up with a select expression which was pushed down even if it was not required to.

We should be more accurate about when we want to push down subquery. We should do it only when we need it especially during AddJoin.

**Comment by tuespetre** [comment]
Hmmmmm :trollface:

**Comment by smitpatel** [comment]
@ajcvickers @anpete - This requires breaking changes in SelectExpression. So it is not possible to do in 2.1 Should we put this in 3.0/backlog?

**Comment by anpete** [comment]
@smitpatel What is the break?

**Comment by smitpatel** [comment]
`SelectExpression.AddJoinFamily` at present takes table & projections. That is where the data about orderby or predicate is going missing like in #8375 
A more robust way to do this would be to pass in whole SelectExpression to join to the method and let the method figure out what to do with it (like pushdown) and how to join it.

**Comment by anpete** [comment]
You should be able to add a new overload of AddJoinFamily without breaking.

**Comment by ajcvickers** [comment]
Make sure to test #10812 when working on this.

**Comment by smitpatel** [comment]
Also consider scenario in #4957

**Comment by smitpatel** [comment]
We have implemented this in new query pipeline. Now join are passed to SelectExpression for binding so that it can copy over internal metadata.
