### ISSUE TITLE
New specification test fails with SQLCE provider

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#8150]
@smitpatel 

Running this new test:
https://github.com/aspnet/EntityFramework/blob/0748e3e8b942855db7035d6a8dff98a8cb77584c/src/EFCore.Specification.Tests/QueryTestBase.cs#L3353

(Just noticed it also fails on my PC with the SQLite and SQL Server test)

```
Expected: Object[] [{ cust = Customer RATTC, ords = 18 }, { cust = Customer OLDWO, ords = 10 }, { cust = Customer GALED, ords = 5 }, { cust = Customer LILAS, ords = 14 }, { cust = Customer MAGAA, ords = 10 }]
Actual:   Object[] [{ cust = Customer DRACD, ords = 6 }, { cust = Customer RATTC, ords = 18 }, { cust = Customer OLDWO, ords = 10 }, { cust = Customer GALED, ords = 5 }, { cust = Customer LILAS, ords = 14 }]
	at Microsoft.EntityFrameworkCore.Specification.Tests.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Boolean assertOrder, Action`2 asserter)
	at Microsoft.EntityFrameworkCore.Specification.Tests.QueryTestBase`1.AssertQuery[TItem1,TItem2](Func`3 efQuery, Func`3 l2oQuery, Boolean assertOrder, Nullable`1 entryCount, Action`2 asserter)
	at Microsoft.EntityFrameworkCore.Specification.Tests.QueryTestBase`1.AssertQuery[TItem1,TItem2](Func`3 query, Boolean assertOrder, Nullable`1 entryCount, Action`2 asserter)
	at Microsoft.EntityFrameworkCore.Specification.Tests.QueryTestBase`1.GroupJoin_customers_orders_count_preserves_ordering()
```

### Further technical details
EF Core version: 2.0.0-preview1-24394
Database Provider: EntityFrameworkCore.SqlServerCompact40
Operating system: Win 10
IDE: (e.g. Visual Studio 2015)

**Comment by smitpatel** [comment]
It is data issue. Since it is ordering by city which has some Unicode characters in Mexico (AFAIK), something is not ordering properly. Could be issue of incorrect data or the comparison semantics.
That test explicitly exclude `Where(c => c.CustomerID != "VAFFE")` because it had Unicode letter in the city which was generating different ordering for sql server SQLite.

**Comment by ErikEJ** [comment]
Wonder why the SQLite and SQL Server test also fail on my PC, though

**Comment by smitpatel** [comment]
I am also surprised at SQLite failure as we have northwind.db in repo for that. Few months ago I had updated northwind.db because the data in SQLite & SQL server wasn't the same. SqlServer you may have different data.

**Comment by ajcvickers** [comment]
@ErikEJ Seems like there is something different on your machine. Maybe locale is different causing different ordering? Could you investigate what might be different about your machine and then we can try to make the test more robust.

**Comment by ErikEJ** [comment]
Will do!

**Comment by ErikEJ** [comment]
@smitpatel @ajcvickers It is a localization "bug"

     from c in cs.Where(c => c.CustomerID != "VAFFE").OrderBy(c => c.City, StringComparer.Create(CultureInfo.InvariantCulture, false)).Take(5)

**Comment by ErikEJ** [comment]
A PR?

**Comment by smitpatel** [comment]
We cannot add string comparer (else it would not translate to server. 
Just modify the where clause to exclude the customer whose city is `Aachen`. `VAFFE` is excluded for same reason causing issue between SQLite/SqlServer.
Feel free to send in PR.
Thanks.

**Comment by smitpatel** [comment]
co-assigning myself to merge the PR.

**Comment by ErikEJ** [comment]
Thanks - what does this mean?? - is it not just a LINQ to Objects statement?:

>> We cannot add string comparer (else it would not translate to server.

**Comment by smitpatel** [comment]
@ErikEJ - It is an query which we run over EF & L2O both to compare results. L2O would work fine but it won't translate to SQL causing client eval. That's not what is intended from the test.

**Comment by ErikEJ** [comment]
from c in cs.Where(c => c.CustomerID != "VAFFE" && c.CustomerID != "DRACD").OrderBy(c => c.City).Take(5)

**Comment by ErikEJ** [comment]
Same issue with: Include_with_orderby_skip_preserves_ordering
