### ISSUE TITLE
Perf: DbSetOperationTests.RemoveRange shows a 25% regression since April 8

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#8298]
Just creating this issue to give us a chance to follow up.

![image](https://cloud.githubusercontent.com/assets/1253414/25464357/c469af5e-2ab0-11e7-95da-223a65e30d1d.png)

Note that it is still significantly more performant than EF6 on the same scenario and that many other benchmarks show significant (and mostly positive) changes in April 8 running on .NET Framework.

**Comment by ErikEJ** [comment]
@divega Just curios: What happened on April 8?

**Comment by ajcvickers** [comment]
Possibly this? https://github.com/aspnet/EntityFramework/pull/8070

**Comment by divega** [comment]
@smitpatel looked a the the changes that come in in those days and we believe another change that could have had widespread effects was the switch to netcoreapp2.0, but we are not sure it can explain a change in perf on .NET Framework.

**Comment by AndriySvyryd** [comment]
Fixed in eef4a6eb25fcdee11fd0568b5aec3c748cd713a1
