### ISSUE TITLE
Perf: DbSetOperationTests.Update benchmark with AutoDetectChanges off shows EF Core is slower then EF6

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#8313]
The difference is of about 25% in the last 10 days:

#### AutoDetectChanges Off
![image](https://cloud.githubusercontent.com/assets/1253414/25507217/8f56f592-2b5f-11e7-87ed-b9ffc9c10458.png)

Note that perf. results for the same test with AutoDetectChanges On are significantly better:

#### AutoDetectChanges On
![image](https://cloud.githubusercontent.com/assets/1253414/25507311/17ac590a-2b60-11e7-8fa5-d0e9fba1918e.png)

**Comment by AndriySvyryd** [comment]
Fixed in eef4a6eb25fcdee11fd0568b5aec3c748cd713a1
