### ISSUE TITLE
Add parameterless overloads of UseSqlServer, UseSqlite, etc.

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#8427]
For cases like #8410 where the provider needs to be known, but no connection to the database is going to be made. This API could also be used for places where the connection string is set later (bur before the connection is used) using `context.Database...`.

**Comment by ajcvickers** [comment]
See also #8350 #6525 #8494

**Comment by roji** [comment]
providers-fyi?
