### ISSUE TITLE
Flaky Test: ComplexNavigationsOwnedQuerySqlServerTest.Level4_Include

### ISSUE THREAD

**Issue by mikeharder** [aspnet/EntityFrameworkCore#8446]
```
	[Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.ComplexNavigationsOwnedQuerySqlServerTest.Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.ComplexNavigationsOwnedQuerySqlServerTest.Level4_Include] Assert.Equal() Failure
                  ↓ (pos 8)
Expected: SELECT [l1.OneToOne_Required_PK.OneToOne_Required···
Actual:   SELECT [t.OneToOne_Required_PK.OneToOne_Required_···
                  ↑ (pos 8)
```

5/11/17: http://aspnetci/viewLog.html?buildId=218889&buildTypeId=Lite_EntityFrameworkTest&tab=buildLog&filter=err#_

**Comment by smitpatel** [comment]
It did not fail in different runs. (also appveyor is green). Do we have access to the repo folder when the particular test failed or it would be cleared out during subsequent run? On test failures, EF generates a file in repo root which can provide more information in this case.

**Comment by mikeharder** [comment]
@ryanbrandenburg, can you check if there's still any artifacts remaining which could help EF debug this?

**Comment by smitpatel** [comment]
No repro.

**Comment by smitpatel** [comment]
Its net461 only

**Comment by smitpatel** [comment]
#8759  Should help investigating this.

**Comment by smitpatel** [comment]
@ajcvickers - This is not possible to investigate without #8759 should we move this out of 2.0 as well?

**Comment by ryanbrandenburg** [comment]
@divega was this closed because we haven't seen a new instance of it in a while? Lets make sure to comment the reasons for closing things when we do so that if it re-occurs we know what's already been tried.

**Comment by divega** [comment]
This test hasn’t failed in many months, plus there have been significant changes on both the test code and product area.

**Comment by ryanbrandenburg** [comment]
Cool, that's what I figured, just wanted it noted for posterity.
