### ISSUE TITLE
Remove remaining primitive type assumptions from Core

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFrameworkCore#8537]
1) The following Core classes still have hard-coded references to primitive types (don't use a type mapper):

ValueGeneratorConvention
ValueGeneratorSelector
EntityQueryModelVisitor

We should try and update to use type mapping here.

2) The StateManager relies on mapped types having value type equality or structural equality implemented. Should we delegate state manager equality determination to type mapping?

**Comment by ajcvickers** [comment]
+1 for pushing comparisons into the type mapper. Although it also relates to type conversions. Maybe type mapping and type conversions merge into one thing?

**Comment by divega** [comment]
> Maybe type mapping and type conversions merge into one thing?

Sounds reasonable. Type conversions will have to do type mapping + conversions.

**Comment by divega** [comment]
@smitpatel @ajcvickers is this something that we need to have in the radar for the 3.0 LINQ work?

**Comment by bricelam** [comment]
I scanned through the places we hardcode types and I didn't see any major concerns:
- Value generator selection
- Value converters
- Sequence doesn't support unsigned
- Design time assumes a few things about string and binary columns (e.g. it won't configure HasMaxLength otherwise)
