### ISSUE TITLE
Migrations: Add IsSqlServer, etc. to MigrationBuilder

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#8566]
Add the same sugar as #8545

**Comment by laskoviymishka** [comment]
It probably already implemented (see b9cd36d3c96f7d65eb0807f963800e17f92cbf20)

**Comment by bricelam** [comment]
@laskoviymishka That was about adding it to `DbContext.Database`. This issue is about adding the same methods to `MigrationBuilder`.

**Comment by bricelam** [comment]
Never mind. We'd have to make a lot of breaking changes to remove `Migration.ActiveProvider`. I can live with it the way it is.

**Comment by ajcvickers** [comment]
@bricelam But we can still add the sugar methods, right? It's just not a breaking change anymore if we don't remove `ActiveProvider`?

**Comment by bricelam** [comment]
Yeah, I kinda hijacked this issue to try and get a breaking change into 3.0. It didn't work out. This issue can just go back to the backlog as up-for-grabs. The original request isn't breaking (or urgent).
