### ISSUE TITLE
Migrations: Leverage IUpdateSqlGenerator for CUD operations 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#8569]
Based on the conversation at https://github.com/aspnet/EntityFramework/pull/8544#pullrequestreview-39877758, we can use IUpdateSqlGenerator as it was already done in the [data seeding PR] (https://github.com/aspnet/EntityFramework/pull/7824) instead of having ad-hoc DML generation code in Migrations.

**Comment by bricelam** [comment]
This change feels risky. The Seeding PR made changes to IUpdateSqlGenerator to get this to work. Given where we are in the release, I think we should punt this.

**Comment by AndriySvyryd** [comment]
Fixed in https://github.com/aspnet/EntityFrameworkCore/pull/9772
