### ISSUE TITLE
SQL Server Migrations: Unable to remove schema

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#8726]
_From @ferrx on May 31, 2017 19:56_

I applied a table mapping like the following,

```
    [Table("blogs", Schema = "blogging")]
    public class Blog
```
Upon using `Add-Migration` and `Update-Database` I see the changes in my DB. The table went from "Blogs" to "blogs (blogging)".

However, if I remove the data annotation like so,

```
    public class Blog
```
Upon using `Add-Migration` and `Update-Database` I get an error `Cannot find the object "Blogs" because it does not exist or you do not have permissions.` 

I can force it work if I do the following,

```
    [Table("blogzzz", Schema = "blogging")]
    public class Blog
```
followed by `Add-Migration` + `Update-Database` and then,
```
    public class Blog
```
It's as if there is a case sensitivity issue? Hard to make sense of it, but it seems like renaming from blogs->Blogs does not work somewhere. It seems that renaming Blogs->blogs worked fine when applying the original data annotation.

While that work-around does fix the issue, the table still shows up with the `blogging` schema as "Blog (blogging)"

_Copied from original issue: aspnet/EntityFramework.Docs#401_

**Comment by divega** [comment]
_From @ajcvickers on May 31, 2017 21:36_

@ferrx What version of EF Core and which database provider are you using?

**Comment by divega** [comment]
_From @ferrx on May 31, 2017 22:40_

@ajcvickers For EF Core I have the following,

Microsoft.EntityFrameworkCore.Design 1.1.1
Microsoft.EntityFrameworkCore.SqlServer 1.1.2
Microsoft.EntityFrameworkCore.SqlServer.Design 1.1.2
Microsoft.EntityFrameworkCore.Tools 1.1.1

Using SQL Server (localdb).

**Comment by divega** [comment]
_From @ferrx on May 31, 2017 22:42_

Updated Microsoft.EntityFrameworkCore.Design to 1.1.2 and ran `Update-Database` again and received the same error,

> Cannot find the object "Blog" because it does not exist or you do not have permissions.

Here is the add-migration output if that helps,

```
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EFGetStarted.AspNetCore.ExistingDb.Migrations
{
    public partial class Schema2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Post_blogs_BlogId",
                table: "Post");

            migrationBuilder.DropPrimaryKey(
                name: "PK_blogs",
                schema: "blogging",
                table: "blogs");

            migrationBuilder.RenameTable(
                name: "blogs",
                schema: "blogging",
                newName: "Blog");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Blog",
                table: "Blog",
                column: "BlogId");

            migrationBuilder.AddForeignKey(
                name: "FK_Post_Blog_BlogId",
                table: "Post",
                column: "BlogId",
                principalTable: "Blog",
                principalColumn: "BlogId",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Post_Blog_BlogId",
                table: "Post");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Blog",
                table: "Blog");

            migrationBuilder.EnsureSchema(
                name: "blogging");

            migrationBuilder.RenameTable(
                name: "Blog",
                newName: "blogs",
                newSchema: "blogging");

            migrationBuilder.AddPrimaryKey(
                name: "PK_blogs",
                schema: "blogging",
                table: "blogs",
                column: "BlogId");

            migrationBuilder.AddForeignKey(
                name: "FK_Post_blogs_BlogId",
                table: "Post",
                column: "BlogId",
                principalSchema: "blogging",
                principalTable: "blogs",
                principalColumn: "BlogId",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
```

Edit: I just noticed this one doesn't even try to rename it to the conventional `Blogs`, instead it tries to use `Blog`. Using a different project on this machine, so slightly different behavior.

**Comment by divega** [comment]
_From @ferrx on June 1, 2017 16:9_

I created a project from scratch and after some testing I see that the add-migration script does not remove a schema when either removing the entire DA or removing the schema property of the DA. The associated designer performs a `ToTable` without a schema parameter (as it should), so any further updates to that table will return an error because the actual table is still associated with a schema that is not dbo. I also tested changing the schema from "blogging" to "dbo" in the DA and saw that it updated properly, after which I was able to remove the DA entirely and perform valid updates to `dbo.Blogs`. Removing the DA or the schema property of the DA should ensure that the schema is changed to `dbo`?

You can replicate this by creating a baseline project with a model, applying a schema to it via data annotation (unsure if Fluent API has the same problem), then either remove the entire DA or remove the schema property from the DA. Any future updates will throw an error of table not found.

Update: Testing with Fluent API causes the same issue.

**Comment by bricelam** [comment]
This is a bug. No SQL is generated to move an object to the default schema.

### Workaround
Explicitly specify *dbo* as the new schema in the migration.
```C#
migrationBuilder.RenameTable(
    name: "Blog",
    schema: "blogging",
    newName: "Blog",
    newSchema: "dbo");
```

**Comment by rockygorden** [comment]
i faced this issue when i was trying to seed some values and trying to create the blog. Once i delete the migration folder the issue got resolved.
