### ISSUE TITLE
Consider renaming this repo to EntityFrameworkCore or EFCore

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#8762]
The current name of the repo, "EntityFramework" is ambiguous. It is not surprising that many EF6 issues are created here. We should probably wait until we ship 2.0.

**Comment by bricelam** [comment]
+1 for EFCore

**Comment by ferrx** [comment]
another +1 for EFCore -- it would be good to match the file naming convention which uses EFCore already.

**Comment by ErikEJ** [comment]
And rename the packages while you are at it  😹

**Comment by ajcvickers** [comment]
Dumb question: won't it mess up all the links out there in the wild? Or does GitHub handle that?

**Comment by bricelam** [comment]
GitHub [handles renames](https://help.github.com/articles/renaming-a-repository/). Everything is redirected unless you create a new repo using the old name.

**Comment by mikes-gh** [comment]
I agree EntityFrameworkCore is too verbose however....

Renaming the repo to EntityFrameworkCore will be easiest and most consistent unless you decide to rename all the namespaces.

@ErikEJ Renaming the packages would be easy enough as most people will be using the `Microsoft.AspNetCore.All` meta package for 2.0. however what about all the namespaces.

That would be a huge pain point for end users brings back memory's of the aspnetcore naming change which took a few weeks to settle and broke just about every ci build in the organisation.




`

**Comment by mikes-gh** [comment]
I just wanted to add I would be happy in my projects to find replace EntityFrameworksCore -> EFCore to avoid verbosity long term

**Comment by ferrx** [comment]
Renaming the repo is fine with links in Docs, just be careful about renaming actual filenames (i.e. if you decide to swtich file naming convention to `EntityFrameworkCore` instead of `EFCore` -- see this issue for example https://github.com/aspnet/HttpSysServer/issues/358

**Comment by ajcvickers** [comment]
@Eilon @muratg Have we renamed repos before? Any gotchas we should be careful of if we do this?

**Comment by Eilon** [comment]
We've renamed tons of repos before, it works great. I would be very happy with `EntityFrameworkCore` as the name.

**Comment by muratg** [comment]
Yup, it works really well. For example, if you use the old name, it forwards you to the new name with the links and the APIs.

For example, https://github.com/aspnet/weblistener will forward to httpsysserver. 

(Not sure how long the forwarding works after the rename, though.)

**Comment by smitpatel** [comment]
> When you rename a repository, all existing information, with the exception of Project Pages URLs, is automatically redirected to the new name, including:
Issues
Wikis
Stars
Followers

I believe the redirection works forever.

**Comment by ajcvickers** [comment]
We will rename to EntityFrameworkCore, after we ship preview2.

**Comment by divega** [comment]
Clearing milestone just to double-check if we want to rename the repo now or wait until 2.0 ships. If the former, can create an announcement and rename the repo, but we need to update various references in cross-repo build.

**Comment by ajcvickers** [comment]
Decision is EntityFrameworkCore
