### ISSUE TITLE
SQLite Migrations: HasComputedColumnSql is ignored

### ISSUE THREAD

**Issue by ferrx** [aspnet/EntityFrameworkCore#8764]
I am using examples from EntityFramework docs to use Sqlite and InMemoryDatabase for unit testing. Most tests work fine, but I am unable to test fluent API model changes that should take place during OnModelCreating.

For example,

```
// please excuse any typos in this example!

public class PersonContext : DbContext
{
    public PersonContext(DbContextOptions<PersonContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>()
            .Property(p => p.DisplayName)
            .HasComputedColumnSql("[LastName] + ', ' + [FirstName]");
    }

    public DbSet<Person> Persons { get; set; }
}

public class Person
{
    public int PersonId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }

    [Display(Name ="Full Name")]
    public string DisplayName { get; set; }
}
```
```
[Fact]
public void TestCreatePerson()
{
    var options = new DbContextOptionsBuilder<PersonContext>()
        .UseInMemoryDatabase(databaseName: "TestCreatePerson")
        .Options;

    using (var context = new PersonContext(options))
    {
        var person = new Person();
        person.FirstName = "Steven";
        person.LastName = "Ferrell";
        PersonsController controller = new PersonsController(context);
        controller.Create(person);
    }

    using (var context = new PersonContext(options))
    {
        Assert.Equal(1, context.Persons.Count());
        Assert.Equal("Steven", context.Persons.Single().FirstName);
//the following fails with the error that DisplayName is actually <null> instead of "Ferrell, Steven"
        Assert.Equal("Ferrell, Steven", context.Persons.Single().DisplayName);
    }
}
```

**Comment by smitpatel** [comment]
Perhaps `HasComputedColumnSql` does not work for InMemoryDb since its not relational or SQL database.

**Comment by ferrx** [comment]
@smitpatel I considered that, so I tested the same thing using Sqlite and had the same issue.

> SQLite in-memory mode allows you to write efficient tests against a provider that behaves like a relational database.

**Comment by ajcvickers** [comment]
@bricelam I don't think `HasComputedColumnSql` will be picked up and used by SQLite. Can you confirm? If so, we should consider a model validation warning.

**Comment by bricelam** [comment]
It looks like computed columns are ignored in the base Migrations SQL generator. We should fix that. They're not supported on SQLite, but they are on other non-MSSQL databases. A validation warning would be good on SQLite.

**Comment by ajcvickers** [comment]
We should throw if you're trying to do this on a provider that doesn't support it.

**Comment by ajcvickers** [comment]
@youngaj Computed columns are not supported by the underlying SQLite engine. It might be possible to simulate this with functions--I don't know SQLite that well. However, fundamentally, if your tests depend on behaviors that are only available with your actual database system, then you'll likely have better luck testing against that database system rather than substituting something with different behaviors.

**Comment by youngaj** [comment]
Thanks for the help @ajcvickers and @bricelam  

I added some logic to the code to handle the computed property during testing.  I'm hoping it won't become a performance problem for the application at run time.

**Comment by bricelam** [comment]
Oops, re-opening. I referenced the wrong bug in my previous PR.
