### ISSUE TITLE
Consider porting fix for Migrations: Parameterless DbContext constructor is used in preference to overload taking DbContextOptions (#6826) to a 1.1 patch

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#8825]
See https://github.com/aspnet/EntityFramework/issues/6826.

**Comment by divega** [comment]
We actually don't need this. #6826 fix did not go in 2.0 so we can issue the original issue to track it for a patch.

**Comment by ajcvickers** [comment]
@bricelam I think this one does meet the bar--we have seen lots of people hit this. Your thoughts?

**Comment by bricelam** [comment]
Agree. Super low risk too. (one-liner)

**Comment by Eilon** [comment]
This patch is *approved* for 1.1.x. Please follow the patch creation instructions that were sent by email, and submit a PR to the correct branch.
