### ISSUE TITLE
Query: equality operator to entity typed as object should be translated.

### ISSUE THREAD

**Issue by Wain123** [aspnet/EntityFrameworkCore#8995]
The following code throws a System.InvalidOperationException: 'The EF.Property< T> method may only be used within LINQ queries.':
```
var blog = ctx.Blogs.First();
var blogObject = (object)blog;
var query = ctx.Posts.Where(z => z.Blog == blogObject);
foreach (var x in query) {
}
```
According to my logger, the SQL that gets sent to the DB selects ALL Posts, ignoring the Where condition. The error only occurs if the DB contains at least one Post.

**Comment by ajcvickers** [comment]
@Wain123 What version of EF Core are you using?

**Comment by Wain123** [comment]
EF Core 1.1.2.0

**Comment by Wain123** [comment]
Looking more carefully, it seems my DB provider (Devart dotConnect for Oracle) decides to evaluate the Where-condition client-side.

If you feel like everything is working as intended EF-side and I should ask Devart support instead, feel free to close this and I'll do that.

**Comment by Wain123** [comment]
In EFCore 2.1 RC1, this doesn't crash anymore, but it's still client-evaluated. So, I think this issue is fixed.

However, is it supposed to be client-evaluated or is that a bug too?

**Comment by smitpatel** [comment]
In 3.1 we evaluate the where clause on server.
