### ISSUE TITLE
Add more test coverage for tooling/RevEng

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#9111]

**Comment by smitpatel** [comment]
@bricelam - Heads up. I am going to start working on modifying reveng tests as we discussed earlier.

**Comment by smitpatel** [comment]
Summary of a recent discussion about testing of tools interface
There are 3 splits of tests needed.
1. PMC/dotnet ef calling into mock ef.exe with correct parameters. 
2. ef.exe calling into mock executor.
3. Executor calling into right entry points into (mock) design assembly.

Above would verify, from command to design assembly entry point pipeline is working correctly. 
Inside design assembly there are tests based on the scenarios.

**Comment by bricelam** [comment]
We also intend to add some IModel -> C# tests.
