### ISSUE TITLE
Make sure all PRs are ported from CodePlex

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#9113]
Or rejected and closed if we are not going to take them.

(This is EF6 work, but tracking here as part of 2.1 MQ.)

**Comment by divega** [comment]
In the EF6 repo this is tracked as https://github.com/aspnet/EntityFramework6/issues/276.

**Comment by maumar** [comment]
created https://github.com/aspnet/EntityFramework6/pull/466 and https://github.com/aspnet/EntityFramework6/pull/467
