### ISSUE TITLE
Metadata: Configuring class as EntityType & later as owned entity type explicitly should throw

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#9148]
```C#
public class Blog
{
    public int Id { get; set; }
    public BlogDetails BlogDetails { get; set; }
}

public class BlogDetails
{
    public int Value { get; set; }
}

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    // Configure model
    modelBuilder.Entity<BlogDetails>();
    modelBuilder.Entity<Blog>().OwnsOne(e => e.BlogDetails);
}
```

In above model `BlogDetails` has been configured as entity type first and then used as owned entity type. At present it works and creates the own entity type. It should throw exception because it is conflict in Explicit configuration source (which is what our behavior is for most other fluent APIs).
Also if this does not throw (and silently remove entity type and add owned entity type) then any facet configuration done on entity types are lost which may seem confusing to user since user may understand `.EntityType<>` as a replacement of `.ComplexType<>` may be.

found while investigating issue #9144

**Comment by ajcvickers** [comment]
Since throwing post 2.0 would be a breaking change, and this doesn't meet the bar to go into 2.0, could we instead copy facets over to the owned type or something like that? @AndriySvyryd?

**Comment by AndriySvyryd** [comment]
@ajcvickers Wouldn't that be a breaking change too?

**Comment by ajcvickers** [comment]
Yes, but maybe an acceptable one. 😸

**Comment by smitpatel** [comment]
Then it would become similar to `ComplexType` API but name merged into `EntityType`.
Also it could give false impression that you can have a CLR type as entity type and owned type both.

**Comment by divega** [comment]
> Then it would become similar to ComplexType API but name merged into EntityType...

I am not convinced that going in that direction would be a bad thing in the long term. Besides the decision we made for 2.0 (and the obvious benefits of forking the two APIs at the root so that Intellisense can better reflect the distinct capabilities of owned entity types vs. non-owned entity types) they are conceptually all entity types in EF Core. I am starting to suspect that negating that is detrimental to the usability of the API.

> Also it could give false impression that you can have a CLR type as entity type and owned type both.

Feature request? :trollface:

**Comment by ajcvickers** [comment]
Discussed in triage and decided to make it throw in the 2.1-preview1 and gather feedback as to whether this is too breaking.

**Comment by ctolkien** [comment]
> Feature request?

Well... now that you mention it....

I just hit this scenario whereby I have a stand alone `Customer` entity... but I also have an `Orders` entity to which I would like to add a `Customer` property as an owned entity.

Basically when an order is created, I could "snapshot" the customer details at that point in time and save them off on the particular order.

By the sounds of things, this scenario is not supported. It doesn't throw.. but things get into a weird state?

**Comment by ajcvickers** [comment]
Marking this for re-triage. It turns out that a [later change in 2.1](https://github.com/aspnet/EntityFrameworkCore/commit/f2dc8c0709af75f69977b8bf8cb9f3ea34198a6f) reverted this behavior, so it currently doesn't throw in this case.

**Comment by ajcvickers** [comment]
We will re-visit this in 3.0 since it is too late to do anything for 2.1.

**Comment by nphmuller** [comment]
Is there perhaps time in the 2.2 release window to makes this throw explicitely? I've ran into multiple ways for this to fail: During migration creation (#13944) and during compilation after succesfull migration creation (#13945). It's pretty confusing with the current behaviour.

**Comment by ajcvickers** [comment]
@nphmuller Unfortunately, 2.2 is locked down now for all but ship-stoppers. Also, this change has the potential to break some incorrectly configured but working applications, so we are targeting 3.0 since changing the behavior here could be a breaking change for those applications.

**Comment by nphmuller** [comment]
@ajcvickers Makes sense, especially if it's breaking. Thanks!
