### ISSUE TITLE
HasOne/HasMany used with single string can be confusing

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#9171]
See discussion on #6674 

If a relationship is configured like this:
```C#
modelBuilder.Entity<Samurai>().HasOne("Entrance").WithOne();
```
it looks like it should be using the navigation property "Entrance", which may be private. But really it is the related entity type name:
```C#
 public virtual ReferenceNavigationBuilder HasOne(
            [NotNull] string relatedTypeName,
            [CanBeNull] string navigationName = null)
```
The correct way to configure it is something like:
```C#
modelBuilder.Entity<Samurai>().HasOne(typeof(Entrance), "Entrance").WithOne();
```

**Comment by ajcvickers** [comment]
Comment from @divega:

I agree that is confusing :disappointed: The fact that the type isn't being specified as a generic argument but is still needed is very easy to miss. I wonder if this is the only API in which this happens. 

If we believe it is worth addressing it, something like this may help:

1. Obsolete this version of `HasOne` that doesn't take a generic argument 
2. Create a new API called `HasOneOfType` for this case. It would look like this:

``` C#
modelBuilder.Entity<Samurai>().HasOneOfType("Entrance", navigationName: "Entrance")
    .WithOne();
```

I think it helps because it reads like the (first) argument is the type. 

This looks complicated though:

``` C#
modelBuilder.Entity<Samurai>().HasOneOfType(typeof(Entrance), navigationName: "Entrance")
    .WithOne();
```

Maybe we do it only for the one that works with strings?

Perhaps there is a better solution.

**Comment by ajcvickers** [comment]
@divega A few of things I have been thinking about:
* If the navigation property exists (even if it is private) that we don't need the type name because it can be obtained from the navigation property. The only reason to pass both as arguments is when configuring a shadow state nav property, currently used only for the model snapshot.
* Having a generic overload for the type would be nice, even if the type is not needed, because it allows the generic to flow through for lambda expressions later later in the chain. I wonder if there is a reason we didn't add it here. 
* I wonder if we could just change it (probably in 3.0) to really have an single string overload just for the navigation name. This might be okay, because the times when you really want to only pass the single string type name seem rare to me--relationship with no navigation property where you don't want to use typeof() for some reason. Also, in this case there isn't a navigation property that matches, so after the change if there was code using this it could throw. It's hackish, but it could even warn and then drop back to using the name as a type if the navigation was not found--but not sure we even need to go that far.

**Comment by smitpatel** [comment]
But we need type always to find out what is related entity type. i.e. where to search that navigation.

**Comment by ajcvickers** [comment]
@smitpatel In the example, Samurai has a property called Entrance, which is of type Entrance. So the type of the navigation property tells us the type of the related entity.

**Comment by ajcvickers** [comment]
Filed #9191 for the generic overload. For the rest, putting in 3.0 as a possible breaking change that we could make at that time. Note that the type name has to be a full entity type name, and hence the code above while passing in OnModelCreating will fail at model validation time, which may make it easier to change the behavior without breaking any real code, at least once re-compiled.

**Comment by AndriySvyryd** [comment]
If the single string overload is changed to mean navigation it needs to retain old behavior when called on a shadow entity type to ensure old snapshots aren't broken.

New snapshots can be generated to always call the two parameter overload.

**Comment by ajcvickers** [comment]
Maybe we need a way to determine that we are building a snapshot--e.g. by setting some flag. That way we could special cases places like this.

**Comment by AndriySvyryd** [comment]
Also remove `HasForeignKey` and `HasPrincipalKey` overloads on `ReferenceReferenceBuilder` and `ReferenceReferenceBuilder<,>` that have the same issue.
