### ISSUE TITLE
Update API docs for Like

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#9172]
To be explicit about provider differences.

**Comment by divega** [comment]
Removing mysel in case someone else can take care of this this week.

**Comment by smitpatel** [comment]
@divega  I believe this is fixed by https://github.com/aspnet/EntityFrameworkCore/pull/9140 already.

I am assigning this to you and moving to backlog if you think we should improve docs further.

**Comment by divega** [comment]
@smitpatel thanks, good point. I will mark it as fixed. If you can tell the exact milestone, please update.

**Comment by smitpatel** [comment]
It was 2.1.0-preview1-final tag when it first appeared so milestone is correct here.
