### ISSUE TITLE
'must be reducible node' with multiple where conditions

### ISSUE THREAD

**Issue by ranouf** [aspnet/EntityFrameworkCore#9199]
Hi,

I m using the version EF Core 1.1.2 and I  have the bug:

        var query = _userFavoriteRepository.GetAll();

        if (user.Role == Role.SuperAdmin || user.Role == Role.Manager)
        {
            query = query
                .Where(uf => uf.Shop != null
                    ? uf.Shop.AllowedUserPermissions.Any(aup => aup.AllowedUserId == user.Id)
                    : true
                )
                .Where(uf => uf.ShopChain != null
                    ? uf.ShopChain.AllowedUserPermissions.Any(aup => aup.AllowedUserId == user.Id)
                    : true
                )
                .Where(uf => uf.ShopLocation != null
                    ? uf.ShopLocation.AllowedUserPermissions.Any(aup => aup.AllowedUserId == user.Id)
                    : true
                );
        }
        return query;
UserFavorite:
public Guid UserId { get; private set; }
public virtual User User { get; set; }

    public Guid? ShopId { get; private set; }
    public virtual Shop Shop { get; set; }

    public Guid? ShopChainId { get; private set; }
    public virtual ShopChain ShopChain { get; set; }

    public Guid? ShopLocationId { get; private set; }
    public virtual ShopLocation ShopLocation { get; set; }
AllowedUserPermissions
[ForeignKey("AllowedUser")]
public Guid AllowedUserId { get; private set; }
public virtual User AllowedUser { get; set; }

    public Guid? ShopId { get; private set; }
    public virtual Shop Shop { get; set; }

    public Guid? ShopChainId { get; private set; }
    public virtual ShopChain ShopChain { get; set; }

    public Guid? ShopLocationId { get; private set; }
    public virtual ShopLocation ShopLocation { get; set; }

    [ForeignKey("User")]
    public Guid? UserId { get; private set; }
    public virtual User User { get; set; }
Shop, ShopChain, ShopLocation:
[...]
public virtual ICollection AssignedOfferPermissions { get; } = new List();

[...]

Is there a solution to fix it?

**Comment by maumar** [comment]
This is fixed in 2.0
