### ISSUE TITLE
Remove reference to NETStandard.Library.NETFramework

### ISSUE THREAD

**Issue by mikeharder** [aspnet/EntityFrameworkCore#9207]
`build\common.props` currently contains a reference to `NETStandard.Library.NETFramework`, to improve the developer experience when using VS 15.2.  This reference should be removed as soon as possible without degrading the developer experience, to align with other aspnet repos.

**Comment by smitpatel** [comment]
I believe this can be done once everyone is using dev 15.3 RTM edition.
