### ISSUE TITLE
Unit test suite questions

### ISSUE THREAD

**Issue by carlosga** [aspnet/EntityFrameworkCore#9228]
Hello:

Two little questions about the unit test suite:

1. Shouldn't **FromSqlQueryTestBase<>.From_sql_queryable_simple_projection_composed** be using quoted identifiers on the "inline" sql query ? ( it looks to be the only one from FromSqlQueryTestBase<> not doing so )

```
SELECT *
FROM Products
WHERE Discontinued <> 1
AND ((UnitsInStock + UnitsOnOrder) < ReorderLevel)
```

2. Shouldn't **BuiltInDataTypesSqlServerTest.Can_query_using_any_mapped_data_type** be checking Text and NText field results ?

Thanks in advance.

**Comment by smitpatel** [comment]
@carlosga - Thanks for analysis. Those are indeed mistakes. They should be easy to fix.
1. Identifiers should be quoted like other tests in same class.
2. Results for missing properties should be verified like other properties.

**Comment by carlosga** [comment]
@smitpatel Thanks. I think **FromSqlSprocQueryTestBase<>.From_sql_queryable_stored_procedure_and_select** and **FromSqlSprocQueryTestBase<>.From_sql_queryable_select_and_stored_procedure** should be using quotes too on:

```
SELECT * FROM Products
```
