### ISSUE TITLE
dotnet ef dbcontext info tries to create the connection

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#9244]
Even though the connection never gets used. Possibly related to: #8350 and/or #6525 #8494

Found in: https://github.com/aspnet/Release/issues/193#issuecomment-316793613

**Comment by divega** [comment]
*EF Triage*: assigning to both @ajcvickers and @bricelam based on @bricelam's comment:

> Something about getting the the context services eagerly creates the connection, model, and context options. aspnet/EntityFramework#8350 might address this.

If we end up having to do something special to address this, we should discuss whether it is worth.

**Comment by ajcvickers** [comment]
Triage: consider moving this to backlog or moving enhancements that would fix it to current release.

**Comment by ajcvickers** [comment]
Moving this to the backlog with notes on related issues to look at it when working on them.

**Comment by ajcvickers** [comment]
Note: #8350 has been moved to the backlog. It should be re-triaged after this work is done.
