### ISSUE TITLE
Query: include doesn't get applied for some elements in a complex query with left joins and coalesce

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFrameworkCore#9256]
query:

```
from g1 in ctx.Gears.Include(g => g.Weapons)
join g2 in ctx.Gears.Include(g => g.Weapons)
on g1.LeaderNickname equals g2.Nickname into grouping
from g2 in grouping.DefaultIfEmpty()
select new { g1, g2, coalesce = g2 ?? g1 };
```

Weapons for g1 are not being included. However if the coalesce part is removed from the projection everything works fine

**Comment by triynko** [comment]
I'm seeing the same problem.  Include seems to just not work in all but the simplest scenarios.  In spite of calling "Include" on and entity's navigation property and in spite of returning that whole entity as part of the output type.... the include is just ignored and the navigation property is not hydrated.

**Comment by anpete** [comment]
@triynko Please list the version of EF Core you are using and the query that is not working, thanks,
