### ISSUE TITLE
AsyncQueryTestBase.Mixed_sync_async_query test still flaky?

### ISSUE THREAD

**Issue by azabluda** [aspnet/EntityFrameworkCore#9301]
While working on my EF.Core provider I ran into some weird issues with [`Mixed_sync_async_query`](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs#L98) test. After some experimenting it doesn't seem very trustworthy to me. For example it fails if I add `.ToList()` and run it against InMemory database
```c#
[ConditionalFact]
public virtual async Task Mixed_sync_async_query()
{
    using (var context = CreateContext())
    {
        var results
            = (await context.Customers
                .Select(c => new
                {
                    c.CustomerID,
                    Orders = context.Orders.Where(o => o.Customer.CustomerID == c.CustomerID)
                                    .ToList() /// <= HERE!
                }).ToListAsync())
                .Select(x => new
                {
                    Orders = x.Orders
                        .GroupJoin(new[] { "ALFKI" }, y => x.CustomerID, y => y, (h, id) => new
                        {
                            h.Customer
                        })
                })
                .ToList();

        Assert.Equal(546, results.SelectMany(r => r.Orders).ToList().Count);
    }
}
```
```
Assert.Equal() Failure
Expected: 546
Actual:   830
```

I went ahead a bit further and excluded the possible influence of asynchrony and also explicitly materialized the `Orders` collection in a separate step
```c#
[ConditionalFact]
public virtual void Mixed_sync_query()
{
    using (var context = CreateContext())
    {
        var list1
            = context.Customers
                .Select(c => new
                {
                    c.CustomerID,
                    Orders = context.Orders.Where(o => o.Customer.CustomerID == c.CustomerID)
                }).ToList();

        var list2 = list1.Select(x => new { x.CustomerID, Orders = x.Orders.ToList() }).ToList();

        var results = list2
            .Select(x => new
            {
                Orders = x.Orders
                    .GroupJoin(new[] { "ALFKI" }, y => x.CustomerID, y => y, (h, id) => new
                    {
                        h.Customer
                    })
            })
            .ToList();

        Assert.Equal(546, results.SelectMany(r => r.Orders).ToList().Count);
    }
}
```
and it still returns 830 rather than 546.

I have to confess I didn't check each and every line of data to prove that the test should expect 830 instead of 546, but also I can't imagine its original author doing such analysis. So for now my question is: **How can one explain different results returned with and without `.ToList()` on the indicated position?**

### Further technical details
EF Core version: 2.0.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by divega** [comment]
The fact that changing the test this way returns different results at first glance it looks like it could be the consequence of a bug somewhere.

**Comment by smitpatel** [comment]
This is a bug in product. The correct result is 830. We are caching the inner subquery incorrectly that in subsequent  runs of N+1 we are just reusing old results causing each customers to be associated with orders of first customer (ALFKI in this case which has 6 orders) hence 91 * 6 = 546 as answer.
