### ISSUE TITLE
Query: Output parameter in FromSql/ExecuteSqlCommand is always returns null

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#9309]
This issue is to track porting of #9277 for patch.

Impact: Using `FromSql` with out parameters on SqlServer will never return value of out parameter. All such scenarios are broken.
Work-around:None

**Comment by smitpatel** [comment]
Impact: Using FromSql with out parameters on SqlServer will never return value of out parameter. All such scenarios are broken.
Risk: Low. The fix was to clear the parameters after reader is disposed. Hence the code to clear parameter collection was moved to appropriate place and it is still part of pipeline in all scenarios.

**Comment by Eilon** [comment]
This patch bug is **approved** for the 2.0.x patch. Please send a PR to the `feature/2.0.1` branch and get it reviewed and merged. When we have the `rel/2.0.1` branches ready please port the commit to that branch.

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon
