### ISSUE TITLE
Remotion Linq: Upgrade package to RTM version

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#9311]
To resolve #4311 we have upgraded to Alpha version of Relinq. We can upgrade to another pre-release version before we ship our preview. Once we are done with next preview, we need to move to RTM version of package before final release of 2.1.0

cc: @MichaelKetting - I will give you heads up in advance when we need RTM.

**Comment by MichaelKetting** [comment]
@smitpatel Thanks :)

**Comment by MichaelKetting** [comment]
@smitpatel Just a quick heads up from my side :)
There's a small codechange for VB-support coming up (support for EmbeddedOperators in addition to Operators, https://www.re-motion.org/jira/browse/RMLNQ-115). If I get a couple of minutes till the end of the weekend, I'll be doing another alpha drop with this. This will only affect VB-compiled code.

**Comment by ajcvickers** [comment]
Note from triage: @smitpatel to work with @MichaelKetting to get the new package version in soon so we can preview with it.
