### ISSUE TITLE
Test: UdfDbFunctionSqlServerTests class should not use northwind database

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#9320]
`UdfDbFunctionSqlServerTests` is used for functional testing for UDFs. Any time we change something and want to add more test that should be the class to go to. But at present that class uses northwind database. 
We don't want to modify northwind database since anytime we modify the script, we need to drop database from machines where it is persisted. (CI & local dev boxes).
We should let this class use northwind model (or may be new model) but use own database which would get recreated every time so that adding more UDFs don't require manual dropping of database on various machines.

This should also remove currently defined UDFs in northwind.

**Comment by pmiddleton** [comment]
I will take this one, as I did create the problem.  It seemed like a good idea at the time :)

**Comment by AndriySvyryd** [comment]
Fixed in f2683c5240843b91702c5060d10d0b685c069e4e
