### ISSUE TITLE
ComplexNavigationsQueryTestBase.GroupJoin  tests throw in verification

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#9340]
GroupJoin_on_a_subquery_containing_another_GroupJoin_projecting_inner
GroupJoin_on_a_subquery_containing_another_GroupJoin_projecting_outer
GroupJoin_on_a_subquery_containing_another_GroupJoin_projecting_outer_with_client_method

	System.AggregateException : One or more errors occurred.
---- System.NullReferenceException : Object reference not set to an instance of an object.
	at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	at System.Threading.Tasks.Task.Wait()
	C:\enlistments\Universe\EntityFramework\src\EFCore.Specification.Tests\Query\QueryTestBase.cs(103,0): at Microsoft.EntityFrameworkCore.Query.QueryTestBase`1.AssertQuery[TItem1,TItem2](Func`3 query, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount)
	C:\enlistments\Universe\EntityFramework\src\EFCore.Specification.Tests\Query\ComplexNavigationsQueryTestBase.cs(2691,0): at Microsoft.EntityFrameworkCore.Query.ComplexNavigationsQueryTestBase`1.GroupJoin_on_a_subquery_containing_another_GroupJoin_projecting_outer_with_client_method()
	----- Inner Stack Trace -----
	at lambda_method(Closure , <>f__AnonymousType125`2 , Level2 )
	at System.Linq.Enumerable.<SelectManyIterator>d__22`3.MoveNext()
	at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	C:\enlistments\Universe\EntityFramework\src\EFCore.Specification.Tests\TestUtilities\QueryAsserter.cs(386,0): at Microsoft.EntityFrameworkCore.TestUtilities.QueryAsserter`1.<AssertQuery>d__20`2.MoveNext()

**Comment by maumar** [comment]
fixed in 25637c2e377dd467cb3bef10b6295ccd70587a90
