### ISSUE TITLE
Design: Make OperationBase.Execute() protected

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#9388]
[These methods](https://github.com/aspnet/EntityFramework/blob/rel/2.0.0/src/EFCore.Design/Design/OperationExecutor.cs#L372-L398) should be protected. We didn't get to it in time for 2.0.0, but we should do it in 3.0.0.

**Comment by ajcvickers** [comment]
Re-opening to ensure breaking change is announced.

**Comment by bricelam** [comment]
I wouldn't announce this. Nobody was calling it.

**Comment by ajcvickers** [comment]
@bricelam I was thinking maybe we could have one post where we announce the changes that a technically breaking, but we don't think there will be any real customer or provider impact. Thoughts @divega

**Comment by divega** [comment]
Yes, one post for minor breaking changes sounds good. That said I don’t feel strongly about including this one if we really think it has zero impact.
