### ISSUE TITLE
EF Core 2.1 Roadmap Update

### ISSUE THREAD

**Issue by steji113** [aspnet/EntityFrameworkCore#9418]
# Roadmap Update
I know EF Core 2.0 was just released, but it might be helpful for contributors and users alike to have an idea of what the roadmap for EF Core 2.1 is looking like. Is this something that can be updated [here](https://github.com/aspnet/EntityFramework/wiki/Roadmap)? Also, it would be an immense help to developers if these feature comparison doc pages could be updated as well [here](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/features).

Thanks!

**Comment by hiyelbaz** [comment]
+1 I think feature comparison should have a higher priority.

**Comment by bricelam** [comment]
To see our current ambitions for 2.1, you can always look at [the issues in the 2.1.0 milestone with the type-enhancement label](https://github.com/aspnet/EntityFramework/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.1.0+label%3Atype-enhancement).

**Comment by MarcoLoetscher** [comment]
Can you please add the issue number to the following paragraphs:
[Critical O/RM features](https://github.com/aspnet/EntityFramework/wiki/Roadmap#critical-orm-features) and [High priority features](https://github.com/aspnet/EntityFramework/wiki/Roadmap#high-priority-features) according to the paragraph [EF Core 2.0 (under development)](https://github.com/aspnet/EntityFramework/wiki/Roadmap#ef-core-20-under-development)?
Thanks.

**Comment by bricelam** [comment]
Added a few. The ones related to some points but didn't cover the whole thing:

* RevEng: Support Views (#1679)
* Allow for declaring aggregates in the model (#1985)
* Relational: TPT inheritance mapping pattern (#2266)
* Relational: TPC inheritance mapping pattern (#3170)
* Turn-key Disconnected Entities Solution (#5536)
* View types support (#9290)

**Comment by steji113** [comment]
Thanks for the updates!

**Comment by divega** [comment]
I have updated both the [roadmap](https://github.com/aspnet/EntityFramework/wiki/Roadmap) and the [feature comparison page](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/features).

@bricelam I would like to understand where the list at https://github.com/aspnet/EntityFrameworkCore/issues/9418#issuecomment-322848857 fits :smile:

**Comment by steji113** [comment]
Thanks!

**Comment by marchy** [comment]
Looking over the roadmap, you have Lazy Loading listed as Critical while TPT as High. I think these should be inversed, since TPT prevents businesses from adopting EF Core while Lazy Loading is simply an optimization that can be done at the code level (ie: either fetch with proper includes upfront or simply query twice). In other words it's not a BLOCKER, while TPT/TPC is.

**Comment by weitzhandler** [comment]
I totally second what @marchy said.
TPT is a must in LoB apps, lazy-loading is just another feature (IMHO an evil one).

**Comment by weitzhandler** [comment]
I totally second what @marchy said.
TPT is a must in LoB apps, lazy-loading is just another feature (IMHO an evil one).
But, from [here](https://github.com/aspnet/EntityFrameworkCore/wiki/Roadmap) I'm not even sure it's gonna be in 2.1. It's not even on the stretch list (any comment @bricelam?), and so is [it](https://github.com/aspnet/EntityFrameworkCore/issues/2266) under the Backlog milestone.

@divega Thanks for updating the roadmap, would be nice if you can point out *2.1 (future)* etc. or something similar in the [list](https://docs.microsoft.com/en-us/ef/efcore-and-ef6/features).

**Comment by divega** [comment]
@weitzhandler all the empty boxes on the EF Core column would be marked as _future_. I am reluctant to try to assign things in that table to a more specific milestone because all future plans can change. In the roadmap page we are very explicit about that as a caveat.

**Comment by weitzhandler** [comment]
First of all I'm glad to hear you guys have the desire to have the whole table implemented...
And secondly, I'd like to express my appreciation to your intense dedication and responsiveness!
Thank you @divega

**Comment by nefcanto** [comment]
Is there a plan for when interceptors come into EF Core? Do they come back at all? I'm about to [use reflection as proposed in this link](https://blogs.msdn.microsoft.com/dotnet/2016/09/29/implementing-seeding-custom-conventions-and-interceptors-in-ef-core-1-0/) for the sake of interception, but that's really not lightweight.

**Comment by ajcvickers** [comment]
@nefcanto EF Core integrates with DiagnosticSource/DisgnosticListener which can be used for many of the things that EF6 interceptors were used for--see the CoreEventId and RelationalEventId classes for events currently generated.

**Comment by nefcanto** [comment]
Can you share a link with me on how to do it? I couldn't find one.

**Comment by ajcvickers** [comment]
@nefcanto There is an issue tracking docs for this: https://github.com/aspnet/EntityFramework.Docs/issues/583. Until that is completed, there is an example here: https://github.com/aspnet/EntityFrameworkCore/issues/626#issuecomment-348574462
