### ISSUE TITLE
Improve Tools packages descriptions

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#9439]
See https://stackoverflow.com/questions/45703613/whats-the-difference-between-efcore-tools-and-efcore-tools-dotnet

**Comment by ajcvickers** [comment]
@divega Thoughts?

**Comment by divega** [comment]
Here is a proposal based on the current description and the stackoverflow thread:

> Entity Framework Core Tools for the Package Manager Console in Visual Studio. Includes Scaffold-DbContext, Add-Migration, Script-Migrations, and Update-Database.

> Entity Framework Core Tools for the “dotnet” Command Line Interface. Includes the “dotnet ef migrations”, “dotnet ef dbcontext”, and “dotnet ef database” commands.

**Comment by ErikEJ** [comment]
@divega Accept PR for this?

**Comment by smitpatel** [comment]
@ErikEJ - Certainly. Thanks.

**Comment by bricelam** [comment]
@ErikEJ Always. `up-for-grabs` just means [tasks specifically for new contributors](http://up-for-grabs.net). Every issue is technically up for grabs by the community. 😉
