### ISSUE TITLE
Sample EF Core provider for Oracle databases

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#9442]
We will build a sample EF Core 2 provider for Oracle databases. 

Note that we don't plan to turn this sample into a product (and therefore we are likely not going to distribute this code in a NuGet package) but with the exercise we want to:

1. Make sure that the EF Core provider APIs are adequate and sufficient to target Oracle databases
2. Help bootstrap any efforts to build an actual production provider for Oracle

Initially the sample will be based on an existing Windows only / .NET Framework version of the Oracle ADO.NET provider, so it won’t function with .NET Core.

**Comment by rjperes** [comment]
"it won’t function with .NET Core"... This is a shame, IMO!

**Comment by ricsmania** [comment]
@rjperes there isn't an official Oracle .Net Core driver, so there really isn't much choice right now. It's supposed to be released until the end of 2017 though, so I guess that by then it will be simple to port. There are third party drivers, but from my experience they aren't as good as the official one.

**Comment by souchprod** [comment]
Hi @divega, that's a great initiative ! I made a provider for a non supported database (Firebird) and used to participate (a bit) in the MySQL provider too. I was searching for a .Net Core provider for oracle, that's a shame (for oracle) that nothing exist... That's a huge company, they could put 3 developers on it during a month but no, they just ignore it, ignoring the evolution... 

Will this sample evolve on GitHub and your team accept PR ?

**Comment by anpete** [comment]
The bulk of this is now in place - can be found under the new "samples" folder in the repo.

**Comment by ChaosEngine** [comment]
Just for reference, http://www.oracle.com/technetwork/topics/dotnet/tech-info/odpnet-dotnet-core-sod-3628981.pdf

**Comment by jpiquot** [comment]
This is an outdated roadmap from Oracle and they don't seem to want to give a new release time.

**Comment by ralmsdeveloper** [comment]
More grace the work of the wonderful team of EF Core, they made available a provider compatible with .Net Framework.

**Comment by Iveky** [comment]
ralm, can you post a link with more info? thx.

**Comment by ralmsdeveloper** [comment]
Yes @Iveky,

[https://github.com/aspnet/EntityFrameworkCore/tree/dev/samples/OracleProvider](https://github.com/aspnet/EntityFrameworkCore/tree/dev/samples/OracleProvider)

[https://github.com/aspnet/EntityFrameworkCore/wiki/roadmap](https://github.com/aspnet/EntityFrameworkCore/wiki/roadmap)

**Comment by jpiquot** [comment]
You can only target .NET and not .NET Core:

> ...Only works on full .NET - utilizes official Oracle managed ADO provider...

**Comment by ralmsdeveloper** [comment]
Exactly, this is because the oracle provider is not compatible with .NET Core!

**Comment by dbones** [comment]
Oracle have a Beta Data Provider located here:
http://www.oracle.com/technetwork/topics/dotnet/downloads/odpnetcorebeta-4077982.html

**Comment by ralmsdeveloper** [comment]
I did some testing, there is a small BUG when using **Parameters.Add**.

but already a big step!

**Comment by ajcvickers** [comment]
Filed #11024 to track updating for .NET Core.
