### ISSUE TITLE
Time to update "Getting and Building the Code" :-) 

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#9518]
https://github.com/aspnet/EntityFrameworkCore/wiki/Getting-and-Building-the-Code 

(No PRs for wiki pages, sadly)

**Comment by ajcvickers** [comment]
@bricelam @smitpatel @AndriySvyryd @maumar @anpete Made a stab at updating this--all feedback welcome.

**Comment by ErikEJ** [comment]
Looks good and useful!
