### ISSUE TITLE
Client vs. Server evaluation - is version 2 produces sub-optimal SQL compared to version 1/2.0.0-preview1-final 

### ISSUE THREAD

**Issue by JonPSmith** [aspnet/EntityFrameworkCore#9519]
I have a Client vs. Server query that uses `string.Join` to combine some of the data as it is returned. Based on ver1 I though this was a 'safe' Client vs. Server  query because no `QueryClientEvaluationWarning` was logged. What I swapped to EF Core 2.0.0 then a `QueryClientEvaluationWarning` IS logged for the same query.

## UPDATE
The problem is not that a `QueryClientEvaluationWarning` is logged, but that the SQL code produces is sub-optimal - see [new comment](https://github.com/aspnet/EntityFrameworkCore/issues/9519#issuecomment-327840211) with the SQL produced by EF Core 2.0.0 for the Client vs. Server evaluated query shown in this comment.

----

The logging output (LogLevel.Information or above) from EF Core 2.0.0 is as follows
```
The LINQ expression 'join Author y.Author in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[DataLayer.EfClasses.Author]) on Property([y], "AuthorId") equals Property([y.Author], "AuthorId")' could not be translated and will be evaluated locally.
Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "x"."Title", "x"."BookId"
FROM "Books" AS "x"
Executed DbCommand (0ms) [Parameters=[@_outer_BookId='?'], CommandType='Text', CommandTimeout='30']
SELECT "b"."BookId", "b"."AuthorId", "b"."Order"
FROM "BookAuthor" AS "b"
WHERE @_outer_BookId = "b"."BookId"
Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "y.Author"."AuthorId", "y.Author"."Name"
FROM "Authors" AS "y.Author"
Executed DbCommand (0ms) [Parameters=[@_outer_BookId='?'], CommandType='Text', CommandTimeout='30']
SELECT "b"."BookId", "b"."AuthorId", "b"."Order"
FROM "BookAuthor" AS "b"
WHERE @_outer_BookId = "b"."BookId"
Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "y.Author"."AuthorId", "y.Author"."Name"
FROM "Authors" AS "y.Author"
```

### Steps to reproduce

I have a `Book` entity class with a Many-to-Many relationship to an `Author` entity class, via a BookAuthor entity class linking table. I am simply trying to get a comma separated list of all the authors of a book.

I have a `Book` entity class with a collection of `Review` entity classes that contain `NumVotes`. I want to calculate the average number of votes. A `Book` can have zero to many `Reviews`.

My entity classes are:
```c#
public class Book                                   
{
    public int BookId { get; set; } 
    public string Title { get; set; }
    public string Description { get; set; }
    public DateTime PublishedOn { get; set; }
    public string Publisher { get; set; }
    public decimal Price { get; set; }
    public string ImageUrl { get; set; }

    //----------------------------------------------
    //relationships

    public PriceOffer Promotion { get; set; }       
    public ICollection<Review> Reviews { get; set; }
    public ICollection<BookAuthor> AuthorsLink { get; set; }                   
}
```
```c#
public class Author                   
{
    public int AuthorId { get; set; }
    public string Name { get; set; }

    //------------------------------
    //Relationships

    public ICollection<BookAuthor> 
        BooksLink { get; set; }       
}
```
Linking Table is 
```c#
public class BookAuthor               
{
    public int BookId { get; set; }   
    public int AuthorId { get; set; } 
    public byte Order { get; set; }   

    //-----------------------------
    //Relationships

    public Book Book { get; set; }    
    public Author Author { get; set; }
}
```

The test code is shown below. EF Core 2.0.0 logs the `QueryClientEvaluationWarning` shown at the top of this comment. If run on EF Core 1.x or 2.0.0-preview1-final then a `QueryClientEvaluationWarning` is NOT logged.
Note: The method `TwoBooksWithAuthors` creates two books, the first with one Author, the second with two Authors.
```c#
private class Dto
{
    public string Title { get; set; }
    public string AuthorsString { get; set; }
}

[Fact]
public void AuthorsStringTwoBooks()
{
    //SETUP
    var options = SqliteInMemory.CreateOptions<EfCoreContext>();

    using (var context = new EfCoreContext(options))
    {
        context.Database.EnsureCreated();

        context.AddRange(SeedData.TwoBooksWithAuthors());
        context.SaveChanges();
        var logs = context.SetupLogging();

        //VERIFY
        var result = context.Books.Select(x => new Dto
        {
            Title = x.Title,
            AuthorsString = string.Join(", ", x.AuthorsLink.Select(y => y.Author.Name))
        }).ToList();

        //VERIFY
        result.First().AuthorsString.ShouldEqual("Author01");
        result.Last().AuthorsString.ShouldEqual("Author02a, Author02b");
        foreach (var log in logs)
        {
            _output.WriteLine(log);
        }
    }
}
```

If EF Core 2.0.0 is logging a `QueryClientEvaluationWarning` when it is not needed, then that will cause problems, especially if the developer has enable the throwing of an exception on a `QueryClientEvaluationWarning`

### Further information

The log output from EF Core 2.0.0-preview1-final  (i.e. the one that works) is as follows
```
Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "x"."Title", "x"."BookId"
FROM "Books" AS "x"
Executed DbCommand (0ms) [Parameters=[@_outer_BookId='?'], CommandType='Text', CommandTimeout='30']
SELECT "y.Author"."Name"
FROM "BookAuthor" AS "y"
INNER JOIN "Authors" AS "y.Author" ON "y"."AuthorId" = "y.Author"."AuthorId"
WHERE @_outer_BookId = "y"."BookId"
Executed DbCommand (0ms) [Parameters=[@_outer_BookId='?'], CommandType='Text', CommandTimeout='30']
SELECT "y.Author"."Name"
FROM "BookAuthor" AS "y"
INNER JOIN "Authors" AS "y.Author" ON "y"."AuthorId" = "y.Author"."AuthorId"
WHERE @_outer_BookId = "y"."BookId"
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.Sqlite (also goes wrong on SqlServer
Operating system: Windows 10
IDE: VS2017 15.3

**Comment by smitpatel** [comment]
We have worsened the query here. It is N+1 query with N queries have translatable join but now we are not translating it anymore. Further we are not doing outer parameter on 2nd level navigation.
This could be related to our N+1 optimizations.

**Comment by JonPSmith** [comment]
I have some more (useful?) information of this Client vs. Server Evaluation. I am now working on performance tuning and started to look at the SQL the expression shown in my first comment produces very significantly poorer code than version 1.1.0 and 2.0.0-preview1-final.

The SQL that EF Core version 2.0.0 produces is as follows:  
Note the second SQL command which loads ALL authors rather that the Authors defined by the BookAuthor linking table, and is called for EVERY book that needs the AuthorsString.
```SQL
SELECT [b0].[BookId], [b0].[AuthorId], [b0].[Order]
FROM [BookAuthor] AS [b0]
WHERE @_outer_BookId = [b0].[BookId]
```
```SQL
SELECT [q.Author].[AuthorId], [q.Author].[Name]
FROM [Authors] AS [q.Author]
```

The correct SQL code, which version 1.1.0 and 2.0.0-preview1-final produce, is as follows
```SQL
SELECT [q.Author].[Name] 
FROM [BookAuthor] AS [q] 
INNER JOIN [Authors] AS [q.Author] 
ON [q].[AuthorId] = [q.Author].[AuthorId] WHERE @_outer_BookId = [q].[BookId] 
ORDER BY [q].[Order]
```

Clearly the 2.0.0 the problem is not that it logs a `QueryClientEvaluationWarning`, but that it produces very inefficient code.

**Comment by maumar** [comment]
@JonPSmith I'm trying to reproduce the issue but I'm getting the expected sql:

```sql
SELECT [y.Author].[Name]
FROM [BookAuthors] AS [y]
INNER JOIN [Authors] AS [y.Author] ON [y].[AuthorId] = [y.Author].[AuthorId]
WHERE @_outer_BookId = [y].[BookId]
```

I'm not sure if we fixed the issue as a by-product of another fix or if I'm doing something wrong. Can you provide full code listing you were using to reproduce it?

**Comment by maumar** [comment]
I verified that the repro I used was producing a bad sql for 2.0.0, but it's producing a correct one for the current bits, closing as fixed
