### ISSUE TITLE
Relational: UDF calls are generated unquoted

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFrameworkCore#9558]
When we generate a call to a user defined database function, the function name is unquoted. Should it be?
```sql
SELECT [dbo].EmployeeOrderCount(@__employeeId_0)
FROM [Employees] AS [e]
```

**Comment by pmiddleton** [comment]
You can create UDFs with keywords and spaces in their names so we should deal with it.

Of course there is a slight problem - Sql Server does not treat built-in functions the same as UDFs.  Built in functions cannot be escaped, unless I as missing some esoteric syntax, and doing so will cause a syntax error.

This means we need some way to differentiate built-in and UDF functions.  We are going to either have to ask for this information in the db function fluent api, or keep a list of all built-in functions.  Keeping a list up to date will be nigh impossible so I'm leaning towards modifying the fluent api.

Anyone have any other ideas?

@bricelam - From my quick test it appears Sqlite does not have this same issue.  Can you confirm.

Delimiting the function name in relational may break providers for other databases, depending on how their syntax works.  Should we make this a Sql Server only change, or make the change in relational and let each provider override if needed?

**Comment by bricelam** [comment]
> Sqlite does not have this same issue

Not as far as I can tell. Heck, it lets you redefine the built-in functions so I'd be surprised if they were treated any different.
