### ISSUE TITLE
All after Take generates wrong SQL and works incorrect

### ISSUE THREAD

**Issue by rasuldev** [aspnet/EntityFrameworkCore#9559]
The command
`context.Transactions.Take(10).All(t => t.UserId == "user")`
generates the following wrong SQL:
```SQL
SELECT CASE
    WHEN NOT EXISTS (
        SELECT 1
        FROM "Transactions" AS "t"
        WHERE "t"."UserId" <> @__user_Id_1
        LIMIT @__p_0)
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END
```
so it returns wrong answer. But if we run
`context.Transactions.Take(10).ToList().All(t => t.UserId ==  "user")`
all is fine.

### Further technical details
EF Core version: 1.1.2 
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 1.1.2
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by smitpatel** [comment]
We should apply predicate after pushing down SelectExpression for correct results.
