### ISSUE TITLE
InvalidOperationException add entity with database generated column

### ISSUE THREAD

**Issue by voronov-maxim** [aspnet/EntityFrameworkCore#9571]
Add graph entities, when value in entity equals database generated throw InvalidOperationException.
In Entity Framework Core 1.1 no exception.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
'The property 'Id' on entity type 'Table' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly or ensure that the database is configured to generate values for this property.'

Stack trace:
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean forceStateWhenUnknownKey)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.AcceptChanges()
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.AcceptAllChanges(IEnumerable`1 changedEntries)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
```

### Steps to reproduce
```c#
public sealed class Table
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
}

public sealed class OrderContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=.\sqlexpress;Initial Catalog=OdataToEntity;Trusted_Connection=Yes;");
        base.OnConfiguring(optionsBuilder);
    }

    public DbSet<Table> Tables { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        using (var context = new OrderContext())
        {
            var table = new Table() { Id = 1 };
            EntityEntry<Table> entity = context.Tables.Add(table);
            entity.GetInfrastructure().MarkAsTemporary(entity.Metadata.FindProperty("Id"), true);
            context.SaveChanges();
        }
    }
}
```

### Further technical details
EF Core version: 2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017 version 15.3.2

**Comment by voronov-maxim** [comment]
Valid commit e44dcdebef05eaea2a877db4f9576b5834a59488

**Comment by ajcvickers** [comment]
Note for triage: this happens when the value of the temporary value is the same as the value that is generated by the database. Possibly related to #9552?

**Comment by voronov-maxim** [comment]
Not related cause column ID is not generated by database

**Comment by ajcvickers** [comment]
@voronov-maxim Thanks for reporting this bug. I wanted to point out a couple of things relating to the code in the repro:
* Using temporary values from the same key-space as values generated by the store can cause issues. For example, if the store might generate values 1, 2, 3, and there are three entities tracked which already have temporary key values 1, 2, and 3, then there is no guarantee that EF won't try to save the entity with key value 3 first, which the store may then assign value 1, which will then result in an identity clash in EF. Instead, either use EF's automatically generated temporary values, or assign values that will not overlap--for example, negative numbers are common.
* This code:
```C#
EntityEntry<Table> entity = context.Tables.Add(table);
entity.GetInfrastructure().MarkAsTemporary(entity.Metadata.FindProperty("Id"), true);
```
makes use if internal API surface which may be changed without warning in future versions of EF. Instead, use the public surface, which is easier anyway:
```C#
EntityEntry<Table> entry = context.Tables.Add(table);
entry.Property(e => e.Id).IsTemporary = true;
````

**Comment by ajcvickers** [comment]
Hi @voronov-maxim. We are gathering information on the use of EF Core pre-release builds. You reported this issue shortly after the release of 2.0.0 RTM. It would be really helpful if you could let us know:

- Did you consider testing your code against the pre-release builds?
- Was there anything blocking you from using pre-release builds?
- What do you think could make it easier for you to use pre-release builds in the future?

Thanks in advance for any feedback. Hopefully this will help us to increase the value of pre-release builds going forward.

**Comment by voronov-maxim** [comment]
Hi @ajcvickers. I can test pre-release builds. Make it easier if your upload EF Core to nuget.
