### ISSUE TITLE
Removing a dependent with an identifying one-to-many throws

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#9605]
Add this to `ChangeTrackerTest`:

```C#
[Fact]
public void Can_remove_dependent_identifying_one_to_many()
{
    using (var context = new EarlyLearningCenter())
    {
        var product = new Product();

        var order = new Order();

        var orderDetails = new OrderDetails { Order = order, Product = product };

        context.Add(orderDetails);

        order.OrderDetails.Remove(orderDetails);

        context.ChangeTracker.DetectChanges();
    }
}
```
>	System.ArgumentNullException : Value cannot be null.
Parameter name: key
	at System.Collections.Generic.Dictionary`2.Remove(TKey key)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\IdentityMap.cs(312,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Remove(TKey key, InternalEntityEntry entry)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\IdentityMap.cs(297,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Remove(InternalEntityEntry entry)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\StateManager.cs(459,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StopTracking(InternalEntityEntry entry)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs(232,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\InternalEntityEntry.cs(79,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean forceStateWhenUnknownKey)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\NavigationFixer.cs(824,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ConditionallyNullForeignKeyProperties(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\NavigationFixer.cs(223,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\InternalEntityEntryNotifier.cs(156,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\ChangeDetector.cs(204,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\ChangeDetector.cs(144,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\Internal\ChangeDetector.cs(112,0): at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
	C:\enlistments\Universe\EntityFramework\src\EFCore\ChangeTracking\ChangeTracker.cs(163,0): at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
	C:\enlistments\Universe\EntityFramework\test\EFCore.Tests\ChangeTracking\ChangeTrackerTest.cs(1221,0): at Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTrackerTest.Can_remove_dependent_identifying_one_to_many()

**Comment by AndriySvyryd** [comment]
A workaround would be to mark the dependent as deleted, but we should still consider this for a patch as it degrades many-to-many experience significantly.

**Comment by ajcvickers** [comment]
Marking for re-triage as with more details it may not meet the patch bar:
* It only happens for Added entities that are then removed, becoming detached. Does not repro for entities that are Unchanged and will be Deleted
* It only happens for composite keys

**Comment by ajcvickers** [comment]
@AndriySvyryd Triage question--we are leaning towards moving this to 2.1. Can you be more specific about the many-to-many scenarios that are blocked? Are they also only about entities in the Added state that are then removed from the graph?

**Comment by AndriySvyryd** [comment]
Yes, only added entities are affected.
