### ISSUE TITLE
In-memory database not persisted across service providers

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#9613]
Each named in-memory database is rooted in the internal service provider. This allows it to persist across multiple uses of a context without being rooted in the app-domain, which could cause leaks. Most of the time this works as expected, but sometimes an options change can cause EF to build a new internal service provider. This causes the two contexts to not be sharing the in-memory database even when it is likely expected they will.

For example:
```C#
using (var context = new FooContext(
    new DbContextOptionsBuilder()
        .UseInMemoryDatabase(nameof(FooContext))
        .Options))
{
    context.Add(new Foo());
    context.SaveChanges();
}

using (var context = new FooContext(
    new DbContextOptionsBuilder()
        .UseInMemoryDatabase(nameof(FooContext))
        .EnableSensitiveDataLogging()
        .Options))
{
    // Fails because one context has EnableSensitiveDataLogging while the other doesn't
    Debug.Assert(context.Foos.Count() == 1);
}
```

**Comment by ajcvickers** [comment]
Note that this can happen if one DbContext is resolved from an IServiceProvider after being registered with AddDbContext, and the other DbContext instance is created with `new'. One workaround is to always resolve the context instance from the service provider. For example:
```C#
using (var scope = serviceProvider.CreateScope())
{
    var db = scope.ServiceProvider.GetService<MyContext>();
}
```
In the case of a web app, the IServiceProvider can be obtained by calling `IWebHost.Services`.

**Comment by ajcvickers** [comment]
@radenkozec Please file a new issue including a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by radenkozec** [comment]
@ajcvickers I manages to solve the issues by following this tutorial http://www.dotnetcurry.com/aspnet-core/1420/integration-testing-aspnet-core
It seams that my issue was related to wrong dependency injection configuration.

**Comment by radenkozec** [comment]
@ajcvickers I have a big problems with dependency injection and InMemory from Integration tests.
I tried to use same instance of InMemoryDatabaseRoot with no success.
What is funny this all was piece of cake in .NET Core 1. From version 2 things are much harder.
 ```
 public class TestStartup : Startup
    {
        public TestStartup(IConfiguration configuration) : base(configuration)
        {
        }
        public override void SetUpDataBase(IServiceCollection services)
        {
            var inMemoryDatabaseRoot = new InMemoryDatabaseRoot();
            services.AddSingleton<InMemoryDatabaseRoot, InMemoryDatabaseRoot>(p => inMemoryDatabaseRoot);
            services
               .AddEntityFrameworkInMemoryDatabase()
               .AddDbContext<ApplicationDbContext>(options => {
                   options.UseInMemoryDatabase("TestDatabase", inMemoryDatabaseRoot,null);

               })
```

Then later in my Startup.cs where I need to resolve ApplicationRepository from ServiceProvider I tried it initialize myself:

```
public class Startup
    {
 public void ConfigureServices(IServiceCollection services)
        {
 SetUpDataBase(services);
/// some code before this
 var inMemoryDatabaseRoot = services.BuildServiceProvider().GetService<InMemoryDatabaseRoot>();
 var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
  optionsBuilder.UseInMemoryDatabase("TestDatabase", inMemoryDatabaseRoot,null);
var appRepository = new ApplicationRepository(new ApplicationDbContext(optionsBuilder.Options));
```
This does not use same instance of InMemoryDatabase where I inserted data in IntegrationTest.
I am using .NET Core 2.1 RTM.
Can you please explain how to persist InMemoryDatabase from Integration Tests to app?

**Comment by ajcvickers** [comment]
Note for others finding this issue. There are two ways to resolve this:
* Either pass a `InMemoryDatabaseRoot` object to `UseInMemoryDatabase`--see below
* Or ensure the context instance is created the same way in each place so that the same internal service provider is used everywhere

Example use of `InMemoryDatabaseRoot`. First, create an instance of this object with an appropriate location and scope for managing the lifetime of the database. Often, this just means having a static somewhere:
```C#
public static readonly InMemoryDatabaseRoot InMemoryDatabaseRoot = new InMemoryDatabaseRoot();
```
Then pass this instance to `UseInMemoryDatabase`:
```C#
    optionsBuilder.UseInMemoryDatabase("MyDb", InMemoryDatabaseRoot);
```

**Comment by issafram** [comment]
@ajcvickers Have you tested this with EntityFrameworkCore 2.2.0?  I tried your example and it isn't working.
I can seed data below, but afterwards the User is not found in the database.
Note that this works when using SQL Server.
Let me know if you see anything that looks incorrect.

```
        private static readonly InMemoryDatabaseRoot InMemoryDatabaseRoot = new InMemoryDatabaseRoot();

        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
            services.AddDbContext<ApplicationDbContext>(
                options => 
                options.UseInMemoryDatabase("MyInMemoryDatabase", InMemoryDatabaseRoot));
                //options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
            services.AddDefaultIdentity<IdentityUser>()
                .AddDefaultUI(UIFramework.Bootstrap4)
                .AddEntityFrameworkStores<ApplicationDbContext>();

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }
```

```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseAuthentication();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            SampleData.Initialize(app);
        }
```

```
    public class SampleData
    {
        public static void Initialize(IApplicationBuilder app)
        {
            using (var serviceScope = app.ApplicationServices.CreateScope())
            //using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
            //using (var context = serviceScope.ServiceProvider.GetService<ApplicationDbContext>())
            {
                //var context = new ApplicationDbContext(options);
                var context = serviceScope.ServiceProvider.GetService<ApplicationDbContext>();
                context.Database.EnsureCreated();

                var user = new IdentityUser
                {
                    Email = "test@test.com",
                    NormalizedEmail = "TEST@TEST.COM",
                    UserName = "test@test.com",
                    NormalizedUserName = "TEST@TEST.com",
                    PhoneNumber = "+2481234444",
                    EmailConfirmed = true,
                    PhoneNumberConfirmed = true,
                    SecurityStamp = Guid.NewGuid().ToString("D")
                };

                if (!context.Users.Any(u => u.UserName == user.UserName))
                {
                    var password = new PasswordHasher<IdentityUser>();
                    var hashed = password.HashPassword(user, "test");
                    user.PasswordHash = hashed;

                    var userStore = new UserStore<IdentityUser>(context);
                    userStore.CreateAsync(user).Wait();
                }

                context.SaveChangesAsync();
            }
        }

    }
```

**Comment by ajcvickers** [comment]
@radenkozec It should work. It might be because you're calling an async method (SaveChangesAsync) in a fire-and-forget way. Use SaveChanges instead, or make the method async and await.

If it still doesn't work, then please open a new issue and include a project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by akalcik** [comment]
@ajcvickers Can you be more detailed about 

> Or ensure the context instance is created the same way in each place so that the same internal service provider is used everywhere

I have the same issue as here with .NET Core 2.2 and EntityFrameworkCore 2.2.0. 

This is my test factory...

```csharp
    public class ToDoAppApiFactory<T> : WebApplicationFactory<T> where T : class
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureServices(services =>
            {
                ConfigureServices(services);
                ServiceProvider = services.BuildServiceProvider();
            });
        }

        public ServiceProvider ServiceProvider { get; private set; }

        protected void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ToDoAppDbContext>(options =>
            {
                ServiceProvider serviceProvider = new ServiceCollection()
                    .AddEntityFrameworkInMemoryDatabase()
                    .BuildServiceProvider();

                options.UseInMemoryDatabase("ToDoAppDb");
                options.UseInternalServiceProvider(serviceProvider);
            });
        }
    }
```
...and this is my method to configure services in ```Startup``` class

```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddDbContext<ToDoAppDbContext>
                (options => options.UseSqlServer(Configuration.GetConnectionString("ToDoAppDbConnectionString")));

            // Register the Swagger generator, defining 1 or more Swagger documents
            services.AddSwaggerGen(swaggerGenOptions =>
            {
                swaggerGenOptions.SwaggerDoc(VersionName, new Info {Title = ApiName, Version = VersionName});

                // Set the comments path for the Swagger JSON and UI
                List<string> xmlFiles = Directory
                    .GetFiles(AppContext.BaseDirectory, "*.xml", SearchOption.TopDirectoryOnly).ToList();
                xmlFiles.ForEach(file => swaggerGenOptions.IncludeXmlComments(file));
            });

            services.AddAutoMapper(Api.Configuration.AutoMapper.Configure);
        }

```
As you can see I'm using the same configuration and still have difference instances in memory database.  

I was able to fix it with ```InMemoryDatabaseRoot``` as you can see below but still wondering why is this necessary.

```csharp
    public class ToDoAppApiFactory<T> : WebApplicationFactory<T> where T : class
    {
        private static readonly InMemoryDatabaseRoot InMemoryDatabaseRoot = new InMemoryDatabaseRoot();

        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureServices(services =>
            {
                ConfigureServices(services);
                ServiceProvider = services.BuildServiceProvider();
            });
        }

        public ServiceProvider ServiceProvider { get; private set; }

        protected void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ToDoAppDbContext>(options =>
            {
                ServiceProvider serviceProvider = new ServiceCollection()
                    .AddEntityFrameworkInMemoryDatabase()
                    .BuildServiceProvider();

                options.UseInMemoryDatabase("ToDoAppDb", InMemoryDatabaseRoot);
                options.UseInternalServiceProvider(serviceProvider);
            });
        }
    }
```

**Comment by ajcvickers** [comment]
@akalcik The configuration for the in-memory database builds and uses a new internal service provider for every context instance. This is where the in-memory database is rooted by default, so using a new one every context instance results in a new in-memory database for every instance.

**Comment by akalcik** [comment]
@ajcvickers Really surprising for me as this isn't mentioned anywhere in the documentation. So the code I provided in my example isn't correct without ```InMemoryDatabaseRoot```, right? Shouldn't be this updated anywhere in the documentation? https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory

**Comment by ajcvickers** [comment]
@akalcik Filed https://github.com/aspnet/EntityFramework.Docs/issues/1308

**Comment by ykysel** [comment]
@ajcvickers, do you know what could be wrong here?

My Factory definition:
`public class WebApiTestFactory: WebApplicationFactory<TestsStartup>
    {
        private static readonly InMemoryDatabaseRoot InMemoryDatabaseRoot = new InMemoryDatabaseRoot();

        protected override IWebHostBuilder CreateWebHostBuilder()
        {
            return WebHost.CreateDefaultBuilder()
                .UseConfiguration(GetConfiguration())
                .UseStartup<TestsStartup>();
        }

        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.UseContentRoot(".");
            builder.UseTestServer();

            builder.ConfigureTestServices(services =>
            {
                services.AddDbContext<IdentityContext>(options =>
                {
                    var serviceProvider = new ServiceCollection()
                        .AddEntityFrameworkInMemoryDatabase()
                        .BuildServiceProvider();

                    options.UseInMemoryDatabase("TestingDB", InMemoryDatabaseRoot);
                    options.UseInternalServiceProvider(serviceProvider);
                });                
                services.AddDbContext<InitIdentityContext>(options =>
                {
                    var serviceProvider = new ServiceCollection()
                        .AddEntityFrameworkInMemoryDatabase()
                        .BuildServiceProvider();

                    options.UseInMemoryDatabase("TestingDB", InMemoryDatabaseRoot);
                    options.UseInternalServiceProvider(serviceProvider);
                });
                services.AddDbContext<IdentityServerConfigurationDbContext>(options =>
                {
                    var serviceProvider = new ServiceCollection()
                        .AddEntityFrameworkInMemoryDatabase()
                        .BuildServiceProvider();

                    options.UseInMemoryDatabase("TestingDB", InMemoryDatabaseRoot);
                    options.UseInternalServiceProvider(serviceProvider);
                });

                services.AddDbContext<IdentityServer.Identity.Storage.Persistence.Context.IdentityContext>(options =>
                {
                    var serviceProvider = new ServiceCollection()
                        .AddEntityFrameworkInMemoryDatabase()
                        .BuildServiceProvider();

                    options.UseInMemoryDatabase("TestingDB", InMemoryDatabaseRoot);
                    options.UseInternalServiceProvider(serviceProvider);
                });
                
                var sp = services.BuildServiceProvider();
            });

            base.ConfigureWebHost(builder);
        }`
        
Base test controller:
        `public class ControllerTestBase: IClassFixture<WebApiTestFactory>, IAsyncLifetime
    {
        private IServiceScope _serviceScope { get; set; }
        protected TestDataService _testDataService { get; private set; }
        
        protected IdentityContext _db { get; private set; }
        protected readonly WebApiTestFactory _factory;

        public virtual string BaseUrl => throw new NotImplementedException();

        public ControllerTestBase(WebApiTestFactory factory)
        {
            _factory = factory;
            _serviceScope = _factory.Server.Host.Services.GetService<IServiceScopeFactory>().CreateScope();
            _db = _serviceScope.ServiceProvider.GetService<BoundedContext.IdentityContext>();
        }
        public virtual async Task InitializeAsync()
        {
            await _db.Database.EnsureDeletedAsync();
        }

        public virtual async Task DisposeAsync()
        {
            _serviceScope.Dispose();
            await _db.DisposeAsync();
            _db = null;
        }`

The test controller itself, which is call an API
`public class UserControllerTest: ControllerTestBase
    {

        public new string BaseUrl = "api/users";
        public UserControllerTest(WebApiTestFactory factory) : base(factory)
        {
        }

        [Fact]
        public async Task Create_WithValidValue_ShouldReturnCode201()
        {
            var user = new UserFaker().Generate();

            var provider = new IdentityProvider
            {
                    Id = IdentityProviderType.Google,
                    Name = "Google"
             }
            _db.IdentityProvider.Add(provider);
            await _db.SaveChangesAsync();
            
            var result = await _client.PostAsJsonAsync(BaseUrl, user);
            result.StatusCode.Should().Be(201);
        }
    }`

When I call an API - I add user using UserManager (from Microsoft.AspNetCore.Identity). It use `InitIdentityContext` inside. but when I try to access that user using `BoundedContext.IdentityContext` - the user is null. Example:
`private async Task<Guid> CreateUserFromSignUpAsync(
            Guid userId,
            string email,
            string lastName,
            string firstName,
            IdentityProvider provider)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user.IsNotNull())
            {
                throw new BusinessException("User already exists");
            }

            user = User.Create(
                userId,
                email,
                lastName,
                firstName);

            await _userManager.CreateAsync(user);

            var userManagerUser = await _userManager.GetUserAsync(user.Id.ToString());
            var boundedContextUser = await _userRepository.GetUserByIdAsync(userId);

            return user.Id;
        }`

![image](https://user-images.githubusercontent.com/70905025/104471093-1ab53900-55c3-11eb-952d-f211b06b0373.png)

**Comment by ajcvickers** [comment]
I would expect this behavior if the entity types are configured differently in each context, but I can't tell that from the code posted. If this isn't the case, then please open a **new** issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by collinbarrett** [comment]
Should this solution still work in dotnet/efcore 6.0 times?

I am using something like this in `Program.cs` and the 2x contexts do not seem to share the same data store.

```csharp
var builder = WebApplication.CreateBuilder(args);

var serviceProvider = new ServiceCollection().AddEntityFrameworkInMemoryDatabase().BuildServiceProvider();
builder.Services.AddDbContext<AnalyticsDbContext>(o =>
{
    o.UseInMemoryDatabase(nameof(TwitterStreamAnalytics), MyInMemoryDatabase.Root);
    o.UseInternalServiceProvider(serviceProvider);
});
builder.Services.AddDbContext<AnalyticsConsumersDbContext>(o =>
{
    o.UseInMemoryDatabase(nameof(TwitterStreamAnalytics), MyInMemoryDatabase.Root);
    o.UseInternalServiceProvider(serviceProvider);
});

var app = builder.Build();
app.Run();

public static class MyInMemoryDatabase
{
    public static readonly InMemoryDatabaseRoot Root = new();
}
```

**Comment by ajcvickers** [comment]
@collinbarrett Yes, this should work. If it isn't, then please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
