### ISSUE TITLE
Consider simplifying roadmap page

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#9615]
In the [roadmap](https://github.com/aspnet/EntityFrameworkCore/wiki/Roadmap) we currently have:

1. A list of "critical O/RM features" from the backlog
   > These are things we think we need before we can say EF Core is the recommended version of EF for **everyone**. Until we implement these features, although EF Core will be a valid option for many applications (especially on platforms like .NET Core where EF 6 does not work), for many applications the lack of these features will make EF 6 a better choice.
2. A list of "high priority features" from the backlog
   > There are many features on our backlog and this is by no means an exhaustive list. These features are high priority but we think EF Core would be a compelling release for the vast majority of applications without them:
3. Things we are actually intending to do in the next release

It seems that the difference between (1) and (2) may have become ambiguous, and as for everything that appears to be set in stone, I also think we should question it and review if they are all still valuable to have listed here :smile: 

Perhaps we could merge the two, and possibly leave some of them to become regular backlog items, unless we believe there is value keeping them here. 

Then it would be nice to find a way to structure things so that what we are doing in the next release and what we consider critical could be visualized together rather than having to look manually compare two different lists.

**Comment by ajcvickers** [comment]
Also, update it to be consistent with issues we have "propose close" closed.
