### ISSUE TITLE
Use MinClientVersion 3.6 in our .NET Standard 2.0 packages

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFrameworkCore#9668]
This is [recommended by the NuGet team](https://github.com/NuGet/Home/issues/5818#issuecomment-326448381) and should help at least customers on older 3.x NuGet client versions know that they need to upgrade. 

We need to understand better if this is a change we can take in a patch version of it needs to wait until 2.1.

**Comment by divega** [comment]
cc @Eilon @DamianEdwards, in case you want to consider this for ASP.NET Core packages as well.

**Comment by Eilon** [comment]
We should do this everywhere or nowhere; I don't see why we'd do it for only some packages, no?

**Comment by Eilon** [comment]
If we do this we should add a NuGetPackageVerifier rule for it as well.

**Comment by divega** [comment]
> I don't see why we'd do it for only some packages, no?

Only reason could be if it is more common for EF Core customers to get errors like this:

> Could not install package ‘Microsoft.EntityFrameworkCore.SqlServer 2.0.0’. You are trying to install this package into a project that targets ‘.NETFramework,Version=v4.7’, but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

But it would not hurt to do it on all packages.

**Comment by ajcvickers** [comment]
@divega to follow up with NuGet on 2.x version support.

**Comment by Eilon** [comment]
Would be good to email the engineering team alias on this.

**Comment by divega** [comment]
Got an answer form @rrelyea: there are no plans to ever update NuGet 2.x to support .NET Standard 2.0, so setting MinClientVersion to 3.6 should at least not result in false negatives.

**Comment by divega** [comment]
Clearing the assignment and milestone to bring this back to triage.
