### ISSUE TITLE
Properties with private setters in base class are not saved

### ISSUE THREAD

**Issue by fgheysels** [aspnet/EntityFrameworkCore#9705]
### Description

When I save a class that inherits from a base-class that has automatic properties with a public getter and a private setter, the values for those properties are not saved.
It seems that no columns are created in the table for  those properties (in a code first approach), and thereby the property values are not saved.

When I specify in OnModelCreating that a (private) backing field must be used to set the property, then it works like a charm: the property is saved and correctly retrieved.

I believe that EF must be able to correctly save the property when it is an auto-property.  Only if the property is declared as 'NotMapped', then it should not be saved.

### Demo code

A little console-application that demonstrates this behaviour can be downloaded [here](https://1drv.ms/u/s!ApGywS96rSAlpzv00YUg6dAb67fy)

### Further technical details
EF Core version: EntityFramework.Core 2.0.0
Database Provider: tested with InMemory and Sqlite DB

**Comment by ajcvickers** [comment]
Note for triage: Properties with private setters are picked up correctly if they are on the actual type, but not if they are on an unmapped base type. This doesn't seem right, but it is also not a regression.

**Comment by fgheysels** [comment]
I guess that this might be the reason:
When retrieving properties via reflection, you have no access to the setter if the setter is private if the property is declared on a base-type.   If you retrieve the property on the actual type, the private setter is available.

If you retrieve the property like this, then you have access to the private setter.

```
            PropertyInfo FindPropertyInHierarchy(string propertyName, Type t)
            {
                if (t == null)
                {
                    return null;
                }

                var pi = t.GetProperty(propertyName, BindingFlags.Instance | BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic);

                if (pi == null)
                {
                    pi = FindPropertyInHierarchy(propertyName, t.BaseType);
                }
                return pi;
            }
```

**Comment by chrisdpratt** [comment]
Just ran into this as well. However, in my experience, columns *are* persisted to the database and saved correctly, but when retrieving back from the database, EF Core does not fill the properties with the values from the database. They all remain null/default.
