### ISSUE TITLE
Review ASP.NET Core templates

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#9714]
We should review:
* Code (including anything that impacts EF tooling)
* Initial generated migration
* Consistency/experience across different platforms
  * See https://github.com/aspnet/templating/issues/4. For consistency, having the same experience regardless of platform would be better. For simplicity of the SQLite experience, having the database file in the template might be better.

**Comment by mguinness** [comment]
Please add IdentityUser POCO [navigation properties](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x#add-identityuser-poco-navigation-properties).

**Comment by ajcvickers** [comment]
@anpete @divega Just starting to look at this. The default connection string still has MARS enabled--is this still the "right thing to do" with EF Core 2.1?

**Comment by anpete** [comment]
@ajcvickers Yeah, I think so.

**Comment by ajcvickers** [comment]
Looking good for 2.1. The consistent experience is still lacking, but that's punted for 2.1 anyway.
