### ISSUE TITLE
Support change tracking of non-primitive types

### ISSUE THREAD

**Issue by dejvid-smth** [aspnet/EntityFrameworkCore#9753]
ChangeTracker does not detect changes to properties of type Dictionary<,>. In provider for PostgreSQL database database column type hstore is mapped to .net type Dictionary<string,string> but this feature can not be used properly if we do not have change tracking for those properties. One solution would be to use ImmutableDictionary but we want to avoid that.

### Steps to reproduce

```c#
public class HStoreContext : DbContext
{
   public DbSet<SomeEntity> SomeEntities { get; set; }
}

public class SomeEntity
{
   public int Id { get; set; }
   public Dictionary<string, string> Tags { get; set; }
}

using (HStoreContext ctx = CreateContext())
{
   var entity = new SomeEntity()
   {
       Tags = new Dictionary<string, string>()
   };
   ctx.SomeEntities.Add(entity);
   var num = ctx.SaveChanges();

   Assert.Equal(1, num);

   var entry = ctx.Entry(entity);
   Assert.Equal(EntityState.Unchanged, entry.State);

   entity.Tags.Add("kind", "new");
   ctx.ChangeTracker.DetectChanges();

   Assert.Equal(EntityState.Modified, entry.State); // This fails
}
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.PostgreSQL
Operating system: 
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment]
@dejvid-smth The ability to extend equality checks beyond ".Equals" is something that is not implemented yet. We intended to do it as part of type conversions (#242), since it is often needed then, although it is really a different feature. It's also being tracked as part of type mapping here: #8537

**Comment by roji** [comment]
Hmm... Unless I'm mistaken Dictionary's `.Equals()` should compare the items, so EF Core should properly detect changes in a dictionary's contents... @dejvid-smth I haven't had time yet to properly review and test [your PR](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/pull/240) which requires this, but could you double-check what's happening?

**Comment by dejvid-smth** [comment]
I don't know how exactly ChangeTracker works but we are just updating the same instance of Dictionary and EntityEntry from ChangeTracker only tracks if we actually change instance so both OriginalValue and CurrentValue are pointing to the same instance of Dictionary and therefore are the same. 

We would have to somehow make a copy of original Dictionary when EntityEntry's state is set to Unmodified and save that as OriginalValue in EntityEntry so we could later compare OriginalValue with CurrentValue.

**Comment by ajcvickers** [comment]
@roji Pretty sure Dictionary just does reference equality on the dictionary instance.

@dejvid-smth Correct, the snapshot would need to have a copy of the dictionary.

**Comment by ajcvickers** [comment]
@roji You will need to generate mappings with the appropriate ValueComparers for the types that Postgres supports. It's not clear to be that a deep snapshot/comparison is always the best choice for this kind of property depending on how it is used, but I think you would know better how people typically use these kinds of properties with Postgres and can therefore make a decision as to which is the appropriate behavior. Let's discuss if I'm missing anything.

**Comment by roji** [comment]
Thanks @ajcvickers! I'll take a look at the relevant types and modify their mappings accordingly for 2.1. I think that for arrays and for hstore (a native `Dictionary<string,string>` PostgreSQL datatype) a deep value comparison is the right thing to do, but we'll see what users say.

For anyone following, I've opened https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/305 for array comprison behavior and https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/306 for hstore.

**Comment by roji** [comment]
Just to report that I've value comparison for hstore seems to work perfectly... I'll be adding comparers to array and other relevant types for 2.1 as well.

Thanks!

**Comment by roji** [comment]
@ajcvickers if you're interesting in seeing a complex/interesting comparer implementation, take a look at [the array comparer](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/commit/f320396a59c107a29c5114db5479841174065897), it will also illustrate some of the issues detailed in #11072.
