### ISSUE TITLE
Improve Nuget discoverability by adding "entityframework" and "entityframeworkcore" to tags

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFrameworkCore#9776]
This is about improving the Nuspec tags in the product

Try a search for "entityframework core" or "entityframeworkcore" on nuget.org! 👎 

Also, seperate tags with spaces as per the nuspec docs. https://docs.microsoft.com/en-us/nuget/schema/nuspec 

Happy to do a PR 😄

**Comment by ajcvickers** [comment]
PR would be great!

**Comment by ErikEJ** [comment]
Already there

**Comment by ErikEJ** [comment]
Sorry, mean coming up 😊

**Comment by ilmax** [comment]
What about adding EFCore as well?

**Comment by ErikEJ** [comment]
Done

**Comment by ajcvickers** [comment]
Thanks @ErikEJ!
