### ISSUE TITLE
Scaffolded models are created with "_" instead of "." separator

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/EntityFrameworkCore#9787]
ef core 2.0

[Possibly related](https://github.com/aspnet/EntityFrameworkCore/issues/6369)

This command 

```
Scaffold-DbContext "Server=yada;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Connect.Model
```

resulted in models with namespaces like this:

```
namespace Domain.Connect_Model
```

Expected:

```
namespace Domain.Connect.Model
```

**Comment by smitpatel** [comment]
This is one of the observations I made during https://github.com/aspnet/EntityFrameworkCore/issues/9723
This is one of the cases where Migrations & RevEng are differing.

RevEng is trying to csharp-ify the output path before making namespace.
output dir arg
a.b.c => a_b_c
a\b\c => a.b.c

**Comment by sam-wheat** [comment]
@smitpatel Oh wow... this seems very convoluted.
Hopefully my comment here:  [9786](https://github.com/aspnet/EntityFrameworkCore/issues/9786) will be considered.  Seems like it would solve a number of issues if we could just scaffold from the project/directory where we want our models to live.

**Comment by sam-wheat** [comment]
BTW in my case "X.Y" is both a valid directory name and .net namespace.

**Comment by smitpatel** [comment]
"X.Y" is valid .net namespace but not valid c# identifier (you cannot name a class like that). It shouldn't have mattered but that is wrong assumption reveng tool did.
