### ISSUE TITLE
UseDatabaseNames not working in columns names

### ISSUE THREAD

**Issue by piyey** [aspnet/EntityFrameworkCore#9820]
I use the flag --use-database-names when generating my classes, table names are done fine, but field names are still PascalCaseify.

Regards!

**Comment by smitpatel** [comment]
@piyey - EF Core does not generate fields. Are you referring to Properties generated inside Entitytypes?

**Comment by piyey** [comment]
I mean field names of my tables are PascalCaseify when generating POCO classes.

**Comment by smitpatel** [comment]
Can you post example of one of incorrectly generated POCO classes?

**Comment by piyey** [comment]
I'm not on my dev machine, so I will try to explain it on the fly (sorry).

**My table:**

this_is_my_table
-field_one INT
-field_two INT
-field_three INT

**Generated POCO classes:**

public class this_is_my_table
{
     public int FieldOne {get;set;}
     public int FieldTwo {get;set;}
     public int FieldThree {get;set;}
}

**Comment by piyey** [comment]
If you see, table name is not PascalCaseify in the class name, but field names do in properties.

**Comment by smitpatel** [comment]
Presently Column Naming does not switch based on UseDatabaseNames (like DbSet & EntityType naming does).

@piyey in C# `public int Property {get; set;}` is auto-property whereas `public int Field;` is field (no getter/setter for a field). Therefore it was bit confusing.

Another interesting observation. We have convention to use DbSet name as table name. Shouldn't reveng scaffold dbset name same as table name regardless of naming strategy.

**Comment by piyey** [comment]
Do you mean UseDatabaseNames apply only to table name but not to columns names?

**Comment by piyey** [comment]
@smitpatel sorry for Field word, I meant column (in spanish we call fields to the columns of a table)

**Comment by smitpatel** [comment]
> Do you mean UseDatabaseNames apply only to table name but not to columns names?

Yes. At least in current code base. We will discuss in team meeting if that is expected behavior or column naming was left out in hindsight.

**Comment by siliond** [comment]
Same issues, additional details:

Column Names are still changed, see EQID below:

`modelBuilder.Entity<DCUTRANSLATIONS>(entity =>
            {
                entity.HasKey(e => new { e.Eqid, e.Analyte });

                entity.Property(e => e.Eqid)
                    .HasColumnName("EQID")
                    .HasMaxLength(20);
...`

Command used:
`dotnet ef dbcontext scaffold "Server=SLCOHW3DSILIO1;Database=sunrise_demo_data;Trusted_Connection=True;" "Microsoft.EntityFrameworkCore.SqlServer" -o "Models" -f -t "DCUTRANSLATIONS" --use-database-names`

[CLI](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)
 --use-database-names                   Use table and **column** names directly from the database.

**Comment by BlackBackground** [comment]
Same Issue.

field names are still PascalCaseify

Working with it is impossible.

I need a fix quickly.

**Comment by siliond** [comment]
@BlackBackground Hope this helps, it helped me: use EF vs core if you have the option, it works when reverse engineering model:
[https://msdn.microsoft.com/en-us/library/jj200620(v=vs.113).aspx](https://msdn.microsoft.com/en-us/library/jj200620(v=vs.113).aspx), see step 3.

**Comment by BlackBackground** [comment]
@siliond Thanks your your answer. Unfortunately your answer doesn't help. The structure must be updated frequently.

**Comment by siliond** [comment]
@BlackBackground Indeed, I don't know how to regenerate again easily besides deleting the model and classes and adding it again.

**Comment by camelinckx** [comment]
Does the team consider pull requests for fixing something like this?

**Comment by ajcvickers** [comment]
@camelinckx Absolutely. Please let us know if you're working on it.

**Comment by chrisAmelinckx** [comment]
@ajcvickers I am, testing now, pushing a PR shortly.

**Comment by chrisAmelinckx** [comment]
@ajcvickers https://github.com/aspnet/EntityFrameworkCore/pull/9981
