### ISSUE TITLE
Query: Remove TaskBlockingExpressionVisitor

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#9824]
It doesn't evaluate whole tree. It just looks at top level and if its Task, it calls .Result. It should be just a method. It will be breaking change because it is in DI.

**Comment by ajcvickers** [comment]
This does not need to be a visitor.

**Comment by smitpatel** [comment]
We removed this class altogether. We don't have IAsyncEnumerable on subquery level due to single query phenomenon.
