### ISSUE TITLE
Enum.ToString() results in SQL translation and returns underlying integer value

### ISSUE THREAD

**Issue by GeorgDangl** [aspnet/EntityFrameworkCore#9894]
After upgrading from 1.1 to 2.0, I noticed a regression in my apps. Enum.ToString() calls in a query are now evaluated in the SQL database, where enums are stored as the underlying integer type, therefore giving numerical strings instead of the enum name.

The example query:

    var dtos= _context.Models
                      .Select(model => new ModelDto
                      {
                          EnumValue = model.EnumValue.ToString()
                      });

Produces the following SQL around the `EnumValue` field:

    CONVERT(VARCHAR(11), [model].[EnumValue]) AS [EnumValue]

Using AutoMapper with defaults produces the same results.

The [SqlServerObjectToStringTranslator ](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerObjectToStringTranslator.cs#L22) uses `VARCHAR(11)` due to it being treated as an int. Later down, the call to `UnwrapEnumType()` seems to return int instead of an enum.

The enum property in the model is annotated with `[Required]` and is part of a composite index. The behavior is still present after I added a new migration with the latest tools.

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (Same behavior in LocalDB and Azure)
Operating system: Windows 10 Pro x64
IDE: Visual Studio 2017 15.3.4

**Comment by ajcvickers** [comment]
Notes for triage: It looks like this was introduced in PR #6908. The code in the PR doesn't look safe to me (but I may be missing something) in the sense that there are lots of types where we have no idea what ToString is expected to produce and so will generally cause differences in server verses client behavior. We will need to decide what to do about this going forward for all types, including enums.

Assigning to @anpete to investigate for 2.0.1 so we can understand our options going forward.

**Comment by smitpatel** [comment]
`SqlServerObjectToStringTranslator` should not `UnwrapEnumType` since `Enum.ToString()` is string representation of enum value and is not related to underlying value of enum which would be stored in database hence it is not convertible.

**Comment by ajcvickers** [comment]
Assigning to @smitpatel to make the suggested change for 2.0.1

**Comment by Eilon** [comment]
This patch bug is **approved** for the 2.0.x patch. Please send a PR to the `rel/2.0.1` branch and get it reviewed and merged.

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon
