### ISSUE TITLE
Client evaluation warning when query contains distinct and include

### ISSUE THREAD

**Issue by xoro91** [aspnet/EntityFrameworkCore#9912]
Why EF can't translate simple distinct ?

Distinct(IEqualityComparer<TSource> comparer) is not supported

Exception message:
System.InvalidOperationException: 'Warning as error exception for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning': The LINQ expression 'Distinct()' could not be translated and will be evaluated locally. To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.'

```c#
context.Entry(this.product)
                    .Collection(p => p.OrderLines)
                    .Query()
                    .Select(ol => ol.Order).Include(o => o.Customer)
                    .Distinct()
                    .ToList();
```

### Further technical details
EF Core version:2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows 10 x64
IDE: Visual Studio 2017

**Comment by xoro91** [comment]
this is my model [database diagram](https://drive.google.com/file/d/0B7eAql4GjubnT1ptRGQ4Mk1UcjQ/view)

**Comment by xoro91** [comment]
And a similar issue when ordering result set
 ```
var query = context.Entry(this.product)
                    .Collection(p => p.OrderLines)
                    .Query()
                    .Select(ol => ol.Order)
                    .Include(o => o.Customer)
                    .OrderBy(o => o.Created) //Microsoft.EntityFrameworkCore.Query.IncludeIgnoredWarning
                    .ToList();
```
                   

'Microsoft.EntityFrameworkCore.Query.IncludeIgnoredWarning': The Include operation for navigation '[e].Order.Customer' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information. To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.'

**Comment by smitpatel** [comment]
First case is bug. We can translate distinct to server. We are not doing it at present because of Include node and we end up marking client evaluation. 

Filed #10101 for 2nd case.
