### ISSUE TITLE
Type mapping may infer type from store type when it shouldn't

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#9916]
Scenario:
* PK type mapping is found and set onto property
* FK mapping looks for store type name on PK--it is found even though not explicitly set because it comes from the type mapping set in the first step
* Store type name is used to generated the mapping for FK, rather than normal mechanism
* If mapping from store type is not full-fidelity (e.g. SQLite) then this can result in wrong type mapping

**Comment by ajcvickers** [comment]
Note for providers: fix is easy--see PR for examples
/cc @ErikEJ @roji @Kagamine

**Comment by Kagamine** [comment]
+ @caleblloyd
