### ISSUE TITLE
Perf Regression: AddDbContextPool in asp.net core System.InvalidOperationException

### ISSUE THREAD

**Issue by mikeharder** [aspnet/EntityFrameworkCore#9923]
"AddDbContextPool in asp.net core System.InvalidOperationException" (https://github.com/aspnet/EntityFrameworkCore/pull/9871) seems to have caused a 30% regression in the TechEmpower "Single Query" and "Fortunes" scenarios, on 9/21/17 between 7:45PM and 8:28PM PST.

Scenario | RPS @ 9/21 7:45 PM | RPS @ 9/21 8:28 PM | Ratio
------------ | ------------- | ------------- | -------------
DbSingleQueryEf | 11,243 | 7,900 | 0.70
DbFortunesEf | 10,355 | 6,833 | 0.66

You can also see the regression in our charts at http://aka.ms/aspnet/benchmarks.

**Comment by anpete** [comment]
@mikeharder I have been unable to repro this so far - I have been running the benchmarks locally and get roughly the same numbers with and without #9871.

Can you do a run against this [branch](https://github.com/aspnet/EntityFrameworkCore/tree/undo-fix-9741) to hopefully confirm either way?

**Comment by mikeharder** [comment]
@anpete: I will try to directly verify the impact of #9871.

**Comment by anpete** [comment]
@mikeharder Thanks.

**Comment by divega** [comment]
@anpete are you running the benchmark locally on Windows? 

@sebastienros suggested that this could be something that only repros on Linux.

I imagine this could be possible if the cost of things `AsycnLocal<T>` does is different on Linux and Windows.

**Comment by anpete** [comment]
@divega Yep, Windows.

**Comment by mikeharder** [comment]
I have verified the Linux regression is caused by "AddDbContextPool in asp.net core System.InvalidOperationException" (d00c4dc).  Here are the results before and after this commit:

```
$ dotnet BenchmarksDriver.dll \
    -s server \
    -c client \
    -n DbFortunesEf \
    -j https://raw.githubusercontent.com/aspnet/benchmarks/dev/src/Benchmarks/benchmarks.html.json \
    -o Benchmarks@mikeharder/default-compiler \
    -o EntityFrameworkCore@fde3acb

RequestsPerSecond:           11629.54
```
```
$ dotnet BenchmarksDriver.dll \
    -s server \
    -c client \
    -n DbFortunesEf \
    -j https://raw.githubusercontent.com/aspnet/benchmarks/dev/src/Benchmarks/benchmarks.html.json \
    -o Benchmarks@mikeharder/default-compiler \
    -o EntityFrameworkCore@d00c4dc

RequestsPerSecond:           8591.95
```

**Comment by mikeharder** [comment]
Also repros on a Windows web server (DB is still PostgreSQL on Linux):

```
$ dotnet BenchmarksDriver.dll \
    -s windows-server \
    -c client \
    -n DbFortunesEf \
    -j https://raw.githubusercontent.com/aspnet/benchmarks/dev/src/Benchmarks/benchmarks.html.json \
    -r Benchmarks@mikeharder/default-compiler \
    -o EntityFrameworkCore@fde3acb

RequestsPerSecond:           16564.1
```

```
$ dotnet BenchmarksDriver.dll \
    -s windows-server \
    -c client \
    -n DbFortunesEf \
    -j https://raw.githubusercontent.com/aspnet/benchmarks/dev/src/Benchmarks/benchmarks.html.json \
    -r Benchmarks@mikeharder/default-compiler \
    -o EntityFrameworkCore@d00c4dc

RequestsPerSecond:           11372.3
```
