### ISSUE TITLE
OrderBy with .Contains(Guid) expression generates invalid SQL

### ISSUE THREAD

**Issue by bradmarder** [aspnet/EntityFrameworkCore#9951]
Using SqlServer database provider, and `Blog` with a Guid primary key `Id`.

```
var guids = new List<Guid>();
await db.Blogs.OrderBy(x => guids.Contains(x.Id)).ToListAsync();
```

This gets translated into

```
SELECT *
      FROM [Blogs] AS [x]
      ORDER BY CASE
          WHEN 0 = 1
          THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
      END DESC
```

When executed, sql server throws the error
`A constant expression was encountered in the ORDER BY list, position 1.`

I would expect this query to compile similarly as other `Contains()` expressions. If I change the the list and Id to ints, the following query is correctly generated. Strings work as well. `DateTimeOffset` does not work.

```
SELECT *
      FROM [Blogs] AS [x]
      ORDER BY CASE
          WHEN [x].[Id] IN (1, 2, 3, 4)
          THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
      END DESC
```

When included in more complicated queries (with `Skip().Take()`, the query fails to compile. (Edit - I think this exception/issue is different since this occurs with string contains as well)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.Expressions.InExpression.Equals(InExpression other)
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at Microsoft.EntityFrameworkCore.Query.Expressions.SelectExpression.AddToProjection(Expression expression, Boolean resetProjectStar)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
```

### Further technical details
EF Core version: Latest version, 2.1.0-preview1-27020
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system:  win 10 64bit
IDE: VS Studio 2017 15.4.0 Preview 4.0

**Comment by MarcoLoetscher** [comment]
`await db.Blogs.Where(x => guids.Contains(x.Id)).OrderBy(x => x.Id).ToListAsync();`

**Comment by bradmarder** [comment]
@MarcoLoetscher That is a filter query, I'm trying to order the data.

**Comment by smitpatel** [comment]
In first query we do generate `InExpression` but the list is empty so we optimize that bit out to replace it with `0 = 1`. I verified that above SQL does throw exception. We need to refine rules to apply optimization because we should not be generating incorrect SQL. Marking this as bug for that. The second expected SQL would be generated for any case of parameter values being non-empty list. 

I am not sure why it would fail only for `DateTimeOffset` but implementation of Equals in `InExpression` does not seem to be null-safe.

**Comment by bradmarder** [comment]
@smitpatel I've narrowed down the cause of the NRE on the `InExpression.Equals()`.
I doubt this is related.

This only throws under specific conditions. `Posts` must be a collection navigation property. 
The `guids` variable could also be a list of int, the same exception occurs. 

```
var guids = new List<Guid> { Guid.Empty };
await db.Blogs
    .Include(x => x.Posts)
    .OrderByDescending(x => guids.Contains(x.Id))
    .Skip(1)
    .ToListAsync();
```
