### ISSUE TITLE
DbFunctions: Consider protected methods for discovering DbFunctionAttribute

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#9956]
At present we have set of BindingFlags to discover methods for UDFs, they explicitly ignores protected methods. But the attribute based discovery should be done regardless of protection level.
The protection level restricts user's ability to use the method inside of the EF Query but if in some way user can use it then we should translate it.
One way to use the method is to pass in IQueryable to public method in DbContext which would apply logics from protected/private methods by calling them and return it. (or there is always reflection)

**Comment by ajcvickers** [comment]
Note from triage: we should do this for any property--public, protected, internal, private.

**Comment by ajcvickers** [comment]
@pmiddleton We would love a PR for this if you are up for it. 😸

**Comment by pmiddleton** [comment]
Sounds good.  

What about private and internal?  Might as well find those as well while we are at it.

**Comment by smitpatel** [comment]
As @ajcvickers said above, we want all of them :trollface:

**Comment by pmiddleton** [comment]
Well that would me I would have to read the whole post :)

**Comment by smitpatel** [comment]
Fixed via 843929da0c1bc90813178e8fa16edf9dbbeb58df
