### ISSUE TITLE
Port scaffolding fix for nvarchar(4000) to 2.0.1

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#9963]
See full details here: https://github.com/aspnet/EntityFrameworkCore/issues/9188

Note: this still needs to be approved for patch, so it's not 100% for sure in 2.0.1 yet.

**Comment by Eilon** [comment]
This patch bug is **approved** for the 2.0.x patch. Please send a PR to the `rel/2.0.1` branch and get it reviewed and merged.

**Comment by Eilon** [comment]
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon

**Comment by ksahota** [comment]
I have tried the ASP.NET/EF Core 2.0.3 patch and the scaffolding issue is still there. 
![image](https://user-images.githubusercontent.com/6529378/32109047-9167c6f4-bb01-11e7-88c9-55dcd080033a.png)

![image](https://user-images.githubusercontent.com/6529378/32109092-ac9dbab4-bb01-11e7-8102-bc02ca93d244.png)

**Comment by smitpatel** [comment]
@ksahota - Did you re-scaffold database or upgraded package in already scaffolded code?

**Comment by ksahota** [comment]
@smitpatel , Upgraded package in already scafolded code .

**Comment by smitpatel** [comment]
This fix does not solve that issue. You manually have to edit generated file in existing files. Or you can delete scaffolded code and re-generate them. This fix stops producing incorrect code.

**Comment by ksahota** [comment]
Seems to be working. Thanks @smitpatel
