### ISSUE TITLE
FileLoadException when migrating with incorrect startup project and and project

### ISSUE THREAD

**Issue by giggio** [aspnet/EntityFrameworkCore#9984]
I ran on PowerShell:

````powershell
 dotnet ef migrations add  --startup-project $startupDir --project $projectDir Update -c $dbContext -o .\Migrations\
````

With `$startupDir` and `$projectDir` set to incorrect directories and I got a not very helpful exception and nothing else.

```
Exception message: Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack trace: N/A
```

### Further technical details

I had both `$startupDir` and `$projectDir` pointed to a similar project, but outside the project where I was running the command. I actually created a git worktree for a different branch in a different directory and was pointing to the original directory.

EF should had told me something was wrong. I need a better error message. I am fine with it erroring, but point me to the right direction.

As soon as I fixed both variables everything worked.

````
$ dotnet --version
2.0.0
$ dotnet ef --version
Entity Framework Core .NET Command Line Tools
2.0.0-rtm-26452
````

Every package is at `2.0.0` version. This is all under .NET Core 2 as well.

**Comment by ajcvickers** [comment]
Triage: we will investigate to see if this can be caught and wrapped in a more helpful exception.

**Comment by giggio** [comment]
I don't know if it helps, but the other project dirs contained EF Core and .NET Core 1.x.

**Comment by bricelam** [comment]
`dotnet-ef.dll` takes a leap of faith when invoking `ef.dll` in the context of the startup app. We could eagerly check for cases we know will fail (e.g. targeting .NET Core 1.x), but I don't think there's anything general we can do in this case.

**Comment by bricelam** [comment]
Triage decision: It's not worth adding code to special case .NET Core 1.x at this point.

**Comment by giggio** [comment]
@bricelam There is nothing here on .NET Core 1.x. You don't need to special case it to 1.x, because everything about this issue is running on .NET Core 2.0.

**Comment by bricelam** [comment]
As far as I could tell, your accidental startup project was targeting .NET Core 1.x. If it wasn't, you'd see a better error (something like, "EFCore.Design isn't referenced")
