### ISSUE TITLE
Script-Migration -Idempotent when default schema contains dot

### ISSUE THREAD

**Issue by graemeenglish** [aspnet/EntityFrameworkCore#9993]
The generated script fails to run giving the following

> There is already an object named '__EFMigrationsHistory' in the database.
### Steps to reproduce
Configure the database with a default schema e.g.
```c#
options.ConfigureDbContext = builder =>
    builder.UseSqlServer(connectionString, sql =>
        {
            sql.MigrationsAssembly(migrationsAssembly);
            sql.MigrationsHistoryTable(HistoryRepository.DefaultTableName, "myapp.cfg");
        }
    );
options.DefaultSchema = "myapp.cfg";
```
In PMC
Script-Migration -Idempotent

results in the following 
```SQL
IF OBJECT_ID(N'myapp.cfg.__EFMigrationsHistory') IS NULL
BEGIN
    IF SCHEMA_ID(N'myapp.cfg') IS NULL EXEC(N'CREATE SCHEMA [myapp.cfg];');
    CREATE TABLE [myapp.cfg].[__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
```
Modifying the first line to the following resolves the problem:
```SQL
IF OBJECT_ID(N'[idsvr.cfg].__EFMigrationsHistory') IS NULL
```

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore (2.0.0)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: 
IDE: Visual Studio 2017

**Comment by bricelam** [comment]
Note to self: It looks like we can just always include the square braces in `OBJECT_ID`
